### ISSUE TITLE
在蓝图里如何调用LUA的函数？

### ISSUE THREAD

**Issue by xermao** [Tencent/UnLua#10]
教程里只写了再C++里调用，没写蓝图里的。

**Comment by xermao** [comment]
顺便再问个问题，如何输出调试信息？就类似UE_LOG，是得自己封装，还是有现成的？

**Comment by litianqi** [comment]
直接调用print就好，UnLua.lua第一行有一个重定义
```lua
print = UEPrint
```

**Comment by rowechien** [comment]
没有为蓝图调用lua提供方法，这个插件的做法是lua override诸如BeginPlay这样的BlueprintEvent，然后直接在lua里定义、调用函数。这个小工程就是参考示例

**Comment by xermao** [comment]
感谢回复，明白思路了。这样确实可以，只是在某些情况下会比较麻烦，比如在商城买了一个模板，我想对他进行改造，改造的部分想用LUA来写，但是大部分代码仍然是蓝图，这种时候，如果可以从蓝图调用LUA就会方便很多，否则的话，就必须得把原蓝图的BeginPlay这些写到另外一个事件或者函数里，再通过LUA里的BeginPlay来调用。

**Comment by rowechien** [comment]
我理解你的意思，你可以看一下[Programming Guide](https://github.com/Tencent/UnLua/blob/master/UnLua_Programming_Guide_EN.md)里的一节“Calls Overridden Functions”，看看这种方式是不是可以稍微简化下这种情况下的处理。
示例工程里的BP_PlayerController_C.lua里有具体用法。
放到你的场景下就是类似这种做法：
function XXXX:ReceiveBeginPlay()
    self.Overridden.ReceiveBeginPlay(self)
    // add your codes here
end

**Comment by futouyiba** [comment]
@xermao 你说的这种情况，比如说on post login里面有很长的蓝图链条，或许可以把其中的一部分collapse成函数，然后在lua里面写同名的函数去override。因为蓝图的函数本质上都是event，在lua里函数也是可以被override的。现在我还没试，有机会的时候我试一下再来留言。

**Comment by rowechien** [comment]
@futouyiba 即使Lua覆写了BlueprintEvent，但依然可以调用到原始的BlueprintEvent实现，具体可以参考[Programming Guide](https://github.com/Tencent/UnLua/blob/master/UnLua_Programming_Guide_EN.md)里的“Calls Overridden Functions”

**Comment by futouyiba** [comment]
> @futouyiba 即使Lua覆写了BlueprintEvent，但依然可以调用到原始的BlueprintEvent实现，具体可以参考[Programming Guide](https://github.com/Tencent/UnLua/blob/master/UnLua_Programming_Guide_EN.md)里的“Calls Overridden Functions”

恩，文档我学习了。btw，文档写的非常好，如果再能有一些设计思路、highlevel 概念解释、主要类的设计思路就更好了。（类似unreal，或者react那样）
上面我说的，主要是针对题主的这个问题：
“感谢回复，明白思路了。这样确实可以，只是在某些情况下会比较麻烦，比如在商城买了一个模板，我想对他进行改造，改造的部分想用LUA来写，但是大部分代码仍然是蓝图，这种时候，如果可以从蓝图调用LUA就会方便很多，否则的话，就必须得把原蓝图的BeginPlay这些写到另外一个事件或者函数里，再通过LUA里的BeginPlay来调用。”
不用把begin play写到另一个函数里。假设begin play包含5大段步骤ABCDE，每段当中包含若干节点和连线。现在想要用lua改写C，不动AB DE，那么：
框选C这段的BP节点，右键collapse成为一个函数，起名字FuncC，编译保存。然后在lua里面去override这个MyClass::Func()，这样AB DE阶段的逻辑不变，只有C部分被覆盖了。
然后跑不通想回去看看bp逻辑，只要把lua里这一段注掉，又会跑回bp逻辑。
