### ISSUE TITLE
CreateExport: Failed to load Outer for resource

### ISSUE THREAD

**Issue by xpc-yx** [Tencent/UnLua#100]
最新的Master版本下载下来，用4.22引擎，报一大堆加载警告。
![@@1578455361116](https://user-images.githubusercontent.com/6227185/71949093-2ed69580-320d-11ea-9181-1dd26aa5fc6c.png)

**Comment by rowechien** [comment]
@xpc-yx 应该是[a15c8ed](https://github.com/Tencent/UnLua/commit/a15c8edf984195c2e2f27260be73d20320b134c4)这个submit导致的。
我在高引擎版本的editor里保存了这个blueprint，你在低引擎版本下加载它的子类出了问题。你可以把这个submit修改的blueprint资源（BP_CharacterBase.uasset）换成最初的版本就可以了。
