### ISSUE TITLE
想请问一下，lua里面可以调用 c 扩展库吗？例如 luasocket 这样的库要如何引入？

### ISSUE THREAD

**Issue by linshuhe** [Tencent/UnLua#102]

**Comment by hxhb** [comment]
你找到方法了吗？

**Comment by zhangweiiscoding** [comment]
我这里试着从插件层面与Lua平级集成了一个自己用的，你可以看看能不能用https://github.com/zhangweiiscoding/UnLuaWithLibs

**Comment by hxhb** [comment]
> 我这里试着从插件层面与Lua平级集成了一个自己用的，你可以看看能不能用https://github.com/zhangweiiscoding/UnLuaWithLibs

好的，感谢 我试一下。

**Comment by rowechien** [comment]
@linshuhe @hxhb 我看了下zhangweiiscoding给的仓库，挺好的，你们可以按他的方式来做。
@zhangweiiscoding thanks!

**Comment by hxhb** [comment]
> @linshuhe @hxhb 我看了下zhangweiiscoding给的仓库，挺好的，你们可以按他的方式来做。
> @zhangweiiscoding thanks!

我改进了一下，因为unlua重写了require，只会查找loaded表和lua文件，，加到Preload表里的不会被查找。
可以看这个仓库：https://github.com/hxhb/debugable-unlua

**Comment by linshuhe** [comment]
> @linshuhe @hxhb 我看了下zhangweiiscoding给的仓库，挺好的，你们可以按他的方式来做。
> @zhangweiiscoding thanks!

好的，已经尝试了 zhangweiiscoding 给的方式，成功集成了 lua-protobuf
