### ISSUE TITLE
在Debug Editor模式下，静态导出c++类会出现对象空指针的问题

### ISSUE THREAD

**Issue by jarjin2000** [Tencent/UnLua#104]
在Debug Editor模式下，静态导出c++类会出现对象空指针的问题，unlua在这个模式下做了一个反射注册表检查，并不是像其他模式那样直接从lua栈里面获取，静态导出的类是不会注册进反射注册表，导致反射注册表里面并没有相关数据，然后它就直接返回为空。
![image](https://user-images.githubusercontent.com/15137027/72421310-31ac2a00-37bb-11ea-9a4e-e06c16662875.png)
![image](https://user-images.githubusercontent.com/15137027/72421313-34a71a80-37bb-11ea-8813-8648d39defb0.png)
临时解决方案：把显式导出的C++静态代码去掉（不再走调用导出的堆栈），或者用BEGIN_EXPORT_REFLECTED_CLASS导出（强制塞进反射注册表，让它调用的时候能够找到类信息）。

**Comment by rowechien** [comment]
@jarjin2000 我的理解是，如果GetArgs走到了UObject对应的特化，那这个参数一定是个反射类的指针，你在取这个参数的时候，它对应的class会被自动注册。如果实际情况不是这样，那应该是bug。所以，方便的话是否可以把你的代码贴出来看下？

**Comment by rowechien** [comment]
@jarjin2000 我试了几种情况没有发现问题，反射类可以不用静态导出，但确实需要时要用BEGIN_EXPORT_REFLECTED_CLASS这个宏，[Programming Guide](https://github.com/Tencent/UnLua/blob/master/UnLua_Programming_Guide_EN.md)有说明的。问题关了，还有问题的话再reopen，并把你的case贴出来。
