### ISSUE TITLE
在Dedicated Server模式+Debug Editor下两游戏进程开启会有断言失败问题

### ISSUE THREAD

**Issue by jarjin2000** [Tencent/UnLua#105]
在特定模式下
![image](https://user-images.githubusercontent.com/15137027/72502316-00dbfb80-3874-11ea-8fd5-6506140632b5.png)

![image](https://user-images.githubusercontent.com/15137027/72502011-506df780-3873-11ea-85d8-423b635c0237.png)
![image](https://user-images.githubusercontent.com/15137027/72502046-61b70400-3873-11ea-9798-51d24389ef07.png)
![image](https://user-images.githubusercontent.com/15137027/72502070-73001080-3873-11ea-83c3-17e11eced7ce.png)
![image](https://user-images.githubusercontent.com/15137027/72502214-bd818d00-3873-11ea-908c-3b6fc42bc816.png)
看起来像是有几率的重复添加导致的检查断言失败，后面跟了下，TSet<FName> &LuaFunctions = ModuleFunctions.Add(InModuleName);会清空并替换原来的数据，不影响运行，不知道网络游戏中，如果第一个角色绑定+其他Player角色绑定应该不会有问题吧？

**Comment by rowechien** [comment]
@jarjin2000 重现你说的问题有什么特殊设置么，我在实例工程里试了很多次都没碰到
