### ISSUE TITLE
静态绑定  静态绑定导出父类的函数 在安卓下编译不过

### ISSUE THREAD

**Issue by caishengxi** [Tencent/UnLua#107]
静态绑定  静态绑定导出父类的函数 在安卓下编译不过

BEGIN_EXPORT_REFLECTED_CLASS(XXXGameInstance)
ADD_FUNCTION(IsDedicatedServerInstance)

IsDedicatedServerInstance这个函数是XXXGameInstance的父类中的函数 

windows中没问题，打包安卓 报错 no matching member function for call to "AddFunction"
ADD_FUNCTION(IsDedicatedServerInstance)

**Comment by rowechien** [comment]
@caishengxi 父类函数你可以在父类的导出中添加，对于反射类，父类添加了函数，子类直接就可以访问了。如果是非反射类，有如下的方法可以做到：
![image](https://user-images.githubusercontent.com/7972243/75618911-98d93e80-5baf-11ea-8e69-6fcae45eb2e1.png)
