### ISSUE TITLE
能讲解一下lua里Cast的实现思路吗？

### ISSUE THREAD

**Issue by FTQZS** [Tencent/UnLua#108]
目前好像只支持Class的Cast？Struct之类的对象并不能Cast？我们项目用的是slua，但slua还不支持Cast，Cast是很常见的操作，所以想看看能不能自己实现一下。

**Comment by rowechien** [comment]
@FTQZS  UnLua只支持UObject这个体系内的Cast，Cast的结果是对象本身或者nil，内部利用的是引擎的反射机制。反射之外的不支持。。。如果要自己实现，如何调整table或者userdata的元表可能是关键。
