### ISSUE TITLE
同一Delegate连续绑定两次导致UFunction无法删除

### ISSUE THREAD

**Issue by kimixuchen** [Tencent/UnLua#110]
Unlua的Delegate在绑定一个lua回调函数时，会创建一个对应函数名的UFunction实例，并且UFunction有一个对应的FSignatureDesc，用NumBindings记录函数已经注册的数量。绑定时NumBindings会加一，解绑时NumBindings再减一，当数量为0时就把创建的UFunction实例删除。
`FloatTrack.InterpFunc:Bind(self, BP_PlayerCharacter_C.OnZoomInOutUpdate)
FloatTrack.InterpFunc:Bind(self, BP_PlayerCharacter_C.OnZoomInOutUpdate)
FloatTrack.InterpFunc:Unbind()`
但是像上面的代码，解绑前一个Delegate连续绑定了相同的函数，OnZoomInOutUpdate对应的UFunction实例NumBindings会变成2，解绑后再变成1，但解绑后已经没有Delegate与这个UFunction实例关联了，因此NumBindings引用无法再减为0，游戏过程中会一直存在。直到Cleanup时UFunction实例才被清理。

请问是否需要在delegate绑定新的lua回调函数时，先把之前的解绑？

**Comment by rowechien** [comment]
@kimixuchen 例子中的InterpFunc是个Delegate, 不是Multicast Delegate，Delegate只能绑定一个callback，对应的是Bind、Unbind，不管连续Bind多少个callback，只要Unbind了就无效了；Multicast Delegate能绑定多个callback，对应的是Add、Remove、Clear。你看下引擎代码会更清楚。
