### ISSUE TITLE
内置数据类型tostring的crash问题

### ISSUE THREAD

**Issue by hxhb** [Tencent/UnLua#111]
比如使用UE4.FVector不会调用构造函数，而UE4.FVector()就可以。

这样是OK的:

```lua
function Cube_Blueprint_C:ReceiveBeginPlay()
    print(tostring(UE4.FVector()))
end
```
这样就不会调用`FVector_New`：

```lua
function Cube_Blueprint_C:ReceiveBeginPlay()
    print(tostring(UE4.FVector))
end
```
导致在tostring的时候传进来的this是null，从而crash。

**Comment by rowechien** [comment]
@hxhb fixed in [cea109c](https://github.com/Tencent/UnLua/commit/cea109c457be2f517bf22cbc6f029b685cf9c40e)
