### ISSUE TITLE
TArray等Core Container类的EmmyLua提示失败（原因是容器类并没有导出intellisense）

### ISSUE THREAD

**Issue by futouyiba** [Tencent/UnLua#112]
从这个图中可以看到TArray的EmmyLua提示失败了：

![image](https://user-images.githubusercontent.com/6793989/75161741-4505ca00-5757-11ea-96f2-7df5983c568b.png)

其他的代码提示都是正常的，只有TArray相关的是这样，于是去查看Intellisense目录：
![image](https://user-images.githubusercontent.com/6793989/75161855-72527800-5757-11ea-9a92-875fca77826c.png)
这是引擎源码中TArray的位置
![image](https://user-images.githubusercontent.com/6793989/75161877-7d0d0d00-5757-11ea-8b73-81827ce20ba5.png)

值得注意的是，在自动导出的Intellisense当中也有一些TArray，它们也都是标红状态：
![image](https://user-images.githubusercontent.com/6793989/75162084-e7be4880-5757-11ea-96d1-5db156ff8e29.png)

PS：当前用的引擎版本是4.23，插件版本是UnLua升到4.24之前的提交：
![image](https://user-images.githubusercontent.com/6793989/75162146-03295380-5758-11ea-8911-143648152cbd.png)

**Comment by futouyiba** [comment]
我看到有一个对于手工导出类处理的commandlet，这个commandlet如何使用呢？

**Comment by rowechien** [comment]
@futouyiba 见issue [114](https://github.com/Tencent/UnLua/issues/114)
