### ISSUE TITLE
如何使用UnLuaIntelliSenseCommandlet？

### ISSUE THREAD

**Issue by futouyiba** [Tencent/UnLua#114]
在readme中提到：
29 | * **UnLuaEditor**. **'Editor'** module includes editor extention (Lua template exporting) and a commandlet.
-- | --

在#29中提到：
IntelliSense是和UHT一同工作的，它只能感知到反射体系内的数据（UClass, UScriptStruct, UEnum, UFunction, UProperty等）。 反射体系之外被静态导出的类、函数等有个Commandlet （UUnLuaIntelliSenseCommandlet）可以生成。

那么如何使用它呢？

**Comment by futouyiba** [comment]
![image](https://user-images.githubusercontent.com/6793989/75405615-1f401700-5949-11ea-9bd7-298f2ddafe19.png)
尝试了多种package name：

![image](https://user-images.githubusercontent.com/6793989/75405625-26ffbb80-5949-11ea-8f4b-6cec9488b7e3.png)
![image](https://user-images.githubusercontent.com/6793989/75405649-3b43b880-5949-11ea-8bbc-ac55eda03ae8.png)

**Comment by rowechien** [comment]
@futouyiba 这就是个ue的commandlet，最典型的commandlet就是资源的cook啊（UCookCommandlet）。具体命令行：
![image](https://user-images.githubusercontent.com/7972243/75618845-a04c1800-5bae-11ea-9469-602648a79f74.png)
