### ISSUE TITLE
请问在重载了蓝图事件之后，能否在其中调用蓝图原本的图形逻辑？

### ISSUE THREAD

**Issue by futouyiba** [Tencent/UnLua#115]
类似于parent:BeginPlay()
或者self.super:ReceiveBeginPlay（）

**Comment by rowechien** [comment]
@futouyiba 我没理解错误的话，你可以看看[Programming Guide](https://github.com/Tencent/UnLua/blob/master/UnLua_Programming_Guide_EN.md)中的Call Overridden Functions这一节

**Comment by futouyiba** [comment]
> @futouyiba 我没理解错误的话，你可以看看[Programming Guide](https://github.com/Tencent/UnLua/blob/master/UnLua_Programming_Guide_EN.md)中的Call Overridden Functions这一节

不好意思忘了close，麻烦你了。那天我把overriden记成了slua特有的写法，纠结了很久。
