### ISSUE TITLE
一个神奇的bug：导出的代码提示TArray里面实际是FVector4

### ISSUE THREAD

**Issue by futouyiba** [Tencent/UnLua#118]
![image](https://user-images.githubusercontent.com/6793989/75675764-bc40de00-5cc2-11ea-9c7a-4bc20d7e13d3.png)

首先感谢 @rowechien ，参考了cook之后，终于成功运行了静态导出的commandlet：
![image](https://user-images.githubusercontent.com/6793989/75675110-72a3c380-5cc1-11ea-8a8e-e0aa452c8daa.png)
出现了新的文件夹：
![image](https://user-images.githubusercontent.com/6793989/75675320-e5ad3a00-5cc1-11ea-9ee4-0e95636227c3.png)
![image](https://user-images.githubusercontent.com/6793989/75675332-ed6cde80-5cc1-11ea-8153-e44ce8affee5.png)
但是FVector4和TArray里面都是FVector4，哪儿都找不到TArray，醉了……
![image](https://user-images.githubusercontent.com/6793989/75675792-d2e73500-5cc2-11ea-98af-e46cb6740189.png)
PS：我检查了LuaLib Array，里面是正确的：
![image](https://user-images.githubusercontent.com/6793989/75676077-79333a80-5cc3-11ea-9bba-2884e1d2b20e.png)

=====================================================
btw：之前一直不成功的原因是Unreal对于commandlet的文档不是太细，对于Editor模块需要做一些变通：
https://docs.unrealengine.com/en-US/API/Runtime/Engine/Commandlets/UCommandlet/index.html
当中说：
Commandlets are executed from the ucc.exe command line utility, using the following syntax: yourgame.exe package_name.commandlet_class_name [parm=value]...

for example: yourgame.exe Core.HelloWorldCommandlet yourgame.exe UnrealEd.CookCommandlet

以及：
https://github.com/ue4plugins/CommandletPlugin
当中也说：
Use the -run command line parameter to run one of the commandlets in this plug-in, i.e. YourGame.exe -run=HelloWorld

最后，在 @rowechien 的提示下参考了cook，最终用这个命令终于运行成功：
![image](https://user-images.githubusercontent.com/6793989/75675944-32dddb80-5cc3-11ea-9731-e3dbc53a7436.png)
究其原因，MCE.exe当中一定没有Editor插件，只有UnLua，没有UnLuaEditor，因此必须用Editor方式打开。

**Comment by futouyiba** [comment]
删除了UnLuaIntellisense目录之后重新运行commandlet，再次导出的依然是同样症状。我现在重启机器试一下，若能解决我会回来close

**Comment by futouyiba** [comment]
更新，重启机器后导出依然有此问题。我会手工先将其填上。但是此问题为何产生，确实挺奇怪的。

**Comment by rowechien** [comment]
@futouyiba fixed in [a015184](https://github.com/Tencent/UnLua/commit/a015184eae4eecdb76a87d980ff8ba0825acfd1b)。但是以luaL_Reg形式导出的函数无法生成符号信息，因为只能知道函数名字，无法得到参数信息
