### ISSUE TITLE
UStruct有类似于UClass.Load这样的功能吗？

### ISSUE THREAD

**Issue by futouyiba** [Tencent/UnLua#119]
比如，在下面这段代码中，若FMyRowStruct不是在代码中创建的，而是在蓝图中创建的结构体，能不能动态创建出一个合适的Row呢？  谢谢！

>    local heroTable = LoadObject('/Game/9Test/NewDataTable.NewDataTable')
>     print('hero table is:'..tostring(heroTable))
>     --print('hero table is:'..heroTable.GetName()..tostring(heroTable))
>     local Row = FMyRowStruct()
>     print('Row is:', Row)
>     local RowNames = TArray(FName)
>     print('RowNames is:', RowNames)
>     UDataTableFunctionLibrary.GetDataTableRowNames(heroTable, RowNames)
>     local NumRows = RowNames:Length()
>     print('RowNames of new Data table count:', NumRows)
>     for i = 1, NumRows do
>         local Name = RowNames:Get(i)
>         UDataTableFunctionLibrary.Generic_GetDataTableRowFromName(heroTable, Name, Row)
>         print(Name..".Level=="..tostring(Row.Level))
>         print(Name..".Health=="..tostring(Row.Health))
>         print(Name..".Name=="..tostring(Row.Name))
>     end

**Comment by futouyiba** [comment]
似乎格式总也搞不好，没有缩进不好阅读。截图贴上。
![image](https://user-images.githubusercontent.com/6793989/75687700-23698d00-5cd9-11ea-9f33-c02824628545.png)

**Comment by rowechien** [comment]
@futouyiba 蓝图中定义的struct需要先用LoadObject加载，后面就是一样了，不过我不建议在lua中使用蓝图里定义的结构体，原因我在[40](https://github.com/Tencent/UnLua/issues/40)里说过了
