### ISSUE TITLE
对于非UObject子类缺少一个New函数

### ISSUE THREAD

**Issue by litianqi** [Tencent/UnLua#12]
需要一个New函数来由类创建实例

**Comment by rowechien** [comment]
能描述的更具体一点吗？
非UObject子类是指反射体系之外的类吧？如果是的话，[Programming Guide](https://github.com/Tencent/UnLua/blob/master/UnLua_Programming_Guide_EN.md)里有详细描述，里面有个导出的Vec3类，Lua里的使用就是local V = Vec3(1,2,3)

**Comment by litianqi** [comment]
对的，是反射体系之外的类，但不是C++定义的，而是完全在Lua中定义的一个Lua类。

**Comment by tary** [comment]
@litianqi lua的类就是Lua表,你要传给C++吗

**Comment by D3ZAX** [comment]
这应该是说的 Unlua.lua文件中的_G.Class方法没有给传进来的表添加new方法的问题，这样没法在lua中直接实例化lua定义的类

**Comment by jarjin2000** [comment]
请问有什么办法实例化lua定义的类吗？还是说借助第三方，这样的话，容易跟模板生成的lua类有差异。

**Comment by rowechien** [comment]
@D3ZAX @jarjin2000 实例lua定义的类，这个可以开发者自己扩展，UnLua.lua中提供的Class()函数构建的lua表是能与引擎类关联的最基本的表格（类），每个开发者自己的需求都不一样，尤其是逻辑代码，插件不会在这方面做过多的事情。
