### ISSUE TITLE
不同蓝图绑定相同lua脚本的问题

### ISSUE THREAD

**Issue by MyJingYu** [Tencent/UnLua#124]
两个Actor蓝图t1,t2  GetModule相同路径的lua脚本，在两个蓝图中都创建函数tlog打印string，在lua脚本的ReceiveBeginPlay中调用蓝图的tlog函数，发现两次打印相同（t1,t2蓝图哪个最后编译打印那个）。

请问大家有这个问题吗，或是我用法不对，谢谢！

**Comment by rowechien** [comment]
@MyJingYu 如果t1, t2这两个蓝图没有继承关系，它们绑定同一个lua模块是不支持的。UnLua只在下面这种情况下支持多个类绑定同一个lua模块：
1. 基类A绑定一个lua模块B；
2. A的子类如果不重新override GetModuleName函数，它们也会绑定B；
3. 如果A的子类重新override GetModuleName函数，需要返回不同于B的lua模块，不然会有逻辑错误。
