### ISSUE TITLE
lua里调用蓝图中声明的远程rpc（run in server），只要在rpc里传字符串数组类型参数，服务器收到的是空字符串

### ISSUE THREAD

**Issue by interlyx** [Tencent/UnLua#125]
这个问题崩溃确实已经解决了，但是如果rpc传递的数组是字符串数组，服务器端收到的字符串都为空。

之前的问题我无法reopen，应该是权限问题。
![image](https://user-images.githubusercontent.com/33210468/76380806-c764cf80-638e-11ea-97a6-efa65dd2936e.png)

**Comment by zh5243a** [comment]
同问

**Comment by rowechien** [comment]
@interlyx @zh5243a fixed in [cc10354 ](https://github.com/Tencent/UnLua/commit/fbd11583ce16a562cab93a732697c50de9bce54f). 对 #77 的修改重新调整了下。。。原因文字比较能描述，但应该没问题了。
