### ISSUE TITLE
部分静态导出的class生成的实例，metatable的__index为metatable本身

### ISSUE THREAD

**Issue by unicodecndddd** [Tencent/UnLua#126]
如TArray，TMap，以及我自己写的一个导出，代码如下：
```cpp
#include "UnLuaEX.h"
#include "Ticker.h"
#include "Delegates/IDelegateInstance.h"

BEGIN_EXPORT_CLASS(FDelegateHandle)
	ADD_CONST_FUNCTION_EX("IsValid", bool, IsValid)
	ADD_FUNCTION(Reset)
END_EXPORT_CLASS()
IMPLEMENT_EXPORTED_CLASS(FDelegateHandle)

BEGIN_EXPORT_CLASS(FTickerDelegate)
END_EXPORT_CLASS()
IMPLEMENT_EXPORTED_CLASS(FTickerDelegate)

BEGIN_EXPORT_CLASS(FTicker)
	ADD_STATIC_FUNCTION(GetCoreTicker)
	ADD_FUNCTION_EX("AddTicker", FDelegateHandle, AddTicker, const FTickerDelegate&, float)
	ADD_FUNCTION(RemoveTicker)
END_EXPORT_CLASS()
IMPLEMENT_EXPORTED_CLASS(FTicker)
```
在蓝图中获得实例后发现如果调用不存在的变量，会触发循环，如：
```lua
local array = UE4.TArray(0)
local test_loop = array.test_loop -- error:'__index' chain too long; possible loop

local map = UE4.TMap(0,0)
local test_loop = map.test_loop -- error:'__index' chain too long; possible loop

local tiker = UE4.FTicker.GetCoreTicker()
local test_loop = tiker.test_loop -- error:'__index' chain too long; possible loop

```

**Comment by rowechien** [comment]
@unicodecndddd 这个确实存在，但不是因为metatable.__index==metatable，而是因为metatable.metatable=metatable，对静态导出的类确实没有这个必要。fixed in [
40c5bec](https://github.com/Tencent/UnLua/commit/40c5beccaaa39c2f3de45532231d545af7035bbd)

**Comment by rowechien** [comment]
@unicodecndddd 这个问题可能还没有好的办法，如果不设置metatable.metatable=metatable会影响到元方法的调用，典型的就是__call，也就是local Array = TArray(0)这种调用就失败了。。。我把上面的commit回滚了

**Comment by unicodecndddd** [comment]
metatable.__index==metatable和metatable.metatable=metatable同时存在就会出现问题。如果metatable.metatable=metatable不好改，可以试试改把metatable.__index==metatable改成metatable.__index==functiion。我发现目前给super使用的方法正好合适。我这边暂时改成了
```cpp
lua_pushstring(L, "__index");
lua_pushvalue(L, -2);
//if (Properties.Num() > 0 || SuperClassName != NAME_None)
//{
//    lua_pushcclosure(L, UnLua::Index, 1);
//}
lua_pushcclosure(L, UnLua::Index, 1);
lua_rawset(L, -3);

lua_pushstring(L, "__newindex");
lua_pushvalue(L, -2);
//if (Properties.Num() > 0 || SuperClassName != NAME_None)
//{
//    lua_pushcclosure(L, UnLua::NewIndex, 1);
//}
lua_pushcclosure(L, UnLua::NewIndex, 1);
lua_rawset(L, -3);
```
可以解决循环问题也不会造成__call无法调用。暂时使用一阵，看看有没有其他问题。

**Comment by rowechien** [comment]
@unicodecndddd 你这个修改没有问题，插件里原来就是这样写的，只所以改成在if (Properties.Num() > 0 || SuperClassName != NAME_None)才设置成metatable.__index==function是因为性能的考虑，metatable.__index==function性能要低于metatable.__index==metatable不少，你自己可以测试下。
当导出的类没有成员变量且没有父类的情况下设置为metatable.__index==function是没有必要的，当然如果纠结于这个问题就这样改吧。
