### ISSUE TITLE
请问如何集成第三方库？

### ISSUE THREAD

**Issue by Junho2009** [Tencent/UnLua#13]
如pbc、lua-rapidjson等。

**Comment by rowechien** [comment]
插件本身只依赖了Lua。
如果你需要在插件层集成这些可以放在Plugins\UnLua\Source\ThirdParty，和Lua平行。
还有一种方式是在工程层面集成，具体你需要选择合适自己的方案。

**Comment by Junho2009** [comment]
> 插件本身只依赖了Lua。
> 如果你需要在插件层集成这些可以放在Plugins\UnLua\Source\ThirdParty，和Lua平行。
> 还有一种方式是在工程层面集成，具体你需要选择合适自己的方案。

好的，谢谢。
补充一下目前的做法：在自己的框架模块中集成，尽可能避免对UnLua插件产生侵入式改动。
如pbc，直接把源码放到框架Private下的某个子目录，如“Lua/Extra/PBC”，跟着框架代码一起编译即可。对于把“protobuf.c”导出给lua，也是在框架的lua层去做。目前是侦听UnLua的“OnLuaStateCreated”，在广播时处理。

**Comment by jarjin2000** [comment]
请问，我按照你们的方法把PBC跟着工程框架代码一起编译，在编辑器下面运行OK，但是在dedicated server模式下，直接protobuff.c找不到，
![image](https://user-images.githubusercontent.com/15137027/72135609-e4e2e080-33c1-11ea-8321-afbc1eec5b98.png)

我也添加到了package表里面。
![image](https://user-images.githubusercontent.com/15137027/72135666-02b04580-33c2-11ea-9aaf-d2cac1f53998.png)
我们编译DS很麻烦，各种报错，不好调试，我在想是不是被shipping server给剔除代码优化掉了导致的？？求大神指教

**Comment by Junho2009** [comment]
> 请问，我按照你们的方法把PBC跟着工程框架代码一起编译，在编辑器下面运行OK，但是在dedicated server模式下，直接protobuff.c找不到，
> ![image](https://user-images.githubusercontent.com/15137027/72135609-e4e2e080-33c1-11ea-8321-afbc1eec5b98.png)
> 
> 我也添加到了package表里面。
> ![image](https://user-images.githubusercontent.com/15137027/72135666-02b04580-33c2-11ea-9aaf-d2cac1f53998.png)
> 我们编译DS很麻烦，各种报错，不好调试，我在想是不是被shipping server给剔除代码优化掉了导致的？？求大神指教

真机下报读取“protobuf/c.lua”失败这个警告，是正常的，具体可以看"LuaCore.cpp"中【Global_Require】的实现，里面是默认把路径中出现的“.”，全部统一改为"/"，然后尝试去读取的。如果失败，会换另一种方式，如log中显示的“use ori require to load file ...”所示。
你在真机下不能使用PBC么？有没有输出检查过【require "protobuf.c"】的返回值？

**Comment by Junho2009** [comment]
> 请问，我按照你们的方法把PBC跟着工程框架代码一起编译，在编辑器下面运行OK，但是在dedicated server模式下，直接protobuff.c找不到，
> ![image](https://user-images.githubusercontent.com/15137027/72135609-e4e2e080-33c1-11ea-8321-afbc1eec5b98.png)
> 
> 我也添加到了package表里面。
> ![image](https://user-images.githubusercontent.com/15137027/72135666-02b04580-33c2-11ea-9aaf-d2cac1f53998.png)
> 我们编译DS很麻烦，各种报错，不好调试，我在想是不是被shipping server给剔除代码优化掉了导致的？？求大神指教

@jarjin2000 
真机下报读取“protobuf/c.lua”失败这个警告，是正常的，具体可以看"LuaCore.cpp"中【Global_Require】的实现，里面是默认把路径中出现的“.”，全部统一改为"/"，然后尝试去读取的。如果失败，会换另一种方式，如log中显示的“use ori require to load file ...”所示。
你在真机下不能使用PBC么？有没有输出检查过【require "protobuf.c"】的返回值？

**Comment by jarjin2000** [comment]
> > 请问，我按照你们的方法把PBC跟着工程框架代码一起编译，在编辑器下面运行OK，但是在dedicated server模式下，直接protobuff.c找不到，
> > ![image](https://user-images.githubusercontent.com/15137027/72135609-e4e2e080-33c1-11ea-8321-afbc1eec5b98.png)
> > 我也添加到了package表里面。
> > ![image](https://user-images.githubusercontent.com/15137027/72135666-02b04580-33c2-11ea-9aaf-d2cac1f53998.png)
> > 我们编译DS很麻烦，各种报错，不好调试，我在想是不是被shipping server给剔除代码优化掉了导致的？？求大神指教
> 
> @jarjin2000
> 真机下报读取“protobuf/c.lua”失败这个警告，是正常的，具体可以看"LuaCore.cpp"中【Global_Require】的实现，里面是默认把路径中出现的“.”，全部统一改为"/"，然后尝试去读取的。如果失败，会换另一种方式，如log中显示的“use ori require to load file ...”所示。
> 你在真机下不能使用PBC么？有没有输出检查过【require "protobuf.c"】的返回值？

这个我知道，不是手机，是PC的dedicated server服务器shipping server模式下运行会卡住，编辑器里面完美运行。

**Comment by jarjin2000** [comment]
客户端的standalone也没问题，只有服务器模式不行，我们部分lua代码要运行在服务器上，所以需要解决这个问题，unlua的引擎功能没问题，所以我在想是不是这种随着工程代码打包的方式，会不会在编译服务器版本的时候被优化掉导致的，还是说只能跟unlua一样，以plugins的方式运行？？？

**Comment by jarjin2000** [comment]
搞清楚了，因为只有在cook数据的时候，走Global_Require重载函数，在里面检查了loaded表
![image](https://user-images.githubusercontent.com/15137027/72232593-18f61580-35fd-11ea-8691-b96d187decb9.png)
但是pbc的protobuf.c并不在这个表里面，所以走了加载实体lua文件的流程，lua文件又不存在，所以导致警告报错。这个地方有点问题吧？希望作者能及时修复。多谢！！！

**Comment by hxhb** [comment]
> 搞清楚了，因为只有在cook数据的时候，走Global_Require重载函数，在里面检查了loaded表
> ![image](https://user-images.githubusercontent.com/15137027/72232593-18f61580-35fd-11ea-8691-b96d187decb9.png)
> 但是pbc的protobuf.c并不在这个表里面，前面，我们只添加到preload表里面，所以走了加载实体lua文件的流程，lua文件又不存在，所以导致警告报错。这个地方有点问题吧？希望作者能及时修复。多谢！！！

你好，这个你怎么解决的呢，我看官方还是没有修复这个问题。
