### ISSUE TITLE
lua调用返回值为TMap<XXX, AActor*>的函数时，获得的TMap无法正常使用

### ISSUE THREAD

**Issue by unicodecndddd** [Tencent/UnLua#130]
测试代码如下：
```cpp
UClass()
class XXXX {
public:
	UFUNCTION()
	TMap<FString, AActor*> GetMap(const UObject* WorldContextObject);
}


TMap<FString, AActor*> XXXX::GetMap(const UObject* WorldContextObject)
{
	TArray<AActor*> OutActors;
	UGameplayStatics::GetAllActorsOfClass(WorldContextObject, AActor::StaticClass(), OutActors);

	TMap<FString, AActor*> OutMap;
	for (auto& Actor : OutActors)
	{
		OutMap.Add(Actor->GetName(), Actor);
	}
	return OutMap;
}
```
lua中获得的TMap调用ToTable()会crash

描述有点歧义，是一个UCLASS下的一个UFUNCTION

**Comment by rowechien** [comment]
@unicodecndddd 这是某个UCLASS下的一个UFUNCTION？或者是某个全局函数，然后静态导出到lua?

**Comment by unicodecndddd** [comment]
描述有点歧义，是一个UCLASS下的一个UFUNCTION

**Comment by rowechien** [comment]
@unicodecndddd fixed in [7ee4ad2](https://github.com/Tencent/UnLua/commit/7ee4ad2c058092f779bd68b3fc27b72b731c205f)

**Comment by rowechien** [comment]
@unicodecndddd 忘了说了，如果这是一个非UFUNCTION，也可以用静态导出的方式在Lua中使用，具体方法如下：
![image](https://user-images.githubusercontent.com/7972243/77219413-892a9580-6b70-11ea-8198-bda1d862f46c.png)
不过需要先更新一下最新的commit [8483d2c](https://github.com/Tencent/UnLua/commit/8483d2ce6b9ed07a5a6cafd31a13cab4b4bd1d47)
