### ISSUE TITLE
父类绑定Lua,然后使用子类会崩溃

### ISSUE THREAD

**Issue by xermao** [Tencent/UnLua#133]
![TIM图片20200320203837](https://user-images.githubusercontent.com/9378718/77164247-d106d980-6aea-11ea-8e53-a678f948afce.png)
![TIM图片20200320203845](https://user-images.githubusercontent.com/9378718/77164254-d2d09d00-6aea-11ea-97f5-04a5aeabde8e.png)

反复测试后，问题描述如下，当我有一个Controller类C1,然后用C1创建了一个子类C2,然后给C1绑定一个Lua文件，再使用C2，就肯定会崩溃。重现几率100%。Actor没这个问题，Controller才会触发。Character应该也会触发，但是我没测试。

**Comment by xermao** [comment]
又测试了一下，发现只有当类为Controller的时候才有这个问题，Actor没问题。
出现错误的函数为bool UUnLuaManager::ReplaceInputs(AActor *Actor, UInputComponent *InputComponent)
可能只有Controller才需要执行这个函数

**Comment by rowechien** [comment]
@xermao fixed in [62e79ab](https://github.com/Tencent/UnLua/commit/62e79ab795e43ca34e488e6ed0f8bca3ba92f3fd)
