### ISSUE TITLE
能够为同一类型的不同实例绑定不同的lua脚本吗？

### ISSUE THREAD

**Issue by hxhb** [Tencent/UnLua#134]
如题，看了一下`Global_NewObject`中的实现：

```cpp
FScopedLuaDynamicBinding Binding(L, Class, ANSI_TO_TCHAR(ModuleName), TableRef);
UObject *Object = StaticConstructObject_Internal(Class, Outer, Name);
```
是动态绑定到UClass的，理解unlua的实现是要通过覆写CDO的信息来实现覆写，有可能实现绑定到不同对象实例吗？

**Comment by rowechien** [comment]
@hxhb 不支持的。覆写不会修改CDO。
细节都在[How to Implement Overriding](https://github.com/Tencent/UnLua/blob/master/How_To_Implement_Overriding.md)里
