### ISSUE TITLE
无限循环调用

### ISSUE THREAD

**Issue by xermao** [Tencent/UnLua#136]
我有一个Controller1，绑定了一个Lua,然后有个子类Controller2,我在游戏里用的是Controller2.
Controller2的BeginPlay里调用了Parent:BeginPlay.
在Controller1绑定的Lua里，覆盖了ReceiveBeginPlay，然后在lua的ReceiveBeginPlay函数里调用了self.Overridden.ReceiveBeginPlay(self)

运行游戏会出现无限循环调用。

我猜测是因为self.Overridden.ReceiveBeginPlay(self)调用的是Controller2里的BeginPlay，然后由于这个BeginPlay调用了Controller1里被覆盖的BeginPlay而不是Controler1里原本的BeginPlay.
那么有没有办法让lua里的self.Overridden.ReceiveBeginPlay(self)调用Controller1里的BeginPlay,或者让蓝图Controller2可以调用Controller1里原本的BeginPlay.

**Comment by rowechien** [comment]
@xermao fixed in [b6ab88f](https://github.com/Tencent/UnLua/commit/b6ab88f01636b2d4895ad9ae6e5cc87fec675c90)
