### ISSUE TITLE
GameInstance绑定lua会Crash

### ISSUE THREAD

**Issue by hxhb** [Tencent/UnLua#137]
Crash位置是在LuaCore.cpp的`NewLuaObject`中，是GameInstance不可以绑定lua吗？

```cpp
#if ENABLE_CALL_OVERRIDDEN_FUNCTION
    lua_pushstring(L, "Overridden");
    lua_pushvalue(L, -2);
    lua_rawset(L, -4); // crash point
#endif
```

**Comment by rowechien** [comment]
@hxhb 我试了下没有发现crash啊... GameInstance创建的时间点很早，在UnLua初始化之前，所以对GameInstance的绑定有些特殊处理，带来的问题是如果Lua里覆写了GameInstance的ReceiveInit函数，可能无法正常调用，其他应该没有什么问题。应该是别的地方出问题，你可以具体描述下，或者贴代码出来，或者github上建个测试工程我来调试

**Comment by hxhb** [comment]
> @hxhb 我试了下没有发现crash啊... GameInstance创建的时间点很早，在UnLua初始化之前，所以对GameInstance的绑定有些特殊处理，带来的问题是如果Lua里覆写了GameInstance的ReceiveInit函数，可能无法正常调用，其他应该没有什么问题。应该是别的地方出问题，你可以具体描述下，或者贴代码出来，或者github上建个测试工程我来调试

抱歉，是我的lua文件里漏掉了return BP_GameInstance_C
