### ISSUE TITLE
纯c++用IUnLuaInterface实现的绑定，会无法重写部分BlueprintEvent

### ISSUE THREAD

**Issue by unicodecndddd** [Tencent/UnLua#138]
例如UActorComponent的ReceiveBeginPlay、ReceiveEndPlay、ReceiveTick。AActor的ReceiveTick
主要原因是UActorComponent的对应方法都有一条类似如下的判断：
```c++
if (GetClass()->HasAnyClassFlags(CLASS_CompiledFromBlueprint))
{
	ReceiveBeginPlay();
}
```
必须从蓝图绑定才会调用对应方法，但对于一些c++类是无法创建出蓝图类的，如一个在c++中定义的Component。
针对类似情况有没有统一的应对方法？例如给绑定的class统一添加CLASS_CompiledFromBlueprint的flag（但不知道这个标记会不会造成其他问题），或者创建ULuaActorComponent将对应方法统一重写一遍？

**Comment by rowechien** [comment]
@unicodecndddd 这个问题很早就注意到了，没有什么好办法，好在ReceiveBeginPlay, ReceiveTick这类函数都是虚函数，只能在你的C++类里override这些函数，然后在实现的地方去除GetClass()->HasAnyClassFlags(CLASS_CompiledFromBlueprint)检查。
