### ISSUE TITLE
多继承层次里不能覆写接口的方法吗？

### ISSUE THREAD

**Issue by hxhb** [Tencent/UnLua#139]
现在有一个UE接口ITestInterface，并声明了一个UFUNCTION函数：
```cpp
UFUNCTION(Category = "GameCore|GamePlayFramework")
	virtual bool Tick(float delta) = 0;
```
然后有一个对象UTestObject继承了这个接口，并实现了接口中的方法：
```
virtual void Tick(float delta)override{}
```
从这个UTestObject继承一个蓝图子类，在这个蓝图子类上挂载`IUnLuaInterface`并指定lua脚本，在绑定的lua里无法覆写`ITestInterface`接口里的Tick函数，外面调不到。

**Comment by hxhb** [comment]
描述有误，是这样：
现在有一个UE接口ITestInterface，并声明了一个UFUNCTION函数：
```cpp
UFUNCTION(Category = "GameCore|GamePlayFramework")
	virtual bool Tick(float delta) = 0;
```
然后有一个对象UTestObject继承了这个接口，并实现了接口中的方法：
```
virtual void Tick(float delta)override{}
```
从这个UTestObject继承一个蓝图子类，在这个蓝图子类上挂载`IUnLuaInterface`并指定lua脚本，在绑定的lua里无法覆写`ITestInterface`接口里的Tick函数，外面调不到。

**Comment by hxhb** [comment]
只能够覆写是BlueprintNativeEvent和BlueprintImplementationEvent才可以吧？

**Comment by rowechien** [comment]
@hxhb 你这种情况是不支持的。
![image](https://user-images.githubusercontent.com/7972243/77714207-6d613c80-7013-11ea-9e6b-84bb0803f2cf.png)
