### ISSUE TITLE
请问和 sluaunreal 有一些什么区别呢？

### ISSUE THREAD

**Issue by HiddenFox** [Tencent/UnLua#14]
还没有使用，所以问得比较基础，如果可以的话，麻烦解答一下，谢谢。

**Comment by HiddenFox** [comment]
性能和profiling方面貌似没有找到相关说明。可以介绍一下和cpp BP的对比吗

**Comment by rowechien** [comment]
基本功能不会有太大的区别，主要是设计思路、编程模式还有实现细节、优化的区别，你可以先看下readme和programming guide，如果没感觉到区别我觉得可以实际用一下。
性能方面我们自己是做过对比的，但这方面数据你可能需要自己去profiling一下了，比如一个简单Case，循环1000000次创建FHitResult。
	for i=1,1000000 do
		local V = FHitResult()
	end
