### ISSUE TITLE
在PIE中运行Gameinstance::Shutdown之后的调用都不会调用到lua

### ISSUE THREAD

**Issue by hxhb** [Tencent/UnLua#140]
看了下代码，是因为`LuaContext.cpp`中写了在`PrePIEEnd`中执行了清理操作：

```cpp
void FLuaContext::PrePIEEnded(bool bIsSimulating)
{
     bIsPIE = false;
     Cleanup(true);
     Manager->CleanupDefaultInputs();
     ServerWorld = nullptr;
     LoadedWorlds.Empty();
     CandidateInputComponents.Empty();
     FWorldDelegates::OnWorldTickStart.Remove(OnWorldTickStartHandle);
}
```
但是在编辑器下PrePIEEnd是先于`GameInstance::Shutdown`的，导致`GameInstance::Shutdown`里所有的调用都不会执行到lua里，Standalone模式没有这个问题。

**Comment by rowechien** [comment]
@hxhb fixed in [7a5ad8c](https://github.com/Tencent/UnLua/commit/7a5ad8c69c0c045f1351606f03c7fe2da5ecd2f4)
