### ISSUE TITLE
Globaal_Require不会查找Preload表里的模块

### ISSUE THREAD

**Issue by hxhb** [Tencent/UnLua#143]
看了下`LuaCore.cpp`里实现的`Globaal_Require`实现，会查找loaded表和查找lua文件，但是不会查找preload表里的模块。

**Comment by rowechien** [comment]
@hxhb 会的吧，Global_Require之前确实是有bug，后来我的同事帮我修正了。
你注意看FindLuaLoader函数，这段代码基本就是lua的源代码，就是为了处理loaded表查找和lua文件加载都失败的情况。package.searchers在调用luaL_openlibs时就已经设置了。
![image](https://user-images.githubusercontent.com/7972243/78423627-2ff75180-769a-11ea-99f1-d857ab68d739.png)
