### ISSUE TITLE
TSoftObjectPtr<UTexture2D>参数的问题

### ISSUE THREAD

**Issue by gokutek** [Tencent/UnLua#147]
在C++类中定义了一个TSoftObjectPtr成员：
`TSoftObjectPtr<UTexture2D> Photo;`
lua中拿到该对象后，使用该对象的Photo成员调用UImage::SetBrushFromSoftTexture失败，
跟踪发现，从LUA调用过来后TSoftObjectPtr<UTexture2D>参数中的AssetPath为空。

在C++中强制Load一下该soft object后可以临时解决该问题：
`Photo.LoadSynchronous()`

**Comment by rowechien** [comment]
@gokutek TSoftObjectPtr保存的其实是Asset的路径，和直接的Asset指针引用（hard reference）不同，你在使用它前确实需要手动把它加载进来的，不管是同步或者异步，总之要有一个加载的操作。而且如果加载进来的Asset没有其他地方保留引用还是会被GC的，它内部是一个FWeakObjectPtr。官方也应该有文档说明的，你可以找找。

**Comment by gokutek** [comment]
可能由于我没表述清楚。

UImage::SetBrushFromSoftTexture的内部实现已经帮助我们去异步加载资源了，这是没有问题的。问题出在TSoftObjectPtr属性在LUA和C++间传递时，其中的AssetPath丢了。

下面是测试代码：

**C++代码**：
```
UCLASS()
class UMyUserWidget : public UUserWidget
{
	GENERATED_BODY()
	
public:
	UFUNCTION(BlueprintCallable)
	void TestSoftObjectPtr(TSoftObjectPtr<UTexture2D> Param);

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly)
	TSoftObjectPtr<UTexture2D> Photo;
};
```
蓝图继承自上面的C++类，并给Photo赋好值。
**LUA代码**：
```
function WB_MyUserWidget_C:OnClicked_TestButton()
    self:TestSoftObjectPtr(self.Photo)
end
```


然后我跟进UnLua插件的代码里看了下：
```
virtual void FObjectPropertyDesc::GetValueInternal(lua_State *L, const void *ValuePtr, bool bCreateCopy) const override
    {
        if (Property->ArrayDim > 1)
        {
            PushObjectArray(L, ObjectBaseProperty, (void*)ValuePtr);
        }
        else
        {
            // 这里会push一个nil进去
            UnLua::PushUObject(L, ObjectBaseProperty->GetObjectPropertyValue(ValuePtr));
        }
    }
```

**Comment by rowechien** [comment]
@gokutek fixed in [106fa9c](https://github.com/Tencent/UnLua/commit/106fa9c3a1a75b4af0e3e6b7e61b0c45609dd53d)
