### ISSUE TITLE
创建出来的TArray(EObjectTypeQuery)无法正常使用

### ISSUE THREAD

**Issue by unicodecndddd** [Tencent/UnLua#149]
创建TArray(EObjectTypeQuery)一旦调用Add就会crash
```lua
local ObjectTypes = TArray(EObjectTypeQuery)
ObjectTypes:Add(EObjectTypeQuery.Player) -- crash
```
检查发现在TArray创建时ElementSize为0。于是Add时用ElementSize申请内存出错。

**Comment by rowechien** [comment]
@unicodecndddd fixed in [2734aec](https://github.com/Tencent/UnLua/commit/2734aec34e0a9f1db85d84971b9596a8c7b7ae85)
