### ISSUE TITLE
Runtime改动过.lua脚本如何马上生效？

### ISSUE THREAD

**Issue by Checkmate** [Tencent/UnLua#155]
是需要重新注册指定的ModuleName脚本吗？有没有什么方便的API。

**Comment by rowechien** [comment]
@Checkmate 你是问热更新吗？插件这一层没有提供这个层面的功能，插件只专注于与引擎通讯的部分，热更新的模块是在这之上的，这部分没有开源，而且各项目也会有自己的相关方案。

**Comment by hxhb** [comment]
> @Checkmate 你是问热更新吗？插件这一层没有提供这个层面的功能，插件只专注于与引擎通讯的部分，热更新的模块是在这之上的，这部分没有开源，而且各项目也会有自己的相关方案。

有大概的思路可以介绍一下吗？

**Comment by chuqiuhan** [comment]
插件里LuaContext.cpp中有一部分处理
![image](https://user-images.githubusercontent.com/22808335/80345155-478db880-889b-11ea-8524-4321f9d59bb9.png),你可以自己做lua部分,然后调用它
