### ISSUE TITLE
lua的object支持直接赋值? 

### ISSUE THREAD

**Issue by 2047241149** [Tencent/UnLua#157]
![image](https://user-images.githubusercontent.com/19194474/79658148-ee13f280-81e5-11ea-8497-0820c7fd4f50.png)

比如我这样的代码,  感觉如果能做到这样，很多业务逻辑写起来会方便很多

**Comment by rowechien** [comment]
@2047241149 不支持，有一个全局函数（NewObject）可以创建UObject，但至少要有一个参数，你可以先了解下UE里面怎样创建UObject

**Comment by 2047241149** [comment]
我的这里 item_object 本身就是UOject对象了,但是我想保存一个table变量到UObject里，有啥办法？

**Comment by 2047241149** [comment]
在python里很容易实现这样的(继承UObject)，就是不知道Lua怎么搞
