### ISSUE TITLE
成功导出了intellisense类型信息，如何结合vsCode或者其他ide用于代码提示？

### ISSUE THREAD

**Issue by futouyiba** [Tencent/UnLua#16]
btw，导出的方法是在unLua intellisense的build文件里把对应的开关开成1.
然后如何使用呢？

当然，如果只能配合g6 ide使用，g6 ide会在何时开源呢？是否有相关的时间表？

**Comment by tangzx** [comment]
G6IDE开放暂时还没有时间表，不过你可以先用[`EmmyLua`](https://github.com/EmmyLua)作为编辑器，`EmmyLua`提供`IDEA`插件和`VSCode`插件两个版本。G6IDE自带的Lua编辑即是从`EmmyLua`上扩展而来，所以它们是兼容的。

使用方法就是将intellisense目录配置到你的 `IDEA`项目或者是`VSCode`项目中即可

**Comment by rowechien** [comment]
UnLuaIntellisense生成的符号信息现在用在我们自己的内部IDE中使用，这个IDE不久后应该也会开放出来。另外，EmmyLua的作者就是我们团队中的一员。。。

**Comment by futouyiba** [comment]
> 你可以先用[`EmmyLua`](https://github.com/EmmyLua)作为编辑器，`EmmyLua`提供`IDEA`插件和`VSCode`插件两个版本。即将开放的G6IDE自带的Lua编辑即是从`EmmyLua`扩展而来，所以它们在Lua代码编辑上来说功能是相近的。
> 
> 使用方法就是将intellisense目录配置到你的 `IDEA`项目或者是`VSCode`项目中即可.
> 
> UnLua生成的代码提示文件中大量用到了`EmmyLua`特性: `注解`，建议了解一下，关于注解的文档 https://emmylua.github.io/zh_CN/annotation.html

非常感谢。“life saver”！

**Comment by futouyiba** [comment]
> UnLuaIntellisense生成的符号信息现在用在我们自己的内部IDE中使用，这个IDE不久后应该也会开放出来。另外，EmmyLua的作者就是我们团队中的一员。。。

国人对于lua的生态看来真的领先，让我小小激动一下……

**Comment by futouyiba** [comment]
> 你可以先用[`EmmyLua`](https://github.com/EmmyLua)作为编辑器，`EmmyLua`提供`IDEA`插件和`VSCode`插件两个版本。即将开放的G6IDE自带的Lua编辑即是从`EmmyLua`扩展而来，所以它们在Lua代码编辑上来说功能是相近的。
> 
> 使用方法就是将intellisense目录配置到你的 `IDEA`项目或者是`VSCode`项目中即可.
> 
> UnLua生成的代码提示文件中大量用到了`EmmyLua`特性: `注解`，建议了解一下，关于注解的文档 https://emmylua.github.io/zh_CN/annotation.html

请问这个将intellisense目录配置到你的 `IDEA`项目或者是`VSCode`项目中即可，怎么做？把整个文件夹拷进来？

**Comment by futouyiba** [comment]
为了让搜索到这里的小伙伴得到参考，我把其他问题回答中的图粘贴过来：
[https://user-images.githubusercontent.com/3354360/63837857-d49c0d00-c9ae-11e9-8c2a-fb9d7afc675c.gif](url)

![Unlua-EmmyLua](https://user-images.githubusercontent.com/6793989/65372052-61c83e00-dc9d-11e9-8754-fa2a921571e7.gif)

**Comment by deqiu** [comment]
为什么我导出的类会有一些缺失，比如slate模块就缺失了，是哪里配置出问题了吗

**Comment by shudal** [comment]
> 为了让搜索到这里的小伙伴得到参考，我把其他问题回答中的图粘贴过来： [https://user-images.githubusercontent.com/3354360/63837857-d49c0d00-c9ae-11e9-8c2a-fb9d7afc675c.gif](url)
> 
> ![Unlua-EmmyLua](https://user-images.githubusercontent.com/6793989/65372052-61c83e00-dc9d-11e9-8754-fa2a921571e7.gif)

好！
