### ISSUE TITLE
编译时 UnLuaBase.h 编译找不到 UnLuaCompatibility.h

### ISSUE THREAD

**Issue by tary** [Tencent/UnLua#160]
是否应该把 UnLuaCompatibility.h 放到Public里
或者 
`#include "UnLua/Private/UnLuaCompatibility.h"`
也能过

环境 UE 4.24.2

**Comment by rowechien** [comment]
@tary fixed in [b46462a](https://github.com/Tencent/UnLua/commit/b46462a6b55aa6d5aee1decf45e66a5eb31446b2)
