### ISSUE TITLE
打包后lua加密问题

### ISSUE THREAD

**Issue by CengJia** [Tencent/UnLua#161]
首先很感谢你们做这个lua插件，真的非常好用，多谢。。。我遇到的问题是打包后，用引擎自带的打包工具解包pak后，其他资源文件都是加密了，但是lua文件都是原原本本的lua文件。。。请问是要怎么加密lua呢？

**Comment by rowechien** [comment]
@CengJia 首先感谢你的肯定！插件里确实没有对lua文件进行处理，因为即使插件做了，开发者也会修改的，不然都用相同的处理方式，那这个处理本身也就没意义了，所以干脆就留给开发者自己定制了。你们可以考虑将lua文件预编译好，也就是用luac处理一遍，然后再做些其他的处理，总之这一块的自由度留给了开发者。
