### ISSUE TITLE
以后会支持一个class的两个变量绑定不同的lua脚本吗

### ISSUE THREAD

**Issue by ttaw** [Tencent/UnLua#162]
现在好像不行，即使使用动态绑定也不行。以后会支持这样的特性吗？

**Comment by rowechien** [comment]
@ttaw 你的意思是为同一个class的不同实例绑定不同脚本对吗？现在插件里的绑定（不管是动态绑定、还是静态绑定）都是在UClass层面而不是实例层面，但是还是有办法做到的。这种场景很常见吗，有大量的需求么。。。

**Comment by ttaw** [comment]
我觉得这个场景比较常见吧。比如游戏里的npc，他们character有一个对话Dialogue组件用于控制玩家与自己的对话。现在只能给每一个npc的Dialogue组件（或者character）生成一个类，如果npc数量很多，就会导致需要制作大量的子类，他们只是绑定的lua脚本不同。如果npc数量有1000个，我就得制作1000种子类，太不方便了。我希望是在场景中拖入很多个相同的类，然后改改其中的一个lua脚本名，最后就可以调用不同的lua逻辑，这个功能不知道好不好做。只要提供一个函数，让我绑定一个对象和lua脚本就行，即使不能自动调用ReceiveBeginPlay或者Initialize我都可以接受。

**Comment by ttaw** [comment]
@rowechien

**Comment by rowechien** [comment]
@ttaw 我了解，目前插件的实现做到这个比较麻烦，为啥绑定是在class层面，我举个例子，假设绑定在实例层面，例如某个Actor类的2个不同实例分别绑定了2个不同的lua模块，而且这2个lua模块分别覆写了类的某个blueprint event，例如ReceiveBeginPlay，这种情况下，ReceiveBeginPlay这个UFUNCTION的实现到底用哪个？
我再考虑一下怎样做能比较优雅的解决这个问题。

**Comment by ttaw** [comment]
@rowechien ，这种情况下2个实例各自使用自己覆写的ReceiveBeginPlay函数，如果是没有绑定lua的这个actor类则不调用任何lua函数就可以了吧。

**Comment by ttaw** [comment]
@rowechien 
想到了一种可能的解决方式，你看看有没有问题：还是用现有class层面的方案，我对character类的Dialogue类只绑定一个lua模块总类，然后在这个lua模块里保存一个映射表luatable，记录所有npc的dialogue对象到该对象需要对应的lua对象的映射，然后对不同的npc从映射表luatable里获取对应的lua对象，然后对该lua对象执行逻辑判断。比如有两个npc（A和B），他们对应的lua逻辑模块是luaA和luaB，但是luaA和luaB为纯lua类，不绑定任何npc；Dialogue类的lua模块总类是luaDialogue，那么：
luaA的实现为local function luaA:GetDialogueText() return 'A' end
luaB的实现为local function luaB:GetDialogueText() return 'B' end
总类的实现为local function luaDialogue:GetDialogueText() 
  lcoal id = self:GetNpcID()
  local moduleName = self:GetNpcLuaModuleName()
  if self.DialogMap==nil then
    self.DialogMap = {}
  end
  if self.DialogMap[id] == nil then
      local luaModule = require moduleName
      self.DialogMap[id] = luaModule
  end
  local luaMod = self.DialogMap[id] 
  return luaMod:GetDialogueText()
end
这样有没有问题？

**Comment by ttaw** [comment]
有关于lua的两个问题（对lua不太熟）：
1.self.DialogMap是对所有npc共享的吗？
2.require moduleName能正常工作吗？moduleName是一个字符串变量，而不是一个字符串字面值("test"这种)
如果不是，这种方法就行不通了

**Comment by rowechien** [comment]
@ttaw 这种方式对开发者不友好，让我考虑下吧

**Comment by ttaw** [comment]
@rowechien ，现在我是这样做的，可能不需要加入对实例的绑定了：

我对character类的Dialogue类只绑定一个lua模块类，然后在这个lua模块的self里保存一个变量CompReal，记录该实例对应的lua对话对象，然后对话逻辑通过这个lua对话对象实现。比如有两个npc（A和B），他们对应的lua逻辑模块是luaA和luaB，但是luaA和luaB为纯lua类，不绑定任何npc；Dialogue类的lua模块总类是luaDialogue，那么：
luaA的实现为local function luaA:GetDialogueText() return 'A' end
luaB的实现为local function luaB:GetDialogueText() return 'B' end
Dialogue总类的实现为：
function DialogueComp:ReceiveBeginPlay()
	local moduleName = self:GetOwner().LuaDialogFile
	if moduleName ~= nil and moduleName ~= '' then
		self.CompReal = Inherit(require(moduleName))
		if self.CompReal ~= nil then
			self.CompReal.Hub = self
		end
	end
end
function DialogueComp:GetDialogueText()
	if self.CompReal ~= nil then
		return self.CompReal:GetDialogueText()
	end
	return false
end
这样应该就可以了。

**Comment by rowechien** [comment]
@ttaw 能解决就好了。实例层面进行绑定我也有点想法，有空时我会尝试一下，现在暂时不动了。
