### ISSUE TITLE
绑了UnLua的用C++实现的单例在Editor模式下停止游戏再开始游戏绑定失效

### ISSUE THREAD

**Issue by zhangweiiscoding** [Tencent/UnLua#164]
实现如图，
![图片](https://user-images.githubusercontent.com/50471110/80368160-dd870a80-88be-11ea-853a-12e05f869be7.png)
![图片](https://user-images.githubusercontent.com/50471110/80368219-f1cb0780-88be-11ea-9110-87c0ee58b807.png)
调用如下：
![图片](https://user-images.githubusercontent.com/50471110/80368269-08715e80-88bf-11ea-9edb-7a6b1ab5f48e.png)
![图片](https://user-images.githubusercontent.com/50471110/80368292-10310300-88bf-11ea-86f5-3059ae9ae497.png)
日志显示第一次是这样的：
![图片](https://user-images.githubusercontent.com/50471110/80368328-22ab3c80-88bf-11ea-88d2-6e7cb34fbfe0.png)
停止游戏再开始游戏是这样的：
![图片](https://user-images.githubusercontent.com/50471110/80368387-3d7db100-88bf-11ea-9734-19161913db7b.png)

d

**Comment by rowechien** [comment]
@zhangweiiscoding 所有UObject对象都是在创建时绑定，你这种情况确实不行。停止游戏后你需要把Instance指针清空的
