### ISSUE TITLE
碰上得声明一个委托变量的怎么办？

### ISSUE THREAD

**Issue by 2047241149** [Tencent/UnLua#170]
`	比如下面C++代码中的 "FWidgetAnimationDynamicEvent FinishEvent;"
`
//BindAnim Event And Start Play Animation
	UWidgetAnimation* FloatAniamtion = GetWidgetAnimation("FloatAnimation");
	if (nullptr != FloatAniamtion)
	{
		FWidgetAnimationDynamicEvent FinishEvent;
		FinishEvent.BindDynamic(this, &UFloatWindow::FloatAnimFinish);
		BindToAnimationFinished(FloatAniamtion, FinishEvent);
		PlayAnimation(FloatAniamtion);
	}
`

这个FWidgetAnimationDynamicEvent FinishEvent是得单独声明的委托变量，然后传入BindToAnimationFinished函数。我模仿源码FScriptDelegate的导出lua接口:
`
int32 UWidgetAnimation_BindAnimtionFinishEvent(lua_State* L)
{
	int32 NumParams = lua_gettop(L);
	if (NumParams != 3)
	{
		UE_LOG(LogUnLua, Warning, TEXT("%s: Invalid parameters!"), ANSI_TO_TCHAR(__FUNCTION__));
		return 0;
	}
	UWidgetAnimation *Animation = Cast<UWidgetAnimation>(UnLua::GetUObject(L, 1));
	if (!Animation)
	{
		UNLUA_LOGERROR(L, LogUnLua, Error, TEXT("%s: Invalid Animation!"), ANSI_TO_TCHAR(__FUNCTION__));
		return 0;
	}

	UUserWidget *UserWidget = Cast<UUserWidget>(UnLua::GetUObject(L, 2));
	if (!UserWidget)
	{
		UNLUA_LOGERROR(L, LogUnLua, Error, TEXT("%s: Invalid UserWidget!"), ANSI_TO_TCHAR(__FUNCTION__));
		return 0;
	}

	const void *CallbackFunction = lua_topointer(L, 3);
	if (!CallbackFunction)
	{
		UNLUA_LOGERROR(L, LogUnLua, Error, TEXT("%s: Invalid function!"), ANSI_TO_TCHAR(__FUNCTION__));
		return 0;
	}

	FWidgetAnimationDynamicEvent Delegate;
	FCallbackDesc Callback(Animation->GetClass(), CallbackFunction);
	FName FuncName = FDelegateHelper::GetBindedFunctionName(Callback);
	
	if (FuncName == NAME_None)
	{
		lua_pushvalue(L, 3);
		int32 CallbackRef = luaL_ref(L, LUA_REGISTRYINDEX);
		FDelegateHelper::Bind(&Delegate, Animation, Callback, CallbackRef);
	}
	else
	{
		Delegate.BindUFunction(Animation, FuncName);
	}

	UserWidget->BindToAnimationFinished(Animation, Delegate);
	return 1;
}`

lua代码如下：
`self.FloatAnimation:BindAnimtionFinishEvent(self, self.FloatAnimFinish)
function FloatWindow:Construct()
    self.Super.Construct(self)
    self.FloatAnimation:BindAnimtionFinishEvent(self, self.FloatAnimFinish)
end

function FloatWindow:FloatAnimFinish()
    self:Close()
end
`

然而并没啥用，PreBind是访问UObject内部委托变量才会访问的吧？
我想的是要么把函数指针扔到C++，绑定委托。 要么在lua中声明委托变量，然后在扔到C++。

**Comment by rowechien** [comment]
@2047241149 我没理解错的话，你是在lua里调用UUserWidget::BindToAnimationFinished(UUserWidget* Widget, FWidgetAnimationDynamicEvent Delegate)这个函数时不知道该如果传入Delegate这个参数吧。你看看下面的截图就知道了：
![image](https://user-images.githubusercontent.com/7972243/81470008-f080cf80-921a-11ea-830e-5f1723c20dff.png)
