### ISSUE TITLE
打的iOS包找不到Lua文件是什么原因

### ISSUE THREAD

**Issue by HoHooHo** [Tencent/UnLua#171]
![image](https://user-images.githubusercontent.com/2968872/81368011-50934b00-9121-11ea-9e66-1746090bcec5.png)

![image](https://user-images.githubusercontent.com/2968872/81367803-bcc17f00-9120-11ea-9bb6-d066e8537ad6.png)

**Comment by gokutek** [comment]
需要在Project setting目录中将script目录加到package目录里去

**Comment by rowechien** [comment]
@HoHooHo 
![image](https://user-images.githubusercontent.com/7972243/81469067-8c0f4180-9215-11ea-97be-590beb1bbe8d.png)
