### ISSUE TITLE
在One Process模式下启动listenserver,两个客户端,UE4崩溃了,版本4.25.0

### ISSUE THREAD

**Issue by chuqiuhan** [Tencent/UnLua#172]
在Lua中Receive Begin Play方法中调用Overidden的ReceiveBeginPlay方法,编辑器崩溃了
![image](https://user-images.githubusercontent.com/22808335/81404092-53189380-9167-11ea-994b-cf2162477466.png)
![image](https://user-images.githubusercontent.com/22808335/81404724-c078f400-9168-11ea-9863-d72bf6aea736.png)

**Comment by rowechien** [comment]
@chuqiuhan 仅仅这个描述我无法定位问题的，我自己的工程也有使用Overidden，无法重现

**Comment by rowechien** [comment]
@chuqiuhan fixed in [8c25bc0](https://github.com/Tencent/UnLua/commit/8c25bc0defc14b759572273b0f70e786bd33838c)
