### ISSUE TITLE
Character父类绑定Lua, 然后使用子类会崩溃

### ISSUE THREAD

**Issue by HoHooHo** [Tencent/UnLua#173]
https://github.com/Tencent/UnLua/issues/133

Character  现在还有这个问题

![image](https://user-images.githubusercontent.com/2968872/81417891-7438ae80-917e-11ea-97ba-138d086c6bda.png)

**Comment by rowechien** [comment]
@HoHooHo 按 #133 的重现步骤，我本地并没有问题。

**Comment by HoHooHo** [comment]
找到原因了，不好意思是我自己这边的问题，感谢回复！
