### ISSUE TITLE
UGameInstance中创建的UObject对象的生命周期问题

### ISSUE THREAD

**Issue by gokutek** [Tencent/UnLua#174]
在我们的项目中，在UMyGameInstance中会创建一些UObject子类对象，这些对象的生命周期不会随着切换Level而结束。
切换关卡触发`UUnLuaManager::Cleanup`事件，其中这行代码：
```
 luaL_unref(*GLuaCxt, LUA_REGISTRYINDEX, ObjectRef);     // remove Lua reference of Lua instance
```
将UObject与Lua State解除了绑定。所以在切关卡后，这个UObject绑定的Lua就不能再执行了，输出下面的日志：
```
UE_LOG(LogUnLua, Warning, TEXT("UObject instance is still alive, but lua instance is dead... Module Name (%s)"), ANSI_TO_TCHAR(ModuleName));
```

**Comment by rowechien** [comment]
@gokutek luaL_unref这一步操作是必要的，不然会有大量lua实例残留。你这种情况需要在Lua侧保留对应实例(lua table)的引用，最简单的就是全局变量。

**Comment by gokutek** [comment]
> @gokutek luaL_unref这一步操作是必要的，不然会有大量lua实例残留。你这种情况需要在Lua侧保留对应实例(lua table)的引用，最简单的就是全局变量。

对lua不太熟悉，能教教我具体怎么做吗？(是在UnLua.lua中定义个全局变量，保存这个全局UObject对象的引用么) [憨笑]

**Comment by rowechien** [comment]
@gokutek 是在lua中用全局变量保留那些不会在切关时被GC的UObject对象

**Comment by cyc520666** [comment]
那怎么避免出这个警告

**Comment by gokutek** [comment]
> 那怎么避免出这个警告

在Lua中保存这个对象引用，如_G.someObj = UMyBPLib.GetSomeObj()

**Comment by gokutek** [comment]
> 那怎么避免出这个警告

不过我更暴力，直接在GameInstance中创建对象时：
UnLua::PushUObject(L, Module);
FString VarName = Name; //起个名字
lua_setglobal(L, TCHAR_TO_ANSI(*VarName));
