### ISSUE TITLE
怎么导出C++的函数接口给Lua

### ISSUE THREAD

**Issue by eonelv** [Tencent/UnLua#176]
在Lua开发的时候C++接口没有自动提示，有办法导出C++的函数接口吗

**Comment by rowechien** [comment]
@eonelv Programming Guide里有用法说明，或者看代码UnLuaEx.h, UnLuaEx.inl

**Comment by eonelv** [comment]
是的，我看了智能语法提示的描述。  但文档中只有简单的描述，运行UE4项目以后，在Plugins\UnLua\Intermediate中并没有找到IntelliSense目录。
而且没有说明反射体系外的怎么用命令导出

**Comment by rowechien** [comment]
@eonelv 
![image](https://user-images.githubusercontent.com/7972243/81630284-c7895600-9437-11ea-926d-26dd81701475.png)
