### ISSUE TITLE
editor模式下编译蓝图时因gc导致的crash

### ISSUE THREAD

**Issue by zhangweiiscoding** [Tencent/UnLua#177]
步骤：
1.editor模式启动项目，以示例工程为例，在 BP_Game_C.lua的SpawnEnemy函数下加这几行代码：
	local Testclass = self.AICharacterClass
	local Actorclass = UE4.UClass.Load("AActor")
	local TestArray = TArray(Testclass)
	UE4.UGameplayStatics.GetAllActorsOfClass(self, Testclass, TestArray)
如图：
![图片](https://user-images.githubusercontent.com/50471110/82975436-fe9e6080-a00e-11ea-80d9-e218def7c3b3.png)
2.运行游戏，停止游戏
3.编译BP_CharacterBase蓝图，会出现gc crash:
Script Stack (0 frames):

Fatal error: [File:D:/Build/++UE4/Sync/Engine/Source/Runtime/CoreUObject/Private/UObject/GarbageCollectionVerification.cpp] [Line: 323] 
Encountered 116 object(s) breaking GC Clusters assumptions. Please check log for details.
UE4Editor.exe has triggered a breakpoint.

ps:如果将TArray括号内的Testclass换成Actorclass 则不会出现这个问题

**Comment by rowechien** [comment]
@zhangweiiscoding fixed in [04333ec](https://github.com/Tencent/UnLua/commit/04333ecab4fc1fe64a459a790bb1070fabbfeff4)
