### ISSUE TITLE
这种接口在Lua中如何调用？

### ISSUE THREAD

**Issue by gokutek** [Tencent/UnLua#178]
```
UFUNCTION(BlueprintCallable, Category=Animation)
void BindToAnimationStarted(UWidgetAnimation* Animation, FWidgetAnimationDynamicEvent Delegate);
```
文档中有关于Delegates作为对象属性时注册回调的方法。作为函数参数怎么注册呢？

**Comment by 977908569** [comment]
self:BindToAnimationEvent(anim, {self, function() end}, UE4.EWidgetAnimationEvent.Finished)

**Comment by rowechien** [comment]
@gokutek 你可以参考 @977908569 的回复使用。示例工程里也有对应的用法：
![image](https://user-images.githubusercontent.com/7972243/83322647-0b7bb800-a28c-11ea-89f3-04c6395a0837.png)
