### ISSUE TITLE
通过REQUIRED_MODULE无法跨级调用继承的方法

### ISSUE THREAD

**Issue by OneBigShrimp** [Tencent/UnLua#179]
比如A = Class(),   B = Class("A"), C = Class("B")
A中定义了一个纯lua方法OnCreate, B中没覆写这个方法, C中覆写这个方法了, 同时想通过C.Super.OnCreate 来调用父类的方法, 就会报错无法找到这个方法.

**Comment by rowechien** [comment]
@OneBigShrimp 这种跨层级的“继承”，仅仅用Super不行的，你这种情况应该是C.Super.Super.OnCreate这种形式，或者直接A.OnCreate。你可以看看UnLua.lua文件中Super的定义

**Comment by OneBigShrimp** [comment]
A. OnCreate这种方式是有隐患的，万一哪天B类觉得自己的OnCreate需要写点东西，就出问题了。双Super本质是一样的。

**Comment by rowechien** [comment]
@OneBigShrimp 你要求的这种完备的继承确实是不支持的，你可以根据‘OnCreate’的具体形态，自己在lua层面扩展
