### ISSUE TITLE
This is looking pretty good!

### ISSUE THREAD

**Issue by Sam-Online** [Tencent/UnLua#18]
This is looking pretty good guys, love this already, just a tiny question, is there an ETA on the "UnLuaIntelliSense" IDE thingy, if if this plugin get intellisense working, WOW, it will be what was missing in UE4 for me and many others i'm sure.

**Comment by tangzx** [comment]
Yes, we recommend you to use vscode with plugin `EmmyLua`, or IDEA with plugin `EmmyLua`.
How to use ? here's a screen GIF for you : )

![nmeQCyneFW](https://user-images.githubusercontent.com/3354360/63837857-d49c0d00-c9ae-11e9-8c2a-fb9d7afc675c.gif)

Learn more about `EmmyLua` -> https://emmylua.github.io
