### ISSUE TITLE
FScriptStructPropertyDesc.GetValueInternal  没有根据参数是否是引用类型来决定是否进行copy

### ISSUE THREAD

**Issue by mengran3275188** [Tencent/UnLua#180]
![image](https://user-images.githubusercontent.com/3140840/82663100-9f80ca80-9c61-11ea-95af-1fb42dc438a3.png)

在相对应的SetValueInternal内部判断了是否是引用类型
![image](https://user-images.githubusercontent.com/3140840/82663199-ca6b1e80-9c61-11ea-8180-63c027736d8b.png)

在lua重写c++方法，并将非引用传递的ustruct保存到table，在栈空间回滚后，会导致保存的ustruct变成悬垂指针。

**Comment by rowechien** [comment]
@mengran3275188 请问有相关的case吗？
