### ISSUE TITLE
如何在lua里创建蓝图里定义的结构体

### ISSUE THREAD

**Issue by xermao** [Tencent/UnLua#181]
蓝图里定义的结构体名为Struct1
用local localstruct=UE4.UObject.Load("/Game/Struct1.Struct1")不报错，但是也无法使用。
下面两种方法都报错。
localstruct=Struct1()
localstruct=UE4.Struct1()

枚举很正常， 就是结构体不行

**Comment by xermao** [comment]
现在唯一成功的方法是在蓝图里写一个MakeAStruct1的函数，返回一个Struct1然后在lua里获取这个返回值来用。

**Comment by isaf** [comment]
在脚本里面的名字要加上F前缀，你用UE4.FStruct1()应该就可以了。

**Comment by xermao** [comment]
> 在脚本里面的名字要加上F前缀，你用UE4.FStruct1()应该就可以了。

你说的对，确实可以了，非常感谢。

**Comment by 977908569** [comment]
@xermao 你可以正常使用吗？ 我再获取数据的时候会报错 
local Chapters = UE4.TArray(UE4.FChapter)
print(Chapters:Get(1)) --正常
print(Chapters:Get(2))--报错
Chapters数组获取到了两个数据 但是在取第二个数据的时候会报错，第一个数据的时候正常

**Comment by FTQZS** [comment]
> 
> 
> @xermao 你可以正常使用吗？ 我再获取数据的时候会报错
> local Chapters = UE4.TArray(UE4.FChapter)
> print(Chapters:Get(1)) --正常
> print(Chapters:Get(2))--报错
> Chapters数组获取到了两个数据 但是在取第二个数据的时候会报错，第一个数据的时候正常

我猜是从0开始的，不存在2的元素，毕竟是C++数组，我没验证，猜的
