### ISSUE TITLE
针对UserDefinedEnum作为函数回调的问题

### ISSUE THREAD

**Issue by unicodecndddd** [Tencent/UnLua#182]
目前lua中正常使用UserDefinedEnum方式只能是直接调用LoadObject("MyEnum")。
如果将UserDefinedEnum作为一个函数返回值，得到的只是一个普通的没有枚举能力的Object。
能否将LuaLib_Object.cpp的UObject_Load这一段
```cpp
int32 UObject_Load(lua_State *L)
{
    //....上略

    UObject *Object = LoadObject<UObject>(nullptr, *ObjectPath);
    if (Object)
    {
		if (auto* Enum = Cast<UEnum>(Object))
		{
			RegisterEnum(L, Enum);
			int32 Type = luaL_getmetatable(L, TCHAR_TO_ANSI(*Enum->GetName()));
			check(Type == LUA_TTABLE);
		}
		else
		{
			UnLua::PushUObject(L, Object);
		}
    }
    //....下略
}
```
直接移动的UnLuaBase.cpp的PushUObject
```cpp
int32 PushUObject(lua_State *L, UObjectBaseUtility *Object, bool bAddRef)
{
	if (!Object)
	{
		lua_pushnil(L);
		return 1;
	}

	if (Object->IsA(UEnum::StaticClass()))
	{
		UEnum* Enum = (UEnum*)Object;
		RegisterEnum(L, Enum);
		int32 Type = luaL_getmetatable(L, TCHAR_TO_ANSI(*Enum->GetName()));
		check(Type == LUA_TTABLE);
		return 1;
	}

	//....下略
}
```

**Comment by unicodecndddd** [comment]
这样修改可以保证使用UserDefinedEnum的时候行为一致。

**Comment by rowechien** [comment]
@unicodecndddd Enum（不管是不是UserDefinedEnum）作为函数返回值是不会以UObject的形式返回的，它返回值只是一个byte。所以你建议的修改是没必要的，也是不对的，因为返回的是一个table。。。

**Comment by unicodecndddd** [comment]
@rowechien 
> @unicodecndddd Enum（不管是不是UserDefinedEnum）作为函数返回值是不会以UObject的形式返回的，它返回值只是一个byte。所以你建议的修改是没必要的，也是不对的，因为返回的是一个table。。。

这里是我没有解释清楚，我指的UserDefinedEnum作为一个函数返回值不是将枚举的具体某个选项作为返回值。而是将UserDefinedEnum这个object作为返回值。就像UObject_Load这个函数做的一样。

**Comment by unicodecndddd** [comment]
本身这个需求是来源于自己构造一个根据PrivateId加载资源的LoadObject。在实现的过程中发现，想要向lua返回一个类型为UserDefinedEnum的Object就要像UObject_Load一样额外注册为Enum。而这个注册过程只会在UObject_Load中执行。所以我想是不是应该在更底层做区分。

**Comment by unicodecndddd** [comment]
在unlua还没有给UObject_Load添加对UserDefinedEnum的支持时，我的做法是用静态导出的方式把UUserDefinedEnum导出给了lua。

``` cpp
BEGIN_EXPORT_REFLECTED_CLASS(UUserDefinedEnum, UObject)
	ADD_LIB(UUserDefinedEnumLib)
END_EXPORT_CLASS()
IMPLEMENT_EXPORTED_CLASS(UUserDefinedEnum)
```
