### ISSUE TITLE
目前unlua得抛出得lua异常，并不能被bugly收集到。

### ISSUE THREAD

**Issue by jarjin** [Tencent/UnLua#186]
目前unlua得抛出得lua异常，并不能被bugly收集到，请问什么时候会适配？其他C++crash，Java得crash都可以顺利收集到。我看了下，所有得错误回调，执行到ReportLuaCallError函数里面，而里面只有对UE_LOG，这个不太可能会被采集上报吧。
![image](https://user-images.githubusercontent.com/5279613/83486852-8d622000-a4dc-11ea-8e17-042a6a247cf7.png)

**Comment by jarjin** [comment]
目前接管了FUnLuaDelegates::ReportLuaCallError，重定向到项目代码，然后直接通过自定义上报到bugly服务器，有两个问题（1）堆栈格式没有了，一长串得日志，（2）最致命得是貌似有1000子节长度限制，对于一个比较复杂得异常，这可能完全不够。

**Comment by jarjin** [comment]
参考cocos搞定了

**Comment by 13825514442** [comment]
大佬，你是怎么解决的，求教
