### ISSUE TITLE
4.24 combine failed

### ISSUE THREAD

**Issue by a2448825647** [Tencent/UnLua#188]
file: UnLua/Source/UnLua/Private/LuaContext.cpp    line: 845
``` cpp
OnWorldTickStartHandle = FWorldDelegates::OnWorldTickStart.AddRaw(this, &FLuaContext::OnWorldTickStart);
```
reson
file: Engine/Source/Runtime/Engine/Classes/Engine/World.h  line:3629
``` cpp
DECLARE_MULTICAST_DELEGATE_ThreeParams(FOnWorldTickStart, UWorld*, ELevelTick, float);
```
this delegate has changed since ue4.24

**Comment by rowechien** [comment]
@a2448825647 这个问题很早应该就fix了，你用的是老代码
