### ISSUE TITLE
支持用lua写编辑器的界面逻辑吗？

### ISSUE THREAD

**Issue by isaf** [Tencent/UnLua#189]
4.25后支持用蓝图来做编辑器的界面了，我稍微改了下UnLua的代码，让编辑器的界面也可以绑定脚本，但偶尔编辑器会crash，可能哪里改得不对。有什么建议吗？

**Comment by rowechien** [comment]
@isaf UnLua只是为了运行时或者PIE设计的，并没有考虑扩展编辑器使用，编辑器内各种UCLASS等对象会变化的，这种情况下UnLua的很多操作就会出问题，所以不推荐用它来扩展编辑器
