### ISSUE TITLE
请问对于静态导入的类型，在Lua实例化后如何调用析构函数？

### ISSUE THREAD

**Issue by GotGimhong** [Tencent/UnLua#192]
看了一下UnLuaEx.inl，静态导入的类型应该会默认创建一个构造函数和析构函数，构造函数通过元方法"__call"触发，析构函数通过元方法"__gc"触发。目前发现把实例设为nil后，即使手动执行一次GC，析构函数仍然是执行不到的。示例代码如下：
```
do
    local obj = FMyClass()
end
collectgarbage("collect")
```
obj是个临时变量，离开代码块后应该就会被GC了，然而却没有执行到FMyClass的析构函数。请问是不是我的做法不正确，有其他调用析构函数的方法呢？

**Comment by GotGimhong** [comment]
这边再做了些测试，发现如果导入的C++类型带有Trivial析构函数的话，析构函数是可以正常执行到的；析构函数执行不到只针对存在非Trivial析构函数的情况——例如带有自定义析构函数和虚析构函数。

从UnLuaEx.inl来看，没有执行到析构函数的原因应该是存在非Trivial析构函数时没有执行到AddDestructor，导致析构函数没有添加到，请问这里的处理有什么用意呢？或许应该把TNot去掉，或者把FFalse改为FTrue？
![1](https://user-images.githubusercontent.com/16437644/85969493-65da7680-b9fa-11ea-812f-7048f31776f2.png)
![2](https://user-images.githubusercontent.com/16437644/85969495-67a43a00-b9fa-11ea-94ec-8da3aa5ab8a3.png)

**Comment by stallboy** [comment]
是写反了吧，求改下吧

**Comment by xbpiao** [comment]
```cpp
class MyClass
{
public:
	MyClass();
	~MyClass();
};

// TIsTriviallyDestructible< MyClass >>>::Value == false
```
试了一下,如果把TNot去掉改为
```cpp
AddDestructor(typename TChooseClass<TAnd<TIsDestructible<ClassType>, TIsTriviallyDestructible<ClassType>>::Value, FTrue, FFalse>::Result());
```
就可以让跑到
```cpp
template <bool bIsReflected, typename ClassType, typename... CtorArgType>
void TExportedClass<bIsReflected, ClassType, CtorArgType...>::AddDestructor(FFalse NotTrivial)
{
    FExportedClassBase::Functions.Add(new TDestructor<ClassType>);
}
```
使得Lua按引用计数析构
```lua
local obj = MyClass()
obj = nil
collectgarbage()
```
但这样是设计的初衷吗?如果有一个方法 ```MyClass* GetMyClass();```然后释放了C++中的对象一样会是灾难性的,目前试了下 **不能** 这样返回一个Cpp对象

**Comment by xbpiao** [comment]
貌似理解了UnLua,如果想让一个对象在Lua层按引用计数自动析构
```cpp
// MyClass.h
class MyClass
{
public:
	MyClass();
	~MyClass();
};

// MyClass.cpp
template <> struct TIsTriviallyDestructible< MyClass > { enum { Value = true }; };

// 有了上面那句则:TIsTriviallyDestructible< MyClass >>>::Value == true
```

不是写反,是有意为之........

**Comment by rowechien** [comment]
@GotGimhong @stallboy 确实写反了。。。fixed in [3e2a140](https://github.com/Tencent/UnLua/commit/3e2a14027b84d71d335b116d2994cfe9ece2cd6e) .

@xbpiao MyClass* GetMyClass()这种函数返回的指针在lua里是个lightuserdata，gc时不会调用到对应的析构函数的
