### ISSUE TITLE
1.1.0编译失败

### ISSUE THREAD

**Issue by ElviraZ** [Tencent/UnLua#195]
使用unlua 1.1.0,UE4.24和4.25，不管是蓝图还是C艹编译失败，但改用1.0.0是成功的，工程目录没有中文也没有Test字眼
![image](https://user-images.githubusercontent.com/15070835/87112673-05bbbe00-c29f-11ea-88dd-716d742544f1.png)

zip里面自带的TPSPeoject，删除了项目的和插件的Binaries、Intermediate、Saved也是同样的错误。

**Comment by tary** [comment]
用UE源码版本编译, 好像从4.24开始 launcher版本就不能生成反射的代码 DefaultParamCollection.inl
UE4源码4.24.2测试了1.1.0没问题

**Comment by tary** [comment]
> 使用unlua 1.1.0,UE4.24和4.25，不管是蓝图还是C艹编译失败，但改用1.0.0是成功的，工程目录没有中文也没有Test字眼
> ![image](https://user-images.githubusercontent.com/15070835/87112673-05bbbe00-c29f-11ea-88dd-716d742544f1.png)
> 
> zip里面自带的TPSPeoject，删除了项目的和插件的Binaries、Intermediate、Saved也是同样的错误。

用UE源码版本编译应该就好了, 好像从4.24开始 launcher版本就不能生成反射的代码 DefaultParamCollection.inl
UE4源码4.24.2测试了1.1.0没问题

**Comment by ElviraZ** [comment]
sln启动后发现，1.1.0里面的很多类名在UIE4.25  launcher版本是属于过时，并且调用的函数参数不匹配导致编译失败，需要自行修改1.1.0以适配4.25

**Comment by rowechien** [comment]
@ElviraZ 我本地在4.25下并没有编译问题啊，但并不是从launcher上得到的代码

**Comment by rowechien** [comment]
@ElviraZ 我这边确实没有发现编译错误，如果你的错误是这样的：
![image](https://user-images.githubusercontent.com/7972243/107194887-9623d200-6a2b-11eb-8dd7-ae7ce1e05eae.png)
你可以按引擎的提示去修改工程的build.cs文件。
如果不是这种错误，你可以reopen这个issue或者新开一个issue，然后提供详细的编译错误。
