### ISSUE TITLE
委托绑定普通Lua函数

### ISSUE THREAD

**Issue by meilaopo** [Tencent/UnLua#196]
希望完善Delegate属性，用UObject封装普通Lua函数，让委托可以绑定普通Lua函数。Button.OnClicked:Add(function()  self:StartTask(Param, Param2)  end)

**Comment by eefan000** [comment]
> 希望完善Delegate属性，用UObject封装普通Lua函数，让委托可以绑定普通Lua函数。Button.OnClicked:Add(function() self:StartTask(Param, Param2) end)

Add(self, function () end)

**Comment by rowechien** [comment]
@meilaopo eefan000已经回答你了，Add的第一个参数传入一个UObject的实例即可
