### ISSUE TITLE
在lua中创建的对象MulticastDelegate问题

### ISSUE THREAD

**Issue by caishengxi** [Tencent/UnLua#197]
for example :
 local button = newobject(XXX)
button.OnClicked.add(self,function()
XXXX

end)

这种必须要在destruct中 button.OnClicked.clear() 吗？

**Comment by caishengxi** [comment]
lua中创建的button .OnClicked.add一个匿名函数。如果最后没有调用OnClicked.clear()，会有残留引用。  
但是如果这样写：
local button = newobject(XXX)
button.OnClicked.add(self, self.__xxxfunction)
即使最后没调用OnClicked.clear()，也没问题

**Comment by rowechien** [comment]
@caishengxi 良好的习惯是应该这样做的，Add, Remove应该成对出现，当然Clear也可以。不这样做的话会在切换关卡时清理。
