### ISSUE TITLE
打包iOS Shipping版本出错

### ISSUE THREAD

**Issue by eonelv** [Tencent/UnLua#198]
打包iOS Shipping的时候报错。  Debug版本没问题。
ld: bitcode bundle could not be generated because '/Users/lv/UE4/Builds/DESKTOP-3CA9RQ2/D/uebuilder/ENGGame/Plugins/UnLua/Source/ThirdParty/Lua/lib/IOS/liblua.a(lauxlib.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64 

clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by hugebug4ever** [comment]
mmm, 自己编译 lua 可以解决.

**Comment by rowechien** [comment]
@eonelv 你们自己编一个ios下的lua库吧
