### ISSUE TITLE
关于lua代码的打包

### ISSUE THREAD

**Issue by Junho2009** [Tencent/UnLua#20]
请问建议做法是不是：把“Content/Script”目录添加到“ProjectSettings -> Packaging -> Additional Non-Asset Directories to Package”，以确保lua代码被正常打包即可？
我们之前的做法是，自定义了一种BinPackage的uasset，内部将所有的lua代码（或其他非uasset文件），将其“文件名，文件内容”以TMap的形式序列化，这个Package参与资源打包。运行时是先加载这个Package，然后读取里面所需文件的内容。不过这样需要自定义加载lua代码的处理，好像UnLua不提供自定义的功能。
那我们是应该用开头说的那种方式来对lua代码做打包吗？

**Comment by Junho2009** [comment]
补充一下，找到了UnLua自定义加载lua代码的delegate：FUnLuaDelegates::LoadLuaFile。
而平时打包时，UnLua推荐哪种做法呢？

**Comment by rowechien** [comment]
就是用你说的方式打包，这个示例工程的Packaging设置里已经是这样了。
对于Cooked数据，插件提供了定制的require机制从UFS里加载lua
