### ISSUE TITLE
什么情况下需要对一个Class对象调用Destroy方法呢？

### ISSUE THREAD

**Issue by liuhao0620** [Tencent/UnLua#202]
我看到UUnLuaManager类中有一个方法为CleanUpByClass。这个方法只在对一个Class的对象调用Destroy方法的时候会触发。
如果我Destroy了一个Class，这个Class的所有对象实例都无法调用到绑定的Lua方法了。
这是一个feature还是一个BUG呢？
如果是feature,什么情况下需要对一个Class对象调用Destroy方法呢？

> function BP_GameMode_C:ReceiveBeginPlay()
>     local BP_GameMode_C_Class = LoadClass("/Game/Demo/Blueprints/GameMode/BP_GameMode.BP_GameMode")
>     BP_GameMode_C_Class:Destroy()
> end
> 
> function BP_GameMode_C:ReceiveTick(DeltaSeconds)
>     print("BP_GameMode_C:ReceiveTick")
> end

类似于上述的代码，会导致Lua中的ReceiveTick方法无法被调到。

**Comment by rowechien** [comment]
@liuhao0620 以实例工程里的UMG_Main_C为例，我把function UMG_Main_C:OnClicked_ExitButton()改为：
![image](https://user-images.githubusercontent.com/7972243/107193192-886d4d00-6a29-11eb-9e41-a62e63bb0119.png)
这段代码的意思是卸载UMG_Main_C的具体实例后，继续卸载UMG_Main_C这个UClass，这种做法的意义在于完整的卸载掉某个UClass时可以同时卸载掉它引用的资源。例如某个UserWidget上引用了某张巨大的贴图，如果不卸载掉这个UserWidget，那么贴图会一直占用资源的，这个做法就是为这种情况准备的

**Comment by jarjin** [comment]
> @liuhao0620 以实例工程里的UMG_Main_C为例，我把function UMG_Main_C:OnClicked_ExitButton()改为：
> ![image](https://user-images.githubusercontent.com/7972243/107193192-886d4d00-6a29-11eb-9e41-a62e63bb0119.png)
> 这段代码的意思是卸载UMG_Main_C的具体实例后，继续卸载UMG_Main_C这个UClass，这种做法的意义在于完整的卸载掉某个UClass时可以同时卸载掉它引用的资源。例如某个UserWidget上引用了某张巨大的贴图，如果不卸载掉这个UserWidget，那么贴图会一直占用资源的，这个做法就是为这种情况准备的

如果是UMG_Main下面包括了子UserWidget，在Load的时候，子UserWidget会被创建多次？原型？蓝图类？最后只能释放对象自身，其他的会导致释放不掉。这个如何释放？
