### ISSUE TITLE
请问StaticMeshActor 的 StaticMeshComponent在lua里应该怎么获取呢? 

### ISSUE THREAD

**Issue by ArchmageMelon** [Tencent/UnLua#204]
> 
![image](https://user-images.githubusercontent.com/29856796/91300829-80e91d00-e7d6-11ea-9e76-f1c4e0263ac6.png)
像这种蓝图能直接读，lua里应该怎么做呢？

**Comment by tary** [comment]
Uproperty的属性直接点就行
`StaticMeshActor.StaticMeshComponent:SetSimulatePhysics(...)`

**Comment by ArchmageMelon** [comment]
> Uproperty的属性直接点就行
> `StaticMeshActor.StaticMeshComponent:SetSimulatePhysics(...)`

感谢解答，之前我用的时候也是直接点的，但是报nil了，我还是换其他方法了~~
