### ISSUE TITLE
CacheScriptContainer缓存了无效的值，导致crash

### ISSUE THREAD

**Issue by sunchunyue** [Tencent/UnLua#206]
-----------------------------CacheScriptContainerTestObject.h--------------------------------------

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "UObject/NoExportTypes.h"
#include "CacheScriptContainerTestObject.generated.h"

/**
 * 
 */
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnFinished, const TArray<UObject*>&, objectArray);

UCLASS()
class TPSPROJECT_API UCacheScriptContainerTestObject : public UObject
{
	GENERATED_BODY()

public:
	UPROPERTY(BlueprintAssignable)
	FOnFinished Completed;
	
};

UCLASS()
class TPSPROJECT_API ACacheScriptContainerTestManager : public AActor
{
	GENERATED_BODY()

public:
	// Sets default values for this actor's properties
	ACacheScriptContainerTestManager()
	{
		PrimaryActorTick.bCanEverTick = true;
	}

protected:
	// Called when the game starts or when spawned
	void BeginPlay() override
	{
		Super::BeginPlay();
	}

public:
	// Called every frame
	void Tick(float DeltaTime) override
	{
		Super::Tick(DeltaTime);

		if (ObjectArray.Num() > 0)
		{
			UCacheScriptContainerTestObject * tempObject = ObjectArray[0];

			ObjectArray.RemoveAt(0);

			TArray<UObject*> resultObjectArray;
			resultObjectArray.Add(tempObject);

			tempObject->Completed.Broadcast(resultObjectArray);
		}
	}

	UFUNCTION(BlueprintCallable)
	void AddOneObject(UCacheScriptContainerTestObject* object)
	{
		ObjectArray.Add(object);
	}

private:
	TArray<UCacheScriptContainerTestObject*> ObjectArray;

};

--------------------------------------------------UMG_Main_C.lua----------------------------------------------------
function  UMG_Main_C:__OnClickButtonCacheScriptContainerTest()
    local objectClass = UE4.UCacheScriptContainerTestObject
    local actorClass = UE4.ACacheScriptContainerTestManager

    local actorPosition = UE4.FVector(0, 0, 0)
    local actorRotation = UE4.FRotator(0, 0, 0)
    local actorScale = UE4.FVector(1, 1, 1)
    local world = self:GetWorld()
    local transform = UE4.UKismetMathLibrary.MakeTransform(actorPosition, actorRotation, actorScale)
    local testManager = world:SpawnActor(actorClass, transform)

    local count = 0
    local function doOnce()
        local object1 = NewObject(objectClass, self)

        local function callBack(_object, objectArray)
            count = count + 1

            if objectArray:Length() > 0 then
                print("objectArray:Get(1) = ", objectArray:Get(1))  -----------------------这里会crash
            end

            object1.Completed:Clear()
            UE4.UKismetSystemLibrary.CollectGarbage()
        end
        object1.Completed:Add(object1, callBack)
        testManager:AddOneObject(object1)
    end

    for i = 1, 2 do
        doOnce()
    end
end

--------------------------------------------------------------------------------------------------------------------
关于CacheScriptContainer，缓存的key目前是个地址，当这个地址被重用时，取到的内容就是旧的，上面的代码是我加的一个测试用例，在Completed回调结束的时候调用了Clear方法（调用Remove也是一样的），然后手动触发了一次GC，会导致FLuaArray->Inner->GetUProperty()被GC掉，下一次使用重用的地址从缓存里取到旧的内容，然后调用objectArray:Get(1) 时会访问被GC掉的UProperty，就会crash。

**Comment by sunchunyue** [comment]
@rowechien 麻烦看看有没有办法解决呀

**Comment by tary** [comment]
这个上跟 #205是一个问题

**Comment by tary** [comment]
这个上跟 #205 是一个问题

**Comment by fdcumt** [comment]
为什么TArray<UCacheScriptContainerTestObject*> ObjectArray;没有加入GC(用UPROPERTY包含)???

**Comment by sunchunyue** [comment]
> 为什么TArray<UCacheScriptContainerTestObject*> ObjectArray;没有加入GC(用UPROPERTY包含)???

这里ObjectArray只是为了存储在lua里绑定代理回调的对象，是否标记UPROPERTY应该并不会影响结果

**Comment by lvpengfeifei** [comment]
已弃坑。。

**Comment by rowechien** [comment]
@sunchunyue fixed in [4663a4d](https://github.com/Tencent/UnLua/commit/4663a4dbadffc8b87784e0b408cbcbdbae7dda17) 。容器的地址作为key这个开发时就考虑过有可能出现的问题，ScriptContainerMap被定义成弱表就是原因之一，为了能让lua及时的GC掉这些被缓存的容器。如果你们还没有完全解决这个问题可以试下我的修正。

@tary 这个问题和 #205 不一样，分开来解决
