### ISSUE TITLE
UUnLuaManager::NotifyUObjectDeleted的时候如果是UClass为什么只调用OnClassCleanup

### ISSUE THREAD

**Issue by interlyx** [Tencent/UnLua#207]
很多蓝图对象的UClass会释放，结果ModuleNames等几个容器里会有很多野指针无法释放
![image](https://user-images.githubusercontent.com/33210468/93879937-37291f00-fd0f-11ea-9b6b-7f700ccb2dfb.png)

ModuleNames只在切换地图的时候清空，这样会导致蓝图actor释放导致该uclass释放后，触发
![image](https://user-images.githubusercontent.com/33210468/93882382-be2bc680-fd12-11ea-8ed5-0418d8f17959.png)

是基于性能考虑吗？逻辑感觉还是有问题的

**Comment by rowechien** [comment]
@interlyx 你说的有道理，这确实有问题，已经修正了。 [e6cfb7b](https://github.com/Tencent/UnLua/commit/e6cfb7bfce03cb8e7f81538815dee5b7cadf4907)
