### ISSUE TITLE
使用FSlateColor构造函数无法正常创建slatecolor

### ISSUE THREAD

**Issue by tizengyan** [Tencent/UnLua#208]
脚本中无论用什么LinearColor作为构造函数的参数，创建的SlateColor都是默认的紫色，打出来的SpecifiedColor成员始终没有被赋值，只能创建一个空的SlateColor，然后手动覆盖SpecifiedColor。
在脚本中更改Text颜色时发现这个问题，umg中可以正常改。

**Comment by yangruihan** [comment]
这样成功了

```lua
local fColor = UE4.FColor(100, 100, 100, 255)
local color = UE4.FSalteColor()
color.SpecifiedColor = fColor:ToLinearColor()
xxxx:SetColorAndOpacity(color)
```

**Comment by tizengyan** [comment]
> 这样成功了
> 
> ```lua
> local fColor = UE4.FColor(100, 100, 100, 255)
> local color = UE4.FSalteColor()
> color.SpecifiedColor = fColor:ToLinearColor()
> xxxx:SetColorAndOpacity(color)
> ```

嗯，我就是这个意思

**Comment by tary** [comment]
直接传FLinearColor就行, 参数会自动转换
```
local fColor = UE4.FLinearColor(0.5, 0.5, 0.5)
xxxx:SetColorAndOpacity(fColor)
```

**Comment by tizengyan** [comment]
> 直接传FLinearColor就行, 参数会自动转换
> 
> ```
> local fColor = UE4.FLinearColor(0.5, 0.5, 0.5)
> xxxx:SetColorAndOpacity(fColor)
> ```

这个对图片可以，但如果是Text的话SetColorAndOpacity会要求一个SlateColor而不是LinearColor

**Comment by tary** [comment]
> > 直接传FLinearColor就行, 参数会自动转换
> > ```
> > local fColor = UE4.FLinearColor(0.5, 0.5, 0.5)
> > xxxx:SetColorAndOpacity(fColor)
> > ```
> 
> 这个对图片可以，但如果是Text的话SetColorAndOpacity会要求一个SlateColor而不是LinearColor

我以为会自动隐式转换, 实际上Lua里没有.
`FLinearColor` 可以通过参数构造是因为  `FLinearColor_New` 创建了`Userdata`并通过参数初始化了Userdata,
于此类似的还有其他位于UnLua\Private\MathLib\LuaLib_FXXX.cpp的`__call`绑定函数如:
 `FTransform_New` `FVector_New`  `FColor_New`  `FTransform_New`  ...

而用自动导出的`USTRUCT`类型, 在创建时会通过`ScriptStruct_New`创建及初始化`Userdata`, 并没有处理参数, 所以应该是所有`USTRUCT`的类型都不能用构造函数初始化

**Comment by rowechien** [comment]
@tizengyan @tary 的解释是正确的，UStruct的构造走的是ScriptStruct_New，不接受参数的。
但是并不是不能做到你想要的，以FSlateColor为例，想传FLinearColor作为构造参数，你可以这样做：
![image](https://user-images.githubusercontent.com/7972243/107192305-6cb57700-6a28-11eb-98e2-f222a5f8b92d.png)
对应的脚本代码：
![image](https://user-images.githubusercontent.com/7972243/107192400-835bce00-6a28-11eb-895d-2510d35d76ad.png)

注意：这样导出后，如果脚本中这样写 local color = FSlateColor() 是会报错的。具体怎样选择看你们自己的需求。
