### ISSUE TITLE
OnRep函数没有被调用的问题

### ISSUE THREAD

**Issue by lzw576910119** [Tencent/UnLua#21]
我在C++代码中声明了一个变量，并且实现了RPC调用从客户端设置服务端的变量，在设置成功的时候会调用变量的OnRep函数同步到客户端。
在lua中重写了OnRep，发现在蓝图中调用Rpc设置变量成功之后会调用到lua的OnRep函数
但是在Lua中调用Rpc设置变量，同样能成功改变服务端的变量，却不会调用lua到OnRep，请问这个是什么问题？

**Comment by futouyiba** [comment]
很关心这个问题，帮顶

**Comment by rowechien** [comment]
@lzw576910119 @futouyiba  我调试之后再回复你们

**Comment by rowechien** [comment]
@lzw576910119 @futouyiba  UnLua.Build.cs文件里把bSupportsRpcCall设为True

**Comment by lzw576910119** [comment]
> @lzw576910119 @futouyiba UnLua.Build.cs文件里把bSupportsRpcCall设为True
多谢~，我试试看
