### ISSUE TITLE
FLuaTable如何作为静态导出函数的参数？

### ISSUE THREAD

**Issue by kimixuchen** [Tencent/UnLua#214]
比如我想这么用，要怎么实现？
ADD_STATIC_FUNCTION_EX("Func", int, Func, UnLua::FLuaTable)

**Comment by rowechien** [comment]
FLuaTable是对lua table的一个非常简单甚至可以说简陋的包装，方便在c++里对lua table做些操作，将它导出到lua里没有必要啊，lua里直接就可以方便的操作table。。。
你一定要导出也没有问题，可以先将FLuaTable进行导出，但我还是觉得不应该有这样的需求的。。。
