### ISSUE TITLE
TMap和TArray遍历偶现溢出

### ISSUE THREAD

**Issue by liangdididi** [Tencent/UnLua#215]
多次循环执行在lua里遍历蓝图中存在的TMap或者TArray容器, 通过lua的Get(i)获取元素, 偶现容器数量为0报TArray_Get: TArray Invalid Index!错误

**Comment by rowechien** [comment]
@liangdididi TArray_Get已经提示Invalid Index了，你也说了容器数量为0，这种情况再用Get(i)来取数据就是会有错误啊。。。
在C++中用operator[](int32 i)来访问长度为0的TArray，是不是会crash?
