### ISSUE TITLE
Global_Require的实现有问题！！！

### ISSUE THREAD

**Issue by liuhao0620** [Tencent/UnLua#219]
LuaCore.cpp中实现的Global_Require函数存在问题。
**应将lua_pcall(L, 2, 1, 0)替换为lua_call(L, 2, 1)**
当UnLua::LoadFile成功时，使用lua_pcall(L, 2, 1, 0)执行Load出来的文件，然后未做任何检查，就加入了loaded表中。导致在专属服务器或客户端中加载lua出错时，会在loaded表内存在一条错误字符串。
lua_call则不存在这个问题，当执行出错时，lua_call会通过longjump向上汇报错误，而不会执行后续操作。
参考文档：
https://www.lua.org/manual/5.3/manual.html#lua_pcall
https://www.lua.org/manual/5.3/manual.html#lua_call

**Comment by rowechien** [comment]
@liuhao0620 thanks very mush! fixed in [88956cf](https://github.com/Tencent/UnLua/commit/88956cf7920d5c548262a3a1211ea9832963f753)
