### ISSUE TITLE
如何导出类的静态成员变量

### ISSUE THREAD

**Issue by Junho2009** [Tencent/UnLua#22]
目前似乎没找到对应的宏。
从实现的方面，可以定义一个对应的静态函数来返回，然后导出这个静态函数，不过这样比较繁琐呢。

**Comment by futouyiba** [comment]
UGameplayStatics这种Bp library里面应该都是static函数，可以参考吧

**Comment by Junho2009** [comment]
> UGameplayStatics这种Bp library里面应该都是static函数，可以参考吧

是希望导出一个类的静态【变量】到lua哈。

**Comment by Junho2009** [comment]
> UGameplayStatics这种Bp library里面应该都是static函数，可以参考吧

是希望导出一个类的静态【变量】到lua哈。
当然也可以用lua的C API pushxxx，不过如果有对应的宏，就不用自行写胶水代码。

**Comment by rowechien** [comment]
@Junho2009 确实是没有这个功能，之后补上吧

**Comment by futouyiba** [comment]
> > UGameplayStatics这种Bp library里面应该都是static函数，可以参考吧
> 
> 是希望导出一个类的静态【变量】到lua哈。
> 当然也可以用lua的C API pushxxx，不过如果有对应的宏，就不用自行写胶水代码。

不好意思，之前把静态变量看成了静态函数

**Comment by rowechien** [comment]
@Junho2009 UnLua对类的非静态变量导出后是以lightuserdata形式存在，通过类元表的__index函数再配合类实例的地址和偏移来对它进行读写。静态变量可以通过类直接访问，在lua里就是通过类元表直接访问，这个在UnLua里不好实现（因为直接就返回lightuserdata了），当然通过类的实例可以正常访问，不过这就少了静态变量的特色了。
UnLua不会对这个情况做特色处理了。你可以自己绕过去，比如写个类的静态成员函数，然后把它导出。
