### ISSUE TITLE
反馈一个DeleteLuaObject引起的问题

### ISSUE THREAD

**Issue by GotGimhong** [Tencent/UnLua#220]
![QQ截图20201107165257](https://user-images.githubusercontent.com/16437644/98537403-2c791800-22c4-11eb-8361-b6752121ccd6.png)

在LuaCore.cpp的DeleteLuaObject函数中，**如果UObject绑定Lua对象有效**（`Type == LUA_TTABLE`），就会断言UObject也仍然有效（`check(Type == LUA_TUSERDATA)`）。然而，DeleteLuaObject函数是通过引擎事件NotifyUObjectDeleted触发的，这个时候UObject已经被引擎GC了。这样来看，这部分的处理似乎有些矛盾。

我做了如下测试：

1. 在Lua中依次执行`_G.luaObject = luaObject`，`luaObject:RemoveFromParent()`和`luaObject.Object = nil`。DeleteLuaObject函数可以执行，但是因为luaObject.Object已经置空了，所以会触发断言错误。

1. 在Lua中依次执行`_G.luaObject = luaObject`和`luaObject:RemoveFromParent()`。luaObject.Object是有效的，但是DeleteLuaObject函数就不会执行了。

**Comment by rowechien** [comment]
@GotGimhong luaObject这个实例如果是个lua table，那luaObject.Object就是个userData，对应保存了一个UObject的二级指针，即使这个UObject被引擎GC了，userData里保存的指针还在，所以这里要 *((void**)Userdata) = nullptr； 
1这种情况，我不建议你直接做luaObject.Object = nil这样的操作，如果不看代码，开发者可能都不知道有这么个变量，而且插件里本身就做了相关清理；
2这种情况我觉得是依然有地方保留了luaObject的引用所以没有被GC，自己也就走不到这里；

最后，FLuaContext::NotifyUObjectDeleted并不是只会被引擎调用，插件里还有其他地方显示的调用了它，由于牵涉到引擎和lua两边的两套GC机制，所以这方面确实有点绕，具体的还是要参考代码。
