### ISSUE TITLE
后续还有更新的计划吗?

### ISSUE THREAD

**Issue by RPG3D** [Tencent/UnLua#224]
很久没有新的提交记录了

**Comment by xermao** [comment]
据说负责人被调其他位置上去了。所以你也可以理解为不会更新了

**Comment by xpc-yx** [comment]
除了最新的支持4.26，其它提交记录都是一年以上了，隔壁slua最近一个月都有提交。。。

**Comment by rowechien** [comment]
@RPG3D 更新确实很少了，我并不是全职维护这个插件，其他工作已经基本占满了我的时间，有限的维护也基本都是自己的业余时间，之后尽量挤出时间来维护它吧。鹅厂另外的脚本插件也不错，而且UnLua的特色特性它们也有了，开发者可以根据自己的需求选择，即使选择不同的方案，相互之间也可以参考借鉴。

**Comment by zjhongxian** [comment]
> 除了最新的支持4.26，其它提交记录都是一年以上了，隔壁slua最近一个月都有提交。。。

slua unreal下半年将有重大更新，回馈大家
