### ISSUE TITLE
userwidget 调用Destroy后 导致 Destruct方法无法被调用的问题

### ISSUE THREAD

**Issue by lzj1989712** [Tencent/UnLua#227]
产生问题的主要原因是 userwidget绑定lua后，无法被gc系统正常销毁 
采用 #123 建议的方案后 

![image](https://user-images.githubusercontent.com/5946974/103346040-ed01c780-4acd-11eb-8145-2e1796870b73.png)

等到Slate析构调用NativeDestruct时，UserWidget已经从 ObjectMap中被删除 
从而导致Destrut方法调用失败，有什么好的解决方法吗？

**Comment by rowechien** [comment]
@lzj1989712 你可以参考这样的做法:
![image](https://user-images.githubusercontent.com/7972243/107194622-3d543980-6a2b-11eb-9138-40da61c73163.png)
