### ISSUE TITLE
都是国内的同学在用吗，好奇

### ISSUE THREAD

**Issue by fatalerror8787** [Tencent/UnLua#228]
UE4官方支持什么脚本语言吗

**Comment by rowechien** [comment]
@fatalerror8787 国内用lua作为脚本语言比较多，当然也有python, c#。 ue4官方有lua的最简化集成，但17年就已经无法工作了，现在官方支持的是python，用于编辑器内的扩展功能，无法runtime应用，当然，也不是不可以改。。。
