### ISSUE TITLE
UE4.25更新最新版Unlua切地图导致重大Crash！！！

### ISSUE THREAD

**Issue by jarjin** [Tencent/UnLua#229]
【1】
![image](https://user-images.githubusercontent.com/5279613/104904982-bdebc100-59bc-11eb-94bc-714f99702589.png)
【2】
![image](https://user-images.githubusercontent.com/5279613/104905007-c3e1a200-59bc-11eb-81fb-7c2a9c5e25d4.png)
【3】
![image](https://user-images.githubusercontent.com/5279613/104905025-c80dbf80-59bc-11eb-8f19-b9aa37101bf3.png)
【4】
![image](https://user-images.githubusercontent.com/5279613/104905048-cd6b0a00-59bc-11eb-81ae-56b2d9464adf.png)
【5】
![image](https://user-images.githubusercontent.com/5279613/104905059-d22fbe00-59bc-11eb-8bb5-d686fdd0a7d0.png)

Crash介绍：首先我们在切换场景时候，所有的对象都没有调用destroy，老版本的Unlua可以正常通过，AttachedActors（跟引擎有重，临时改名）里面有三个Actor，执行UUnLuaManager::OnActorDestroyed第二个会被移除掉，然后我看到UEngine::LoadMap会被执行，当执行过LoadPackage以后（里面有LoadAllObject），会回到UUnLuaManager::AddAttachedObject，就看到列表这三个元素变成了很奇怪的状态，图2跟图3是不同的情况遇到的。当执行到图4里面的UUnLuaManager::OnMapLoaded的时候，进入UObjectBase::IsValidLowLevelFast里面会被check崩溃掉。

猜想：不知道这个会不会跟我们一直靠UE4的GC来释放资源的使用方式有关，还是说这是新版的一个BUG。

**Comment by jarjin** [comment]
作者已经弃更了吗？

**Comment by rowechien** [comment]
@jarjin 仅看你的描述我定位不出问题，图中看出问题的是UnluaAttachedActors这个变量，这个是你们自己加的吧，UUnLuaManager里已经有了个AttachedActors，这里面的对象有问题吗？

**Comment by jarjin** [comment]
> @jarjin 仅看你的描述我定位不出问题，图中看出问题的是UnluaAttachedActors这个变量，这个是你们自己加的吧，UUnLuaManager里已经有了个AttachedActors，这里面的对象有问题吗？

AttachedActors（跟引擎有重，临时改名）

**Comment by Panda-UE** [comment]
![1FA9ACAD-DC21-4ed8-BCB1-697CFD26B664](https://user-images.githubusercontent.com/72717755/108674026-98078e00-751f-11eb-889f-91ecf8ea0c2e.png)
![C46FEAF2-D32E-4386-AAEB-FECCD6F498F7](https://user-images.githubusercontent.com/72717755/108674199-d604b200-751f-11eb-80e1-302b2951f184.png)
我也同样在跳转地图的时候出现了这样的问题

**Comment by Panda-UE** [comment]
我的问题是解决了，在单机中跳转地图之前会调用Cleanup（）清除AttachedActors中的元素，但是联机时就没有调用Cleanup（）。后面经过查找是这里判断问题
![2425E966-99ED-4bc1-A56E-4684BDAFF105](https://user-images.githubusercontent.com/72717755/108697167-76b59a80-753d-11eb-8666-6b83b5a7fccb.png)导致联机时直接return了，添加上World && World->IsPlayInEditor()后就正常了

**Comment by jarjin** [comment]
> 我的问题是解决了，在单机中跳转地图之前会调用Cleanup（）清除AttachedActors中的元素，但是联机时就没有调用Cleanup（）。后面经过查找是这里判断问题
> ![2425E966-99ED-4bc1-A56E-4684BDAFF105](https://user-images.githubusercontent.com/72717755/108697167-76b59a80-753d-11eb-8666-6b83b5a7fccb.png)导致联机时直接return了，添加上World && World->IsPlayInEditor()后就正常了

多谢大佬，我按照你这个修改能过了，希望没啥问题
