### ISSUE TITLE
UE4.20 + VS2015编译报错 error : Failed to initialize the engine (PreInit failed).

### ISSUE THREAD

**Issue by AingeLu** [Tencent/UnLua#23]
EXEC : error : UnrealHeaderTool failed for target 'UnrealProjectEditor' (platform: Win64, module info: C:\F1\Client_proj\trunk\UnrealProject\Intermediate\Build\Win64\UnrealProjectEditor\Development\UnrealProjectEditor.uhtmanifest, exit code: CrashOrAssert (3)).

**Comment by rowechien** [comment]
仅仅这条错误可能信息不足，不太清楚具体情况。但是，4.20.x下由于UBT的bug，所以会有些问题，需要对UBT做些修改，具体你可以参考下：
[UE 4.20 + VS2017 编译错误](https://github.com/Tencent/UnLua/issues/4)

**Comment by lzw576910119** [comment]
@rowechien 我遇到过同样的问题，也是4.20修改完UBT之后，如果重编项目1不会报错，但是如果去编译项目2的时候似乎就会报错，如果用同样的解决方法去编译项目2成功之后，再次编译项目1又会报错。给我的感觉应该是有一个什么文件无法在不通的项目中共用，第一个项目编译之后就会生成，第二个项目再次编译的时候不会再次生成，使用旧的文件就会报错，个人猜测。
