### ISSUE TITLE
UE4.26 Android平台流关卡卸载导致崩溃

### ISSUE THREAD

**Issue by hrlnldy** [Tencent/UnLua#238]
工程为Unlua官方工程，在蓝图加载后卸载流关卡Test；
![image](https://user-images.githubusercontent.com/8519680/111979883-8fb36a80-8b40-11eb-909b-45ae4a87d6b7.png)
报错堆栈
D/UE4     : [2021.03.22-10.52.32:420][124]LogLevel: ActivateLevel /Game/Core/Maps/Test 0 0 0
D/UE4     : [2021.03.22-10.52.32:421][124]LogUnLua: == UNLUA_PRINT : Test.ReceiveEndPlay    
D/UE4     : [2021.03.22-10.52.32:436][125]LogBlueprintUserMessages: [MainMap_C_2] unload finish
D/UE4     : [2021.03.22-10.52.32:437][125]LogOutputDevice: Warning: 
D/UE4     : 
D/UE4     : Script Stack (0 frames):
D/UE4     : 
D/UE4     : Assertion failed: !IsRooted() [File:D:/Build/++UE4/Sync/Engine/Source/Runtime/CoreUObject/Public\UObject/UObjectBaseUtility.h] [Line: 173] 
D/UE4     : 
D/UE4     : [2021.03.22-10.52.32:490][125]Assertion failed: !IsRooted() [File:D:/Build/++UE4/Sync/Engine/Source/Runtime/CoreUObject/Public\UObject/UObjectBaseUtility.h] [Line: 173] 
D/UE4     : 
D/UE4     : [2021.03.22-10.52.32:490][125]LogAndroid: Error: === Critical error: ===
D/UE4     : [2021.03.22-10.52.32:490][125]LogAndroid: Error: 
D/UE4     : [2021.03.22-10.52.32:490][125]LogAndroid: Error: Assertion failed: !IsRooted() [File:D:/Build/++UE4/Sync/Engine/Source/Runtime/CoreUObject/Public\UObject/UObjectBaseUtility.h] [Line: 173] 
D/UE4     : [2021.03.22-10.52.32:490][125]LogAndroid: Error: 
D/UE4     : [2021.03.22-10.52.32:490][125]LogAndroid: Error: [Callstack] 0x00000000C3783208 libUE4.so(0x000000000B883208)![Unknown]()  []
D/UE4     : [2021.03.22-10.52.32:490][125]LogAndroid: Error: [Callstack] 0x00000000BF5672C8 libUE4.so(0x00000000076672C8)!ForEachObjectWithPackage(UPackage const*, TFunctionRef<bool (UObject*)>, bool, EObjectFlags, EInternalObjectFlags)  []
D/UE4     : [2021.03.22-10.52.32:490][125]LogAndroid: Error: [Callstack] 0x00000000C37830BC libUE4.so(0x000000000B8830BC)![Unknown]()  []
D/UE4     : [2021.03.22-10.52.32:490][125]LogAndroid: Error: [Callstack] 0x00000000BF565EA8 libUE4.so(0x0000000007665EA8)!ForEachObjectWithOuter(UObjectBase const*, TFunctionRef<void (UObject*)>, bool, EObjectFlags, EInternalObjectFlags)  []
D/UE4     : [2021.03.22-10.52.32:490][125]LogAndroid: Error: [Callstack] 0x00000000C375BF08 libUE4.so(0x000000000B85BF08)!FLevelStreamingGCHelper::PrepareStreamedOutLevelsForGC()  []
D/UE4     : [2021.03.22-10.52.32:490][125]LogAndroid: Error: [Callstack] 0x00000000BD97DA08 libUE4.so(0x0000000005A7DA08)!TBaseStaticDelegateInstance<void (), FDefaultDelegateUserPolicy>::ExecuteIfSafe() const  []
D/UE4     : [2021.03.22-10.52.32:490][125]LogAndroid: Error: [Callstack] 0x00000000BD969A80 libUE4.so(0x0000000005A69A80)!TMulticastDelegate<void (), FDefaultDelegateUserPolicy>::Broadcast() const  []
D/UE4     : [2021.03.22-10.52.32:490][125]LogAndroid: Error: [Callstack] 0x00000000BF372D28 libUE4.so(0x0000000007472D28)!CollectGarbageInternal(EObjectFlags, bool)  []
D/UE4     : [2021.03.22-10.52.32:490][125]LogAndroid: Error: [Callstack] 0x00000000BF375DEC libUE4.so(0x0000000007475DEC)!TryCollectGarbage(EObjectFlags, bool)  []
D/UE4     : [2021.03.22-10.52.32:490][125]LogAndroid: Error: [Callstack] 0x00000000C35D45E0 libUE4.so(0x000000000B6D45E0)!UEngine::ConditionalCollectGarbage()  []
D/UE4     : [2021.03.22-10.52.32:490][125]LogAndroid: Error: [Callstack] 0x00000000C2CD2CE4 libUE4.so(0x000000000ADD2CE4)!UWorld::Tick(ELevelTick, float)  []
D/UE4     : [2021.03.22-10.52.32:490][125]LogAndroid: Error: [Callstack] 0x00000000C2ABF504 libUE4.so(0x000000000ABBF504)!UGameEngine::Tick(float, bool)  []
D/UE4     : [2021.03.22-10.52.32:491][125]LogAndroid: Error: [Callstack] 0x00000000BD94E02C libUE4.so(0x0000000005A4E02C)!FEngineLoop::Tick()  []
D/UE4     : [2021.03.22-10.52.32:491][125]LogAndroid: Error: [Callstack] 0x00000000BD9419CC libUE4.so(0x0000000005A419CC)!AndroidMain(android_app*)  []
D/UE4     : [2021.03.22-10.52.32:491][125]LogAndroid: Error: [Callstack] 0x00000000BD9572A8 libUE4.so(0x0000000005A572A8)!android_main()  []
D/UE4     : [2021.03.22-10.52.32:491][125]LogAndroid: Error: [Callstack] 0x00000000BD98A8E8 libUE4.so(0x0000000005A8A8E8)![Unknown]()  []
D/UE4     : [2021.03.22-10.52.32:491][125]LogAndroid: Error: [Callstack] 0x00000000F3298CDC libc.so(0x00000000000ABCDC)![Unknown]()  []
D/UE4     : [2021.03.22-10.52.32:491][125]LogAndroid: Error: [Callstack] 0x00000000F324FDC4 libc.so(0x0000000000062DC4)![Unknown]()  []
D/UE4     : [2021.03.22-10.52.32:491][125]LogAndroid: Error: 
D/UE4     : [2021.03.22-10.52.32:491][125]LogAndroid: Error: 
D/UE4     : [2021.03.22-10.52.32:502][125]LogUnLua: Error: Lua stack : 
D/UE4     : 
D/UE4     : [2021.03.22-10.52.32:514][125]LogExit: Executing StaticShutdownAfterError
D/UE4     : [2021.03.22-10.52.32:516][125]LogAndroid: FAndroidMisc::RequestExit(1)

Test关卡绑定脚本
![image](https://user-images.githubusercontent.com/8519680/111980115-d608c980-8b40-11eb-9079-4758f9a232e6.png)

**Comment by Panda-UE** [comment]
估计也是代理的问题

**Comment by hrlnldy** [comment]
> 估计也是代理的问题

有什么解决的思路吗，这个问题只有手机端出现了

**Comment by Panda-UE** [comment]
参考一下#229 看能不能解决

**Comment by hrlnldy** [comment]
解决方案：https://github.com/hrlnldy/UnLua
