### ISSUE TITLE
lua变量共用的问题

### ISSUE THREAD

**Issue by lzw576910119** [Tencent/UnLua#24]
我在一个服务端客户端都有的Actor（PlayerController）里，加了个local变量，在ReceiveBeginPlay的时候判断如果是客户端对值 +2，如果是服务端对值+4，运行的时候服务端的local变量是+2，但是客户端的local变量变成+6，如果开启多进程模式或者standalone模式就是正常的，这个有办法解决吗。
另外，目前demo中的AI还是走的行为树和蓝图，如果实现接口用lua重写，效率和蓝图比大概差多少？

**Comment by rowechien** [comment]
第一个问题，方便的话贴出代码来看看。
示例工程里应该就是BTService_CheckPlayer是蓝图吧，不是效率不行，是遗漏了它。。。性能我们自己测试下来对比蓝图是有优势的，对比其他lua方案也是有明显优势的。之后会加上一些用例的

**Comment by lzw576910119** [comment]
> 第一个问题，方便的话贴出代码来看看。
> 示例工程里应该就是BTService_CheckPlayer是蓝图吧，不是效率不行，是遗漏了它。。。性能我们自己测试下来对比蓝图是有优势的，对比其他lua方案也是有明显优势的。之后会加上一些用例的

![image](https://user-images.githubusercontent.com/39950802/63495703-ef740a80-c4f2-11e9-91d8-915e2512bd2d.png)
大致代码如图，就是在beginPlay的时候增加一个值，如果这个playerController在服务端和客户端都有的时候，打印出来服务端的值为30，而客户端则为70，实际上我期望的值应该是服务端为30，客户端为50.

对于lua的使用我可否这样理解，他是蓝图或者c++的拓展，实际上就是重写函数的实现以及调用。是否有办法在lua中直接增加变量就能实现属性同步，增加函数实现RPC调用？

**Comment by rowechien** [comment]
@lzw576910119 你在ReceiveBeginPlay()里面定义这个变量吧：self.fTest = 10

**Comment by lzw576910119** [comment]
> @lzw576910119 你在ReceiveBeginPlay()里面定义这个变量吧：self.fTest = 10
> 
> ReceiveBeginPlay()里的self是个 lua table，你在这个table上定义变量就不会有上面的问题

试过确实可以解决~ 谢谢@rowechien 的答疑
![image](https://user-images.githubusercontent.com/39950802/63562091-e46eb800-c58e-11e9-8f83-4c5c333fa755.png)
这个问题目前能做吗，目前就是想看看unlua可以做到什么程度，不一定后面会用到，就是单纯的好奇。

**Comment by rowechien** [comment]
@lzw576910119 这个是不支持的，你可以加任意lua变量，但这些变量是无法支持replication的，同理你也可以加任意函数，但它们不是rpc函数

**Comment by lzw576910119** [comment]
@rowechien 好的，多谢解惑~,了解了
