### ISSUE TITLE
如何通过UENUM的枚举值获得枚举名字符串？

### ISSUE THREAD

**Issue by TongYuSamwise** [Tencent/UnLua#241]
例：C++中有一个UENUM
```
UENUM(BlueprintType, Blueprintable)
enum EAttributeType
{
	Attribute_None,

	Attribute_HP,
	Attribute_MaxHP,
    
    AblAbilityAttribute_Num
};
```

已知在lua中可以通过`EAttributeType.Attribute_HP`的方式获得枚举值。
但是在lua中似乎无法获得UEnum对象，所以无法使用`Enum->GetNameStringByValue(EnumeratorValue)`。
请问如何反过来通过枚举值获得枚举名的字符串呢？

谢谢。

**Comment by wangqinyincase** [comment]
同问

**Comment by xuyanghuang-tencent** [comment]
`UE4.ECollisionResponse:GetNameByValue(UE4.ECollisionResponse.ECR_Overlap)`

**Comment by TongYuSamwise** [comment]
Really helps, thanks a lot ~(^_^
