### ISSUE TITLE
UMG嵌套 Class循环引用导致内存泄露的问题

### ISSUE THREAD

**Issue by Harley-Jing** [Tencent/UnLua#242]
问题 ：嵌套UMG，Class循环引用导致内存泄
UnLua版本 ：1.1.0
UE4版本 ：4.26.1
平台: PC包 Development

问题重现：
1. 创建两个UMG，这里直接以A（UMG_Main），B（UMG_Test）代指
2. A，B均实现UnLuaInterface。
3. 在A中嵌入B
4. 销毁A的实例后，Class无法销毁

```c++
function UMG_Main_C:Destruct()
    print("====== [Harley] UMG_Main_C:Destruct")
    UObject.Destroy(self)
    UObject.Destroy(UUMG_Main_C)
end
```
```c++
function UMG_Test_C:Destruct()
    print("====== [Harley] UMG_Test_C:Destruct")
    UObject.Destroy(self)
    UObject.Destroy(UUMG_Test_C)
end
```

> LogReferenceChain: (root) (NeverGCed) GCObjectReferencer /Engine/Transient.GCObjectReferencer_2147482645::AddReferencedObjects(): Unknown FGCObject
LogReferenceChain:  UMG_Test_C /Game/Core/UI/UMG_Main.UMG_Main_C:WidgetTree.UMG_Test->Class
LogReferenceChain:   WidgetBlueprintGeneratedClass /Game/Core/UI/UMG_Test.UMG_Test_C
LogReferenceChain:   
LogReferenceChain: (root) (NeverGCed) GCObjectReferencer /Engine/Transient.GCObjectReferencer_2147482645::AddReferencedObjects(): Unknown FGCObject
LogReferenceChain:  UMG_Test_C /Game/Core/UI/UMG_Main.UMG_Main_C:WidgetTree.UMG_Test->Slot
LogReferenceChain:   CanvasPanelSlot /Game/Core/UI/UMG_Main.UMG_Main_C:WidgetTree.CanvasPanel_0.CanvasPanelSlot_8->Outer
LogReferenceChain:    CanvasPanel /Game/Core/UI/UMG_Main.UMG_Main_C:WidgetTree.CanvasPanel_0->Slots
LogReferenceChain:     CanvasPanelSlot /Game/Core/UI/UMG_Main.UMG_Main_C:WidgetTree.CanvasPanel_0.CanvasPanelSlot_4->Content
LogReferenceChain:      Button /Game/Core/UI/UMG_Main.UMG_Main_C:WidgetTree.ExitButton->Outer
LogReferenceChain:       WidgetTree /Game/Core/UI/UMG_Main.UMG_Main_C:WidgetTree->Outer
LogReferenceChain:        WidgetBlueprintGeneratedClass /Game/Core/UI/UMG_Main.UMG_Main_C->ScriptAndPropertyObjectReferences
LogReferenceChain:         WidgetBlueprintGeneratedClass /Game/Core/UI/UMG_Test.UMG_Test_C
LogReferenceChain:   
LogReferenceChain: (root) (NeverGCed) GCObjectReferencer /Engine/Transient.GCObjectReferencer_2147482645::AddReferencedObjects(): Unknown FGCObject
LogReferenceChain:  UMG_Test_C /Game/Core/UI/UMG_Main.UMG_Main_C:WidgetTree.UMG_Test->Slot
LogReferenceChain:   CanvasPanelSlot /Game/Core/UI/UMG_Main.UMG_Main_C:WidgetTree.CanvasPanel_0.CanvasPanelSlot_8->Outer
LogReferenceChain:    CanvasPanel /Game/Core/UI/UMG_Main.UMG_Main_C:WidgetTree.CanvasPanel_0->Slots
LogReferenceChain:     CanvasPanelSlot /Game/Core/UI/UMG_Main.UMG_Main_C:WidgetTree.CanvasPanel_0.CanvasPanelSlot_4->Content
LogReferenceChain:      Button /Game/Core/UI/UMG_Main.UMG_Main_C:WidgetTree.ExitButton->Outer
LogReferenceChain:       WidgetTree /Game/Core/UI/UMG_Main.UMG_Main_C:WidgetTree->Outer
LogReferenceChain:        WidgetBlueprintGeneratedClass /Game/Core/UI/UMG_Main.UMG_Main_C
LogReferenceChain:

**Comment by Harley-Jing** [comment]
![image](https://user-images.githubusercontent.com/49121194/117390631-19689d00-af21-11eb-8e9d-a5574cd92d22.png)

继续研究发现，UMG嵌套后导致UMG_Test添加了五次，卸载的时候只卸载了最后添加的那次。

这样修改后，解决了，但是现在还不知道为什么会多次添加。
![image](https://user-images.githubusercontent.com/49121194/117390942-9d228980-af21-11eb-8736-31c08b685755.png)

**Comment by MichaelZDL** [comment]
> ![image](https://user-images.githubusercontent.com/49121194/117390631-19689d00-af21-11eb-8e9d-a5574cd92d22.png)
> 
> 继续研究发现，UMG嵌套后导致UMG_Test添加了五次，卸载的时候只卸载了最后添加的那次。
> 
> 这样修改后，解决了，但是现在还不知道为什么会多次添加。
> ![image](https://user-images.githubusercontent.com/49121194/117390942-9d228980-af21-11eb-8736-31c08b685755.png)

我也遇到了这个问题，前几次的UMG_Test应该是加载Package的时候绑定的

**Comment by Harley-Jing** [comment]
> > ![image](https://user-images.githubusercontent.com/49121194/117390631-19689d00-af21-11eb-8e9d-a5574cd92d22.png)
> > 继续研究发现，UMG嵌套后导致UMG_Test添加了五次，卸载的时候只卸载了最后添加的那次。
> > 这样修改后，解决了，但是现在还不知道为什么会多次添加。
> > ![image](https://user-images.githubusercontent.com/49121194/117390942-9d228980-af21-11eb-8736-31c08b685755.png)
> 
> 我也遇到了这个问题，前几次的UMG_Test应该是加载Package的时候绑定的

具体可以展开说下吗？加载Package是指？

**Comment by MichaelZDL** [comment]
> > > ![image](https://user-images.githubusercontent.com/49121194/117390631-19689d00-af21-11eb-8e9d-a5574cd92d22.png)
> > > 继续研究发现，UMG嵌套后导致UMG_Test添加了五次，卸载的时候只卸载了最后添加的那次。
> > > 这样修改后，解决了，但是现在还不知道为什么会多次添加。
> > > ![image](https://user-images.githubusercontent.com/49121194/117390942-9d228980-af21-11eb-8736-31c08b685755.png)
> > 
> > 
> > 我也遇到了这个问题，前几次的UMG_Test应该是加载Package的时候绑定的
> 
> 具体可以展开说下吗？加载Package是指？

在这里加上这些代码，断个点，看堆栈可以看到这些对象是哪里创建出来的，我发现前几个卸载不掉的是来自创建Package的时候实例化的
![image](https://user-images.githubusercontent.com/14016306/119107658-0510be00-ba52-11eb-8b2c-50f71f56213c.png)
