### ISSUE TITLE
有关于UMG Destroy的疑问继续

### ISSUE THREAD

**Issue by lzj10** [Tencent/UnLua#243]
@lzj1989712 你可以参考这样的做法:
![image](https://user-images.githubusercontent.com/7972243/107194622-3d543980-6a2b-11eb-9138-40da61c73163.png)

_Originally posted by @rowechien in https://github.com/Tencent/UnLua/issues/227#issuecomment-774970167_

**Comment by lzj1989712** [comment]
按照你的方法销毁后 依然存在这个问题 ，Lua中实现的Destruct方法没有被调用到，因为Destroy的时候已经解除了Lua和UObject的绑定，Slate销毁的时候已经不存在绑定关系了
![image](https://user-images.githubusercontent.com/5946974/120153198-021b8780-c221-11eb-9ecf-d586ae46a6b0.png)
