### ISSUE TITLE
请大佬支持UE5

### ISSUE THREAD

**Issue by Naivebug** [Tencent/UnLua#247]
现在下载UE5跑不起来。一堆报错~大佬更新支持下。

**Comment by FTQZS** [comment]
+1

**Comment by xuyanghuang-tencent** [comment]
大部分报错都是因为宏定义的关系，可以尝试本地合入feature/ue5分支，目前Tutorial相关都是可以跑通的，欢迎反馈

**Comment by qmpz00** [comment]
UE5-master分支 有几处编译错误,  大佬有空看一下 :
1. 绝大部分是因为UE5的FLargeWorldCoordinatesReal 从float 改为了double类型   ---> float改为double可解决
2. ADD_FUNCTION(ToAxisAndAngle)   推导RetType失败       -->   没解决
3. linkError   Dot3/Dot4  --->  修改LuaLib_FVector4.cpp 中的float为double

**Comment by xuyanghuang-tencent** [comment]
目前 `feature/ue5` 分支上只支持到了5.0EA，抽空我看一下，如果你找到解决方法了也可以直接PR到这个分支上

**Comment by crazytuzi** [comment]
> 

ADD_CONST_FUNCTION_EX("ToAxisAndAngle", void, TQuat<double>::ToAxisAndAngle, UE::Math::TVector<double>&, double&)

**Comment by crazytuzi** [comment]
ADD_FUNCTION(ToAxisAndAngle) 推导RetType失败 --> ADD_CONST_FUNCTION_EX("ToAxisAndAngle", void, TQuat<double>::ToAxisAndAngle, UE::Math::TVector<double>&, double&) @CharlesFriday
