### ISSUE TITLE
C++如何直接调用lua的方法？

### ISSUE THREAD

**Issue by untitledlhc** [Tencent/UnLua#248]
之前搜索C++ bytes和lua之前如何相互传递，找到了一个回答是LuaStateMgr:GetLuaStateMgr:CallLuaFunction(),但是在官方库里面没找到LuaStateMgr的类～～求大佬

**Comment by untitledlhc** [comment]
找到方法了,项目引入 UnLua Lua 的依赖库，然后调用
	UnLua::FLuaFunction luaFunc("OnGlobalFuncTest");
	int32 value = 100;
	int32 value2 = 9;
	luaFunc.Call(value, value2);

**Comment by wh569860630** [comment]
![image](https://user-images.githubusercontent.com/17903846/124751735-903e0880-df59-11eb-90ff-06d153f30c24.png)
