### ISSUE TITLE
lua中如何创建DynamicDelegate？

### ISSUE THREAD

**Issue by Junho2009** [Tencent/UnLua#26]
在自定义的AssetManager子类中，提供了一些异步加载资源的接口。这些接口的参数一般是
（要加载的资源路径，回调Delegate）
对于暴露给蓝图的版本，使用的Delegate是通过宏"DECLARE_DYNAMIC_DELEGATE_XXX"来定义的，也就是DynamicDelegate。
以前使用另一种lua方案时，方案中定义了一个形如“LuaDelegate”的类型，并提供了一个给lua使用的接口“createDelegate”——传入参数是lua函数，返回值是LuaDelegate对象。这个LuaDelegate对象就可作为DynamicDelegate类型的参数来使用。
请问在UnLua下，如何实现类似的调用需要？

**Comment by Junho2009** [comment]
Duplicate of #19 
这个issue的作者提到，UnLua的示例工程里，用到 UKismetSystemLibrary.K2_SetTimerDelegate 的地方有相关示例。

我试了下，似乎是：拥有此回调函数的lua对象，必须对应着一个UObject对象。
是否可以不受这个限制呢？
因为在平时使用中，可能是在某个纯lua table类中，定义了一个回调函数，然后调用某个C++暴露给蓝图的接口（如上面所说的资源加载接口），然后等待资源加载完成，再在lua中做进一步处理。

**Comment by rowechien** [comment]
能在蓝图中使用的delegate (ScriptDelegate, MulticastScriptDelegate， 4.23.x加了一种叫SparseDelegate)，它们绑定回调都需要绑定一个UObject，所以在lua中使用delegate相关功能（Bind, Unbind, Add, Remove，还有你说的创建操作等）都需要提供一个对应的UObject。
如果不想提供这个UObject，那做法就是内部创建一个临时的UObject对象，这是可以操作的，但会有额外的消耗，所以UnLua并没有选择这个方案

**Comment by Junho2009** [comment]
> 能在蓝图中使用的delegate (ScriptDelegate, MulticastScriptDelegate， 4.23.x加了一种叫SparseDelegate)，它们绑定回调都需要绑定一个UObject，所以在lua中使用delegate相关功能（Bind, Unbind, Add, Remove，还有你说的创建操作等）都需要提供一个对应的UObject。
> 如果不想提供这个UObject，那做法就是内部创建一个临时的UObject对象，这是可以操作的，但会有额外的消耗，所以UnLua并没有选择这个方案

**目前对delegate的机制不太了解，为了先以低修改成本的方式接入，请教一下怎么实现“内部创建临时UObject”的方式，来暂时兼容类似原来的做法呢？**

目前我做的尝试是，参考原lua方案，自行定义类似原来“LuaDelegate”的UObject子类，编写了一个静态导出函数Create，函数中先是NewObject了一个LuaDelegate对象，然后从lua栈中获取传过来的lua函数，并保存为LuaDelegate的一个FLuaFunction对象（UnLua定义的）。然后在lua中，将Create所得到的LuaDelegate对象，传递给接收DynamicDelegate参数的UFunction。
为了方便说明，假设要调的UFunction是这样的：GetAsset(Path, Callback)，Callback是DynamicDelegate类型的。
**目前遇到的问题是**，我按照 LuaCore.cpp 中 GetDelegateInfo 所要求的格式，在lua层构造了一个table，里面有两个元素，一个是上面所说的 LuaDelegate对象，另一个是我希望调用的lua回调函数。在C++层的断点看到，GetAsset函数的Callback实参，已经绑定了UObject，但最后回调时并没有触发lua层的对应函数。
是因为，lua层构造的table，第二个元素的lua回调函数，必须是第一个元素（UObject）对应的lua table的函数才可以吗？

**Comment by Junho2009** [comment]
> 能在蓝图中使用的delegate (ScriptDelegate, MulticastScriptDelegate， 4.23.x加了一种叫SparseDelegate)，它们绑定回调都需要绑定一个UObject，所以在lua中使用delegate相关功能（Bind, Unbind, Add, Remove，还有你说的创建操作等）都需要提供一个对应的UObject。
> 如果不想提供这个UObject，那做法就是内部创建一个临时的UObject对象，这是可以操作的，但会有额外的消耗，所以UnLua并没有选择这个方案

**目前对delegate的机制不太了解，为了先以低修改成本的方式接入，请教一下怎么实现“内部创建临时UObject”的方式，来暂时兼容类似原来的做法呢？**

以下先简要说明我做过的尝试。为了方便说明具体的使用场景，假设我要调的UFunction是这样的：GetAssetByName(Path, Callback)。其中，Callback是DynamicDelegate类型的。
**首先**，参考原lua方案，自行定义了一个类似原来“LuaDelegate”的UObject子类，然后为其编写一个静态的导出函数“Create”，以在lua层调用、创建这个LuaDelegate对象。
**然后**，按照 LuaCore.cpp 中 GetDelegateInfo 函数所要求的格式，在lua层构造了一个table，作为Callback参数传入。例如这样：
local dlgt = ULuaDelegate.Create()
UAssetMgr.K2_GetAssetByName(Path, {dlgt, XXXTab.CallbackFunc})
从C++断点上看，在 UEReflectionUtils.cpp 的 FDelegatePropertyDesc.SetValueInternal 中，是创建了一个Delegate的绑定。但最终并没有正常回调到lua那边（XXXTab.CallbackFunc），也没有报错。
是这种绑定方式有问题吗？我试过将 XXXTab 改为 dlgt在lua创建的函数，仍然不起效果。

由于沿用原lua方案，lua中不少地方用到了“临时UObject绑定Delegate”的方式，而我本人对此确实不怎么了解，所以请教一下怎么实现这种方式。感谢！

**Comment by Junho2009** [comment]
@rowechien

**Comment by rowechien** [comment]
你说的原有方案是哪个我不清楚，我也没仔细去了解过现有的其他方案。简单来说，UnLua里对delegate进行Add， Bind时，第一个UObject参数是需要开发者自己传入的，如果想省去这一步，只需要插件内部生成一个临时的UObject来代替现在需要传入的参数，具体需要你自己去修改代码了。
但是，我还是觉得由开发者自己传入一个UObject才是最合理的方式，你可以尝试在C++代码里为一个dynamic delegate绑定一个回调，看看代码是怎样调用的就会明白。

**Comment by hxhb** [comment]
> > 能在蓝图中使用的delegate (ScriptDelegate, MulticastScriptDelegate， 4.23.x加了一种叫SparseDelegate)，它们绑定回调都需要绑定一个UObject，所以在lua中使用delegate相关功能（Bind, Unbind, Add, Remove，还有你说的创建操作等）都需要提供一个对应的UObject。
> > 如果不想提供这个UObject，那做法就是内部创建一个临时的UObject对象，这是可以操作的，但会有额外的消耗，所以UnLua并没有选择这个方案
> 
> **目前对delegate的机制不太了解，为了先以低修改成本的方式接入，请教一下怎么实现“内部创建临时UObject”的方式，来暂时兼容类似原来的做法呢？**
> 
> 以下先简要说明我做过的尝试。为了方便说明具体的使用场景，假设我要调的UFunction是这样的：GetAssetByName(Path, Callback)。其中，Callback是DynamicDelegate类型的。
> **首先**，参考原lua方案，自行定义了一个类似原来“LuaDelegate”的UObject子类，然后为其编写一个静态的导出函数“Create”，以在lua层调用、创建这个LuaDelegate对象。
> **然后**，按照 LuaCore.cpp 中 GetDelegateInfo 函数所要求的格式，在lua层构造了一个table，作为Callback参数传入。例如这样：
> local dlgt = ULuaDelegate.Create()
> UAssetMgr.K2_GetAssetByName(Path, {dlgt, XXXTab.CallbackFunc})
> 从C++断点上看，在 UEReflectionUtils.cpp 的 FDelegatePropertyDesc.SetValueInternal 中，是创建了一个Delegate的绑定。但最终并没有正常回调到lua那边（XXXTab.CallbackFunc），也没有报错。
> 是这种绑定方式有问题吗？我试过将 XXXTab 改为 dlgt在lua创建的函数，仍然不起效果。
> 
> 由于沿用原lua方案，lua中不少地方用到了“临时UObject绑定Delegate”的方式，而我本人对此确实不怎么了解，所以请教一下怎么实现这种方式。感谢！

你最后是怎么解决的呢？同样遇到了需要把代理对象传递给K2_SetTimerDelegate的问题。
