### ISSUE TITLE
2.0版本的FindLuaLoader有bug。

### ISSUE THREAD

**Issue by isaf** [Tencent/UnLua#260]
如果lua是5.43之前的版本，在遍历searchers的时候，searchers在栈的位置应该是4，lua_rawgeti的第2个参数要传4（上个版本的时候就是4，不知道为什么2.0要改为3，被注释坑了？）
如果lua版本是5.43，luaL_buffinit是会压一个数据进栈的（lua官方说明也有问题，官方文档显示没有数据压栈），此时searchers在栈的位置应该是5。
其实不管哪种情况，searchers都在栈顶，lua_rawgeti的第2个参数传-1就行了。

**Comment by hernanzhou** [comment]
感谢提醒，并给出这么详细的解释，相关bug 在公司内使用时，也有其他同事遇到，已经提交了修改，相关 commit:
https://github.com/Tencent/UnLua/commit/b6be86e149c1b923286410a0e5ac6e37fed7cde0
