### ISSUE TITLE
仿照样例编写静态导出类型编译不通过

### ISSUE THREAD

**Issue by chowJY** [Tencent/UnLua#261]
编译始终提示，无法打开LuaCore的头文件。

**Comment by chowJY** [comment]
![image](https://user-images.githubusercontent.com/19146127/133753973-d6aae98c-a7bc-4b8a-9fbb-22f32d642170.png)
build已经引入了Unlua和lua 模块

**Comment by hernanzhou** [comment]
一般只要引入 UnLua 的依赖即可使用，可以参考 仓库工程 Source 目录下的 TutorialObject.cpp 文件， 如果方便的话，建议提供一个可以复现的demo方便定位看下

**Comment by yeheiGame** [comment]
#include "../Private/LuaCore.h"
这样写就可以了
