### ISSUE TITLE
创建Lua模版按钮所创建的Lua文件的路径和文件名问题

### ISSUE THREAD

**Issue by Mapz** [Tencent/UnLua#27]
- GetModuleName 返回 BP_Game 的时候， 创建的 Lua 文件为 BP_Game_C ，加载 Lua 文件的时候，却加载的 BP_Game.lua，导致加载失败

- GetModuleName 返回 XX.BP_Game_C 的时候，创建的 Lua 文件的位置还是在 Script 目录下，而不是正确的 Script/XX 

- 创建模版的时候，没有提示，直接覆盖了以前的文件，感觉不妥

**Comment by rowechien** [comment]
理论上是可以根据GetModuleName()函数的返回值来创建对应的lua模板，提示也是可以做的，但我们选择了最简单的方式，单纯的生成一个模板，至于它目标的位置还有最终的名字都交给程序员自己去调整
