### ISSUE TITLE
Unlua2.0版本Lua中全局函数无法直接在C++中调用Call了

### ISSUE THREAD

**Issue by kevinofsias** [Tencent/UnLua#275]
比如lua中有
function AA()
end
在C++中无法直接调用
	UnLua::Call(UnLua::GetState(), "AA");
会报Global function AA doesn't exist!
我记得以前1.几版本的时候是可以直接调用的，现在全局函数需要加一句_G.AA = AA,或者如下，
function _G.AA()
end
怎么弄呢

**Comment by kevinofsias** [comment]
--testlua.lua
fuction testfunc()
  print("this is a test function")
end

--xxactor.cpp
void Axxactor::BeginPlay()
{
 Super::BeginPlay();
 if(Unlua::Call(Unlua::GetState(),"require","testlua").IsValid())
  Unlua:Call(Unlua::GetState(),"testfunc");
}


以上测试代码在unlua1.0可以打印this is a test function，在2.0版本提示找不到testfunc函数。

**Comment by kevinofsias** [comment]
> 使用 `UnLua::Call(L, "AA")` 调用全局函数的方式并没有错，只是热重载模块导致了直接 `function AA() end` 并不会把函数写到真正的 `_G`。有两种解决方式可以参考： 1、使用`function _G.AA() end` 2、移除`UnLuaFrameWork`模块（也要移除UnLua.uplugin里相应的声明）

实测2套方案均可行，谢谢。

**Comment by xuyanghuang-tencent** [comment]
UnLua 2.0.1 默认关闭了热重载模块
