### ISSUE TITLE
游戏世界暂停后，coroutine delay 功能不工作

### ISSUE THREAD

**Issue by xiejiangzhi** [Tencent/UnLua#276]
Unlua 1.2

通过蓝图创建 UI 后，使用蓝图节点 SetGamePause。

这时，游戏世界是暂停的，UI是可以正常使用的。

在 widget 蓝图中， construct 后或者任何事件后，都可以正常加入 delay 节点，并能执行节点后的逻辑。

而在 lua 中通过 coroutine 调用的 delay ，在游戏暂停时，永远不会被执行，只会等到游戏取消暂停后才会继续执行。

lua 调用 delay 传入的 world context object 是 widget 本身。

源代码看不懂 latent 的实现。求助！

**Comment by xuyanghuang-tencent** [comment]
的确有这个问题，因为一些历史设计原因目前没有找到更优雅的设计，可以参考上面的两个提交：

https://github.com/Tencent/UnLua/blob/feature/tests/Content/Script/Tests/Regression/Issue276/TestWidget.lua

增加了UUnLuaLatentAction:SetTickableWhenPaused()用来应对需要Pause和非Pause的应用场景，下个版本会合入master

**Comment by xiejiangzhi** [comment]
辛苦辛苦,, 由于不太了解 C++ 方面的东西，我自己就简单弄了一个暂停游戏后可以手动 Tick 的 TimerManager 来解决延迟时的问题。。。
