### ISSUE TITLE
取父类成员使用 self.Super.XXX 返回类型为 userdata 类型

### ISSUE THREAD

**Issue by Mapz** [Tencent/UnLua#28]
如果一个父类蓝图类中有成员 XXComponent
则在子类Lua类中
通过 self.XXComponent 可取出正确的类型 UXXComponent 的变量
通过 self.Super.XXComponent 去获得则得到一类型为 userdata 的变量

**Comment by rowechien** [comment]
self.XXComponent可以正常访问，为何要用self.Super.XXComponent这种方式呢。。。前面这种方式也是符合正常的编程习惯啊。
self是UObject实例在lua中的副本（本质是个lua table），而self.Super并不是一个UObject实例，它就是lua中调用Class()返回的一个lua table，它们是不同东西。。。

**Comment by Mapz** [comment]
其实这么是有个问题的哈
例如
父类
function A.RecieveBeginPlay()
 local name = self:GetName()
end
子类
function B.RecieveBeginPlay()
 self.Super:ReciveBeginPlay()
end
因为 self.Super 不是一个合法的 object
所以 GetName 会报错
