### ISSUE TITLE
UMG 内嵌依然会内存泄露呀?

### ISSUE THREAD

**Issue by jackfong66** [Tencent/UnLua#282]
A Widget 中 放一个B Widget

A,B都有各自的蓝图.

**Comment by xuyanghuang-tencent** [comment]
Content/Tutorials/11_ReleaseUMG

这里有你提到的UMG嵌套的案例，ReleaseUMG_ItemParent里包含了ReleaseUMG_ItemChild，描述下如何重现你所说的情况？

**Comment by jackfong66** [comment]
> 内容/教程/11_ReleaseUMG
> 
> 这里有你提到的UMG 语义的案例，ReleaseUMG_ItemParent 里包含了ReleaseUMG_ItemChild，描述下如何重现你所说的情况？

是的,我使用ReleaseUMG例子

RealaseUMG_Root 能够安全释放, 但是嵌套的子Widget 还存在于内存

点击 "释放全部" 并C++gc luagc 后使用Obj List , Obj Refs 查看如下
![xxxx](https://user-images.githubusercontent.com/407890/140488441-6e4dae73-6c3f-4d92-a81b-6ca5fe810321.png)
![企业微信截图_16361045661409](https://user-images.githubusercontent.com/407890/140489228-dc5216fd-132f-47a4-b811-822e301d7992.png)
![企业微信截图_16361046197714](https://user-images.githubusercontent.com/407890/140489244-4dc1d077-cfb7-4266-84f9-9e7f5205e772.png)

**Comment by xuyanghuang-tencent** [comment]
![image](https://user-images.githubusercontent.com/83756024/140675003-09e6626e-dd66-4031-b107-6956a51cdaf9.png)

1. 打开ReleaseUMG场景
2. 创建元素
3. 释放全部
4. C++ GC
5. Lua GC

貌似没有重现。。。截图里还有带root的Function的确是比较奇怪
