### ISSUE TITLE
require 不存在的 lib 会崩

### ISSUE THREAD

**Issue by xiejiangzhi** [Tencent/UnLua#284]
测试使用 master 分支最新代码，平台： win10， UE 4.26.2

在BP_ProjectileBase_C  require 了一个不存在的 lib

```
function BP_ProjectileBase_C:ReceiveBeginPlay()
	self:SetLifeSpan(4.0)
	require 'asdf.asdf'
end
```

只要一开枪编辑器就崩了

**Comment by xiejiangzhi** [comment]
![image](https://user-images.githubusercontent.com/1396853/141061691-5a68bd18-326e-4cbf-a565-19cb9e040db7.png)

![image](https://user-images.githubusercontent.com/1396853/141061785-ef8227a6-085b-4401-9d31-2ef05ee6015b.png)

![image](https://user-images.githubusercontent.com/1396853/141061848-5331647e-5b77-456e-a172-d4da3e2ea67f.png)

上面是调用堆栈
看不懂 lua 的堆栈操作。。太难了。。

**Comment by xuyanghuang-tencent** [comment]
麻烦试一下master上最新的修改

**Comment by xiejiangzhi** [comment]
刚测试已经正常，不会崩了，感谢修复。
