### ISSUE TITLE
UMG里Image用到的Texture内存泄漏

### ISSUE THREAD

**Issue by ulympgf** [Tencent/UnLua#288]
用obj list看UMG对象释放了，但UMG里Image控件引用的Texture没有释放

**Comment by ulympgf** [comment]
首先我把ReleaseUMG_ItemParent界面里的Image_Background设置了一张图：
![image](https://user-images.githubusercontent.com/39459051/141448759-a98db4af-afdf-4e08-b373-8adb05b3a092.png)
然后运行demo在点“创建元素”之前使用 memreport -full 导出数据，然后创建元素，按Demo的流程释放对象, 
 用obj list 查看ReleaseUMG_ItemParent确实释放了
![image](https://user-images.githubusercontent.com/39459051/141449128-abd24bf7-0330-4d3d-a63f-6da5043ac1e7.png)
接着再使用 memreport -full 导出数据，对比2份数据，发现图片资源没有释放：
![image](https://user-images.githubusercontent.com/39459051/141449231-aa5095c8-e295-47bb-ba4a-ee251a9c65bc.png)

**Comment by ulympgf** [comment]
我在2.0.1的版本上，更新了#289的代码，移动端会经常闪退。还原就正常。
![image](https://user-images.githubusercontent.com/39459051/142593470-89f55024-af0a-4ee8-8ba8-714e0065f330.png)

**Comment by xuyanghuang-tencent** [comment]
看堆栈和 #289 的情况一样，可能是哪里实现还有点问题。是只有真机Crash，Editor下不会吗？能否发一个精简过的复现工程给我，我来跟一下

**Comment by ulympgf** [comment]
只有真机，editor不会，没办法提供工程哦，不是100%Crash，概率很大，每次Crash的地方都可能不一样，但基本都是Delegate

**Comment by xuyanghuang-tencent** [comment]
和切地图有关系吗，或者试试能不能在UnLua的工程做个重现？

**Comment by ulympgf** [comment]
没关系，但发生问题的Delegate都是C++定义，绑的lua function

**Comment by ulympgf** [comment]
我试试看在Unlua的工程里能不能重现

**Comment by ulympgf** [comment]
在UnLua的工程里无法重现

**Comment by xuyanghuang-tencent** [comment]
或者直接拉develop分支的UnLua在你的工程里试试？可能有某个commit依赖我漏了标注

**Comment by ulympgf** [comment]
develop试了下，也会崩

**Comment by xuyanghuang-tencent** [comment]
@ulympgf 再试试develop上的最新提交？

**Comment by ulympgf** [comment]
试了，还是一样
![image](https://user-images.githubusercontent.com/39459051/144191273-d82da925-2e0a-4d24-a105-14795faf2fea.png)

**Comment by xuyanghuang-tencent** [comment]
这个堆栈和之前的似乎不一样，像之前那样挂在`FReflectionRegistry::RegisterFunction` 的情况还有出现吗？

` check(Function->FunctionRef == INDEX_NONE || Function->FunctionRef == InFunctionRef);`  ← 挂在这一行

**Comment by ulympgf** [comment]
之前的没有出现了

**Comment by xuyanghuang-tencent** [comment]
@ulympgf 这个issue我先关了，转到#299。后续如果找到复现方式的话我们在2.1.1版本中修复。
