### ISSUE TITLE
IntelliSence 生成的 API 不是很齐全

### ISSUE THREAD

**Issue by Mapz** [Tencent/UnLua#29]
例如 UWorld 就没有 SpawnActor

**Comment by rowechien** [comment]
IntelliSense是和UHT一同工作的，它只能感知到反射体系内的数据（UClass, UScriptStruct, UEnum, UFunction, UProperty等）。
反射体系之外被静态导出的类、函数等有个Commandlet （UUnLuaIntelliSenseCommandlet）可以生成。
