### ISSUE TITLE
AnimNotifyState没有绑定

### ISSUE THREAD

**Issue by impulsexuan** [Tencent/UnLua#290]
PIE模式下动画中的AnimNotifyState没有绑定Lua，怎么破？

**Comment by xuyanghuang-tencent** [comment]
#85 目前UnLua这样的工作机制虽然不影响真机游戏，但在编辑器下的确有点局限性。后面可能考虑在启动的时候就拉起UnLua环境，这个环境是随着整个编辑器生命周期的，但相应的还有很多前置工作要做。比如做多UnLua环境的隔离，这样也能解决单进程模式下多人游戏RPC的问题。

**Comment by impulsexuan** [comment]
谢谢，了解！

**Comment by Mr-Gu666** [comment]
请问现在有支持吗?

**Comment by xuyanghuang-tencent** [comment]
换了种方式，已经支持了

**Comment by Mr-Gu666** [comment]
但是我的AnimNotify并没有执行到Lua函数,而且在启动编辑器之后,只有第一次执行了Lua函数.

**Comment by Mr-Gu666** [comment]
请问是怎么支持的呢?

**Comment by xuyanghuang-tencent** [comment]
什么版本？新版UnLua会在PIE启动的时候对内存里所有指定类型进行预绑定
https://github.com/Tencent/UnLua/blob/master/Plugins/UnLua/Source/UnLua/Private/UnLuaSettings.cpp

可以在UnLua菜单->设置->运行时->预绑定类型里添加对应的类型

**Comment by Mr-Gu666** [comment]
谢谢.
我使用的版本是 2.2.1 看起来似乎没有更新到支持 AnimNotify 的版本
