### ISSUE TITLE
delegate绑定本身不在lua里有引用的object，在绑定后触发gc会导致无法调用绑定的函数。

### ISSUE THREAD

**Issue by unicodecndddd** [Tencent/UnLua#291]
~~如以下绑定代码：~~
~~调用bind()后，如果发生gc。Capsule对应的lua会被销毁。直接调用LuaCore.cpp中的DeleteUObjectRefs~~
~~但实际上delegate绑定的object并没有被销毁，只是对应的lua被销毁了。~~

之前的说明有点问题。应该是delegate绑定本身不在lua里有引用的object，在绑定后触发gc会导致无法调用绑定的函数。

我用的是最新的master
测试用例如下：
``` lua
print("++++++++++++++++++++++++++++++++++++++++")

local class = LoadClass("角色蓝图")
actor = world:SpawnActor(class)

function test()
    error("test++++++++++++++++++++++++++++++++++++++++")
end

print("bind++++++++++++++++++++++++++++++++++++++++")
actor.Capsule.OnInputTouchBegin:Add(actor.Capsule, test)

print("gc++++++++++++++++++++++++++++++++++++++++")
UE4.UKismetSystemLibrary.CollectGarbage()
collectgarbage("collect")

-- 不会生效
print("Broadcast++++++++++++++++++++++++++++++++++++++++")
actor.Capsule.OnInputTouchBegin:Broadcast()

print("++++++++++++++++++++++++++++++++++++++++")
```

我这边输出的log信息
LogUnLua: UNLUA_PRINT[138991] : [LuaLog]    [string "module/gm/gm_manager.lua"]:177  ++++++++++++++++++++++++++++++++++++++++    
LogUnLua: PushObjectCore : 0000029407DC1D00,BP_Cst_Preview_Test_C,ABP_Cst_Preview_Test_C
LogUnLua: RegisterClass : ABP_Cst_Preview_Test_C,0000029434208F00
LogUnLua: PushObjectCore : 00000293E5994100,EntryLevel,UWorld
LogUnLua: PushObjectCore : 0000029444B0A080,BP_Cst_Preview_Test_C_0,ABP_Cst_Preview_Test_C
LogUnLua: UNLUA_PRINT[138991] : [LuaLog]    [string "module/gm/gm_manager.lua"]:186  bind++++++++++++++++++++++++++++++++++++++++    
LogUnLua: RegisterClass : UNavRelevantInterface,0000029434208800
LogUnLua: RegisterClass : UCapsuleComponent,0000029434209280
LogUnLua: PushObjectCore : 00000294406FB900,Capsule,UCapsuleComponent
LogUnLua: GetMulticastDelegateInfo : 00000294406FBDAA,00000294406FB900,Capsule
LogUnLua: FDelegateHelper::Add: 00000294406FBDAA,00000294406FB900,Capsule
LogUnLua: UNLUA_PRINT[138991] : [LuaLog]    [string "module/gm/gm_manager.lua"]:189  gc++++++++++++++++++++++++++++++++++++++++    
LogUnLua: UObject_Delete : Capsule,00000294406FB900!
LogUnLua: RemoveUFunction: [0000029415644E00], [LuaFunc:[module/gm/gm_manager.lua:176]_CppMulticastDelegate:[Capsule.OnInputTouchBegin_86F4FD204A72EF38FC6FB6A58E6F9949]] From Class : [00000293C29BD080], [Class /Script/Engine.CapsuleComponent]
LogUnLua: ~FFunctionDesc : LuaFunc:[module/gm/gm_manager.lua:176]_CppMulticastDelegate:[Capsule.OnInputTouchBegin_86F4FD204A72EF38FC6FB6A58E6F9949],000002941A8B35E0
LogUnLua: UObject_Delete : EntryLevel,00000293E5994100!
LogUnLua: UNLUA_PRINT[138991] : [LuaLog]    [string "module/gm/gm_manager.lua"]:193  Broadcast++++++++++++++++++++++++++++++++++++++++    
LogUnLua: PushObjectCore : 00000294406FB900,Capsule,UCapsuleComponent
LogUnLua: UNLUA_PRINT[138991] : [LuaLog]    [string "module/gm/gm_manager.lua"]:195  ++++++++++++++++++++++++++++++++++++++++

**Comment by xuyanghuang-tencent** [comment]
是master上的版本吗？我在develop和master上都试了下没有重现，可以尝试修改下上面提到的测试用例看看能不能重现。

PS：由于master上还没有自动测试机制，我在master上的手动重现步骤是：
1、新建一个测试用的蓝图TestActor，里边加上Capsule组件，不绑定Lua
2、在MainMap中放置2个这个TestActor，分别命名为Actor1和Actor2作为变量暴露
3、用Lua实现MainMap的关卡蓝图，执行 `self.Actor1.Capsule.OnInputTouchBegin:Add(self.Actor2.Capsule, function() end)`
4、每帧进行luagc+uegc

发现不会执行到 `DeleteUObjectRefs` ，是哪里有遗漏的细节么

**Comment by unicodecndddd** [comment]
我用的是最新的master，我看看是不是漏了什么步骤

**Comment by unicodecndddd** [comment]
需要把绑定方法加到一个lua函数中，函数调用完执行gc，就会触发。
lua代码可以改成：

**Comment by unicodecndddd** [comment]
其实主要问题是绑定的function不会被调用。之前怀疑是因为绑定的object被销毁导致的。

**Comment by xuyanghuang-tencent** [comment]
重现了，我看下

**Comment by xuyanghuang-tencent** [comment]
梳理了下流程：
1、在`OnInputTouchBegin:Add`的时候创建了一个 `FScriptDelegate`，绑定到**第一个参数**
2、`actor.Capsule` 在Lua侧的引用在GC后就会被回收，此时回调到 `UObject_Delete` ，进入 `DeleteUObjectRefs` 进行引用的移除
3、触发 `FDelegateHelper::Remove` ，对象为Capsule（也就是 **第一个参数** ），释放它所有相关的回调信息和对应的`FScriptDelegate`

从设计上看是为了使用**第一个参数**在Lua侧的生命周期作为动态委托的生命周期，这里可能比较引起歧义认为是UObject的生命周期。目前来看，这个Issue只能说是设计如此。

PS：
这里的实现是通过将UFUNCTION动态创建后AddFunctionToFunctionMap到**第一个参数**所对应的UClass上，感觉不如由UnLua创建一个对象来负责转发、统一管理生命周期更干净点。这样在调用的风格上也更符合UE原生的样式：

```
self.Actor.Capsule.OnInputTouchBegin:Add(function() end) -- 隐式创建，C++侧强引用，UnLua自动管理

self.Callback = UnLua.CreateDelegate(function() end) -- 显示创建，Lua侧强引用，用户手动管理
self.Actor.Capsule.OnInputTouchBegin:Add(self.Callback) 
```

等下个版本的时候我看看怎么调整下吧，要是有什么点子也可以交流。

**Comment by unicodecndddd** [comment]
我之前的想法是在DeleteUObjectRefs中判断一下绑定的对象是不是真的被销毁了，再处理delegate的解绑。因为delegate的生命周期应该和传入的object相同，而不是object的lua引用。

但是如果能直接让unlua管理第一个参数，就不需要考虑这些问题，确实更方便一些。在lua侧的代码写起来也方便。唯一的问题是这个自动创建的对象的生命周期是什么样的，这样绑定之后是不是只能主动销毁了。

**Comment by xuyanghuang-tencent** [comment]
自动创建的生命周期可以跟着 `OnInputTouchBegin` 这个 `FMulticastDelegateProperty` 的Owner，通过 `FPropertyDesc` 就可以拿到，这里就是 `Capsule` 了。可以用个`Map<TWeakPtr, TArray>`记录下 `Capsule` 和自动创建的对象列表，在 `Capsule` 真实销毁的时候把对应的列表下所有的委托都清理了。大致想法是这样，可能实践起来还会有别的细节问题。

**Comment by xuyanghuang-tencent** [comment]
[v2.2.0](https://github.com/Tencent/UnLua/releases/tag/v2.2.0)
