### ISSUE TITLE
静态绑定的类的子类，动态绑定失败的问题

### ISSUE THREAD

**Issue by Mapz** [Tencent/UnLua#30]
蓝图父类 -- Lua 父类 在蓝图中 静态绑定
蓝图子类 -- Lua 子类 未在蓝图中 静态绑定
尝试在 Lua 代码中 world spawn actor 动态绑定 Lua 子类到蓝图子类上
执行后，Lua 子类没有绑定上 ，子类的 field 没有办法获取

**Comment by rowechien** [comment]
这种情况下，插件会判断子类也实现了UnLuaInterface这个接口，也就说认为子类也是静态绑定的，所以会出现你描述的问题。
从根本上说，当某个类既有静态绑定又有动态绑定，插件是优先考虑静态绑定，具体你可以看FLuaContext::TryToBindLua(...)这个函数的实现。
如果你确实有这种需求，可以把两者的判断顺序替换一下即可，具体如下图：
![TryToBindLua](https://user-images.githubusercontent.com/7972243/63835217-94865b80-c9a9-11e9-954e-19ccde40b16a.png)
