### ISSUE TITLE
使用CreateLuaTemplate按钮创建的lua文件不能正确绑定

### ISSUE THREAD

**Issue by BlackdBlook** [Tencent/UnLua#301]
版本：ue4.27.1   unlua2.1.0   使用示例项目添加一个LuaActor
使用按钮创建的lua文件并不能正确绑定,
CreateLuaTemplate生成的路径默认为蓝图所在路径，而不是GetModuleName返回的值，因此不能正确匹配
GetBindingStatus ”正确的“ 返回了 BoundButInvalid
将lua文件移动到GetModuleName指定的路径下可以正常绑定

GetModuleName的值：
![image](https://user-images.githubusercontent.com/47099583/145199730-e28805f8-4d27-4854-aca3-3bffd9eb6df4.png)
实际生成的文件的路径：
![image](https://user-images.githubusercontent.com/47099583/145199774-e96f5610-7df0-4698-8505-c71ef175f252.png)

**Comment by xuyanghuang-tencent** [comment]
旧版的UnLua设计时可能考虑从蓝图文件目录结构来对应到Lua，目前看来和预期使用方式不太符合，已修改
