### ISSUE TITLE
有没有办法调用 BlueprintFunctionLibrary 中的全局方法

### ISSUE THREAD

**Issue by l15621737** [Tencent/UnLua#306]
RT

**Comment by xuyanghuang-tencent** [comment]
如果是在C++里定义的可以参考[教程](https://github.com/Tencent/UnLua/blob/master/Content/Script/Tutorials/08_CppCallLua.lua)直接这样访问：
```
      UE.UTutorialBlueprintFunctionLibrary.CallLuaByGlobalTable()
```

如果是从蓝图定义的：
```
	local MyFunctionLibrary = UE.UClass.Load("/Game/MyFunctionLibrary.MyFunctionLibrary_C")
	MyFunctionLibrary.Test()
```

**Comment by l15621737** [comment]
多谢大佬回复&nbsp;



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月13日(周一) 下午2:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Tencent/UnLua] 有没有办法调用 BlueprintFunctionLibrary 中的全局方法 (Issue #306)




 
如果是在C++里定义的可以参考教程直接这样访问：
       UE.UTutorialBlueprintFunctionLibrary.CallLuaByGlobalTable()  
如果是从蓝图定义的：
 local MyFunctionLibrary = UE.UClass.Load("/Game/MyFunctionLibrary.MyFunctionLibrary_C") MyFunctionLibrary.Test()  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
