### ISSUE TITLE
lua重写"BlueprintNativeEvent"函数时，报"Failed to bind native function xxx"的警告提示

### ISSUE THREAD

**Issue by Junho2009** [Tencent/UnLua#31]
初步debug一下，似乎与 UnLuaManager 中处理lua重写蓝图事件接口的逻辑有关，在对UFunction对象做复制处理的地方。
请问这个提示是否有影响呢？（使用方面是不影响的，可以正确调用到lua的重写版本）

**Comment by rowechien** [comment]
不影响使用。之后我想办法去掉这个告警
