### ISSUE TITLE
不同的UMG类绑定同一个脚本,Lua无法获取返回的控件

### ISSUE THREAD

**Issue by gbyyy** [Tencent/UnLua#320]
测试环境如下:
创建BP_UMG_A和BP_UMG_B,绑定同一个脚本BP_UIBase,
BP_UMG_A有ImageA,BP_UMG_B有ImageB
在BP_UIBase的Construct里print(self,ImageA,self.ImageB)
结果是UImage,nil和nil,nil
感觉理论上应该是UImage,nil和nil,UImage

**Comment by xuyanghuang-tencent** [comment]
#314 应该和这个是同一个问题
