### ISSUE TITLE
不同文件夹下创建两个相同名字的UMG时，UE4.UClass.Load加载异常

### ISSUE THREAD

**Issue by nvmgo** [Tencent/UnLua#321]
分别在A，B两个文件夹下，都建立一个UMG_Main，通过UE4.UClass.Load加载，先加载A/UMG_Main正常，再加载B/UMG_Main时，加载到的还是A/UMG_Main。

**Comment by xuyanghuang-tencent** [comment]
蓝图同名是设计上的历史遗留问题，后面我看看怎么调整

**Comment by xuyanghuang-tencent** [comment]
@nvmgo 在 `feature/bp-fullname` 上做了一些重构，现在应该能支持了，有空可以帮忙试一下

**Comment by nvmgo** [comment]
@xuyanghuang-tencent 这个版本可以了，谢谢

**Comment by xuyanghuang-tencent** [comment]
[v2.2.0](https://github.com/Tencent/UnLua/releases/tag/v2.2.0)
