### ISSUE TITLE
绑定中文名字的蓝图会报错

### ISSUE THREAD

**Issue by xermao** [Tencent/UnLua#322]
错误提示为
`LogUnLua: Warning: Failed to call luaL_loadbufferx, error code: 3
LogUnLua: Error: Lua error message: [string "Blueprints/zhongwenlantu_C.lua"]:1: unexpected symbol near '<\255>'
stack traceback:
    [C]: in function 'require'
LogUnLua: Error: Lua error message: file loading from file system error
stack traceback:
    [C]: in ?
    [C]: in function 'require'
LogUnLua: Warning: Failed to attach Blueprints.zhongwenlantu_C module for object 中文蓝图_2,000002008854D000!
invalid return value of require()`

以前提交过这个错误，但是原作者自认为不存在这个错误，既然现在换了开发者了，索性再提交一次。

**Comment by xuyanghuang-tencent** [comment]
测试了下的确没有这个错误，不过看你上面的报错，应该是在加载lua文件时的错误。

``` 1: unexpected symbol near '<\255>' ```

我猜可能是因为你用的编码是`UTF-16 LE`？因为会有个 `0xFF 0xFE` 的头。

**Comment by xermao** [comment]
确实是编码问题，很奇怪，如果蓝图名字是英文，那么点unlua的创建模板按钮创建出来的文件编码是utf-8，如果是中文，则是utf-16 little endian
