### ISSUE TITLE
SpawnActor 时 scale 参数没效果

### ISSUE THREAD

**Issue by xiejiangzhi** [Tencent/UnLua#329]
Unlua 2.1.1

UE 4.26

先创建一个 简单的蓝图

![image](https://user-images.githubusercontent.com/1396853/148630583-70cf836f-64a5-405b-9f56-46c9aada08f3.png)

然后在 player character 的蓝图中创建两棵树，一个放大两倍一个放大3倍

![image](https://user-images.githubusercontent.com/1396853/148630612-9e7f7de9-f8f4-4197-86ca-5993b24a0b7b.png)

同样，我也在 player character  lua receive begin 最后加入下面代码创建两个棵，一个不放大，一个放大2倍

```lua
	local world = self:GetWorld()
	local tree_cls = UE.UClass.Load("/Game/Core/Blueprints/BP_Tree.BP_Tree")
	local pos = UE.FVector(0, 0, 0)
	local rot = UE.FRotator(0, 0, 0)
	local scale = UE.FVector(1, 1, 1)
	local tf = UE.UKismetMathLibrary.MakeTransform(pos, rot, scale)
	world:SpawnActor(tree_cls, tf)

	local pos2 = UE.FVector(-300, 0, 0)
	local scale2 = UE.FVector(2, 2, 2)
	local tf2 = UE.UKismetMathLibrary.MakeTransform(pos2, rot, scale2)
	world:SpawnActor(tree_cls, tf2)

	self.Overridden.ReceiveBeginPlay(self)
```

然后游戏中的结果 

![image](https://user-images.githubusercontent.com/1396853/148630723-9baf29c3-b1a6-4104-ba61-2585eb5fa58c.png)

明显看出，4个树大小是1,1,  2, 3，也就是蓝图中创建的大小缩放是正常的。而在 unlua 中设定的缩放没有效果。。

**Comment by xiejiangzhi** [comment]
在 Unlua 中 World->SpawnActor 之前打印了一下 transform 变量，发现 scale 是对的，但在游戏世界中生成出来的就是默认的 1,1,1 了。。。

**Comment by xuyanghuang-tencent** [comment]
印象中蓝图里这样调的是 `UGameplayStatics::BeginDeferredActorSpawnFromClass` 和 `UGameplayStatics::FinishSpawningActor`，流程和直接SpawnActor还不太一样。

**Comment by xiejiangzhi** [comment]
多谢，我之前在 UE 源码里找了下，都不知道蓝图调用的是哪个方法去生成的。。。
之前一直以为 Unlua 的 SpawnActor 和蓝图里的一样

> 印象中蓝图里这样调的是 `UGameplayStatics::BeginDeferredActorSpawnFromClass` 和 `UGameplayStatics::FinishSpawningActor`，流程和直接SpawnActor还不太一样。

**Comment by xiejiangzhi** [comment]
我刚试了下，用 lua 调用 UGameplayStatics 里面的方法是没问题的。

Unlua 是否可以支持这种 Defered Spawning 的方式？ Unlua SpawnActor 的动态绑定设置使用蓝图方法是无法做到吧。

Deferred Spawning 可以在对象进入世界前做一些配置，感觉还是有用的。。

**Comment by xiejiangzhi** [comment]
想把 `FActorSpawnParameters` 导出，发现有点复杂，一些变量不知道怎么导出。。。
像 `Enum FActorSpawnParameters::ESpawnActorNameMode` 
直接使用 `BEGIN_EXPORT_ENUM(FActorSpawnParameters::ESpawnActorNameMode)` 编译不了，不知道怎么导出
然后 `SpawnCollisionHandlingOverride`  这样的 Enum 使用 ADD_PROPERTY 导出也报错，不会玩。。

**Comment by xuyanghuang-tencent** [comment]
```
DEFINE_TYPE(ESpawnActorCollisionHandlingMethod)
DEFINE_TYPE(EObjectFlags)
DEFINE_TYPE(FActorSpawnParameters::ESpawnActorNameMode)

BEGIN_EXPORT_CLASS(FActorSpawnParameters)
    ADD_PROPERTY(Name)
    ADD_PROPERTY(Template)
    ADD_PROPERTY(Owner)
    ADD_PROPERTY(Instigator)
    ADD_PROPERTY(OverrideLevel)
#if WITH_EDITOR
    ADD_PROPERTY(OverridePackage)
    ADD_PROPERTY(OverrideParentComponent)
    ADD_PROPERTY(OverrideActorGuid)
#endif
    ADD_PROPERTY(SpawnCollisionHandlingOverride)
    ADD_FUNCTION(IsRemoteOwned)
    ADD_BITFIELD_BOOL_PROPERTY(bNoFail)
    ADD_BITFIELD_BOOL_PROPERTY(bDeferConstruction)
    ADD_BITFIELD_BOOL_PROPERTY(bAllowDuringConstructionScript)
#if WITH_EDITOR
    ADD_BITFIELD_BOOL_PROPERTY(bTemporaryEditorActor)
    ADD_BITFIELD_BOOL_PROPERTY(bHideFromSceneOutliner)
    ADD_BITFIELD_BOOL_PROPERTY(bCreateActorPackage)
    ADD_PROPERTY(NameMode)
    ADD_PROPERTY(ObjectFlags)
#endif
END_EXPORT_CLASS()
IMPLEMENT_EXPORTED_CLASS(FActorSpawnParameters)
```

大概是这么个样子，`EObjectFlags` 和 `ESpawnActorNameMode` 可以直接在lua里定义好，反正就是个`uint8`

**Comment by xiejiangzhi** [comment]
好了，PR 已经更新了，加了个 SpawnActor2  ，直接使用 FActorSpawnParameters 去创建 actor 。

SpawnCollisionHandlingOverride 是蓝图类型， 已经自动导出了。
ESpawnActorNameMode  不是蓝图类型，没有导出，也就只能通过 int 这种非标准的方式使用，而不是 UE 中定义的 enum

**Comment by xiejiangzhi** [comment]
然后 PR 中我就把生成武器改成这个新方法去生成，测试了下可以正常创建，正常打怪。

测试用例代码，我暂时还不会写。。
