### ISSUE TITLE
打安卓包的时候clang++报错

### ISSUE THREAD

**Issue by zhangweiiscoding** [Tencent/UnLua#33]
UATHelper: Packaging (Android (ETC1)): ********** BUILD COMMAND STARTED **********
UATHelper: Packaging (Android (ETC1)): Running: D:\UE\UE_4.22\Engine\Binaries\DotNET\UnrealBuildTool.exe TPSProject Android Shipping -Project=H:\UE_project\MobileTest\MobileTPS.uproject  H:\UE_project\MobileTest\MobileTPS.uproject -NoUBTMakefiles  -remoteini="H:\UE_project\MobileTest" -skipdeploy -Manifest=H:\UE_project\MobileTest\Intermediate\Build\Manifest
.xml -NoHotReload -log="C:\Users\AERO\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+UE+UE_4.22\UBT-TPSProject-Android-Shipping.txt"
UATHelper: Packaging (Android (ETC1)):   PLATFORM_ANDROID_NDK_VERSION = 140200
UATHelper: Packaging (Android (ETC1)):   NDK toolchain: r14b, NDK version: 19, GccVersion: 4.9, ClangVersion: 3.8.275480
UATHelper: Packaging (Android (ETC1)):   Compiling Native code with NDK API 'android-19'
UATHelper: Packaging (Android (ETC1)):   Writing manifest to H:\UE_project\MobileTest\Intermediate\Build\Manifest.xml
UATHelper: Packaging (Android (ETC1)):   Building 2 actions with 12 processes...
UATHelper: Packaging (Android (ETC1)):     [1/2] TPSProject-Android-Shipping-armv7-es2.so
UATHelper: Packaging (Android (ETC1)):     D:/UE/UE_4.22/Engine/Intermediate/Build/Android/UE4/Shipping/Voice/Module.Voice.cppa7.o:D:/Build/++UE4/Sync/Engine/Intermediate/Build/Android/UE4/Shipping/Voice/Module.Voice.cpp:function FVoiceCaptureOpenSLES::Init(FString const&, int, int): error: undefined reference to 'UAndroidPermissionFunctionLibrary::Initializ
e()'
UATHelper: Packaging (Android (ETC1)):     D:/UE/UE_4.22/Engine/Intermediate/Build/Android/UE4/Shipping/Voice/Module.Voice.cppa7.o:D:/Build/++UE4/Sync/Engine/Intermediate/Build/Android/UE4/Shipping/Voice/Module.Voice.cpp:function FVoiceCaptureOpenSLES::Init(FString const&, int, int): error: undefined reference to 'UAndroidPermissionFunctionLibrary::CheckPerm
ission(FString const&)'
UATHelper: Packaging (Android (ETC1)):     clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
PackagingResults: Error: undefined reference to 'UAndroidPermissionFunctionLibrary::Initialize()'
PackagingResults: Error: undefined reference to 'UAndroidPermissionFunctionLibrary::CheckPermission(FString const&)'
PackagingResults: Error: linker command failed with exit code 1 (use -v to see invocation)
UATHelper: Packaging (Android (ETC1)): Took 28.7963488s to run UnrealBuildTool.exe, ExitCode=5
UATHelper: Packaging (Android (ETC1)): ERROR: UnrealBuildTool failed. See log for more details. (C:\Users\AERO\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+UE+UE_4.22\UBT-TPSProject-Android-Shipping.txt)
UATHelper: Packaging (Android (ETC1)):        (see C:\Users\AERO\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+UE+UE_4.22\Log.txt for full exception trace)
PackagingResults: Error: UnrealBuildTool failed. See log for more details. (C:\Users\AERO\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+UE+UE_4.22\UBT-TPSProject-Android-Shipping.txt)
UATHelper: Packaging (Android (ETC1)): AutomationTool exiting with ExitCode=5 (5)
UATHelper: Packaging (Android (ETC1)): BUILD FAILED
PackagingResults: Error: Unknown Error

**Comment by rowechien** [comment]
应该是AndroidPermission这个插件被disable了吧，你再检查一下

**Comment by zhangweiiscoding** [comment]
> 应该是AndroidPermission这个插件被disable了吧，你再检查一下

是的，已解决，谢谢
