### ISSUE TITLE
ue5 向量运算会得到错误的结果

### ISSUE THREAD

**Issue by kf953741** [Tencent/UnLua#337]
local p1 = UE4.FVector2D(1,1);
local p2 = UE4.FVector2D(2,2);
print(p1+p2);
结果不正确 

原因：double和float类型的转换   
  template<> struct TMathTypeTraits<FVector2D>
    {
        typedef float FieldType;
        typedef float ScalarType;
        enum { NUM_FIELDS = 2 };
    };
需要把float 改成unluaReal

**Comment by xuyanghuang-tencent** [comment]
的确，这里改漏了，方便提个PR到 `feature/ue5` 分支？

**Comment by kf953741** [comment]
好
