### ISSUE TITLE
UnLuaIntelliSense在vscode的EmmyLua的具体使用方式

### ISSUE THREAD

**Issue by zhangweiiscoding** [Tencent/UnLua#34]
请问能讲解一下UnLuaIntelliSense在vscode的EmmyLua的具体使用方式吗，这方面不是很了解，谢谢

**Comment by tangzx** [comment]
给你录了个视频
EmmyLua注解相关的内容参考：https://emmylua.github.io/zh_CN/annotation.html


![nmeQCyneFW](https://user-images.githubusercontent.com/3354360/63837857-d49c0d00-c9ae-11e9-8c2a-fb9d7afc675c.gif)

**Comment by zhangweiiscoding** [comment]
> 给你录了个视频
> EmmyLua注解相关的内容参考：https://emmylua.github.io/zh_CN/annotation.html

太强大了！非常感谢！
