### ISSUE TITLE
Lua延迟绑定的问题

### ISSUE THREAD

**Issue by greatzane** [Tencent/UnLua#343]
我们的项目之前在1.X版本没有问题的代码，迁移到2.1.1后发现很多ReceiveBeginPlay没有执行，经过调研发现新版会延迟绑定Lua，而此时Actor的BeginPlay已经执行过了。log如下：
LogBlueprintUserMessages: [TestActor_26] BeginPlay
LogUnLua: FLuaContext::OnDelayBindObject[450386]: Delay bind object TestActor_26,0000022FDE4EAB00
LogUnLua: UNLUA_PRINT[450387] : TestActor:Construct 
其中，第一行的BeginPlay是蓝图中打出来的，然后才发生了延迟绑定以及第三行Lua对象构造。Lua对象的ReceiveBeginPlay则没有执行。
请看一下这个问题，谢谢。

**Comment by GlorySL** [comment]
偶现：UserWidget 也有出现该对象已经生成 ，但是LuaScript对应的Construct未调用的情况，切换关卡后销毁该界面Destruct会调用

**Comment by xuyanghuang-tencent** [comment]
之前有处理过类似的问题 #268 ，有什么办法可以快速重现吗？

**Comment by greatzane** [comment]
> 之前有处理过类似的问题 #268 ，有什么办法可以快速重现吗？

我们测试是只要进到这个if就有这个问题：
![image](https://user-images.githubusercontent.com/2712575/150952661-b42e4991-4aeb-4d2e-b51b-4da65a12d751.png)

**Comment by xuyanghuang-tencent** [comment]
我在Editor下尝试重现了下：
1. 创建 `Map1` 和 `Map2` ，在 `Map2` 中放置一个绑定过Lua的Actor，覆写了`ReceiveBeginPlay`来打印日志
2. 增加 `Map1` 的蓝图逻辑，等待1秒，`OpenLevel`到 `Map2`
3. 打开 `Map1` 启动游戏，命中 `OnDelayBindObject` 的断点，放开断点后看到日志是正确执行了`ReceiveBeginPlay`

![image](https://user-images.githubusercontent.com/83756024/151118899-7bf7585c-50b3-48f4-afff-2c7280255e42.png)

**Comment by greatzane** [comment]
我再试试能不能抽出个demo来复现

**Comment by greatzane** [comment]
@xuyanghuang-tencent 在我们项目里这个问题是必现的，在上次提到的OnDelayBindObject之后，在lua对象实际构造之前，BeginPlay在如下的堆栈中被调用了，所以后续lua对象构造之后就不会再调用ReceiveBeginPlay了，代码基于4.27.2：
![image](https://user-images.githubusercontent.com/2712575/151357544-3807f238-6ca0-4dac-97ee-be5fd1f0846b.png)

**Comment by xuyanghuang-tencent** [comment]
的确和LevelStreaming有关系，目前测试下来的重现步骤是：
1. 在`Map1`中通过`OpenLevel`打开`Map2`（包含一个`Map3`的SubLevel，且`Streaming Method`为`Blueprint`）
2. 在`Map2`中通过`Load Stream Level(by Name)`加载`Map3`（启用`Make Visible After Load`和`Should Block on Load`）
3. 在`Map3`中摆放的绑定到Lua的Actor不会执行`ReceiveBeginPlay`

如果取消勾选`Should Block on Load`，则会执行`ReceiveBeginPlay`

**Comment by xuyanghuang-tencent** [comment]
@greatzane 移除了主线程中的延迟绑定，麻烦在你们工程上验证一下

**Comment by greatzane** [comment]
> 

验证了，没有问题，感谢~
