### ISSUE TITLE
UMG蓝图绑定Unlua后导致内存泄漏

### ISSUE THREAD

**Issue by dawnarc** [Tencent/UnLua#347]
测试环境：
Windows 10
UE 4.26.2
Unlua 2.1.2

测试步骤：

1. 新建一个自定义UserWidget的C++类`MyUserWidget`，并覆写`BeginDestroy()`。
```
void UMyUserWidget::BeginDestroy()
{
	Super::BeginDestroy();
	GEngine->AddOnScreenDebugMessage(-1, 5.f, FColor::Cyan, TEXT("====== BeginDestroy"));
}
```
2. 新建一个UMG蓝图，并继承`MyUserWidget`，然后继承UnluaInterface，并绑定一个Unlua代码 `TestWidget_2.lua`
```
require "UnLua"
local print = UEPrint

local M = Class()

function M:Construct()
	print("==== TestWidget_2 Construct")
end

return M
```
![image](https://user-images.githubusercontent.com/3351764/150920867-1609d85f-34a9-43ba-8576-7f7f0ac72ca8.png)

3. 然后写一段测试逻辑：先创建UMG并显示，然后移除UMG，并强制垃圾回收：
![image](https://user-images.githubusercontent.com/3351764/150921035-d8061a18-ef0c-422e-ae92-0f8d3b5059cb.png)
会发现`UMyUserWidget::BeginDestroy()`没有触发。
但是如果去掉Unlua绑定，再测试：
![image](https://user-images.githubusercontent.com/3351764/150921190-67b2fd76-7427-4f2b-b360-742b8464c38d.png)
则`UMyUserWidget::BeginDestroy()`可以正常触发。
这个问题不仅出现在PIE，打包版本中也存在；引擎升级到4.27.2，UMG同样无法销毁。

附件是测试相关蓝图和C++代码，可以直接复制到官方`TPSProject`工程下，编译启动editor，打开`AAAA/NewMap`运行游戏，按`Y`创建UMG，然后按`U`销毁UMG并强制GC。
[UnLua.zip](https://github.com/Tencent/UnLua/files/7931060/UnLua.zip)

不知UE侧做完GC后，是否需在lua侧手动GC，如果需要，请问如何操作，谢谢！

**Comment by xuyanghuang-tencent** [comment]
可以参考[UMG的GC流程](https://github.com/Tencent/UnLua/blob/master/Content/Script/Tutorials/11_ReleaseUMG.lua#L2-L8)
例子里似乎没有在Destruct()里self:Release()？

**Comment by dawnarc** [comment]
@xuyanghuang-tencent 添加`Destruct()`之后也不行，`BeginDestroy()`仍然没有触发。
```
require "UnLua"
local print = UEPrint

local M = Class()

function M:Construct()
    print("==== TestWidget_2 Construct")
end

function M:Destruct()
    self:Release()
    print("==== TestWidget_2 Destruct")
end

return M
```

**Comment by dawnarc** [comment]
@xuyanghuang-tencent 在`UUnLuaManager::ReleaseAttachedObjectLuaRef()`内追加一行：
```
GObjectReferencer.RemoveObjectRef((UObject*)Object);
```
可以正常触发`BeginDestroy()`
![image](https://user-images.githubusercontent.com/3351764/150988757-94008480-b350-4a79-a1e2-adc479067fa8.png)

**Comment by xuyanghuang-tencent** [comment]
没有触发Destroy的原因是还没有到[UMG的GC流程](https://github.com/Tencent/UnLua/blob/master/Content/Script/Tutorials/11_ReleaseUMG.lua#L2-L8)的第2步，也就是lua侧有引用/还没LuaGC。
这样改的话会提前让UE进行回收，想了下貌似也没什么问题，方便发个PR到 `develop` 分支？

**Comment by dawnarc** [comment]
@xuyanghuang-tencent 好的:ok_hand:，稍等
