### ISSUE TITLE
关于LuaContext.cpp中的UObjPtr2Id疑问

### ISSUE THREAD

**Issue by JiyuanLiao** [Tencent/UnLua#348]
请问LuaContext.cpp中自己维护了一个UObjPtr2Idx用来判断UObject是否Valid，为什么不直接用UE全局的GUObjectArray呢？
期待回复，感谢。

bool FLuaContext::IsUObjectValid(UObjectBase* UObjPtr)
{
    if (!UObjPtr)
    {
        return false;
    }
    int32 UObjIdx = -1;
    {
        FScopeLock Lock(&Async2MainCS);
        if (UObjPtr2Idx.Contains(UObjPtr))
        {
            UObjIdx = UObjPtr2Idx[UObjPtr];
        }
    }
    if (-1 != UObjIdx)
    {
        FUObjectItem* UObjectItem = GUObjectArray.IndexToObject(UObjIdx);
        if (!UObjectItem)
        {
            return false;
        }
        else
        {
            return (UObjPtr == UObjectItem->Object) && ((UObjPtr->GetFlags() & (RF_BeginDestroyed | RF_FinishDestroyed)) == 0)
                    && !UObjectItem->IsUnreachable();
        }
    }
    else
    {
        //!!!Fix!!!
        //all should be false here?
        return false;
    }
}

**Comment by xuyanghuang-tencent** [comment]
目前来看是因为UnLua的启动时机会晚于Engine，在这之前创建的对象是不受UnLua管理的，所以需要自己维护一个列表来确认对象是否可操作，相当于GUObjectArray的一个子集。这块后续在多LuaState支持的时候可能会调整下。

**Comment by JiyuanLiao** [comment]
多谢回复
