### ISSUE TITLE
是否支持覆盖蓝图函数（Call in Editor类型）？

### ISSUE THREAD

**Issue by ZhuangZhongjie** [Tencent/UnLua#351]

**Comment by xuyanghuang-tencent** [comment]
PIE下是支持的，非运行期因为UnLua环境没有启动，所以无法覆盖

**Comment by ZhuangZhongjie** [comment]
反馈迅速，谢谢。后续有计划支持Call in Editor么？

**Comment by xuyanghuang-tencent** [comment]
理论上是可以支持的，也就是需要确保UnLua在Editor初始化完了就启动，并且做好环境隔离。目前还只支持单进程全局唯一Lua环境，所以得先做好这块重构工作，才能够进一步支持使用lua做编辑器扩展的相关特性。

**Comment by ZhuangZhongjie** [comment]
好的， 期待~
