### ISSUE TITLE
RPC函数重载

### ISSUE THREAD

**Issue by AingeLu** [Tencent/UnLua#36]
Lua中无法重载RPC函数吗

**Comment by rowechien** [comment]
你是说覆写rpc函数对吧？这是可以的。
1. 将UnLua.Build.cs里的bSupportsRpcCall设为True;
2. 对应的覆写的rpc函数在lua里需要加上“_RPC”后缀，例如，蓝图里定义了一个rpc函数ServerFire，那lua里覆写的函数应该是ServerFire_RPC

**Comment by AingeLu** [comment]
![image](https://user-images.githubusercontent.com/32765061/64020113-62205e00-cb63-11e9-8825-4f1d43149c70.png)

![image](https://user-images.githubusercontent.com/32765061/64020150-73696a80-cb63-11e9-84bb-f6fc3ebb70a9.png)

![image](https://user-images.githubusercontent.com/32765061/64019199-0e147a00-cb61-11e9-9edf-a17ae4e16b9f.png)
重写了蓝图的RPC方法，无法调用到重写的RPC方法。这个条件判断是不是有问题？
@rowechien

**Comment by lzw576910119** [comment]
遇到一样的问题，貌似是在注册函数的时候由于基类已经存在ServerSetAiming，在lua中重写的时候会把"BP_CharacterAimComponent:ServerSetAiming_RPC"注册为“ServerSetAimingCopy”，然后调用RPC函数的时候会在NetWorkDriver的UNetDriver::InternalProcessRemoteFunction里去调用ClassCache->GetFromField找ServerSetAimingCopy函数，找不到这个对应函数RPC就调用失败了
@rowechien

**Comment by rowechien** [comment]
@AingeLu @lzw576910119 我本地尝试了一下，并没有发现什么问题。
![ServerSetAiming](https://user-images.githubusercontent.com/7972243/64107640-90917980-cdad-11e9-8b49-f956fab5d464.png)
![ServerSetAiming_RPC](https://user-images.githubusercontent.com/7972243/64107675-a43ce000-cdad-11e9-8a53-71db94832610.png)
![ServerSetAiming_RPC_Result](https://user-images.githubusercontent.com/7972243/64107796-e9611200-cdad-11e9-87c7-040c264e1d45.png)

**Comment by lzw576910119** [comment]
@rowechien  问下你是在蓝图还是lua中调用RPC的呢？我的蓝图中调用没问题，lua上调用就调不到了。

**Comment by rowechien** [comment]
@lzw576910119 Lua里调用的：
![ServerSetAiming_RPC_Invoking](https://user-images.githubusercontent.com/7972243/64142634-6be5e200-ce3f-11e9-8c19-c4c6d0e130a6.png)

**Comment by lzw576910119** [comment]
![image](https://user-images.githubusercontent.com/39950802/64159544-014b9b00-ce6d-11e9-9233-6362a626fcbe.png)
![image](https://user-images.githubusercontent.com/39950802/64159593-1294a780-ce6d-11e9-9e46-a4da44ff9866.png)
![image](https://user-images.githubusercontent.com/39950802/64159634-1de7d300-ce6d-11e9-85f7-c6e89bb68d9d.png)
![image](https://user-images.githubusercontent.com/39950802/64159771-4e2f7180-ce6d-11e9-957c-2c883a882ad5.png)
@rowechien 貌似我的用法和你的一样，不过确实调用失败了

**Comment by rowechien** [comment]
BP_CharacterBase_C:StartFire是哪里打印的？这个log是server的log还是client的？

**Comment by lzw576910119** [comment]
> BP_CharacterBase_C:StartFire是哪里打印的？这个log是server的log还是client的？

简单的测试下，客户端服务端都有的脚本，但是都不会打出来

**Comment by lzw576910119** [comment]
@rowechien 刚刚发现这个调用不了的问题是用编辑器的单进程+独立服务器的情况下才会发生，如果是多进程或者发布版就没有问题

**Comment by rowechien** [comment]
@AingeLu @lzw576910119 fixed in [630447b](https://github.com/Tencent/UnLua/commit/29bee56d1c4f9b5026ccbc3510c6340d4d8c662b). reopen the issue if it doesn't work...

**Comment by rowechien** [comment]
@lzw576910119 fixed in [cc10354](cc10354c35910a5bcdec9606ef6f83a6d48b09b9). reopen the issue if it doesn't work.
