### ISSUE TITLE
UE版本4.27.2，打包出来运行会崩溃

### ISSUE THREAD

**Issue by dragonwang2016** [Tencent/UnLua#365]
UE版本4.27.2，创建ThirdPerson c++模板工程，工程里创建1蓝图，绑定lua, lua里面重写ReceiveTick ，在Editor里运行正常，ReceiveTick 执行正常，但打包出来运行时直接崩溃
 Game has crashed and will close, text: Assertion failed: (int32)Script.Num() >= (int32)(MissingProperty.Value + sizeof(FField*)) [File:D:/Build/++UE4/Sync/Engine/Source/Runtime/CoreUObject/Private/UObject/Class.cpp] [Line: 1987]

**Comment by HSHSir** [comment]
我也遇到过这种问题,我也是4.27.2源码版,但是我是用UnLua重写BTService函数,运行就崩溃,而且4.27.2的UnLuaRPC函数BUG太多了,一调用服务器就会把客户端踢掉
