### ISSUE TITLE
feature/ue5分支是那个版本UE和VS编译的，为毛我一编译就好多问题

### ISSUE THREAD

**Issue by LikeScientist** [Tencent/UnLua#369]
![image](https://user-images.githubusercontent.com/86754697/155069955-c1f604d0-6741-4857-a4dc-a7c8bd15b244.png)

**Comment by xuyanghuang-tencent** [comment]
https://github.com/epicgames/unrealengine/tree/ue5-main

**Comment by LikeScientist** [comment]
这是ue5-main分支的编译报错，边解决边出现其他衍生报错，还是用EA版本的分支才能编译过：https://www.unrealengine.com/en-US/blog/unreal-engine-5-is-now-available-in-early-access
