### ISSUE TITLE
用什么 lua ide 比较好？

### ISSUE THREAD

**Issue by sudongg** [Tencent/UnLua#37]
如题。不知道用哪个。

**Comment by tangzx** [comment]
参考 #34

**Comment by sudongg** [comment]
@tangzx 
感谢回复，我安照教程安装了EmmyLua和导入了UnLuaIntelliSense，但是发现新建的函数和部分函数无法转到定义，提示未找到定义？请问是我的个别现象吗？

**Comment by tangzx** [comment]
问题不够具体，加emmylua群529914962提问吧。
