### ISSUE TITLE
4.27.2使用Unlua2.1.2(或2.1.1)在Controller中重写OwningClientRPC函数,调用任意RPC函数都会导致客户端被踢

### ISSUE THREAD

**Issue by HSHSir** [Tencent/UnLua#377]
使用引擎版本(源码版本)
![image](https://user-images.githubusercontent.com/61901106/156507564-023a6fb4-082c-4734-a2af-0b1dda4945f0.png)
使用默认的第三人称模板,增加一个继承自PlayerController的蓝图类[BP_Controller],在[BP_Controller]中新增如下函数
![image](https://user-images.githubusercontent.com/61901106/156507627-f8a97e41-47ca-436f-afd5-c83757fe0a76.png)
导入UnLua插件,2.1.1或者2.1.2,创建[BP_Controller]lua文件并绑定,如图
![image](https://user-images.githubusercontent.com/61901106/156507687-68a269f9-1210-4961-931b-7cb84affca4e.png)
之后进行DS打包服务器和客户端,运行结果,客户端一开始连接DS服务器一切正常,可以移动跳跃,但是,当我按下数字键1时(只是在服务器打印一串字符串,没有做其它事,甚至OwningClientRPC函数仅仅只是在lua中重写而没有调用),服务器把客户端踢了
![image](https://user-images.githubusercontent.com/61901106/156508289-69c1030e-400c-4914-be8c-9cb932f4b2ad.png)
后续改动:在蓝图中把Client_LuaBBB函数移除了,lua不动(由于蓝图中移除了,lua没有重写,只算是lua的一个普通函数),之后打包,运行正常,即使按下数字键1,运行也没有问题,RPC调用也没有问题
![image](https://user-images.githubusercontent.com/61901106/156509629-477b1a7b-fe25-46d5-a422-60bb79fbe1df.png)
![image](https://user-images.githubusercontent.com/61901106/156509304-be71f297-76a5-4ac0-91e5-d3da8f6325e7.png)
后面还做过很多测试,比如在Character中重写OwningClientRPC函数,运行没有问题,在Controller中用Lua重写ServerRPC函数,用蓝图写OwningClientRPC函数(lua不重写),运行都没有问题,就是在Controller中用lua重写OwningClientRPC函数会出现被踢,即使不调用(没有在蓝图或lua中调用OwningClientRPC函数)

**Comment by xuyanghuang-tencent** [comment]
挺奇怪的，`master`分支在4.27下重现了，4.26却没问题。`develop`分支在两个版本上都没重现。

**Comment by HSHSir** [comment]
> 挺奇怪的，分支在4.27下重现了，4.26却没问题。分支在两个版本上都没重现。`master``develop`

谢谢你的反馈,目前我项目暂时不敢用Lua覆写任何RPC函数,都是通过RPC函数调用普通函数,然后lua覆写普通函数来进行开发,但是还是希望官方能够解决这个问题,好让项目的代码能够更加优雅

**Comment by FeigerHuang** [comment]
+1
