### ISSUE TITLE
UMG中使用DynamicEntryBox，如果在生成的Entry中执行异步加载，会导致找不到绑定的Object

### ISSUE THREAD

**Issue by unicodecndddd** [Tencent/UnLua#379]
UMG中使用DynamicEntryBox，如果在生成的Entry中执行异步加载，会导致找不到绑定的Object。

**Comment by unicodecndddd** [comment]
重现方法是：
1.在一次循环中多次调用DynamicEntryBox::BP_CreateEntry，并在创建的Entry中执行异步加载。
2.第二个创建的Entry，在调用它的OnInitialized时，会找不到对应的Object。

**Comment by unicodecndddd** [comment]
原因是在执行第二个Entry的的绑定时，FLuaContext::TryToBindLua中的条件if (!IsInGameThread() || IsAsyncLoading())被触发，绑定过程被延后了，但OnInitialized却直接执行了。

**Comment by xuyanghuang-tencent** [comment]
理解你的意思了，看来得找另外个接口来判断需要绑定的对象是否处于异步加载中。如果去掉IsAsyncLoading的判断，会在4.27导致 #365 这个问题

**Comment by xuyanghuang-tencent** [comment]
[v2.1.4](https://github.com/Tencent/UnLua/releases/tag/v2.1.4)
