### ISSUE TITLE
使用BEGIN_EXPORT_REFLECTED_CLASS编译报错

### ISSUE THREAD

**Issue by cici01** [Tencent/UnLua#38]
使用BEGIN_EXPORT_REFLECTED_CLASS导出UClass的非UFunction函数编译报错。确认了lua lib路径是正确的。

2>UnLuaTestGameInstance.cpp.obj : error LNK2019: 无法解析的外部符号 lua_gettop，该符号在函数 "public: virtual int __cdecl UnLua::TExportedMemberFunction<class UUnLuaTestGameInstance,class FTreasureHunterRoleHandler *>::Invoke(struct lua_State *)" (?Invoke@?$TExportedMemberFunction@VUUnLuaTestGameInstance@@PEAVFTreasureHunterRoleHandler@@$$V@UnLua@@UEAAHPEAUlua_State@@@Z) 中被引用
2>UnLuaTestGameInstance.cpp.obj : error LNK2019: 无法解析的外部符号 lua_settop，该符号在函数 "int __cdecl UnLua::Index(struct lua_State *)" (?Index@UnLua@@YAHPEAUlua_State@@@Z) 中被引用
2>UnLuaTestGameInstance.cpp.obj : error LNK2019: 无法解析的外部符号 lua_pushvalue，该符号在函数 "int __cdecl UnLua::Index(struct lua_State *)" (?Index@UnLua@@YAHPEAUlua_State@@@Z) 中被引用
2>UnLuaTestGameInstance.cpp.obj : error LNK2019: 无法解析的外部符号 lua_copy，该符号在函数 "int __cdecl UnLua::Index(struct lua_State *)" (?Index@UnLua@@YAHPEAUlua_State@@@Z) 中被引用
2>UnLuaTestGameInstance.cpp.obj : error LNK2019: 无法解析的外部符号 lua_tolstring，该符号在函数 "int __cdecl UnLua::Index(struct lua_State *)" (?Index@UnLua@@YAHPEAUlua_State@@@Z) 中被引用
2>UnLuaTestGameInstance.cpp.obj : error LNK2019: 无法解析的外部符号 lua_touserdata，该符号在函数 "int __cdecl UnLua::Index(struct lua_State *)" (?Index@UnLua@@YAHPEAUlua_State@@@Z) 中被引用
2>UnLuaTestGameInstance.cpp.obj : error LNK2019: 无法解析的外部符号 lua_pushstring，该符号在函数 "public: virtual void __cdecl UnLua::FGlueFunction::Register(struct lua_State *)" (?Register@FGlueFunction@UnLua@@UEAAXPEAUlua_State@@@Z) 中被引用
2>UnLuaTestGameInstance.cpp.obj : error LNK2019: 无法解析的外部符号 lua_pushcclosure，该符号在函数 "public: virtual void __cdecl UnLua::FGlueFunction::Register(struct lua_State *)" (?Register@FGlueFunction@UnLua@@UEAAXPEAUlua_State@@@Z) 中被引用
2>UnLuaTestGameInstance.cpp.obj : error LNK2019: 无法解析的外部符号 lua_pushlightuserdata，该符号在函数 "public: virtual void __cdecl UnLua::TExportedMemberFunction<class UUnLuaTestGameInstance,class FTreasureHunterRoleHandler *>::Register(struct lua_State *)" (?Register@?$TExportedMemberFunction@VUUnLuaTestGameInstance@@PEAVFTreasureHunterRoleHandler@@$$V@UnLua@@UEAAXPEAUlua_State@@@Z) 中被引用
2>UnLuaTestGameInstance.cpp.obj : error LNK2019: 无法解析的外部符号 lua_getfield，该符号在函数 "int __cdecl UnLua::Index(struct lua_State *)" (?Index@UnLua@@YAHPEAUlua_State@@@Z) 中被引用
2>UnLuaTestGameInstance.cpp.obj : error LNK2019: 无法解析的外部符号 lua_rawget，该符号在函数 "int __cdecl UnLua::Index(struct lua_State *)" (?Index@UnLua@@YAHPEAUlua_State@@@Z) 中被引用
2>UnLuaTestGameInstance.cpp.obj : error LNK2019: 无法解析的外部符号 lua_rawset，该符号在函数 "public: virtual void __cdecl UnLua::FGlueFunction::Register(struct lua_State *)" (?Register@FGlueFunction@UnLua@@UEAAXPEAUlua_State@@@Z) 中被引用
2>F:\TH\TreasureHunterResearch\UnLuaTest\Binaries\Win64\UE4Editor-UnLuaTest.dll : fatal error LNK1120: 12 个无法解析的外部命令

**Comment by rowechien** [comment]
看上去你是在自己的工程里测试吧。你有吧Lua, UnLua这2个模板加到自己工程的build.cs里吗？例如：
        PrivateDependencyModuleNames.AddRange(
            new string[]
            {
                "Lua",
                "UnLua"
            }
            );

**Comment by cici01** [comment]
感谢回帖，已解决
