### ISSUE TITLE
热更失败

### ISSUE THREAD

**Issue by daphnis-kau** [Tencent/UnLua#381]
当在Global_LoadLuaFile打断点时，可以热更成功，不打断点时热更失败：
LogStreaming: Warning: Failed to read file 'C:/GitHub/Tencent/UnLua/Content/Script/Tutorials/01_HelloWorld.lua' error.
LogUnLua: Warning: UnLua::LoadFile: Failed to load lua file!
LogUnLua: UNLUA_PRINT[192645] : SelfLoadFile : loadfile failed :     Tutorials/01_HelloWorld.lua    nil    

新添一个函数，然后修改老的函数，在老函数里调用新函数，报告新函数不存在：
LogUnLua: Error: Lua error message: [string "Tutorials/01_HelloWorld.lua"]:30: attempt to call a nil value (method 'TestHotfix')
stack traceback:
    [string "Tutorials/01_HelloWorld.lua"]:30: in function 'Tutorials.01_HelloWorld_#1.ReceiveTick'
代码如下：
function M:TestHotfix(DeltaSeconds)
    Screen.Print( "4484".. DeltaSeconds )
end

function M:ReceiveTick( DeltaSeconds)
    self:TestHotfix(DeltaSeconds )
end

**Comment by xuyanghuang-tencent** [comment]
`develop`分支合入了重构后的热重载模块，可以再试试看

![image](https://user-images.githubusercontent.com/83756024/159465169-525e348d-06b0-477b-bd18-3a28cd421df1.png)

**Comment by xuyanghuang-tencent** [comment]
[v2.2.0](https://github.com/Tencent/UnLua/releases/tag/v2.2.0)
