### ISSUE TITLE
关于UserDefinedStruct的问题

### ISSUE THREAD

**Issue by zhujian886** [Tencent/UnLua#382]
问题1：
无引用的UserDefinedStruct，直接使用UE.FXXXXX时，会是nil。
在editor环境下stop之后再play，UE.FXXXXX就会被加载进去有结果。（收集类型的时序较晚？）
解决办法有，就是在时序比较靠前的蓝图中定义一个该结构体类型的变量，将结构体的类型注册进去，后面就可以使用。
这个是否可以提供一个类似loadclass或loadobject的接口去手动加载？

问题2：
使用UDataTableFunctionLibrary的GetRowDataStructure时，会因为内存分配问题，崩溃在StructType->CopyScriptStruct(Userdata, RowPtr);这个应该也是自定义结构体导致的。
解决办法是用GetDataTableRowFromName方法，但需要先定义一个该datatable使用的结构体将指针传入。这样做的话又回到问题1上面。无法通过newobject去构造一个结构体。

问题3：
editor中unlua的图标，执行了bind和createTemplate之后，图标和下拉框没有及时更新，需要关闭再打开才是实际的状态。（小问题）

**Comment by zhujian886** [comment]
感谢解答，以为struct是class，所以尝试用loadclass来加载，以失败告终，原来是用loadobject加载的。
这里再问一个问题吧，关于delegate的，其他人应该也遇到过：
lua原生table，self并非UObject类型，想要注册个回调，Add或Bind方法第一个参数必须是非null的Uobject类型，回调方法中需要使用self，还有一些业务数据透传。
我的解决方法是使用一定存在的UObject传入，然后用local的function去包装回调，例如aaa.OnXXX:Add(GetGameInstance(),function(...) self:OnXXXX(param,select(2,...)) end);

由于是local的function，每Add一次，delegate中就多一条数据，Remove时没法指定，只能用Clear来清空，但Clear也可能把其他地方注册的回调一并清除了。除此之外还有没有更安全的方式？

**Comment by xuyanghuang-tencent** [comment]
delegate的问题的确是个历史包袱，之前也有讨论过 #291 ，一直没时间去搞

**Comment by PredawnRaziel** [comment]
> 问题1和问题2，可以使用`UE.UObject.Load`接口，应该就是你需要的，[参考用例](https://github.com/Tencent/UnLua/blob/576706aebf0a4b75e74e35e930a4999650769ba6/Plugins/UnLua/Source/UnLuaTestSuite/Private/Specs/LuaLib_DataTable.spec.cpp)。
> 
> 问题3，图标没有更新的问题已经在`feature/settings`分支修复了，晚点我把它合到`develop`分支，感谢提醒

问题1和2提到的方法 UObject.Load("xxx") 的确能实现功能，但是在PIE模式下，如果按ESC退出时，貌似会报警告：
LogUnLua: ScriptStruct : Invalid FClassDesc!
我现在把其他的代码删除，只留下了 local outRowClass = UE.UObject.Load("....") 一句，然后进行对比，删掉它就不会报警告，不删就可以。
（测试环境：一个esc前不会进行destruct的界面里。）

**Comment by xuyanghuang-tencent** [comment]
[v2.2.0](https://github.com/Tencent/UnLua/releases/tag/v2.2.0)
