### ISSUE TITLE
真机环境下GameInstance的ReceiveInit无法覆写

### ISSUE THREAD

**Issue by xuyanghuang-tencent** [Tencent/UnLua#383]
UnLua的加载时机是`PostConfigInit`，而非编辑器模式下`GameInstance`在这之前就已经被创建出来了。

考虑将插件的加载时机提前到`PreDefault`。

**Comment by shuiliulcl** [comment]
ReceiveShutdown也无法覆写，因为比Unlua:SetEnable(false)的时机要晚

**Comment by xuyanghuang-tencent** [comment]
[v2.2.0](https://github.com/Tencent/UnLua/releases/tag/v2.2.0)
