### ISSUE TITLE
访问引擎自带蓝图数据 Crash

### ISSUE THREAD

**Issue by xiejiangzhi** [Tencent/UnLua#385]
![image](https://user-images.githubusercontent.com/1396853/159644336-00904bd5-a846-4b1d-b082-be7575737eac.png)

![image](https://user-images.githubusercontent.com/1396853/159644394-a065ce17-f6e0-4cd3-825f-668dea803d1e.png)

比如我尝试访问引擎自带蓝图的 BP_Sky_Sphere 中的 `Directional Light Actor` ，self['Directional Light Actor'] 一访问就直接 crash 了。

**Comment by xiejiangzhi** [comment]
好像不是因为空格的问题，我只是 `print(self.UpdateSunDirection)` 也崩了，而是继承 BP_Sky_Sphere 蓝图的一个 UnLua 实现。
而崩的原因也是一样的，RegisterField  一直循环到崩。

**Comment by xiejiangzhi** [comment]
![image](https://user-images.githubusercontent.com/1396853/159651436-3d40a1aa-8d37-4340-8420-8109baa2f3a8.png)

堆栈数据

**Comment by xuyanghuang-tencent** [comment]
![image](https://user-images.githubusercontent.com/83756024/161886113-330c50fb-d929-46f8-8754-d5b926a920e2.png)
是什么版本的UnLua？在master上试了下没有重现

**Comment by xiejiangzhi** [comment]
我刚又试了下，发现怎么都重现不了，调用和获取又都正常了。。。。
想不通，不知道是不是之前蓝图关联的数据不正常，先关了
