### ISSUE TITLE
开启多窗口，一个有UI展示，一个没有UI展示

### ISSUE THREAD

**Issue by dzCxy** [Tencent/UnLua#387]
用的是release  2.1.3  unlua版本
引擎版本是  4.26.2

我这里将局内UMG创建都放置Lua层了，结果发现多个窗口，一个有UI展示，一个没有UI展示
![image](https://user-images.githubusercontent.com/12756983/160316371-ddf58388-5cca-49ed-86ea-06083ac5b7ac.png)

试过AB两个模式，一个有UI，一个没有UI
试过C模式，直接两个都没有UI了

然后再引过另一个讨论过的问题：
https://github.com/Tencent/UnLua/issues/78

发现多个窗口时，Lua会出现数据共享问题，就跟上面这个issue提的一样，都会只有一个LuaContext
体现在：
本地A窗口我按了 下蹲按键，我将状态值存到Lua中，并派发出UI刷新展示事件（UI根据是否下蹲状态值会显示不同的图标）
结果是本地A窗口对应的UI没变化，B窗口的下蹲UI变化了

**Comment by xuyanghuang-tencent** [comment]
原因是早期UnLua的设计没有考虑多LuaState，单进程环境下会导致状态混乱。大量全局对象的使用导致重构工作量比较大，目前这个重构工作的分支在`refactor/luaenv`上，预计2.2.0会合入。

PS：可以关闭UE的`Run Under One Process`选项，使用多进程跑就没有这个问题了，代价是启动多个游戏进程会慢一点点。

**Comment by dzCxy** [comment]
> 原因是早期UnLua的设计没有考虑多LuaState，单进程环境下会导致状态混乱。大量全局对象的使用导致重构工作量比较大，目前这个重构工作的分支在`refactor/luaenv`上，预计2.2.0会合入。
> 
> PS：可以关闭UE的`Run Under One Process`选项，使用多进程跑就没有这个问题了，代价是启动多个游戏进程会慢一点点。

我试过这个选项
我刚测试过
1.数据共享的问题是解决了
2.UI的问题依旧，还是如上述所述：
         试过AB两个模式，一个有UI，一个没有UI
         试过C模式，直接两个都没有UI了

**Comment by xuyanghuang-tencent** [comment]
试试`develop`分支，或者手动合下上面那个提交

**Comment by dzCxy** [comment]
感谢，我试试

**Comment by dzCxy** [comment]
> 试试`develop`分支，或者手动合下上面那个提交

试了手动合并，不行。开启多窗口时直接报错了。我的版本是release2.1.3,可能跟develop差别比较大
我下午试试develop分支

**Comment by dzCxy** [comment]
> 试试`develop`分支，或者手动合下上面那个提交

针对UI在Standalone模式显示的问题已经修改好了，感谢
单进程多LuaState的问题，就期待你们了2.2.0咯

**Comment by jackfong66** [comment]
> > 试试`develop`分支，或者手动合下上面那个提交
> 
> 针对UI在Standalone模式显示的问题已经修改好了，感谢 单进程多LuaState的问题，就期待你们了2.2.0咯

是合并到  refactor/luaenv分支就好了吗  我也有这个问题

**Comment by dzCxy** [comment]
![image](https://user-images.githubusercontent.com/12756983/164955811-630f7d84-f34a-4fd6-8558-652757c38694.png)
![image](https://user-images.githubusercontent.com/12756983/164955815-74880627-a02d-407c-85f7-6ea993b4c9bd.png)

**Comment by dzCxy** [comment]
> > > 试试`develop`分支，或者手动合下上面那个提交
> > 
> > 
> > 针对UI在Standalone模式显示的问题已经修改好了，感谢 单进程多LuaState的问题，就期待你们了2.2.0咯
> 
> 是合并到 refactor/luaenv分支就好了吗 我也有这个问题

1

**Comment by jackfong66** [comment]
> > > > 试试`develop`分支，或者手动合下上面那个提交
> > > 
> > > 
> > > 针对UI在Standalone模式显示的问题已经修改好了，感谢 单进程多LuaState的问题，就期待你们了2.2.0咯
> > 
> > 
> > 是合并到 refactor/luaenv分支就好了吗 我也有这个问题
> 
> 1

develop分支并没有解决 多个 LuaState的问题.   看样子只能 等refactor/luaenv到 2.2.0了

**Comment by xuyanghuang-tencent** [comment]
[v2.2.0](https://github.com/Tencent/UnLua/releases/tag/v2.2.0)
