### ISSUE TITLE
编辑器下 crash

### ISSUE THREAD

**Issue by xiejiangzhi** [Tencent/UnLua#388]
![image](https://user-images.githubusercontent.com/1396853/160744918-7261a081-c249-455e-b9ff-d2b6a9181238.png)

![image](https://user-images.githubusercontent.com/1396853/160744966-9cc14ee0-2434-4eb6-92f5-615b5360aedc.png)

![image](https://user-images.githubusercontent.com/1396853/160744994-92363c7a-245c-4c0d-a54a-704fdfe9be10.png)

一般发生在在编辑器停止模拟时。

**Comment by xuyanghuang-tencent** [comment]
[v2.1.4](https://github.com/Tencent/UnLua/releases/tag/v2.1.4)
