### ISSUE TITLE
lua中的FName会出现中文乱码

### ISSUE THREAD

**Issue by goderyu** [Tencent/UnLua#389]
![image](https://user-images.githubusercontent.com/39651921/160990873-615f2a29-24b1-47bd-9fdd-02725e34d376.png)

![image](https://user-images.githubusercontent.com/39651921/160990944-87af74e9-3742-4228-a09d-cc70a666f494.png)

**Comment by goderyu** [comment]
我使用的是老版本的Unlua插件，支持的是Lua5.3版本的

**Comment by xuyanghuang-tencent** [comment]
印象中老版本的编码转换用的是ANSI_TO_TCHAR/TCHAR_TO_ANSI，可以参考2.0的修改换成UTF8_TO_TCHAR/TCHAR_TO_UTF8，或者直接用最新版本的

**Comment by goderyu** [comment]
好的，非常感谢，我试一下

xuyanghuang ***@***.***> 于2022年4月6日周三 11:00写道：
