### ISSUE TITLE
请问如何在异步加载时绑定 Lua？

### ISSUE THREAD

**Issue by GotGimhong** [Tencent/UnLua#390]
看了一下 `FLuaContext::TryToBindLua` 的实现，如果当前正在异步加载，就会导致绑定 Lua 失败（返回 false），然后在 `FLuaContext::OnAsyncLoadingFlushUpdate` 当中异步绑定 Lua。
![TryToBindLua](https://user-images.githubusercontent.com/16437644/161963702-b8c5ebd5-021f-4e6f-81ae-def312726f5c.png)

目前我们遇到的问题是，一些需要在异步加载时创建的对象无法绑定 Lua。例如在切换场景的时候，我们会显示一个加载 UI，用来显示加载进度条，我们的做法是：在切换场景的时候预加载一些资源，并且显示加载 UI。当创建这个加载 UI 的时候，预加载通常是还没有完成的，这样就导致了加载 UI 无法绑定 Lua，从而无法正常显示。

因此我们想请教一下关于这个问题的建议，能否在异步加载的时候也能够绑定 Lua，或者是有其他解决方法。

**Comment by xuyanghuang-tencent** [comment]
这里的实现的确有点问题，可以参考下这个 #379
设计上是期望异步加载的对象会被推到队列里，等加载完成回调后再进行绑定

**Comment by GotGimhong** [comment]
> 这里的实现的确有点问题，可以参考下这个 #379 设计上是期望异步加载的对象会被推到队列里，等加载完成回调后再进行绑定

谢谢您的回复，我们参考了您的 [这个](https://github.com/Tencent/UnLua/commit/ef1fb0fe7f7ae4850d084722da4c45fae91ca7b0) 做法，问题暂时解决了。

**Comment by GotGimhong** [comment]
问题已解决，请见 7b5d2e760a5cb78145167be7ab4a6ba5df0820e4 。
