### ISSUE TITLE
FSoftObjectPtr 的静态导出类型似乎缺少了一些接口

### ISSUE THREAD

**Issue by GotGimhong** [Tencent/UnLua#392]
在最新的版本当中，`FSoftObjectPtr` 的静态导出类型缺少了一些接口，这些接口在 2.0.0 版本之前是有的，但是从 2.0.0 版本开始就删除了，这些接口包括：
+ `IsNull`
+ `IsPending`
+ `LoadSynchronous`

这是 2.0.0 版本之前的静态导出：
![FSoftObjectPtr_1 x](https://user-images.githubusercontent.com/16437644/162903523-ef262c5b-5ed4-439a-aabf-c39a3ba13b27.png)

这是最新版本的静态导出：
![FSoftObjectPtr_2 x](https://user-images.githubusercontent.com/16437644/162903591-1ba469db-6cb5-4111-94a8-99b5c96e7275.png)

请问有什么方法可以访问这些缺失的接口呢？还是说需要我们自己添加静态导出？

**Comment by xuyanghuang-tencent** [comment]
应该是只是漏了…… 方便发个PR？

**Comment by GotGimhong** [comment]
> 应该是只是漏了…… 方便发个PR？

可以的，请问基于哪个分支来发 PR 比较好呢？这次 PR 只需要改动 LuaLib_Object.cpp 这个文件，我看了一下这个文件在 master 分支和 develop 分支下是不一样的。

**Comment by xuyanghuang-tencent** [comment]
提到 `develop` 分支就行，感谢

**Comment by GotGimhong** [comment]
> 提到 `develop` 分支就行，感谢

不客气，已经向 `develop` 分支提交了一个 PR，请见 #399

**Comment by xuyanghuang-tencent** [comment]
[v2.2.0](https://github.com/Tencent/UnLua/releases/tag/v2.2.0)
