### ISSUE TITLE
package.path添加新路径后，打包windows后找不到文件

### ISSUE THREAD

**Issue by kevinofsias** [Tencent/UnLua#393]
package.path = UE.UBlueprintPathsLibrary.ConvertRelativePathToFull(UE.UBlueprintPathsLibrary.ProjectContentDir().."Script/UI/?.lua")..";"..package.path
我在Script目录下增加一个UI目录，有如下2种调用
方式1.require “UITest”
方式2.require “UI.UITest”
编辑器模式下打印path路径为
`package.path E:/UnrealProjects/UE427/battlecar/Content/Script/UI/?.lua;E:\EpicGamesLauncher\Epic Games\UE_4.27\Engine\Binaries\Win64\lua\?.lua;E:\EpicGamesLauncher\Epic Games\UE_4.27\Engine\Binaries\Win64\lua\?\init.lua;E:\EpicGamesLauncher\Epic Games\UE_4.27\Engine\Binaries\Win64\?.lua;E:\EpicGamesLauncher\Epic Games\UE_4.27\E
ngine\Binaries\Win64\?\init.lua;E:\EpicGamesLauncher\Epic Games\UE_4.27\Engine\Binaries\Win64\..\share\lua\5.4\?.lua;E:\EpicGamesLauncher\Epic Games\UE_4.27\Engine\Binaries\Win64\..\share\lua\5.4\?\init.lua;.\?.lua;.\?\init.lua;E:/UnrealProjects/UE427/battlecar/Content/Script/?.lua    `
方式1,2编辑器运行正常，可找到UITest脚本，打包windows版本，并且勾上
![image](https://user-images.githubusercontent.com/11285988/162904007-796a382a-d011-48b3-9bcb-3598a8f796f6.png)
运行时，方式1会报错，方式2正常。报错log如下：
` package.path E:/UnrealProjects/UE427/battlecar/Saved/WindowsNoEditor/BattleCar/Content/Script/UI/?.lua;E:\UnrealProjects\UE427\battlecar\Saved\WindowsNoEditor\BattleCar\Binaries\Win64\lua\?.lua;E:\UnrealProjects\UE427\battlecar\Saved\WindowsNoEditor\BattleCar\Binaries\Win64\lua\?\init.lua;E:\UnrealProjects\UE427\battlecar\Saved\WindowsNoEditor\BattleCar\Binaries\Win64\?.lua;E:\UnrealProjects\UE427\battlecar\Saved\WindowsNoEditor\BattleCar\Binaries\Win64\?\init.lua;E:\UnrealProjects\UE427\battlecar\Saved\WindowsNoEditor\BattleCar\Binaries\Win64\..\share\lua\5.4\?.lua;E:\UnrealProjects\UE427\battlecar\Saved\WindowsNoEditor\BattleCar\Binaries\Win64\..\share\lua\5.4\?\init.lua;.\?.lua;.\?\init.lua;E:/UnrealProjects/UE427/battlecar/Saved/WindowsNoEditor/BattleCar/Content/Script/?.lua;./UI/?.lua    
[2022.04.12-07.05.56:175][  0]LogUnLua: UNLUA_PRINT[1] : ===NewCreateUI:UITest    
[2022.04.12-07.05.56:176][  0]LogUnLua: Error: Lua error message: [string "UIManager.lua"]:63: module 'UITest' not found:
	no field package.preload['UITest']
	no file 'E:/UnrealProjects/UE427/battlecar/Saved/WindowsNoEditor/BattleCar/Content/Script/UI/UITest.lua'
	no file 'E:\UnrealProjects\UE427\battlecar\Saved\WindowsNoEditor\BattleCar\Binaries\Win64\lua\UITest.lua'
	no file 'E:\UnrealProjects\UE427\battlecar\Saved\WindowsNoEditor\BattleCar\Binaries\Win64\lua\UITest\init.lua'
	no file 'E:\UnrealProjects\UE427\battlecar\Saved\WindowsNoEditor\BattleCar\Binaries\Win64\UITest.lua'
	no file 'E:\UnrealProjects\UE427\battlecar\Saved\WindowsNoEditor\BattleCar\Binaries\Win64\UITest\init.lua'
	no file 'E:\UnrealProjects\UE427\battlecar\Saved\WindowsNoEditor\BattleCar\Binaries\Win64\..\share\lua\5.4\UITest.lua'
	no file 'E:\UnrealProjects\UE427\battlecar\Saved\WindowsNoEditor\BattleCar\Binaries\Win64\..\share\lua\5.4\UITest\init.lua'
	no file '.\UITest.lua'
	no file '.\UITest\init.lua'
	no file 'E:/UnrealProjects/UE427/battlecar/Saved/WindowsNoEditor/BattleCar/Content/Script/UITest.lua'
	no file './UI/UITest.lua'
	no file 'E:\UnrealProjects\UE427\battlecar\Saved\WindowsNoEditor\BattleCar\Binaries\Win64\UITest.dll'
	no file 'E:\UnrealProjects\UE427\battlecar\Saved\WindowsNoEditor\BattleCar\Binaries\Win64\..\lib\lua\5.4\UITest.dll'
	no file 'E:\UnrealProjects\UE427\battlecar\Saved\WindowsNoEditor\BattleCar\Binaries\Win64\loadall.dll'
	no file '.\UITest.dll'
stack traceback:
	[C]: in function 'require'
	[string "UIManager.lua"]:63: in function <[string "UIManager.lua"]:61>
	(...tail calls...)
	[string "UIManager.lua"]:123: in method 'OpenTestUI'`

看到log中有对应UI路径，因为是打包pak的，所以不清楚为啥没找到UITest，去掉上面打包pak的勾是可以找到的，打包后的pak文件路径如下：
E:\UnrealProjects\UE427\battlecar\Saved\WindowsNoEditor\BattleCar\Content\Paks\BattleCar-WindowsNoEditor.pak

**Comment by kevinofsias** [comment]
已找到lua文件查找相关代码，不支持这种读取方式。

**Comment by heshan0x1** [comment]
后面怎么解决的呢？
