### ISSUE TITLE
2.0.0以后的版本对soft object是怎么支持的

### ISSUE THREAD

**Issue by ulympgf** [Tencent/UnLua#397]
![screenshot-20220419-143337](https://user-images.githubusercontent.com/39459051/163940646-e4b2898a-0937-453a-93c4-3debd9cae20a.png)
我对比了一下日志，在2.0.0版本的时候，就把SoftObject的LoadSynchronous函数去掉了，那该怎么使用

**Comment by xuyanghuang-tencent** [comment]
同 #392

**Comment by xuyanghuang-tencent** [comment]
[v2.2.0](https://github.com/Tencent/UnLua/releases/tag/v2.2.0)
