### ISSUE TITLE
接口列表从lua传到c++/蓝图层会丢失一半信息

### ISSUE THREAD

**Issue by shuitian** [Tencent/UnLua#398]
先定义接口类：
![screenshot-20220419-163113](https://user-images.githubusercontent.com/3433773/163960659-57665d77-c596-4245-80f9-1e1b5d9515b6.png)

然后ACharacterBase实现该接口
![screenshot-20220419-163144](https://user-images.githubusercontent.com/3433773/163960633-3f40b557-842c-4048-b571-89805f85f5e5.png)

然后在蓝图函数库里定义一个函数，输入的参数是EffectSourceInterface的列表，输出的参数是一样的。
![screenshot-20220419-163222](https://user-images.githubusercontent.com/3433773/163960675-771dde7b-c5c4-4f31-b219-adf1b362f679.png)

在CharacterBase的lua的BeginPlay里，调用这个函数，理论上两次PrintArray的结果是一样的，因为Test函数并没有做任何处理
![screenshot-20220419-163241](https://user-images.githubusercontent.com/3433773/163960683-c348391f-30a4-4d4f-bc6f-5bb4802db9ee.png)

但是输出的结果很奇怪，第二个参数是nil，我多试了几次，发现总是有一半的数据变成nil，怀疑是接口列表在传递的时候，信息有丢失
![screenshot-20220419-163745](https://user-images.githubusercontent.com/3433773/163961382-824467d3-b4ca-42b4-92ce-92642a470c1e.png)
![screenshot-20220419-163811](https://user-images.githubusercontent.com/3433773/163961404-7a8e749f-275e-4356-9d45-8586a3ee7769.png)

**Comment by shuitian** [comment]
补充一句，如果Test函数的参数改成Actor列表，就不会有这个问题

**Comment by xuyanghuang-tencent** [comment]
[v2.2.0](https://github.com/Tencent/UnLua/releases/tag/v2.2.0)
