### ISSUE TITLE
如何在Lua中使用蓝图结构体类型创建变量

### ISSUE THREAD

**Issue by AingeLu** [Tencent/UnLua#40]
![image](https://user-images.githubusercontent.com/32765061/64172862-79738a00-ce88-11e9-90b5-f6d1f90cd1d4.png)

想要在Lua里面使用这个结构体类型

**Comment by rowechien** [comment]
不推荐用编辑器里定义的结构体，因为它的变量名和真正的UProperty名字不一样，例如EquipState这个变量它实际的UProperty名字会是EquipState_XXXXXX，其中XXXXXX是个GUID，所以你基本上是无法在Lua里访问到这个变量的。具体原因可以看下面代码：
![Snipaste_2019-09-04_10-45-07](https://user-images.githubusercontent.com/7972243/64222143-d0697580-cf01-11e9-97d4-90c36b3efc8c.png)

**Comment by zealotxxx** [comment]
GUID好像也是有规律的，可以在UnLua和Ue4之间加一个名字映射的方法来处理吗？感觉可行吗？

**Comment by rowechien** [comment]
@zealotxxx 找GUID的规律么，这个路子有点野应该是走不通或者不值得的

**Comment by rowechien** [comment]
@AingeLu @zealotxxx [740576d](https://github.com/Tencent/UnLua/commit/740576de58635eeea79649e593f3f7f17014e852) 这个commit对editor里定义的struct和enum做了更好的支持。
