### ISSUE TITLE
一个蓝图函数参数为int数组的时候，如果lua重写了函数，那么蓝图调用该函数的时候，没法传递数组参数

### ISSUE THREAD

**Issue by shuitian** [Tencent/UnLua#401]
在蓝图中定义函数TestArray，只接受一个参数整数数组
![screenshot-20220426-101320](https://user-images.githubusercontent.com/3433773/165206217-d1266a02-7489-43f3-9aef-62c668d8ce10.png)
分别在lua中调用和蓝图中调用
![screenshot-20220426-101335](https://user-images.githubusercontent.com/3433773/165206317-40cf7522-1446-4c2e-9fa4-3e85e9d5cbee.png)
![screenshot-20220426-101346](https://user-images.githubusercontent.com/3433773/165206321-7a5f8612-3d59-4c3f-88ec-36785813aec5.png)
输出结果是对的，都是长度为2
![screenshot-20220426-101404](https://user-images.githubusercontent.com/3433773/165206364-43cd2c9c-7a8c-43ea-9ec4-f240e72f0d77.png)

但是，当在lua中重写该函数时
![screenshot-20220426-101511](https://user-images.githubusercontent.com/3433773/165206402-442e58e2-729f-4e81-9923-a1c108aee974.png)
再打印出来的长度，其中一个不对了，就是蓝图中的函数调用不对了。
![screenshot-20220426-101455](https://user-images.githubusercontent.com/3433773/165206457-4763b15e-3499-4801-b748-c4e1a8a5041a.png)

**Comment by xuyanghuang-tencent** [comment]
[v2.2.1](https://github.com/Tencent/UnLua/releases/tag/v2.2.1)
