### ISSUE TITLE
无效的蓝图资源导致   FUnLuaIntelliSenseGenerator 的崩溃

### ISSUE THREAD

**Issue by YJ66xiaopipi** [Tencent/UnLua#405]
无效的蓝图资源导致   FUnLuaIntelliSenseGenerator 的崩溃
![4KGW27R`~YZXL03H{A%OA(K](https://user-images.githubusercontent.com/99896149/167331986-580801e0-fe9d-495d-8785-ff9673565f55.png)
![企业微信截图_16519196235725](https://user-images.githubusercontent.com/99896149/167332021-0f173644-9aa2-4e6d-abf6-88dc4785108c.png)

**Comment by YJ66xiaopipi** [comment]
bool FUnLuaIntelliSenseGenerator::ShouldExport(const FAssetData& AssetData)
{
	const auto& Settings = *GetDefault<UUnLuaEditorSettings>();
	if (!Settings.bGenerateIntelliSense)
		return false;
    static bool tb;
    UObject* tUobj = AssetData.FastGetAsset(tb);
	if (tUobj)
	{
        if (UBlueprint* Blueprint = Cast<UBlueprint>(tUobj))
        {
            if (!Blueprint->SkeletonGeneratedClass || !Blueprint->GeneratedClass)
            {
                return false;
            }
        }
        else
        {
            return false;
        } 
	}
    else
    {
        return false;
    }

    if (!IsBlueprint(AssetData))
        return false;

    return true;
}
修改了一下这个函数不会崩溃了

**Comment by xuyanghuang-tencent** [comment]
#409
