### ISSUE TITLE
在lua中将一个TMap调用Keys或者Values返回的数组作为参数传给c++，c++端收到的数组参数是空的

### ISSUE THREAD

**Issue by daiwei1999** [Tencent/UnLua#407]
在蓝图或者c++定义一个TMap，类型随意，比如：
    TMap<int32, int32> TestMap;
然后给TestMap添加一些元素，让其不为空，在lua中调用TestMap的Keys或者Values方法，并将返回值作为参数传给c++函数，比如在c++定义一个Func函数：
    UFUNCTION(BlueprintCallable)
    void Func(TArray<int32> Array);
在lua中调用此Func函数：
    self:Func(self.TestMap:Keys())
    self:Func(self.TestMap:Values())
在c++的Func函数中设断定可以看到Array参数是空的。

**Comment by xuyanghuang-tencent** [comment]
最新`develop`分支上没有重现，可能和 #401 同一个问题

**Comment by shuitian** [comment]
> 最新`develop`分支上没有重现，可能和 #401 同一个问题

不是同一个问题。之前我们也遇到了这个问题，当时看感觉是lua这变TMap的Keys()得到的TArray和重新的创建的TAarry(1)不是相同的类型。

举例就是。如果只是传TMap的Key()得到的和TArray，会失败。但是建一个空TArray，然后遍历TMap的Keys()，将每个元素都加入这个TArray，然后将他传到c++，就会成功。

**Comment by xuyanghuang-tencent** [comment]
[Plugins/UnLuaTestSuite/Source/UnLuaTestSuite/Private/Tests/Issue407Test.cpp](https://github.com/Tencent/UnLua/commit/324ace4176a09999d664950dae3fe4e7da82b227#diff-b1ff202d38b0f8520cfc776b864d164a4ebd5271f2388a5aa98ab7a482392fc0)
可以在develop分支上试试重现下，或者看看这个回归测试用例哪里有疏漏的地方

**Comment by shuitian** [comment]
我等我们升到2.2了再去试下，2.1.4确实有这个问题

**Comment by xuyanghuang-tencent** [comment]
[v2.2.1](https://github.com/Tencent/UnLua/releases/tag/v2.2.1)
