### ISSUE TITLE
Create lua template 时允许空的 module name

### ISSUE THREAD

**Issue by xiejiangzhi** [Tencent/UnLua#413]
可以考虑在现在的设置里面加一个自动生成时的目录路径。
生成时，如果 module name 是空的，就自动按蓝图文件路径生成，如果能自动将生成文件的 module name 写入，或者支持在 module name 为空时也能基于生成的路径直接将 module name 写入剪贴板，然后用户粘贴一下就非常方便了。
如果有 module name 的话，就按用户自定路径的生成（也就是现有方式）

**Comment by xuyanghuang-tencent** [comment]
[v2.2.1](https://github.com/Tencent/UnLua/releases/tag/v2.2.1)
