### ISSUE TITLE
Duplicate出来的UFunction释放问题

### ISSUE THREAD

**Issue by OneBigShrimp** [Tencent/UnLua#414]
我们用的UnLua版本比较老，DuplicateUFunction中还是这样写的
if (GUObjectArray.DisregardForGCEnabled() || GUObjectClusters.GetNumAllocatedClusters())
{
      NewFunc->AddToRoot();
}
这样有个问题就是不切换场景，Class就无法释放，因为会被复制出来的Function引用，我看现在UnLua这部分处理是这样的
if (OuterClass->IsRooted() || GUObjectArray.IsDisregardForGC(OuterClass))
{
    NewFunc->AddToRoot();
}
else
{
    NewFunc->Next = OuterClass->Children;
    OuterClass->Children = NewFunc;
    NewFunc->AddToCluster(OuterClass);
}

如果走了下面else的分支，而且Class位于Cluster（包括ClusterRoot）中，即使触发了RemoveUFunction，这个UFunction是不是没法被GC的（除非Class被GC），感觉这是不是也不太对，是不是要Dissolve掉这个Class的Cluster。

**Comment by xuyanghuang-tencent** [comment]
是的，早期的设计比较依赖于切场景来释放。大概在2.0.1版本之后所有Duplicate出来的UFunction就都挂在其对应的UClass上了，不会有多余引用，也会随着它的Owner一起释放。

另外，上面那个`GUObjectClusters.GetNumAllocatedClusters()`是GPropertyCreator创建出来的，上面放着的是各种Property。

**Comment by xuyanghuang-tencent** [comment]
[v2.2.1](https://github.com/Tencent/UnLua/releases/tag/v2.2.1)
