### ISSUE TITLE
编辑器模式正常，出包报错找不到资源

### ISSUE THREAD

**Issue by 19920716** [Tencent/UnLua#417]
local widget_class = UE.UClass.Load("/Game/Resource/UI/UI_Main/UI_Main.UI_Main_C")
    local widget_root = NewObject(widget_class, self)
    widget_root:AddToViewport()

![image](https://user-images.githubusercontent.com/19903385/168070807-5b418a9e-9e77-4a9f-8ff4-7869624c401c.png)

**Comment by YJ66xiaopipi** [comment]
盲猜是资源没打进包里

**Comment by 19920716** [comment]
是的，UI_Main 没有被Cooked 到 Save，出包就找不到
