### ISSUE TITLE
开启Unlua，退出UE，必崩溃

### ISSUE THREAD

**Issue by Italink** [Tencent/UnLua#421]
在构造函数里用this创建共享指针，再外部用new又赋值了一个共享指针，导致插件退出时，两个指针都会触发Style的析构，因此崩溃，挺简单的错误，请尽快修复，谢谢=.=
![image](https://user-images.githubusercontent.com/33830802/168740129-0d770697-c127-4aaf-8b8c-ebeea8c3232d.png)

**Comment by xuyanghuang-tencent** [comment]
尴尬，低级错误了
