### ISSUE TITLE
unlua PS4、PS5平台支持

### ISSUE THREAD

**Issue by cyzqq** [Tencent/UnLua#423]
我看 unlua 目前好像没有对PS4、PS5平台的支持，请问可否考虑一下增加对PS4、PS5平台的支持？ 我现在的项目中使用了unlua，但是打PS5版本的包失败，报了不少关于unlua的错，估计得自己想法编译一个PS5的包，但是PS5不是太熟悉，请大佬们给些指点。部分编译报错信息如下：
E:\Dissidia_new\Plugins\UnLua\Source\ThirdParty\Lua\src/lstate.h(125,10): fatal error: 'signal.h' file not found
    #include <signal.h>
             ^~~~~~~~~~
    1 error generated.
    [9/49] loslib.c
    E:\Dissidia_new\Plugins\UnLua\Source\ThirdParty\Lua\src\loslib.c(174,10): error: implicit declaration of function 'system' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      stat = system(cmd);
             ^
    E:\Dissidia_new\Plugins\UnLua\Source\ThirdParty\Lua\src\loslib.c(199,13): error: use of undeclared identifier 'L_tmpnam'; did you mean 'os_tmpname'?
      char buff[LUA_TMPNAMBUFSIZE];
                ^~~~~~~~~~~~~~~~~
                os_tmpname
    E:\Dissidia_new\Plugins\UnLua\Source\ThirdParty\Lua\src\loslib.c(135,27): note: expanded from macro 'LUA_TMPNAMBUFSIZE'
    #define LUA_TMPNAMBUFSIZE       L_tmpnam
                                    ^
    E:\Dissidia_new\Plugins\UnLua\Source\ThirdParty\Lua\src\loslib.c(198,12): note: 'os_tmpname' declared here
    static int os_tmpname (lua_State *L) {
               ^
    E:\Dissidia_new\Plugins\UnLua\Source\ThirdParty\Lua\src\loslib.c(199,13): error: size of array has non-integer type 'int (lua_State *)' (aka 'int (struct lua_State *)')
      char buff[LUA_TMPNAMBUFSIZE];
                ^~~~~~~~~~~~~~~~~
    E:\Dissidia_new\Plugins\UnLua\Source\ThirdParty\Lua\src\loslib.c(135,27): note: expanded from macro 'LUA_TMPNAMBUFSIZE'
    #define LUA_TMPNAMBUFSIZE       L_tmpnam
                                    ^~~~~~~~
    E:\Dissidia_new\Plugins\UnLua\Source\ThirdParty\Lua\src\loslib.c(201,3): error: implicit declaration of function 'tmpnam' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      lua_tmpnam(buff, err);
      ^
    E:\Dissidia_new\Plugins\UnLua\Source\ThirdParty\Lua\src\loslib.c(149,33): note: expanded from macro 'lua_tmpnam'
    #define lua_tmpnam(b,e)         { e = (tmpnam(b) == NULL); }
                                           ^
    E:\Dissidia_new\Plugins\UnLua\Source\ThirdParty\Lua\src\loslib.c(210,21): error: implicit declaration of function 'getenv' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      lua_pushstring(L, getenv(luaL_checkstring(L, 1)));  /* if NULL push nil */
                        ^
    E:\Dissidia_new\Plugins\UnLua\Source\ThirdParty\Lua\src\loslib.c(210,21): error: incompatible integer to pointer conversion passing 'int' to parameter of type 'const char *' [-Werror,-Wint-conversion]
      lua_pushstring(L, getenv(luaL_checkstring(L, 1)));  /* if NULL push nil */
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    E:\Dissidia_new\Plugins\UnLua\Source\ThirdParty\Lua\src/lua.h(237,65): note: passing argument to parameter 's' here
    LUA_API const char *(lua_pushstring) (lua_State *L, const char *s);

**Comment by xuyanghuang-tencent** [comment]
理论上应该可以支持的，不过我本地也没有PS的开发环境，这个需要去索尼申请开发者授权。可以加官方交流群贴一下，看看怎么编过去就行了。

**Comment by cyzqq** [comment]
嗯，已尝试申请加群，被“虚幻引擎的英文缩写是”这个进群问题难住了，能给个提示吗？哈哈

**Comment by xuyanghuang-tencent** [comment]
**U**nreal **E**ngine -> UE

**Comment by xuyanghuang-tencent** [comment]
[v2.3.1](https://github.com/Tencent/UnLua/releases/tag/v2.3.1)
