### ISSUE TITLE
动画通知调用组件Lua复写函数崩溃【Bug】

### ISSUE THREAD

**Issue by upbins** [Tencent/UnLua#430]
创建动画状态事件,Tick实现如下.
![image](https://user-images.githubusercontent.com/7933961/170158730-d80e78f2-2191-4ba4-b982-5a7344d04b7c.png)
AC_Collision组件自定义函数
![image](https://user-images.githubusercontent.com/7933961/170158886-3f607e43-63c8-4677-9da0-d700ab8a74cc.png)
并绑定AC_Collision_C脚本
AC_Collision_C脚本复写Test函数
![image](https://user-images.githubusercontent.com/7933961/170158939-6994703e-b0c2-4efa-85f8-69abe903c591.png)
之后在动作蒙太奇配置上面动画状态通知
![image](https://user-images.githubusercontent.com/7933961/170159077-92e92a6d-6ed4-488d-b1bb-839799cc9787.png)
最后播放蒙太奇,出现崩溃。
![image](https://user-images.githubusercontent.com/7933961/170159377-d5ad1b7b-af5d-410a-9f88-754542c06a42.png)

**Comment by Italink** [comment]
运行issue430的测试地图，主线程死循环
![企业微信截图_16535561395883](https://user-images.githubusercontent.com/33830802/170456873-093e7914-b04d-4001-a792-edef8c5aa60c.png)

**Comment by xuyanghuang-tencent** [comment]
[v2.2.1](https://github.com/Tencent/UnLua/releases/tag/v2.2.1)
