### ISSUE TITLE
UE 5.0.1 无法编译UnLua工程

### ISSUE THREAD

**Issue by livingyang** [Tencent/UnLua#431]
Generate Vistual Studio Project的时候提示如下错误：

Some Platforms were skipped due to invalid SDK setup: IOS, Android.
See the log file for detailed information

Discovering modules, targets and source code for project...
E:\developer\ue5\UnLua-2.2.0\Plugins\UnLua\Source\UnLua\UnLua.Build.cs(17,7): error CS0246: The type or namespace name 'Tools' could not be found (are you missing a using directive or an assembly reference?)
E:\developer\ue5\UnLua-2.2.0\Plugins\UnLua\Source\UnLua\UnLua.Build.cs(70,39): error CS0246: The type or namespace name 'FileReference' could not be found (are you missing a using directive or an assembly reference?)
E:\developer\ue5\UnLua-2.2.0\Plugins\UnLua\Source\UnLua\UnLua.Build.cs(71,26): error CS0103: The name 'FileReference' does not exist in the current context
ERROR: Expecting to find a type to be declared in a target rules named 'TPSProjectTarget'.  This type must derive from the 'TargetRules' type defined by Unreal Build Tool.

**Comment by xuyanghuang-tencent** [comment]
使用`develop`分支或参考这个[commit](https://github.com/Tencent/UnLua/commit/88afe9bd95d7aa542454f809111594a98e0d0f11)

今晚更新个版本

**Comment by xuyanghuang-tencent** [comment]
[v2.2.1](https://github.com/Tencent/UnLua/releases/tag/v2.2.1)
