### ISSUE TITLE
DynamicEntryBox创建Iteam绑定蓝图代理，只有第一个Iteam执行代理效果

### ISSUE THREAD

**Issue by SimpleXiongmao** [Tencent/UnLua#434]

**Comment by SimpleXiongmao** [comment]
示例代码：
![image](https://user-images.githubusercontent.com/72717755/170412371-ee096500-d822-4a02-a9e6-11f1c387144b.png)
![image](https://user-images.githubusercontent.com/72717755/170412255-1c679f56-4b83-4eee-988e-bfd8aeca89bb.png)
![image](https://user-images.githubusercontent.com/72717755/170412294-a4597bca-16bb-441c-8d3d-7f3fca1729b2.png)
![image](https://user-images.githubusercontent.com/72717755/170412440-91dc2b9e-9da4-4c3f-b491-a8ac651275c8.png)

**Comment by xuyanghuang-tencent** [comment]
这个和`DynamicEntryBox`应该没关系，是为`MulticastDelegate`添加`lua function`作为handler的时候，UnLua会为这个`lua function`创建对应的`ULuaDelegateHandler`。也就是说它们是1对1的关系，所以添加到委托的时候不会重复。

像多个Item共用一个脚本的这种场景，可以这样：

```lua
PlayerController.TestDelegate:Add(self, function(self, ...) UMG_Test_C.OnTestDelegate(self, ...) end)
```

**Comment by SimpleXiongmao** [comment]
ok，方式可行， 多谢
