### ISSUE TITLE
使用远程打包 iOS 的方式会出现错误

### ISSUE THREAD

**Issue by GotGimhong** [Tencent/UnLua#435]
我们是用远程打包的方式来打包 iOS 的。在打包过程的 Build 阶段，引擎会自动将 C++ 代码发送到远端的 Mac 设备上进行编译，引擎发送的内容并不包括 Content 目录下的内容。

然而，在 UnLua.Build.cs 当中，会通过 `SetupScripts` 函数将 UnLua/Content 目录下的 UnLua.lua 拷贝到游戏工程的 Content/Script 目录下。因为引擎并不会把 UnLua/Content 目录下的内容拷贝到远端的 Mac 设备上，所以在 Build 阶段，执行到 `SetupScripts` 函数的时候就会出现错误了。
![1](https://user-images.githubusercontent.com/16437644/170426441-f021333c-cf4e-4276-8702-29692bde921d.png)

当然，全程在 Mac 设备上打包 iOS 就不会有这样的问题，不过我们还是希望能够兼容远程打包的方式，毕竟远程打包也是比较常用的打包方式。

**Comment by xuyanghuang-tencent** [comment]
可以，我做个保护

**Comment by xuyanghuang-tencent** [comment]
[v2.2.1](https://github.com/Tencent/UnLua/releases/tag/v2.2.1)
