### ISSUE TITLE
如何在lua里写构造函数？

### ISSUE THREAD

**Issue by xermao** [Tencent/UnLua#44]
Initialize和UserConstructionScript我都试了，都不行。要在地图编辑器里拖动的时候会执行。

**Comment by xermao** [comment]
为什么不回答我的问题呢，后面的问题都回答了？？如果不支持请给个答复，我好寻找其他解决方案

**Comment by futouyiba** [comment]
关注

**Comment by rowechien** [comment]
@xermao 抱歉我看过问题后没有即时回答，后来就忽略了。。。
UnLua在Editor模式下，只在PIE时才真正工作，所以你希望在视口内拖动时能调用UserConstructionScript是不支持的

**Comment by xermao** [comment]
好的，感谢回复
