### ISSUE TITLE
 TArray 引用不存在的方法，会出现 c stack overlfow

### ISSUE THREAD

**Issue by xiejiangzhi** [Tencent/UnLua#441]
master 分支

![KS5M2H8RTLEDX$_NQ_CC{ 3](https://user-images.githubusercontent.com/1396853/170820202-146f3d14-eb5a-4bec-b05f-c4720edf058b.png)
![SRECJ}YJ@)@VBY(U}JWE6ZS](https://user-images.githubusercontent.com/1396853/170820208-12821b0c-873f-4d7d-a6da-e10e7db6bb26.png)

![1$X3RY$ER71(_5{W@O 8W88](https://user-images.githubusercontent.com/1396853/170820216-5f9fb18d-bd56-4e09-aca4-34c24755f95c.png)

**Comment by xiejiangzhi** [comment]
补充说明一下，如果 lua 这边的 stack 多一些，那么靠近错误发现点的 stack 就会完全被 [C] xx 的覆盖掉，造成无法定位错误位置。

**Comment by xuyanghuang-tencent** [comment]
[v2.3.0](https://github.com/Tencent/UnLua/releases/tag/v2.3.0)
