### ISSUE TITLE
Play in standalone game 静态导出失败

### ISSUE THREAD

**Issue by xiejiangzhi** [Tencent/UnLua#448]
UE 4.27

Unlua master 分支

![R)(R3(9UE36~IJIZ WOD))I](https://user-images.githubusercontent.com/1396853/171330822-a7ad81f6-d9d9-42e0-a045-909cc28c8cc8.png)

**Comment by xuyanghuang-tencent** [comment]
[v2.2.2](https://github.com/Tencent/UnLua/releases/tag/v2.2.2)
