### ISSUE TITLE
引用参数造成的内存泄漏

### ISSUE THREAD

**Issue by greatzane** [Tencent/UnLua#450]
我使用2.1.4版本，发现只要调用参数中含有引用返回的函数时，会造成UE4的Engine Misc内存的泄漏，如果大量调用这样的函数，会造成Engine Misc内存快速上涨，并且gc后也无法恢复。例如在官方的demo中添加如下代码：
```
function BP_PlayerController_C:ReceiveTick()
    for i = 1, 1000 do
        self:GetActorBounds()
    end
end
```
通过stat LLMFULL就能看到Engine Misc内存的快速增长。
麻烦看看如何解决，谢谢！

**Comment by xuyanghuang-tencent** [comment]
印象中改过类似的问题，牵扯到的commit有点多，可以参考develop上最新的这个文件。

主要就是在`FFunctionDesc::CallLuaInternal`里对Out参数错误地进行了拷贝：

https://github.com/Tencent/UnLua/blob/27b5e7f1f1684666ae530883425107cca52eee34/Plugins/UnLua/Source/UnLua/Private/ReflectionUtils/FunctionDesc.cpp#L624

**Comment by greatzane** [comment]
2.1.4的这部分代码和上面的develop版大致是一致的。而且我用最新的develop版试了一下，这个问题依然存在，因此应该是有别的问题：
![MemoryLeak](https://user-images.githubusercontent.com/2712575/172081668-277ce26d-d2eb-4585-82b6-8c97a2d9e306.gif)

**Comment by xuyanghuang-tencent** [comment]
我用你的测试代码跑了一下，的确会这样不停增长，不过这里应该是lua的单次垃圾回收速度赶不上每帧分配导致的，比如：

```lua
local counter = 0

function BP_PlayerCharacter_C:ReceiveTick()
    if counter % 1000 ~= 0 then
        for i = 1, 10000 do
            self:GetActorBounds()
        end
    else
        print("lua gc before", collectgarbage("count") / 1024)
        collectgarbage("collect")
        print("lua gc 1", collectgarbage("count") / 1024)
        collectgarbage("collect")
        print("lua gc 2", collectgarbage("count") / 1024)
        collectgarbage("collect")
        print("lua gc after", collectgarbage("count") / 1024)
    end
    counter = counter + 1
end
```

启动后稍等一会：

```
LogUnLua: UNLUA_PRINT[123082] : lua gc before    373.07512569427    
LogUnLua: UNLUA_PRINT[123082] : lua gc 1    110.36200237274    
LogUnLua: UNLUA_PRINT[123082] : lua gc 2    0.20433330535889    
LogUnLua: UNLUA_PRINT[123082] : lua gc after    0.20433330535889   
```

因为Out参数如果你不传的话，最终需要从C++创建后再拷贝回lua里，所以每次调用这类函数都会有额外的lua对象分配（最终会被gc回收）。应对这种需要大量调用的场景，可以考虑这样优化处理：

```lua
local Origin = UE.FVector(0, 0, 0)
local BoxExtent = UE.FVector(0, 0, 0)

function BP_PlayerCharacter_C:ReceiveTick()
    for i = 1, 10000 do
        self:GetActorBounds(false, Origin, BoxExtent)
    end
end
```

**Comment by greatzane** [comment]
好的，感谢~
