### ISSUE TITLE
从Lua传递到蓝图的TArray引用变成了空Array

### ISSUE THREAD

**Issue by coderdamin** [Tencent/UnLua#453]
环境：UE 4.7.2

1、在项目示例的BP_PlayerCharacter_C.lua文件的ReceiveBeginPlay()方法末尾添加
```
local TestArray = UE.TArray(UTest);
TestArray:Add(UTest());
print("#### Befo =　" .. TestArray:Length());
self["TestArrayRefFunc"](self, TestArray, "Name1", "Param1");
print("#### After1 =　" .. TestArray:Length());
self["TestArrayRefFunc2"](self, TestArray, "Name2", "Param2");
print("#### After2 =　" .. TestArray:Length());

local TestArray2 = UE.TArray(UTest2);
TestArray2:Add(UTest2());
self["TestArrayRefFunc3"](self, TestArray2);
print("#### After3 =　" .. TestArray2:Length());
```

2、在蓝图BP_PlayerCharacter.uasset中添加TestArrayRefFunc、TestArrayRefFunc2、TestArrayRefFunc3三个函数
![2022_06_07_23_46 40](https://user-images.githubusercontent.com/20620630/172424667-9f1f946f-8f06-485a-8590-5021ce838722.jpg)

3、UTest和UTest2为蓝图中定义的UStruct
![2022_06_07_23_50 26](https://user-images.githubusercontent.com/20620630/172425382-2e39c182-fac7-4e1a-9ad9-57645cff8801.jpg)

4、输出如下：
```
LogUnLua: UNLUA_PRINT[25407] : #### Befo =　1    
LogBlueprintUserMessages: [BP_PlayerCharacter_C_0] 0
LogUnLua: UNLUA_PRINT[25407] : #### After1 =　1    
LogBlueprintUserMessages: [BP_PlayerCharacter_C_0] 0
LogUnLua: UNLUA_PRINT[25407] : #### After2 =　1    
LogUnLua: UNLUA_PRINT[25407] : #### Befo2 =　1    
LogBlueprintUserMessages: [BP_PlayerCharacter_C_0] 1
LogUnLua: UNLUA_PRINT[25407] : #### After3 =　2    
```
可以看到将UTest的TArray引用传递到蓝图后，长度变为了0，在蓝图中添加的项在Lua中可以取到，同样的操作对UTest2得到了预期输出。

**Comment by xuyanghuang-tencent** [comment]
[v2.2.2](https://github.com/Tencent/UnLua/releases/tag/v2.2.2)
