### ISSUE TITLE
CacheScriptContainer导致的崩溃

### ISSUE THREAD

**Issue by Italink** [Tencent/UnLua#455]
你好，我在动画蓝图中使用Unlua遭遇了崩溃，虽然触发的条件比较苛刻，但它确实是一个问题，当下的使用情况是：
- 在一个动画蒙太奇使用了**多个动画通知**，这些动画通知都有一些**不同数组类型的局部变量**（这些**局部变量会在执行动画通知时创建，执行结束后销毁**）。
- 动画通知中都调用一个Lua函数（由蓝图接口公开过去，再在Lua中覆盖的），函数的参数包含动画通知的局部变量
- 综上，在我执行上述蒙太奇时会导致崩溃。

下面是估计的崩溃原因：
- 当蒙太奇在调用第一个动画通知时，会进入到FFunctionDesc::CallLuaInternal，中，读取动画通知的局部变量，通过追踪 FArrayPropertyDesc::GetValueInternal，我发现它最终会根据地址将该数组Cache，即调用了LuaCore.cpp中的CacheScriptContainer
- 在第一个通知执行结束时，它的局部变量被释放。
- 执行到第二个动画通知，会在原先的地址上创建新的Property，这时就导致Unlua使用Cahce中的数组进行访问。
- 由于数组类型保存的是元素的引用，Unlua会根据引用按原先的数组结构去访问新的数组内容，因此导致了崩溃。

花了好长时间才找到问题所在，如果能解决的话就太好了，感激不尽。

**Comment by xuyanghuang-tencent** [comment]
> * 动画通知中都调用一个Lua函数（由蓝图接口公开过去，再在Lua中覆盖的），函数的参数包含动画通知的局部变量

这条有点不太明白，这里的蓝图接口方法是同一个吗？

假设有两个动画通知类，ASN1和ASN2，它们各有两个局部变量，Array1（元素为Struct1）和Array2（元素为Struct2）。

蓝图接口方法假设叫Test，那么它的函数签名中的参数应该是怎么样的，才能同时接受Array1和Array2？

**Comment by Italink** [comment]
作者大大考虑解决这个问题吗? 
出现这个问题的主要原因是单纯使用地址不足以作为缓存容器的Key，或许应该增加其他上下文标识来进行区分，比如ElementType，ContainerSize之类的，我对Lua不太熟，如果能解决这个问题的话感激不尽.

**Comment by xuyanghuang-tencent** [comment]
是的，如果lua里一直持有这个缓存是会有问题的，需要找个办法统一理下

**Comment by xuyanghuang-tencent** [comment]
调整了一下，不会把本地变量（`UObject::execLocalVariable` 里的 `Stack.Locals`，分配在栈上 ）直接传递到Lua里了，而是拷贝到FFunctionDesc的参数缓存里。但如果Lua函数中将这个参数指针缓存起来，可能还是会有点问题，还是得找个时机去释放这个Cache（比如调完了就释放，但这样性能可能会比较差）。

**Comment by Italink** [comment]
哇，都不睡觉的=.=，感谢感谢，考虑到Lua的调用频率比较高，确实有必要缓存，这个问题主要是容易在一些内存变动比较频繁的地方出现（目前也只是在动画蓝图里发现）。

**Comment by xuyanghuang-tencent** [comment]
[v2.2.2](https://github.com/Tencent/UnLua/releases/tag/v2.2.2)
