### ISSUE TITLE
运行时使用"obj list"命令会引发fatal错误："Script serialization mismatch ..."

### ISSUE THREAD

**Issue by Junho2009** [Tencent/UnLua#46]
Unreal 4.22.0
Class.cpp 1410行

似乎是涉及在lua层重写过的蓝图事件。
用以上UE版本，在 TPSProject 中运行游戏，可重现。

**Comment by rowechien** [comment]
我来检查一下

**Comment by rowechien** [comment]
@Junho2009 fixed in the latest commit...
