### ISSUE TITLE
使用ListView组件AddItem时发现的问题

### ISSUE THREAD

**Issue by Lp-new** [Tencent/UnLua#466]
1、创建一个BP_SystemEntranceUI，然后里面会有个ListView, 这时候动态创建一个BP_TopBarItemUI  然后通过ListView:AddItem() 添加进ListView
2、调用ListView:AddItem的同一帧，下一个逻辑(没有等待这个TopBarItem的Construct执行到)，就直接创建下一个UI->
BP_BagMainViewUI
3、接着在这个BagMainViewUI的Construct方法里往BagMainViewUI的一个ListView加入有个Item->BP_BagBarItemUI
4、当2,3步执行完之后，1步创建的TopBarItem的Construct才会执行到。这个时候就会像视频里面那样，BP_BagBarItemUI的trybind就会判断到ObjectName.Contains(":WidgetTree.")这个判断里面，导致绑定丢失
5、这个是断点的视频
https://user-images.githubusercontent.com/6648990/174043043-89252dde-f024-474f-a7d5-7bf23992d0d0.mp4

**Comment by xuyanghuang-tencent** [comment]
这个`:WidgetTree.`的判断应该是以前为了不产生额外UObject的引用加的（避免Lua里持有对象导致一直释放不掉），2.2 之后应该可以直接去掉了

**Comment by xuyanghuang-tencent** [comment]
[v2.2.3](https://github.com/Tencent/UnLua/releases/tag/v2.2.3)
