### ISSUE TITLE
自建的enum蓝图（content中的枚举资源）如何在lua中load？

### ISSUE THREAD

**Issue by futouyiba** [Tencent/UnLua#47]
local ENotifyEvent = UE4.UClass.Load('/MultiplayerCombatEditor/Settings/ENotifyEvent.ENotifyEvent')
路径：UserDefinedEnum'/MultiplayerCombatEditor/Settings/ENotifyEvent.ENotifyEvent'
得到错误：
LogUnLua: Warning: RegisterClass: Failed to register class /MultiplayerCombatEditor/Settings/ENotifyEvent.ENotifyEvent_C!

**Comment by rowechien** [comment]
枚举（UUserDefinedEnum）不是UClass，用UObject.Load

**Comment by futouyiba** [comment]
虽然问题关闭了，我还是写一下后续的情况，以便其他小伙伴们参考。
这几天用UObject.Load时，还是遇到了问题：编辑器中定义的UEnum，其中每一个枚举项的名字并不是用户所写的名字，类似于 #40 
所以现在用的workaround是：在相关的蓝图当中新建一个变量，设置其为我想要的那个ENotifyEvent：：FirstEvent，然后直接在lua当中调用这个蓝图变量

**Comment by rowechien** [comment]
@futouyiba [740576d](https://github.com/Tencent/UnLua/commit/740576de58635eeea79649e593f3f7f17014e852) 这个commit对editor里定义的enum做了更好的支持。

**Comment by futouyiba** [comment]
> @futouyiba [740576d](https://github.com/Tencent/UnLua/commit/740576de58635eeea79649e593f3f7f17014e852) 这个commit对editor里定义的enum做了更好的支持。

它的改动是不是说可以直接用用户写的名字来作为UnLua中调用的变量名？

**Comment by xermao** [comment]
> > @futouyiba [740576d](https://github.com/Tencent/UnLua/commit/740576de58635eeea79649e593f3f7f17014e852) 这个commit对editor里定义的enum做了更好的支持。
> 
> 它的改动是不是说可以直接用用户写的名字来作为UnLua中调用的变量名？

是的，直接用蓝图里的名字。非常方便。
