### ISSUE TITLE
编辑器模式下结束运行一些Lua函数不会被执行

### ISSUE THREAD

**Issue by FreeNightKnight** [Tencent/UnLua#472]
编辑器模式下退出PIE的时候unlua环境过早释放导致一些Lua函数不会被执行。
目前发现的函数有：
GameInstance:ReceiveShutdown
Actor:ReceiveEndPlay
UserWidget:Destruct

**Comment by xuyanghuang-tencent** [comment]
[v2.2.3](https://github.com/Tencent/UnLua/releases/tag/v2.2.3)
