### ISSUE TITLE
通过NewObject接口添加的Uobject引用该如何释放？

### ISSUE THREAD

**Issue by Ritchielambda** [Tencent/UnLua#476]

**Comment by Ritchielambda** [comment]
在Lua中调用NewObject，并且传入一个ModuleName，绑定一个lua脚本，这时候会通过NewLuaObject函数来在注册表下面添加一个LuaInstance实例，并且在C++端进行引用，但是这个脚本是绑定在某个table下的临时变量，应该对应的lua变量应该在table gc的时候一起gc，但是现在被挂在了lua的注册表下，要怎么释放引用呢

**Comment by xuyanghuang-tencent** [comment]
是的，这里的逻辑有点问题，'LuaIntance'应该是在'ObjectMap'这个弱引用表里的

**Comment by xuyanghuang-tencent** [comment]
[v2.2.3](https://github.com/Tencent/UnLua/releases/tag/v2.2.3)
