### ISSUE TITLE
用Lua生成一个自定义蓝图结构体和对应表，通过循环遍历使用GetDataTableFromName获取Row会引起内存拷贝错误，崩溃。 还有使用UE.UClass.Load，不蹦但也不对直接获取到nil的Row。使用UE.UObject.Load直接蹦

### ISSUE THREAD

**Issue by mietiandazao** [Tencent/UnLua#477]
用Lua生成一个自定义蓝图结构体和对应表，通过循环遍历使用GetDataTableFromName获取Row会引起内存拷贝错误，崩溃。
还有使用UE.UClass.Load，不蹦但也不对直接获取到nil的Row。使用UE.UObject.Load直接蹦

**Comment by xuyanghuang-tencent** [comment]
这里说的循环遍历是指的是什么？我试着做了个用例没有重现，看看上面有什么漏掉的地方

**Comment by mietiandazao** [comment]
> 
我本地是这样的，过去在UE4中都能正常，在UE50.3，和2.2.1Unlua就无法正常执行
local IconDataTable = UE.UDataTable.Load("/Game/UI/Data/IconData/IconDataStructureDataTable_C")--蓝图里自定义的表
    local Row = UE.FIconDataStructure()-----蓝图里自定义的表结构体。这里过去是这样子的，后来改成UE.UObject.Load就崩，如果用UClass，后面的Row也是nil
    local RowNames = UE.TArray(UE.FName)
    UE.UDataTableFunctionLibrary.GetDataTableRowNames(IconDataTable , RowNames)
    local NumRows = RowNames:Length()
for index = 1, NumRows do
    local name = RowNames:Get(index)
    UE.UDataTableFunctionLibrary.GetDataTableRowFromName(IconDataTable ,name , Row  #)--这里不是Row空，就是直接内存报错
end

**Comment by xuyanghuang-tencent** [comment]
`FIconDataStructure`如果是个蓝图类型，那应该这样：
```lua
local RowStruct = UE.UObject.Load("蓝图路径")
local Row = RowStruct()
```

**Comment by mietiandazao** [comment]
FIconDataStructure 和Row 各种加载组合都试过，结尾加不加_C之类也试过，最后都会报错。。。。我现在是放弃使用Unlua读取蓝图表和结构了，等官方有标准方式在用[扶额哭笑]

**Comment by xuyanghuang-tencent** [comment]
官方群里联系我看看能不能重现下，上面说的就是标准加载方式，可能是有什么地方没有考虑到

**Comment by mietiandazao** [comment]
local FIconDataStructure = UE.UObject.Load("蓝图路径")
local Row = FIconDataStructure()
是对的
感谢官方，问题已解决，一开始是我理解错我
