### ISSUE TITLE
绑定一个有语法错误的lua时 不会提示错误

### ISSUE THREAD

**Issue by YJ66xiaopipi** [Tencent/UnLua#480]
![YVPK((}ZIB6CPEH)1{5F87C](https://user-images.githubusercontent.com/99896149/177260763-14326d9d-ae3c-43f8-89ea-f0710af6db2c.jpg)
随便找个lua 插入一行会崩溃的代码
蓝图或者C++绑定的时候 不会提示异常，直接用lua 本身的require 该lua文件会提示这行有异常

**Comment by xuyanghuang-tencent** [comment]
[v2.2.3](https://github.com/Tencent/UnLua/releases/tag/v2.2.3)
