### ISSUE TITLE
调用K2_DestroyActor时，Lua侧不会删除引用。

### ISSUE THREAD

**Issue by chowJY** [Tencent/UnLua#481]
复现方式：生成一个Actor，并把它赋值给另一个对象的一个属性
![image](https://user-images.githubusercontent.com/19146127/177454573-73fbd4f3-689d-4342-b7c8-0ee64666c04b.png)
再被赋值的对象的tick里加如下打印
![image](https://user-images.githubusercontent.com/19146127/177454668-20becc3b-c224-43fe-a621-f6764d49d2f0.png)
发现当Actor调用destroy时Actor已经不合法了，lua侧的引用并没有被清除。
![image](https://user-images.githubusercontent.com/19146127/177454775-0a5c6d2d-c612-4da5-8a00-aca50f315be2.png)
参考2.1.3版本
![image](https://user-images.githubusercontent.com/19146127/177455069-3d393f9a-6afa-437f-8458-bdf5fb0525f8.png)
当Actor被销毁时，是有去GObjectReferencer把lua侧的引用情况的。
新版的ManualObjectReferencer好像并没有此操作，清除引用的的逻辑只找到了UObject_delete内的一处
想知道2.1.3版本清除lua侧引用的逻辑是否迁移到了别处。还是处于何种原因被移除了。

**Comment by xuyanghuang-tencent** [comment]
调用`K2_DestroyActor`的时候不会立即销毁这个`Actor`，会等UEGC回收后，通过`NotifyUObjectDeleted`通知到`FObjectRegistry::Unbind`来进行unref对应的table，等待后续luagc回收。

这样的好处是不会因为luagc不及时或者无法回收table，从而导致UE对象也无法及时或者无法释放的问题；
坏处是需要用户理解把UE对象挂在UE的引用链下才不会回收；

从排查和解决问题的角度来看，去**检查到底哪里引用了对象**显然比**加个引用**困难得多
