### ISSUE TITLE
0x000000000000dead是一个特殊的指针么.(崩溃的时候遇到的)

### ISSUE THREAD

**Issue by monkqq** [Tencent/UnLua#482]
切场景的时候还在蓝图还在Tick(Lua中实现具体逻辑），较大概率遇到的崩溃。
![微信图片_20220707202436](https://user-images.githubusercontent.com/10555371/177772503-e0500285-9b8e-492c-b8ba-24d5b2300885.png)

**Comment by xuyanghuang-tencent** [comment]
[v2.2.3](https://github.com/Tencent/UnLua/releases/tag/v2.2.3)
