### ISSUE TITLE
静态导出FFileHelper后，调用LoadFileToString导致UE4 崩溃

### ISSUE THREAD

**Issue by MyTree163** [Tencent/UnLua#485]
**问题触发的代码如下**：  
cpp代码：

BEGIN_EXPORT_ENUM_EX(FFileHelper::EHashOptions, EFileHelperHashOptions)
	ADD_SCOPED_ENUM_VALUE(None)
	ADD_SCOPED_ENUM_VALUE(EnableVerify)
	ADD_SCOPED_ENUM_VALUE(ErrorMissingHash)
END_EXPORT_ENUM(EFileHelperHashOptions)

BEGIN_EXPORT_CLASS(FFileHelper)
	ADD_STATIC_FUNCTION_EX("ReadFile", bool, LoadFileToString, FString&, const TCHAR*, FFileHelper::EHashOptions, uint32)
END_EXPORT_CLASS()
IMPLEMENT_EXPORTED_CLASS(FFileHelper)

lua代码：
-- 从目标文件中读取content信息

local content = ""
local root_path = UE.UBlueprintPathsLibrary.GeneratedConfigDir()
UE.FFileHelper.ReadFile(content, root_path.."TestFile.txt", UE.EFileHelperHashOptions.None, 0)

**UE4崩溃信息为**：
Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000

**Comment by xuyanghuang-tencent** [comment]
#486

**Comment by xuyanghuang-tencent** [comment]
[v2.2.3](https://github.com/Tencent/UnLua/releases/tag/v2.2.3)
