### ISSUE TITLE
如何在UnLua中使用蓝图中定义的结构体类型的变量

### ISSUE THREAD

**Issue by zealotxxx** [Tencent/UnLua#49]
slua好像在这一点上是支持的，后续我们会加入这个功能吗

**Comment by rowechien** [comment]
前面有个类似的问题，[40](https://github.com/Tencent/UnLua/issues/40)

**Comment by rowechien** [comment]
slua不熟悉，如果它真的支持并且对你有用的话，你可以参考他们的实现自己改一下，这个功能应该不在计划中

**Comment by rowechien** [comment]
@zealotxxx [740576d](https://github.com/Tencent/UnLua/commit/740576de58635eeea79649e593f3f7f17014e852) 这个commit对editor里定义的struct和enum做了更好的支持。
