### ISSUE TITLE
通过C++类绑定的时候使用自动创建脚本功能会崩溃

### ISSUE THREAD

**Issue by YJ66xiaopipi** [Tencent/UnLua#490]
通过C++类绑定脚本的时候再蓝图中使用该功能自动创建脚本会奔溃
![image](https://user-images.githubusercontent.com/99896149/181146359-79cc6c0b-4b46-406c-a64d-9dc43e0bb408.png)

![image](https://user-images.githubusercontent.com/99896149/181146167-8c27dd58-4ff2-4702-8c53-f32098797a0e.png)

![image](https://user-images.githubusercontent.com/99896149/181146246-198369c0-813a-49fd-88aa-9925a0d94f44.png)
![image](https://user-images.githubusercontent.com/99896149/181146263-0435cac7-9724-45aa-9277-6bb49fc52c13.png)

**Comment by xuyanghuang-tencent** [comment]
[v2.2.4](https://github.com/Tencent/UnLua/releases/tag/v2.2.4)
