### ISSUE TITLE
UE4.27+Unlua2.2.3，启独立，蓝图调不到C++定义蓝图中实现的接口

### ISSUE THREAD

**Issue by coderdamin** [Tencent/UnLua#494]
UE4.27+Unlua2.2.3，启独立，蓝图调不到C++定义蓝图中实现的接口
PIE下正常，回退到Unlua2.2.2正常

![VPYUJN@8FPR){JGL01` 2UG](https://user-images.githubusercontent.com/20620630/181891921-2584afc2-38ee-4617-bb55-7dcfcc356619.png)

**Comment by xuyanghuang-tencent** [comment]
试着按图里的蓝图做了个用例，貌似没重现，麻烦看看有什么遗漏的地方？看描述似乎和lua本身无关，只是蓝图cast到C++接口失败了？

**Comment by coderdamin** [comment]
我这边的接口是在用unlua旧版本的时候就已经添加了，蓝图里实现了，在旧版本时正常，更到Unlua2.2.3后出的问题，试了把蓝图实现的接口删除，重新实现后OK了。谢谢 谢谢

**Comment by coderdamin** [comment]
这个问题还是建议查一下，当用户的Unlua从低版本升上来后，就可能会遇到，并且是逻辑跑不到又不报错，逻辑复杂时还不好追查
