### ISSUE TITLE
正式版本日志会出现 warning Filter Uobject of *** in WidgetArchetype，编辑器则没事

### ISSUE THREAD

**Issue by yudehai0204** [Tencent/UnLua#495]
正式版本日志会出现 warning Filter Uobject of *** in WidgetArchetype，编辑器则没事

![W_SOVE~RCT{J296K(03YZ5G](https://user-images.githubusercontent.com/10924643/182562486-a5cb94c2-6bee-4c8b-a463-868e44729902.png)
![image](https://user-images.githubusercontent.com/10924643/182562577-3668f5cf-e43e-4516-92a9-f86aec24f0e0.png)
如图所示，目前线上偶先会有崩溃问题，不知道是否与此有关系，想知道这行打印代表着什么，是代表着这个组件没有捕获到吗？

**Comment by xuyanghuang-tencent** [comment]
#466 和这个是同一个情况，但和崩溃本身应该没什么关系，得看看崩溃的堆栈具体挂在哪里

**Comment by yudehai0204** [comment]
> 

我用的是2.2.4版本啊
