### ISSUE TITLE
关于重复生成 IntelliSence，以及蓝图Module中标识符错误的问题

### ISSUE THREAD

**Issue by CRAFTSTARCN** [Tencent/UnLua#498]
描述：  
使用最新2.2.3 release版本
当蓝图编译保存是，会在IntelliSence文件夹下，直接生成一个对应蓝图类的IntelliSence文件  
而此时如果点击主界面上Unlua图标中的Generate IntelliSence 则会在IntelliSence文件夹下，根据蓝图所在目录，生成另外一个IntelliSence文件  
两者中都声明了改类(使用---@class)，会造成Duplicate，IDE报错（且生成两份是不必要的）
如下图：
![BUG](https://user-images.githubusercontent.com/24621848/183664946-4ada4a5e-dfeb-43e6-990b-c94df9bab7aa.png)

而更糟糕的是，在使用Unlua在蓝图编辑界面中生成模板文件中，对于类的注解仍是---@class，造成duplicate，此处并不是声明类型，而是使用该类型，应注解为---@type

**Comment by xuyanghuang-tencent** [comment]
[v2.2.4](https://github.com/Tencent/UnLua/releases/tag/v2.2.4)
