### ISSUE TITLE
请问如何在Lua获取（访问）绑定在UObject上的Lua Object（Table）实例？

### ISSUE THREAD

**Issue by GotGimhong** [Tencent/UnLua#50]
例如在MyActor.lua中定义了如下内容：
`require "UnLua"`
`local MyActor_C = Class() `
`...`
`return MyActor_C`
当其绑定的UObject实例化时，MyActor_C也会通过NewLuaObject函数进行实例化，那么请问如何在Lua中获取到这些MyActor_C的实例（Table）呢？

**Comment by rowechien** [comment]
这个Actor应该是你自己Spawn出来的吧，那你肯定需要有方法去取到这个对象啊，具体方法由你自己定。
举个例子：PlayerController, Character一般都是由引擎负责生成，所以引擎也提供了对应的方法来获取具体实例UGameplayStatics::GetPlayerController, UGameplayStatics::GetPlayerCharacter

**Comment by GotGimhong** [comment]
> 这个Actor应该是你自己Spawn出来的吧，那你肯定需要有方法去取到这个对象啊，具体方法由你自己定。
> 举个例子：PlayerController, Character一般都是由引擎负责生成，所以引擎也提供了对应的方法来获取具体实例UGameplayStatics::GetPlayerController, UGameplayStatics::GetPlayerCharacter。在Lua里调用这2个函数返回的就是你要取的对应Lua实例(Table)

明白了，谢谢！

**Comment by futouyiba** [comment]
@rowechien 谢谢答疑。这下我也知道了
