### ISSUE TITLE
Unlua2.2.3版本，lua重写的方法在重新打开编辑器后需要refreshnode

### ISSUE THREAD

**Issue by coderdamin** [Tencent/UnLua#500]
![6X2M(D2A@KR(5)OG(LVV%P4](https://user-images.githubusercontent.com/20620630/184820024-f512a3e9-a97a-40e7-b909-4a0dcf4c1a4c.png)

![image](https://user-images.githubusercontent.com/20620630/184821385-9adc7c10-557e-4564-90a7-6401f66aa396.png)

Unlua2.2.3，Lua重写的C++声明的方法，每次启动编辑器都提示报错，刷新节点后正常

**Comment by xuyanghuang-tencent** [comment]
[v2.2.4](https://github.com/Tencent/UnLua/releases/tag/v2.2.4)
