### ISSUE TITLE
UUnluaManager 野指针访问导致crash

### ISSUE THREAD

**Issue by DianxinWang** [Tencent/UnLua#504]
打包之后的游戏在退出时，UUnLuaManager会先于UnLuaEnv释放并调用析构函数，导致UnLuaEnv所持有的Manager指针为野指针。而之后UnLuaEnv释放时，将调用Manager野指针的函数，并造成crash。

crash 堆栈
![image](https://user-images.githubusercontent.com/36990568/185764171-5deae595-5549-4427-b4ff-1ed1cd2d4fe5.png)
![image](https://user-images.githubusercontent.com/36990568/185764189-c48bd4d8-21ed-4760-a68d-72764cfb2cb7.png)

虽然原生代码中有对Manager进行AddToRoot 和RemoveFromRoot进行管理，但在打包游戏退出时（PIE和StandAloneGame未有该问题），UUnluaManager确实先于UnLuaEnv析构掉。这里本地尝试通过手动添加UnLuaManager析构函数，并分别于UnluaEnv和UnluaManager的析构函数上设置断点，进行验证。
![image](https://user-images.githubusercontent.com/36990568/185764717-e311648a-64a6-4fed-8f45-c4de1d4eeff6.png)
![image](https://user-images.githubusercontent.com/36990568/185764782-b95712d4-0131-459b-b142-39ad90dbb501.png)

修改建议：
可简单将UnLuaEnv析构函数中对Manager->CleanUp()的调用剔除。
亦或通过某种机制确保UnLuaManager后于UnLuaEnv析构。

**Comment by xuyanghuang-tencent** [comment]
`EngineExit`时对UObject的销毁顺序是不保证的，这里应该是先销毁了`LuaManager`，然后才是`LuaEnvLocator`（引起`FLuaEnv`的析构）

**Comment by xuyanghuang-tencent** [comment]
[v2.2.4](https://github.com/Tencent/UnLua/releases/tag/v2.2.4)
