### ISSUE TITLE
Lua持有结构体下的TArray字段，在结构体本身被GC后访问该数组会导致崩溃

### ISSUE THREAD

**Issue by xuyanghuang-tencent** [Tencent/UnLua#505]

**Comment by jozhn** [comment]
使用复制会导致A.B.C这样的赋值失效，对赋值造成较大的困难，所以还是给访问被GC的结构体的成员增加错误提示更合适一些

**Comment by xuyanghuang-tencent** [comment]
[v2.3.1](https://github.com/Tencent/UnLua/releases/tag/v2.3.1)
