### ISSUE TITLE
TCHAR_TO_XXX等字符串宏的使用问题 会导致读写非法内存

### ISSUE THREAD

**Issue by jozhn** [Tencent/UnLua#509]
在UE中，XXX_TO_XXX等字符串宏只能用于作为函数的参数使用，因为在宏内Get结束后，字符串的生命周期就结束了，之后存储的指针会随时变成野指针，在之后导致内存问题。

https://docs.unrealengine.com/4.27/zh-CN/ProgrammingAndScripting/ProgrammingWithCPP/UnrealArchitecture/StringHandling/CharacterEncoding/

**Comment by jozhn** [comment]
https://github.com/Tencent/UnLua/pull/508

**Comment by xuyanghuang-tencent** [comment]
[v2.2.4](https://github.com/Tencent/UnLua/releases/tag/v2.2.4)
