### ISSUE TITLE
UnLuaIntelliSense 沒有自動導出符號信息

### ISSUE THREAD

**Issue by kuangjin520** [Tencent/UnLua#51]
能給個詳細點的説明嗎？

**Comment by kuangjin520** [comment]
UnLuaIntelliSense It's disabled by default。怎么开启它呢？建议给个开启方法，方便初学者。

**Comment by futouyiba** [comment]
@kuangjin520 在build.cs里面有个开关。默认是0，把它改成1就行了

**Comment by kuangjin520** [comment]
好的，已解决，谢谢！
