### ISSUE TITLE
打包成win64程序,退出游戏时报错,FDelegateRegistry析构函数CachedHandlers里有空指针

### ISSUE THREAD

**Issue by subird12345** [Tencent/UnLua#512]
FDelegateRegistry::~FDelegateRegistry()
    {
        for (auto& Pair : CachedHandlers)
        {
            const auto ToRelease = Pair.Value.Get();
            ToRelease->Reset();**//ToRelease是空指针**
            Env->AutoObjectReference.Remove(ToRelease);
        }
        Delegates.Empty();
        FCoreUObjectDelegates::GetPostGarbageCollect().Remove(PostGarbageCollectHandle);
    }

**Comment by xuyanghuang-tencent** [comment]
是的，这里漏提交了，已经修正

**Comment by subird12345** [comment]
好了，不报错了
