### ISSUE TITLE
ULuaDelegateHandler提前Reset，导致没有执行luaL_unref(L, LUA_REGISTRYINDEX, Handler->LuaRef);

### ISSUE THREAD

**Issue by wtmsuperman** [Tencent/UnLua#516]
测试Delegate时，如果Delegate绑定的函数如果是一个闭包函数，发现他的upvalue无法被gc掉。退出后才被gc掉。

通过查代码，发现释放Handler时，从CachedHandlers中Remove后，立即执行了Reset。但是Handler去unref是通过BeginDestory的。最后执行到BeginDestory时，LuaRef已经是LUA_NOREF。
![1662453093504](https://user-images.githubusercontent.com/1977474/188586956-340b0e59-7383-4695-a830-a4a277d8f58f.png)

到这里时，LuaRef已经重置了
![1662453340739](https://user-images.githubusercontent.com/1977474/188587928-b45bddfa-33d4-424e-ab32-5edb21a95975.png)

把Reset注释掉，就可以正常gc了。

**Comment by wtmsuperman** [comment]
版本是2.2.4

**Comment by jozhn** [comment]
直接去掉Reset会导致时序问题产生崩溃，因为ULuaDelegateHandler BeginDestroy时LuaEnv可能已经销毁

![16626905728134](https://user-images.githubusercontent.com/19300336/189260876-1d80c58c-ee5a-4539-b0e5-5753ddfa146e.png)

所以OnPostGarbageCollect里面也要处理luaL_unref，最后Reset

**Comment by wtmsuperman** [comment]
看代码Env析构的时候，会delete registry。看样子是ULuaDelegateHandler拿的Registry指针已经被释放了。感觉不能根治，还是得Registry释放的时候，通知一下所有的Handler Reset。不然ULuaDelegateHandler BeginDestroy还是会用释放的Registry指针。

**Comment by xuyanghuang-tencent** [comment]
[v2.3.0](https://github.com/Tencent/UnLua/releases/tag/v2.3.0)
