### ISSUE TITLE
Actor有一个Struct的成员变量，在Lua里引用，C++释放Actor后，Lua里的引用仍然可以直接使用，不会抛异常

### ISSUE THREAD

**Issue by wtmsuperman** [Tencent/UnLua#517]
比如这样一个结构体
![1662546680470](https://user-images.githubusercontent.com/1977474/188857040-3c9eef40-68d9-4f6c-bc89-a39d43320fc4.png)

在lua里
![1662546725420](https://user-images.githubusercontent.com/1977474/188857164-2be58750-e2fa-4a00-9916-3fd4f8b0f19e.png)

输出的日志：
LogUnLua: FMyStruct: 000002D1053630C0 10.0    MyStruct
LogUnLua: FMyStruct: 000002D1053630C0 10.0    MyStruct
LogTemp: Display: MyStruct,struct is released.
LogUObjectHash: Compacting FUObjectHashTables data took   1.20ms
LogUnLua: FMyStruct: 000002D1053630C0 0.0 

这时其实是在访问一块被释放的内存。

看了一下源码，结构体成员变量是直接把指针直接压给lua用了；不同于UObject，UObject销毁后，指针会被改成Released；非UObject的指针就不会被管理了。

针对这种情况，是只能靠在Lua这边做约定吗？主动拷贝一下吗？有没有更好的办法？
目前看函数返回值是给一个拷贝，参数传过来是指针，Index也是指针。

**Comment by wtmsuperman** [comment]
后来通过禁止把一个指针存储到某个lua table里，或者是一个闭包的upvalue解决了。通过hook，检查rawset的value、闭包的upvalue是不是指针来抛异常。判断是不是指针，目前通过遍历StructMap和ScriptContainerMap，如果在这两个map则认为是指针。因为只在开发模式下启用检查，虽然慢一点，也可以接受。issue可以关闭了。

**Comment by wtmsuperman** [comment]
要是能提供一个快捷的办法，来判断userdata是不是指针就更好了。

**Comment by xuyanghuang-tencent** [comment]
hook rawset 是个不错的思路，或者可以在C++调完lua之后把StructMap里的userdata的二级指针置成nullptr/ReleasedPtr？

**Comment by ShuraLiu** [comment]
我这边的方案是这样，在非Shipping下新增一个全局弱表，Key缓存所有拷贝到Lua的Struct/Object，Value缓存从Key读到Lua端的member指针以及读取时的Lua堆栈，Key触发__gc时把仍在Lua端的member指针和读取堆栈打印出来，这样在runtime下能查到Lua端非法持有UserData成员变量的代码位置

**Comment by xuyanghuang-tencent** [comment]
[v2.3.1](https://github.com/Tencent/UnLua/releases/tag/v2.3.1)
