### ISSUE TITLE
IntelliSense is terribly slow

### ISSUE THREAD

**Issue by egorlepa** [Tencent/UnLua#524]
Auto completion for UE. is unusable. 
I wait 15 to 30 seconds every time i use it.

Using LuaBooster plugin.

With Tencent Lua plugin auto completion works fast, but it randomly stops working after a couple of minutes and i have to restart VsCode every time.

Really want to use UnLua, but these problems make it unusable for me :(

![image](https://user-images.githubusercontent.com/76429849/191987500-f48a2012-1e00-4c85-bd9c-76f8a58ce718.png)

**Comment by JEuler** [comment]
Same problem :(
