### ISSUE TITLE
有其他的code plugin插件，其intellisense未得到导出

### ISSUE THREAD

**Issue by futouyiba** [Tencent/UnLua#53]
如何才能让unlua intellisense导出其他的插件代码提示呢？

**Comment by futouyiba** [comment]
补充：code plugin安装在这个路径下：J:\UE_4.22\Engine\Plugins\Marketplace\GCFSM

**Comment by rowechien** [comment]
是整个插件的相关符号信息都没有导出吗？你先确认一下UnLuaIntelliSense.Build.cs文件中是否设置了ENABLE_INTELLISENSE=1？如果设置了，你找找Plugins\UnLua\Intermediate\IntelliSense目录下是否有UnLua这个文件夹，我本地是有的，里面也有对应的符号信息

**Comment by futouyiba** [comment]
> 是整个插件的相关符号信息都没有导出吗？你先确认一下UnLuaIntelliSense.Build.cs文件中是否设置了ENABLE_INTELLISENSE=1？如果设置了，你找找Plugins\UnLua\Intermediate\IntelliSense目录下是否有UnLua这个文件夹，我本地是有的，里面也有对应的符号信息

Hi,

> Plugins\UnLua\Intermediate\IntelliSense目录下是否有UnLua这个文件夹？
这个文件夹是有的，里面有3个lua文件，分别是：FPropertyCollector、UUnLuaInterface、UUnLuaManager。
不知我的问题是否描述清楚了：在项目当中用到了两个插件，一个是UnLua，放在了【项目目录】下的plugins里面；另一个是GCFSM，放在了引擎下的J:\UE_4.22\Engine\Plugins\Marketplace\GCFSM里面。
现在这个GCFSM的代码提示没有导出。其他的都导出了。

**Comment by rowechien** [comment]
@futouyiba 请问GCFSM这个插件是有多少个模块，每个模块都是什么类型，或者你方便的话把插件的.uplugin文件发给我看下。

**Comment by futouyiba** [comment]
> @futouyiba 请问GCFSM这个插件是有多少个模块，每个模块都是什么类型，或者你方便的话把插件的.uplugin文件发给我看下。

Sure.
`{
	"FileVersion": 3,
	"Version": 13,
	"VersionName": "1.5.7",
	"FriendlyName": "GC FSM Plugin by Gamecentric",
	"Description": "Event-driven, hierarchical Finite State Machines in blueprints",
	"Category": "Blueprints",
	"CreatedBy": "Gamecentric",
	"CreatedByURL": "http://gamecentric.com",
	"DocsURL": "http://gamecentric.com/gcfsm/",
	"MarketplaceURL": "com.epicgames.launcher://ue/marketplace/content/be0b4cb9916b4eba882cbe9dffd4fb5a",
	"SupportURL": "http://gamecentric.com/contacts/",
	"EngineVersion": "4.22.0",
	"CanContainContent": false,
	"Installed": true,
	"Modules": [
		{
			"Name": "GCFSM",
			"Type": "Runtime",
			"LoadingPhase": "PreDefault",
			"WhitelistPlatforms": [
				"Win64",
				"Win32",
				"Linux",
				"PS4",
				"XboxOne",
				"Android",
				"HTML5",
				"Mac",
				"IOS"
			]
		},
		{
			"Name": "GCFSMEditor",
			"Type": "Developer",
			"LoadingPhase": "PreDefault",
			"WhitelistPlatforms": [
				"Win64",
				"Win32",
				"Linux",
				"PS4",
				"XboxOne",
				"Android",
				"HTML5",
				"Mac",
				"IOS"
			]
		}
	]
}`

**Comment by futouyiba** [comment]
[GCFSM.zip](https://github.com/Tencent/UnLua/files/3714174/GCFSM.zip)

**Comment by rowechien** [comment]
@futouyiba 这个问题有什么进展么。。。我这里不会有这种问题，从uplugin文件来看，GCFSM这个runtime模块会被解析的，GCFSMEditor这个Developer类型模块不会被解析

**Comment by futouyiba** [comment]
> @futouyiba 这个问题有什么进展么。。。我这里不会有这种问题，从uplugin文件来看，GCFSM这个runtime模块会被解析的，GCFSMEditor这个Developer类型模块不会被解析

目前还是不能代码提示。请问有没有什么线索，可以让我排查的时候关注一下？

**Comment by rowechien** [comment]
@futouyiba 你的插件的uplugin文件中加上"EnabledByDefault": true试试吧

**Comment by futouyiba** [comment]
> @futouyiba 你按下面步骤试试：
> 
> 1. 你的插件的uplugin文件中加上"EnabledByDefault": true；
> 2. 修改一下这个插件中任意cpp文件；
> 3. 删除工程目录下的.deps文件，以UnLua的例子工程为例：D:\github\UnLua\Intermediate\Build\Win64\TPSProjectEditor\Debug\TPSProjectEditor.deps
> 4. 编译你的工程；
> 5. 查看UnLua插件的对应目录（Plugins\UnLua\Intermediate\IntelliSense）内是否有生成对应插件的符号信息。

成功了！谢谢。
