### ISSUE TITLE
添加删除事件导致蓝图无法打开

### ISSUE THREAD

**Issue by pizzama** [Tencent/UnLua#533]
测试环境ue4.27.2，unlua2.2.4。我新建了umg蓝图在里边添加了override事件并删除编译，unlua会写入空对象到childarray里导致蓝图无法打开，我之前删除的事件并没有删除。
![test](https://user-images.githubusercontent.com/39514551/194981142-f4036b45-b42b-4a13-819b-0e991bbf7879.png)

**Comment by xuyanghuang-tencent** [comment]
编译蓝图就会这样？不启动PIE是不应该有`__Overridden`的。如果启动过PIE，就需要看看退出PIE的时候 `ULuaFunction::RestoreOverrides(Class)` 为什么漏还原了这些`__Overridden`。

**Comment by xuyanghuang-tencent** [comment]
[2.3.5](https://github.com/Tencent/UnLua/releases/tag/v2.3.5)
