### ISSUE TITLE
2.2.4  UE5 打开 apple prores 插件 unlua崩溃

### ISSUE THREAD

**Issue by yudehai0204** [Tencent/UnLua#534]
这个是插件
![NX0D_}5 $K} _V~F)TKR2VQ](https://user-images.githubusercontent.com/10924643/195284255-3fabaa7d-6245-4ec3-9448-46704193398d.png)
这个是报错内容
![_T6OIJTX0`X%K_23A(3ZPGM](https://user-images.githubusercontent.com/10924643/195284221-a8fb232a-4f37-4dc0-aa8a-68b3ca0a31f9.png)

**Comment by yudehai0204** [comment]
![RP` 9OP(SM KCJIA)3@$47A](https://user-images.githubusercontent.com/10924643/195292079-8052f105-23d8-4ecb-8dd2-39d9f52d4029.png)

**Comment by xuyanghuang-tencent** [comment]
![_C_2Q2CQET3SSY8F 8Z{YU](https://user-images.githubusercontent.com/83756024/196914298-fa6240a5-43e4-44b3-a2bf-c15ee39b321f.png)

https://github.com/EpicGames/UnrealEngine/blob/4.26/Engine/Plugins/Media/AppleProResMedia/Source/AppleProResMedia/Private/AppleProResMediaModule.cpp#L42

确认是这个插件的bug，少了一行FPlatformProcess::PopDllDirectory，导致在延迟加载Lua.dll的时候找不到了

**Comment by xuyanghuang-tencent** [comment]
[v2.3.1](https://github.com/Tencent/UnLua/releases/tag/v2.3.1)
