### ISSUE TITLE
lua重写C++函数时参数为*&，lua返回nil时无法赋值其返回参数

### ISSUE THREAD

**Issue by 909185693** [Tencent/UnLua#539]
![image](https://user-images.githubusercontent.com/12391857/196600968-a76087a6-d313-484d-9b95-620ca9fa1afc.png)
![image](https://user-images.githubusercontent.com/12391857/196601731-695a6b71-9501-4b9f-9391-524753cde6e0.png)

**Comment by xuyanghuang-tencent** [comment]
[v2.3.1](https://github.com/Tencent/UnLua/releases/tag/v2.3.1)
