### ISSUE TITLE
Lua调试

### ISSUE THREAD

**Issue by kuangjin520** [Tencent/UnLua#54]
请问有Unlua的调试方案吗？在G6IDE没有发布情况下，我们有什么备选调试方案可以选择吗？能出个这方面的教程就最好了。

**Comment by rowechien** [comment]
暂时是没有的。。。但G6IDE肯定是会开放出来的。

**Comment by mdyshad0w** [comment]
可以自己编译出一个luasocket，之后放入content/script下，之后在LuaContext.cpp中的AddPackagePath这个函数下面，对照AddPackagePath这个函数写一个类似的函数，把?.dll加入到package.cpath中就可以require到luasocket的dll了。最后用LuaPanda就可以加断点调试了，我就是这么用的，挺好用的

**Comment by kuangjin520** [comment]
函数是怎么写的，能贴出来吗？基础知识比较薄弱，搞了几天了，还是没有弄好。

**Comment by mdyshad0w** [comment]
1）void FLuaContext::CreateState()函数中，在AddPackagePath(L, TCHAR_TO_UTF8(*LuaSrcPath));这个函数后面加入下面代码，
#if WITH_EDITOR
#if PLATFORM_WINDOWS
        // add new package cpath
        FString LuaSrcCPath = GLuaSrcFullPath + TEXT("?.dll");
        AddPackageCPath(L, TCHAR_TO_UTF8(*LuaSrcCPath));// 这个函数是后来自己加的，对照AddPackagePath重写的,为了能require luasocket

        // Create 'DEBUG' namespace (a Lua table)
        lua_pushboolean(L, true);
        lua_setglobal(L, "WITH_LUAIDE_DEBUG");//注册WITH_LUAIDE_DEBUG宏，在lua里用
#endif
#endif

2）：
//AddPackageCPath代码如下：
UNLUA_API void AddPackageCPath(lua_State* L, const char* cPath)
{
    if (!cPath)
    {
        UE_LOG(LogUnLua, Warning, TEXT("%s, Invalid package cpath!"), ANSI_TO_TCHAR(__FUNCTION__));
        return;
    }

    lua_getglobal(L, "package");
    lua_getfield(L, -1, "cpath");
    char FinalPath[MAX_SPRINTF];
    FCStringAnsi::Sprintf(FinalPath, "%s;%s", lua_tostring(L, -1), cPath);
    lua_pushstring(L, FinalPath);
    lua_setfield(L, -3, "cpath");
    lua_pop(L, 2);
}

3）：之后编译出luasocket的dll，将编译出的socket目录放入Content/Script下（socket目录下有core.dll）；最后在lua代码里加上如下代码：
    if WITH_LUAIDE_DEBUG then
        require("LuaPanda").start("127.0.0.1",8818)
    end
就可以用vscode调试lua代码了，需要下载LuaPanda插件

**Comment by kuangjin520** [comment]
非常感谢!编译luasocket你这边有推荐的教程链接吗？我怀疑是我编译出来的dll有问题，如果你方便的话，能把你编译的出来的文件发我一份吗？我邮箱283819133@qq.com。

LogUnLua: Warning: Lua error message: error loading module 'socket.core' from file 'E:/Workplace/Client/UnrealPro/Content/Script/socket\core.dll':
    %1 ??????Ч?? Win32 Ӧ?ó?????
是不是我编译的dll是32位？

**Comment by kuangjin520** [comment]
很感谢 mdyshad0w ，在你的指导和帮助下，问题已经解决啦。

**Comment by fdcumt** [comment]
@mdyshad0w 你好, 能把dll发我一份吗?? 1040183251@qq.com

**Comment by hxhb** [comment]
> 可以自己编译出一个luasocket，之后放入content/script下，之后在LuaContext.cpp中的AddPackagePath这个函数下面，对照AddPackagePath这个函数写一个类似的函数，把?.dll加入到package.cpath中就可以require到luasocket的dll了。最后用LuaPanda就可以加断点调试了，我就是这么用的，挺好用的

你好，我尝试了一下你说的方法，可以在VSCode中使用LuaPanda断点，但是我在编辑器开启调试的时候就crash了，异常抛在FSoftObjectPath::ToString中，你有遇到过这样的问题吗？

**Comment by hxhb** [comment]
> 很感谢 mdyshad0w ，在你的指导和帮助下，问题已经解决啦。

请问你有遇到UnLua+LuaPanda调试Crash的问题吗？

**Comment by kuangjin520** [comment]
我也会偶尔crash，没有解决。

**Comment by leecya** [comment]
> > 很感谢 mdyshad0w ，在你的指导和帮助下，问题已经解决啦。
> 
> 请问你有遇到UnLua+LuaPanda调试Crash的问题吗？

把launch.json文件中的stopOnEntry设置为false试一下， 似乎stopOnEntry进入断点太早有时资源没加载完。我这样设置后似乎没有crash了

**Comment by zhangweiiscoding** [comment]
> 很感谢 mdyshad0w ，在你的指导和帮助下，问题已经解决啦。

你好，请问可以分享一下你的经验吗，我的luasocket也编译不出64位的

**Comment by hxhb** [comment]
> > > 很感谢 mdyshad0w ，在你的指导和帮助下，问题已经解决啦。
> > 
> > 
> > 请问你有遇到UnLua+LuaPanda调试Crash的问题吗？
> 
> 把launch.json文件中的stopOnEntry设置为false试一下， 似乎stopOnEntry进入断点太早有时资源没加载完。我这样设置后似乎没有crash了

我看Luapanda的issus里也有人提到这个问题，https://github.com/Tencent/UnLua/issues/61 ，你现在使用Luapanda调试正常吗？

**Comment by coldonesongli** [comment]
> 
你是怎么解决的呢？我也是报这个错

**Comment by jinkuang-code** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
