### ISSUE TITLE
异步回调中绑定C++委托崩溃

### ISSUE THREAD

**Issue by pgf1995** [Tencent/UnLua#540]
![image](https://user-images.githubusercontent.com/30193178/196907187-8ad64115-0c8d-4ec7-9fee-90d6605d8430.png)
![image](https://user-images.githubusercontent.com/30193178/196907289-df4cf033-23a5-4aee-9ade-3c112858df22.png)

**Comment by xuyanghuang-tencent** [comment]
老版本的UnLua？

我试着在master上按以下步骤操作，没能重现：

1. 在场景里放一个Actor，蓝图变量名为MyActor
2. 重写这个场景的蓝图的ReceiveBeginPlay
3. 开始游戏

![image](https://user-images.githubusercontent.com/83756024/196950461-22c77ee1-d3dd-41f2-be7c-21cdff98bb56.png)

**Comment by pgf1995** [comment]
新版本试了没问题的。我用的是2.1.0，下载试了下2.0.0之前的版本都没有这个问题，2.0.0才开始有这个问题。
我这边更新一下版本，用最新版本的。
