### ISSUE TITLE
Unlua Memory持续上涨

### ISSUE THREAD

**Issue by HSHSir** [Tencent/UnLua#541]
使用GitHub上下载好的示例工程,版本为2.2.0(2.1.4和最新2.3.0都存在该问题)
使用stat Unlua查看统计的信息,不添加任何代码是正常的,内存不会涨,但是,添加以下代码就会发现问题,(还有其它类似这种正常代码也有这样的问题)
![image](https://user-images.githubusercontent.com/61901106/197716030-2897588d-9604-4895-8b70-ada565a90da0.png)
程序运行1.7秒时,0.81MB
![image](https://user-images.githubusercontent.com/61901106/197715927-3b68d45f-17f0-4043-b29c-c8b150698e66.png)
内存随时间增加持续上涨
![image](https://user-images.githubusercontent.com/61901106/197716198-82efd895-27d4-4910-9541-f26e7bd3184c.png)
不定时回落,但是回落的值不是最初的值
![image](https://user-images.githubusercontent.com/61901106/197716249-d4037579-ff25-4190-aa32-dba0531bc96f.png)
![image](https://user-images.githubusercontent.com/61901106/197716311-4f854561-9c44-4026-a500-8732a0256ce1.png)
下降了,估计GC清理了一波,但是并没有全部清理掉
![image](https://user-images.githubusercontent.com/61901106/197716362-eb25ac19-4592-4257-b9d5-63869745c40e.png)
程序运行576秒,使用内存41.47
![image](https://user-images.githubusercontent.com/61901106/197716475-3f64885a-da28-49a6-95b7-c18dcc5bf4ee.png)
程序运行615秒,使用内存38.76
![image](https://user-images.githubusercontent.com/61901106/197716513-fc4ef842-bc07-4c9c-b8be-52e97583b6c7.png)
暂时到这了
![image](https://user-images.githubusercontent.com/61901106/197716716-20790e6e-ff5e-4d6e-8d43-1851a67f5e28.png)
后面持续上涨,虽然中途也有回落,但是总体趋势在一直上涨

**Comment by xuyanghuang-tencent** [comment]
在函数底部加一个 `collectgarbage("collect")` 试试？

**Comment by HSHSir** [comment]
> 在函数底部加一个 试试？`collectgarbage("collect")`

手动调用lua的GC是可行的，按理GC因该由系统自动处理才对，必须由程序手动管理吗？

**Comment by HSHSir** [comment]
上传后图片看不清了,补一下图片的内容,该代码在示例工程的BP_PlayerCharacter_C.lua中

function BP_PlayerCharacter_C:ReceiveBeginPlay()
	self.Super.ReceiveBeginPlay(self)
	self.DefaultFOV = self.Camera.FieldOfView
	self.TimerHandle = UE.UKismetSystemLibrary.K2_SetTimerDelegate({self, BP_PlayerCharacter_C.FallCheck}, 1.0, true)
	local InterpFloats = self.ZoomInOut.TheTimeline.InterpFloats
	local FloatTrack = InterpFloats:GetRef(1)
	FloatTrack.InterpFunc:Bind(self, BP_PlayerCharacter_C.OnZoomInOutUpdate)

	self.BoomRot=UE.FRotator(0,0,0)
end

function BP_PlayerCharacter_C:ReceiveTick(DeltaSeconds)
	UE.UKismetSystemLibrary.PrintString(self, UE.UGameplayStatics.GetUnpausedTimeSeconds(self), true, false, UE.FLinearColor(1,0,0,1), 0)
	--UE.UKismetMathLibrary.RInterpTo(self.SpringArm.RelativeRotation,self.BoomRot,DeltaSeconds,8)
    self.SpringArm:K2_SetRelativeRotation(self.BoomRot,false,nil,false)
    self.SpringArm:K2_SetRelativeRotation(self.BoomRot,false,nil,false)
    self.SpringArm:K2_SetRelativeRotation(self.BoomRot,false,nil,false)
    self.SpringArm:K2_SetRelativeRotation(self.BoomRot,false,nil,false)
    self.SpringArm:K2_SetRelativeRotation(self.BoomRot,false,nil,false)
    self.SpringArm:K2_SetRelativeRotation(self.BoomRot,false,nil,false)
    self.SpringArm:K2_SetRelativeRotation(self.BoomRot,false,nil,false)
    self.SpringArm:K2_SetRelativeRotation(self.BoomRot,false,nil,false)
    self.SpringArm:K2_SetRelativeRotation(self.BoomRot,false,nil,false)
    self.SpringArm:K2_SetRelativeRotation(self.BoomRot,false,nil,false)
    self.SpringArm:K2_SetRelativeRotation(self.BoomRot,false,nil,false)
    self.SpringArm:K2_SetRelativeRotation(self.BoomRot,false,nil,false)
    self.SpringArm:K2_SetRelativeRotation(self.BoomRot,false,nil,false)
    self.SpringArm:K2_SetRelativeRotation(self.BoomRot,false,nil,false)
    self.SpringArm:K2_SetRelativeRotation(self.BoomRot,false,nil,false)
    self.SpringArm:K2_SetRelativeRotation(self.BoomRot,false,nil,false)
    self.SpringArm:K2_SetRelativeRotation(self.BoomRot,false,nil,false)
    self.SpringArm:K2_SetRelativeRotation(self.BoomRot,false,nil,false)
end
![Snipaste_2022-10-26_09-50-12](https://user-images.githubusercontent.com/61901106/197915697-330f5adf-c594-43a2-a3d8-618704e37c4a.png)

**Comment by laughxing** [comment]
1f0acbc8 may be a fix related to this

**Comment by xuyanghuang-tencent** [comment]
[v2.3.1](https://github.com/Tencent/UnLua/releases/tag/v2.3.1)
