### ISSUE TITLE
Variable types in function params

### ISSUE THREAD

**Issue by faseceroo** [Tencent/UnLua#545]
Functions params has no type in Lua??? so a function like this:

```
FVector ASnipplets::GetLocation(AActor *Alarm)
{
	return Alarm->GetActorLocation();
}
```

it should be something like this

```
function M:GetLocation(Alarm)
	
end
```

but, how do I call AActor->GetActorLocation() if Lua has no idea what Alarm is?

**Comment by faseceroo** [comment]
I can use

```
    ---@type AActor 
    local Alarm 
```
for local variables, and this activates the code completion for alarm. I can't find how to do the same for function params.

**Comment by xuyanghuang-tencent** [comment]
```lua
local M = {}

---comments for function
---@param AActor Alarm @comments for parameters
---@return FVector @comments for return value
function M:GetLocation(Alarm)
end
```

**Comment by faseceroo** [comment]
thanks, unfortunately ---@param does not activate code completion
![notworking](https://user-images.githubusercontent.com/93630866/199001218-4f538588-114e-4960-a0c4-685fa433da10.png)

while it works for UE namespace and when I use ---@type
![working](https://user-images.githubusercontent.com/93630866/199001376-ac1c469d-804a-4f7a-8b45-0adc9e5ade1b.png)

I'm using this vscode extension
![codecompletion](https://user-images.githubusercontent.com/93630866/199001536-72592721-d23a-4412-9832-655838e6488e.png)

I'm wondering if there's a way to activate code completion for @param working like variables with @type.

**Comment by xuyanghuang-tencent** [comment]
My fault, the name of parameter should be put first:

```lua
---comments for function
---@param Alarm AActor @comments for parameters
---@return FVector @comments for return value
function M:GetLocation(Alarm)
end
```

**Comment by faseceroo** [comment]
Perfect! Thank you!!!!
