### ISSUE TITLE
GetAllActorsOfClass() not working

### ISSUE THREAD

**Issue by faseceroo** [Tencent/UnLua#546]
```
local allActors = UE.TArray(UE.AActor)
UE4.UGameplayStatics.GetAllActorsOfClass(self:GetWorld(), UE4.UClass.Load("AActor"), allActors)
UE.UKismetSystemLibrary.PrintString(nil, tostring(allActors:Num()), true, false, UE.FLinearColor(1,1,1,1), 10)
```
AllActors always return empty after the call.

**Comment by faseceroo** [comment]
It works with custom classes for example
```
local allActors = UE.TArray(UE.AActor)
UE4.UGameplayStatics.GetAllActorsOfClass(self:GetWorld(),
UE4.UClass.Load("/Game/ThirdPersonBP/Blueprints/ThirdPersonCharacter.ThirdPersonCharacter_C"), allActors)
	UE.UKismetSystemLibrary.PrintString(nil, tostring(allActors:Num()), true, false, UE.FLinearColor(1,1,1,1), 10)
```
but not generic classes like AActor or ACharacter.

**Comment by xuyanghuang-tencent** [comment]
use `UE.XXX` for native classes

**Comment by faseceroo** [comment]
Thanks. GetAllActorsOfClass returns an empty array when requesting native classes

```
    local allActors = UE.TArray(UE.AActor)
    UE4.UGameplayStatics.GetAllActorsOfClass(self:GetWorld(), UE4.UClass.Load("AActor"), allActors)
    UE.UKismetSystemLibrary.PrintString(nil, tostring(allActors:Num()), true, false, UE.FLinearColor(1,1,1
,1), 10)
```

this example shows 0 (zero) on any level

**Comment by xuyanghuang-tencent** [comment]
local allActors = UE.TArray(**UE.AActor**)
UE.UGameplayStatics.GetAllActorsOfClass(self:GetWorld(), **UE.AActor**, allActors)
UE.UKismetSystemLibrary.PrintString(nil, tostring(allActors:Num()), true, false, UE.FLinearColor(1,1,1,1), 10)

**Comment by faseceroo** [comment]
Nice - I think I have everything I need to program in this language. I have discovered UnLua (and Lua) 3 days ago and it looks like the ideal partner  for Unreal. If I get good performance this will be heaven. Way easier and faster to design gameplay than c++ and BP. Thank you very much for for providing us this project, it is incredible!
