### ISSUE TITLE
Blueprint struct

### ISSUE THREAD

**Issue by faseceroo** [Tencent/UnLua#547]
One last question, sorry for asking so much. Can we use BP structures in Lua?
![struct](https://user-images.githubusercontent.com/93630866/199022294-7bb3ef49-adb6-41dc-bf20-147f55ee15fe.png)

I can't find a way to get intellisense to detect it. I tried to use it anyway but the below code does nothing
![code](https://user-images.githubusercontent.com/93630866/199022537-f9e2ebf2-a2f2-4703-ac94-2237fce0fe97.png)

**Comment by faseceroo** [comment]
Searching through the issues I see I should have used UE.FBPStruct() but still is not working. C++ USTRUCT's are not working for me also, or at least I don't know how to use them.

**Comment by xuyanghuang-tencent** [comment]
blueprint types should load with `UE.UClass.Load`

```lua
local BPStruct = UE.UClass.Load("/Game/Path/To/Your/Struct")
local struct = BPStruct()
struct.Text = "Hello"
```

**Comment by faseceroo** [comment]
I must be missing something very obvious but I can't print on screen struct.Text (nothing comes up)
![image](https://user-images.githubusercontent.com/93630866/199065218-2902ab7a-6e92-40d2-83ae-801868628ded.png)
 
```
function M:ReceiveBeginPlay()
	local BPStruct = UE.UClass.Load("/Game/ThirdPersonBP/Blueprints/BPStruct")
	local struct = BPStruct()
	struct.Text = "Hello"
	UE.UKismetSystemLibrary.PrintString(nil, struct.Text, true, false, UE.FLinearColor(1,1,1,1), 10)
end
```

**Comment by faseceroo** [comment]
I can't get it to work for blueprint but it works fine for C++ structs so I can declare my structs on C++.

On a side note, I can't get c++ UENUM() to work correctly. It works  fine for UE native UENUM() but I can't get the same result for a UENUM() defined by me

C++ code
```
UENUM() enum Status
{
	Stopped,
	Moving,
	Attacking,
};
```
 
Lua code
```
function M:Begin()
	-- UE Enum works ok - prints 2
	local AttachRule = UE.EAttachmentRule.SnapToTarget
	UE.UKismetSystemLibrary.PrintString(self:GetWorld(), tostring(AttachRule), true, false, UE.FLinearColor(1,1,1,1), 10)

	-- User Enum is not working - it doesn't work
	local Status = UE.Status.Moving
	UE.UKismetSystemLibrary.PrintString(self:GetWorld(), tostring(Status), true, false, UE.FLinearColor(1,1,1,1), 10)
end
```

**Comment by xuyanghuang-tencent** [comment]
According to unreal engine coding standard, an `UENUM` should named with prefix of `E`. Otherwise unlua can't identify what type it is.

**Comment by faseceroo** [comment]
Changing the name to EStatus did the trick. Thank you so much for your patience.
