### ISSUE TITLE
使用【obj list】命令，提示【LogScriptSerialization】类型的错误

### ISSUE THREAD

**Issue by Junho2009** [Tencent/UnLua#55]
UnLua版本：master，5a6f4e8。
在UnLua工程中能重现。
这个类型的log，目前在UE中只有一个，在“ScriptSerialization.h”第545行（UE 4.22.0）。
似乎都是与UFunction相关。

p.s.: 之前修复了使用“obj list”命令引发fatal错误的问题，不过由于UnLua还没发布新的release版本，我们暂时直接沿用当前master的版本了。有新release版本的计划吗？

**Comment by rowechien** [comment]
这个问题应该在398b308这个Commit里修改过了，请问是在什么配置下出的问题？

**Comment by rowechien** [comment]
另外，这个应该只是个warning吧？会影响正常逻辑吗？

**Comment by Junho2009** [comment]
> 另外，这个应该只是个warning吧？会影响正常逻辑吗？

是以错误报出来的，在UnLua示例工程里也能重现。
不影响游戏运行，命令本身也能正常输出其他的信息，不过对命令的执行结果有没有影响就暂时不能确定。

**Comment by rowechien** [comment]
@Junho2009 这个问题我自己重现过，我想398b308这个Commit应该已经搞定了这个问题。插件本身虽然今年8月份开源，但之前已经有超过1年时间多个项目的验证了，已经算是比较稳定，除非有重大修改或者增加大的特性，就用master分支的代码吧

**Comment by Junho2009** [comment]
> @Junho2009 这个问题我自己重现过，我想398b308这个Commit应该已经搞定了这个问题。插件本身虽然今年8月份开源，但之前已经有超过1年时间多个项目的验证了，已经算是比较稳定，除非有重大修改或者增加大的特性，就用master分支的代码吧

398b308 这个Commit是解决了这个问题： #46 
我是已经更新过master的代码了哈（5a6f4e8），不过仍出现本issue所描述的错误，只是并非fatal错误——输出红色的错误log。

**Comment by rowechien** [comment]
Log是不是Error: Unknown bytecode 0xFF; ignoring it ?
是的话不影响使用

**Comment by rowechien** [comment]
@Junho2009 0xFF是插件新注册的一个Opcode，做为插件也不会去修改引擎里对应的地方，所以会出现这个Log，不会影响使用的。谢谢你的反馈！
