### ISSUE TITLE
UGameplayStatics.LoadStreamLevel协程加载完触发时lua脚本加载异常

### ISSUE THREAD

**Issue by askdad** [Tencent/UnLua#551]
在lua使用UGameplayStatics.LoadStreamLevel加载关卡，加载完瞬间在该协程内require还没加载过的lua脚本会提示找不到
请问这是正常的么
之前用2.1版本，一样的逻辑没有问题。升级2.3后出现的

又做了个测试，在lua协程内require一个新脚本会加载不到，协助会直接结束掉，没有弹异常log

**Comment by yc1011** [comment]
同出现

**Comment by xuyanghuang-tencent** [comment]
[v2.3.3](https://github.com/Tencent/UnLua/releases/tag/v2.3.3)
