### ISSUE TITLE
用PlayerController Possess新的角色时，新角色上的InputComponent无法正常ReplaceInputs，导致新角色无法响应input输入

### ISSUE THREAD

**Issue by 610789338** [Tencent/UnLua#553]
bool FLuaEnv::TryReplaceInputs(UObject* Object)
{
    ...
    // 此时服务器的RemoteRole已经是ROLE_AutonomousProxy，但还未同步到客户端，导致这个判断不过
    if (!Actor || Actor->GetLocalRole() < ROLE_AutonomousProxy)
        return false;
    ...
}

**Comment by 610789338** [comment]
详细介绍可参考Tencent内网km：
https://km.woa.com/articles/show/562766?ts=1667810607

**Comment by xuyanghuang-tencent** [comment]
[v2.3.1](https://github.com/Tencent/UnLua/releases/tag/v2.3.1)
