### ISSUE TITLE
LogUnLua: Warning: UObject instance is still alive, but lua instance is dead... Module Name (MyGameInstance_C)

### ISSUE THREAD

**Issue by steaaaaaaaam** [Tencent/UnLua#56]
创建了GameInstance的蓝图脚本下面生成了Lua,切换关卡的时候发现GameInstance下的lua脚本被释放,无法正常访问

**Comment by rowechien** [comment]
按log的提示，就是GameInstance在Lua中的实例已经被GC了，但是GameInstance肯定还在，所以在重新绑定时出了问题，这种情况下你可以试试在Lua中为对应的实例保留一份引用

**Comment by steaaaaaaaam** [comment]
我用提供的demo创建GameInstance也有同样的问题,我现在暂时把ClearLoadedModule这个方法给注释掉了.希望下个版本能够解决这个问题
