### ISSUE TITLE
UObject类动态绑定Lua后，其他实例无法绑定其他的Lua文件

### ISSUE THREAD

**Issue by cymhellfire** [Tencent/UnLua#573]
我在自己的项目中实验了动态绑定的方法，本意是希望通过动态绑定来实现同一UObject类的不同实例绑定不同的Lua脚本。但实际操作下来发现，第一次创建实例时绑定的Lua脚本地址，将会持续影响后续创建的实例。
例如：我创建了一个UMyObject类，第一次实例化时，绑定了脚本Test1.lua。第二次再次创建实例时，我传入了Test2.lua，但发现执行的脚本还是Test1.lua。
请问这个行为是符合设计的吗？如果不符合设计会在后续更新中进行修改吗？谢谢。

**Comment by xuyanghuang-tencent** [comment]
Lua的绑定/覆写机制是基于`UClass`的，可以理解成一个类型对应一个Lua模块，无论静态绑定还是动态绑定。

“同一UObject类的不同实例绑定不同的Lua脚本”这样的需求，可以通过策略模式来包装一下，统一在Lua里做转发。

**Comment by cymhellfire** [comment]
> Lua的绑定/覆写机制是基于`UClass`的，可以理解成一个类型对应一个Lua模块，无论静态绑定还是动态绑定。
> 
> “同一UObject类的不同实例绑定不同的Lua脚本”这样的需求，可以通过策略模式来包装一下，统一在Lua里做转发。

感谢回复，这边把需要做实例绑定的数据封装成另外一个table作为参数满足了需求
