### ISSUE TITLE
lua语法错误，启动游戏导致crash

### ISSUE THREAD

**Issue by 610789338** [Tencent/UnLua#574]
Development模式下启动游戏，若lua脚本有语法错误，那么会crash在luaL_error里面
<img width="727" alt="企业微信截图_16716038022911" src="https://user-images.githubusercontent.com/37659937/208835973-bb3ffecc-fba9-4b69-92e8-082636f5679c.png">

**Comment by lobe830** [comment]
我最近遇到了类似的错误，运行环境如下：
UE5.1
unlua master分支
操作：在官方例子的lua代码中，添加一段错误代码（比如函数体外输出一段文字或者函数体加一行文字），之后点击UEEditor的运行按钮
结果：UE编辑器闪退，错误堆栈定位到LuaEnv.cpp, 行数：569行
期待：不能因为lua代码出现错误，一直崩UE编辑器，这样开发效率太低了，希望问题尽快得到修复或者告知一下哪个unlua版本是可以正常运行不闪退的。

**Comment by xiejiangzhi** [comment]
![image](https://user-images.githubusercontent.com/1396853/209783756-90da9bb6-698d-4299-81ac-d3cf97ef7b76.png)

顺便丢个错误栈

就是蓝图绑定的 lua 文件，在加载时，如果出现语法错误（当前文件名是加载时require 的其它文件）。那么编辑器就会 crash.

**Comment by i0gan** [comment]
-- 采用这种声明函数方式，启动UE4会直接崩溃
-- 测试环境：Windows UE4 4.27.2 
function() BugFunc()

end

**Comment by xuyanghuang-tencent** [comment]
[v2.3.3](https://github.com/Tencent/UnLua/releases/tag/v2.3.3)
