### ISSUE TITLE
Unlua最新版本打包后无法使用蓝图枚举

### ISSUE THREAD

**Issue by heartunderblade85817155** [Tencent/UnLua#585]
1、BUG触发方式：声明任意蓝图枚举（例如A.a1,A.a2,A.a3）并在lua中使用，打包项目后，枚举值无法使用，枚举值为nil（A.a1、A.a2、A.a3皆为nil）
2、BUG原因：最新的Unlua不在lua层自动引用加载的资源，导致蓝图枚举加载后又被GC。即使尝试在lua层使用UnLua.Ref( UE.UObject.Load("xxxxxx"))手动加载后并添加引用，也是无效的，会提示Error: invalid UObject。
3、个人临时解决方案：在Object载入后直接添加引用，默认认为枚举资源一般情况下不需要卸载。
UnLua::FLuaEnv::FindEnvChecked(L).GetEnumRegistry()->Register(Enum);
UnLua::FLuaEnv::FindEnvChecked(L).GetObjectRegistry()->AddManualRef(L, Object);
int32 Type = luaL_getmetatable(L, TCHAR_TO_UTF8(*UnLua::LowLevel::GetMetatableName(Enum)));
check(Type == LUA_TTABLE);

**Comment by xuyanghuang-tencent** [comment]
[v2.3.3](https://github.com/Tencent/UnLua/releases/tag/v2.3.3)
