### ISSUE TITLE
unlua如何调用蓝图自带的方法

### ISSUE THREAD

**Issue by icefoxhz** [Tencent/UnLua#587]
通过重写蓝图方法是可以调用， 但是unlua如何调用蓝图自带的方法呢？   比如，我要调用蓝图的 SetActorHiddenInGame 方法

**Comment by xuyanghuang-tencent** [comment]
`SetActorHiddenInGame `是`BlueprintCallable`的`UFUNCTION`，所以可以直接在lua里调用，比如：
```lua
self:SetActorHiddenInGame(true)
YourActor:SetActorHiddenInGame(true)
```

**Comment by icefoxhz** [comment]
感谢

**Comment by icefoxhz** [comment]
![image](https://user-images.githubusercontent.com/35057092/215426064-3e14aeeb-09a2-4f04-958c-c5735442e298.png)

这个调用的参数设置有什么问题吗？  self 和 蓝图的self 是对应的吗？
local pmc = UE.UK2Node_AddComponent.AddProceduralMeshComponent(self)

这样写全貌似还是不对
local pmc = UE.UK2Node_AddComponent.AddProceduralMeshComponent(self, false, transform)
