### ISSUE TITLE
unlua调用蓝图的参数问题

### ISSUE THREAD

**Issue by icefoxhz** [Tencent/UnLua#588]
![image](https://user-images.githubusercontent.com/35057092/215423464-ad7b8e60-5d49-47e9-b73b-d1920a1344d9.png)

这个调用的参数设置有什么问题吗？ 还是说必须写全参数？ self 和 蓝图的self 是对应的吗？
local pmc = UE.UK2Node_AddComponent.AddProceduralMeshComponent(self)

**Comment by xuyanghuang-tencent** [comment]
蓝图节点只是编辑器下的表现，和实际执行的代码并不是一一对应的，可以从注释里的`UK2Node_AddComponent`这个C++类里看节点实际做的事情。看代码这个节点应该调用的是`Actor::AddComponent`这个函数。

另外有个小技巧可以参考下：选中蓝图节点，`Ctrl+C`复制，粘贴到文本编辑器中，就一般就能推断出它实际调用的函数和参数。

**Comment by icefoxhz** [comment]
非常感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月30日(星期一) 下午4:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tencent/UnLua] unlua调用蓝图的参数问题 (Issue #588)





 
蓝图节点只是编辑器下的表现，和实际执行的代码并不是一一对应的，可以从注释里的UK2Node_AddComponent这个C++类里看节点实际做的事情。看代码这个节点应该调用的是Actor::AddComponent这个函数。
 
另外有个小技巧可以参考下：选中蓝图节点，Ctrl+C复制，粘贴到文本编辑器中，就一般就能推断出它实际调用的函数和参数。
