### ISSUE TITLE
想要给EditorUtilityWidget绑定Lua该怎么做?

### ISSUE THREAD

**Issue by Mr-Gu666** [Tencent/UnLua#589]
尝试了在 预绑定类型列表 中添加了 EditorUtilityWidget 类,但是并没有效果.
这种类型现在还无法绑定lua吗?

**Comment by xuyanghuang-tencent** [comment]
`EditorUtilityWidget`是编辑器环境下的类型，目前UnLua 2.3 版本只工作在PIE游戏启动后的环境，退出时就没有Lua环境了。

可以使用最新的[2.4.0](https://github.com/Tencent/UnLua/releases/tag/v2.4.0)版本来做类似的编辑器扩展功能，不过目前还是beta

**Comment by Mr-Gu666** [comment]
谢谢
