### ISSUE TITLE
重写ActorComponent组件的RPC失败，重写PlayerController的RPC成功。这是UnLua内部限制了吗？

### ISSUE THREAD

**Issue by lvpengfeifei** [Tencent/UnLua#59]

**Comment by lvpengfeifei** [comment]
ActorCompoent里面的RPC重写不需要加RPC，就重写成功了

**Comment by lvpengfeifei** [comment]
我看了一下插件代码，是只支持Actor的远程调用/重写，这样做是有什么特殊原因吗？UE4的蓝图是都支持的，如果组件是挂载目标Actor上面的。

**Comment by rowechien** [comment]
这个问题我会调试一下

**Comment by futouyiba** [comment]
请问有新的进展吗？

**Comment by lvpengfeifei** [comment]
我们自己项目改了这块



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: futouyiba <notifications@github.com&gt;
发送时间: 2020年2月27日 10:51
收件人: Tencent/UnLua <UnLua@noreply.github.com&gt;
抄送: lvpengfeifei <354506360@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Tencent/UnLua] 重写ActorComponent组件的RPC失败，重写PlayerController的RPC成功。这是UnLua内部限制了吗？ (#59)




请问有新的进展吗？

**Comment by rowechien** [comment]
@lvpengfeifei fixed in [fbd1158 ](https://github.com/Tencent/UnLua/commit/c42033bf4a74b267f07a97bc8e1afbd40ffaa027).
