### ISSUE TITLE
关于切场景不会销毁的对象，怎么保证它对应的Lua table不被销毁呢

### ISSUE THREAD

**Issue by dotdotsp** [Tencent/UnLua#60]
游戏中有一些始终存在的对象，切换场景的时候不会销毁，但是扩展的lua却会在LoadMap的时候执行Cleanup被清理掉，这个怎么处理呢

**Comment by dotdotsp** [comment]
如果想在Lua为对应的实例保留一份引用的话，怎么才能创建一个Lua的全局对象呢？还有就是说明中C++调用lua函数UnLua::Call或者UnLua::CallTableFunc能给出一个具体的示例么？

**Comment by fdcumt** [comment]
问题1: 全局变量对应的lua table在loadMap时候会销毁.
原因: 没有在lua中对其进行引用, lua gc时候发现没有任何对象持有它, 就释放掉了.
解决方法: 在lua建立一个全局变量, 在创建时候赋值一下就行了 
例如: G_GameInstance = self;

**Comment by eonelv** [comment]
> 还有就是说明中C++调用lua函数UnLua::Call或者UnLua::CallTableFunc能给出一个具体的示例么？ 

这个问题也一直困扰着我，  在C++中调用之后，代码编不过了

**Comment by dotdotsp** [comment]
> > 还有就是说明中C++调用lua函数UnLua::Call或者UnLua::CallTableFunc能给出一个具体的示例么？
> 
> 这个问题也一直困扰着我， 在C++中调用之后，代码编不过了

我后来的办法
lua_State* L = UnLua::GetState();
UnLua::RunFile(L, “Test.lua”);
UnLua::Call(L, LuaTest);

//  Test.lua
function LuaTest()
end

如果你的Test.lua已经被加载，则不需要RunFile

**Comment by dotdotsp** [comment]
> 楼主留个联系方式或者加QQ：708888157
> 请教下怎么实现的， 我在自己的代码中动用UnLua::Call(L, “LuaTest”); 就编译不过。 出现一堆的错误
> 大致就是无法解析的外部符号lua_type
> 无法解析的外部符号lua_settop等

是不是你工程的build.cs里没有引入lua?
PrivateDependencyModuleNames中增加“Lua”

**Comment by lvpengfeifei** [comment]
> 问题1: 全局变量对应的lua table在loadMap时候会销毁.
> 原因: 没有在lua中对其进行引用, lua gc时候发现没有任何对象持有它, 就释放掉了.
> 解决方法: 在lua建立一个全局变量, 在创建时候赋值一下就行了
> 例如: G_GameInstance = self;

不对啊 在UnluaManager::Cleanup()的时候如果有引用就销毁 没引用才没被销毁。。

**Comment by fdcumt** [comment]
> > 问题1: 全局变量对应的lua table在loadMap时候会销毁.
> > 原因: 没有在lua中对其进行引用, lua gc时候发现没有任何对象持有它, 就释放掉了.
> > 解决方法: 在lua建立一个全局变量, 在创建时候赋值一下就行了
> > 例如: G_GameInstance = self;
> 
> 不对啊 在UnluaManager::Cleanup()的时候如果有引用就销毁 没引用才没被销毁。。

有引用怎么会销毁呢??? 有引用就不会被gc掉. 我现在就是这么用的, 没问题. 
这里的引用是指在lua中有对象持有它.

**Comment by rowechien** [comment]
这个问题，fdcumt同学已经回答了。相反，如果要强制删除某个绑定的UObject，可以调用它的Destroy接口，用法可以参考[#123](https://github.com/Tencent/UnLua/issues/123)
