### ISSUE TITLE
UE5 UHT 的兼容性问题

### ISSUE THREAD

**Issue by GotGimhong** [Tencent/UnLua#600]
目前使用 UE5.1 编译 UnLua 时会出现以下提示：

```
DEPRECATED: C++ UHT being used because 'UnLuaTestSuite' does not have a C# version. C++ UHT has been deprecated and will be removed in 5.2
DEPRECATED: C++ UHT being used because 'UnLua' does not have a C# version. C++ UHT has been deprecated and will be removed in 5.2
```

看起来是因为 UE5 改用了 C# 版本的 UHT，而当前的 UnLua 还不支持使用 C# 版本的 UHT，使得引擎仍然使用 C++ 版本的 UHT。请问这个问题需要怎么解决呢？

如果只是开发一个简单的工程，使用 C++ 版本的 UHT 也没什么问题。不过由于我们的项目对 UHT 做了定制修改，如果仍然使用 C++ 版本的 UHT 就会使得我们的定制修改无法生效了。

**Comment by GotGimhong** [comment]
我们发现 UnLua 插件的警告源于 UnLuaDefaultParamCollector 模块，需要在编译 UHT 时启动，导出 DefaultParamCollection.inl。于是我们写了一个 C# 版本的 UnLuaDefaultParamCollector 模块，在 2.3.3 和 2.4.0 中测试过，都顺利去除了 UnLua 插件的编译警告。

不过，UnLuaTestSuite 插件的警告仍然存在。我们发现 UnLuaTestSuite 模块启动和关闭时，并没有做什么事情（`FUnLuaTestSuite` 的 `StartupModule` 和 `ShutdownModule` 函数是空的），所以就想请教一下，UnLuaTestSuite 插件的 `CanBeUsedWithUnrealHeaderTool` 设置为 true 的目的。

如果 UnLuaTestSuite 插件不需要和 UHT 关联，那么理论上我们就解决了兼容性问题，也请你们评估下是否需要我们提个 PR🤝。

**Comment by xuyanghuang-tencent** [comment]
`UnLuaTestSuite `是UnLua自己的单元测试和回归测试用例，正式的游戏项目是用不到这个的，欢迎PR到develop分支🤝

**Comment by GotGimhong** [comment]
> `UnLuaTestSuite `是UnLua自己的单元测试和回归测试用例，正式的游戏项目是用不到这个的，欢迎PR到develop分支🤝

好的明白🤝，已经提交 PR #607  到 develop 分支了，具体说明请见 README.md。

**Comment by xuyanghuang-tencent** [comment]
[2.3.5](https://github.com/Tencent/UnLua/releases/tag/v2.3.5)
