### ISSUE TITLE
这里类型错了

### ISSUE THREAD

**Issue by jokinqin** [Tencent/UnLua#608]
![image](https://user-images.githubusercontent.com/20416083/227824847-29dfd30c-3a6c-49d9-8dff-25876ec8d023.png)

![image](https://user-images.githubusercontent.com/20416083/227824766-bb484d10-ad82-4570-bcda-219b2fba105b.png)

**Comment by xuyanghuang-tencent** [comment]
的确，方便提个PR？

**Comment by xuyanghuang-tencent** [comment]
[2.3.5](https://github.com/Tencent/UnLua/releases/tag/v2.3.5)
