### ISSUE TITLE
有Unlua+LuaPanda的调试方案吗？

### ISSUE THREAD

**Issue by hxhb** [Tencent/UnLua#61]
RT，目前不能调试有点麻烦...

**Comment by hxhb** [comment]
我使用https://github.com/Tencent/UnLua/issues/54 中的方法在VSCode启动LuaPanda listening时 在编辑器启动游戏会crash。

**Comment by lvpengfeifei** [comment]
@hxhb 请问luaPanda可以智能提示 代码补全吗

**Comment by hxhb** [comment]
> @hxhb 请问luaPanda可以智能提示 代码补全吗

我使用的是UnLua它有一个UnLuaIntelliSense的模块可以为UE的代码导出Lua符号，然后使用emmyLua就可以代码提示了。

**Comment by lvpengfeifei** [comment]
emmyLua是个VsCode插件吧 我也用UnLuaIntelliSense导出了Lua符号 可是还是没智能提示 官网给的例子是有部分有提示的

**Comment by hxhb** [comment]
> emmyLua是个VsCode插件吧 我也用UnLuaIntelliSense导出了Lua符号 可是还是没智能提示 官网给的例子是有部分有提示的

你要把Plugins/UnLua/Intermediate/InteliSence这个目录拖到VSCode的窗口里才可以。

**Comment by lvpengfeifei** [comment]
这就去试试，感谢！

**Comment by hxhb** [comment]
> 这就去试试，感谢！

你试过LuaPanda调试Unlua的项目吗？

**Comment by lvpengfeifei** [comment]
发自我的iPhone


------------------ 原始邮件 ------------------
发件人: imzlp <notifications@github.com&gt;
发送时间: 2019年10月24日 14:00
收件人: Tencent/UnLua <UnLua@noreply.github.com&gt;
抄送: lvpengfeifei <354506360@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[Tencent/UnLua] 有Unlua+LuaPanda的调试方案吗？ (#61)



 
emmyLua是个VsCode插件吧 我也用UnLuaIntelliSense导出了Lua符号 可是还是没智能提示 官网给的例子是有部分有提示的
  
你要把Plugins/UnLua/Intermediate/InteliSence这个目录拖到VSCode的窗口里才可以。

**Comment by hxhb** [comment]
> 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: imzlp <notifications@github.com&gt; 发送时间: 2019年10月24日 14:00 收件人: Tencent/UnLua <UnLua@noreply.github.com&gt; 抄送: lvpengfeifei <354506360@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[Tencent/UnLua] 有Unlua+LuaPanda的调试方案吗？ (#61) emmyLua是个VsCode插件吧 我也用UnLuaIntelliSense导出了Lua符号 可是还是没智能提示 官网给的例子是有部分有提示的 你要把Plugins/UnLua/Intermediate/InteliSence这个目录拖到VSCode的窗口里才可以。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

？

**Comment by alexump** [comment]
按照 #54 的办法是可以调试的，crash的问题是因为一些系统变量的tostring没有做好。
在lua中敲 tostring(UE4.FVector) ，直接运行，ue也会挂掉。
希望能早点修复呀，demo中有好多变量都有这个问题

**Comment by hxhb** [comment]
> 按照 #54 的办法是可以调试的，crash的问题是因为一些系统变量的tostring没有做好。
> 在lua中敲 tostring(UE4.FVector) ，直接运行，ue也会挂掉。
> 希望能早点修复呀，demo中有好多变量都有这个问题

你有暂时的解决方案吗？

**Comment by stuartwang** [comment]
https://github.com/Tencent/LuaPanda/issues/41
试一下这个哈，目前的解决方案

**Comment by lzxcs** [comment]
刚才找到crash的问题这个commit解决了~https://github.com/Tencent/UnLua/commit/cea109c457be2f517bf22cbc6f029b685cf9c40e

**Comment by hxhb** [comment]
> 刚才找到crash的问题这个commit解决了~[cea109c](https://github.com/Tencent/UnLua/commit/cea109c457be2f517bf22cbc6f029b685cf9c40e)

嗯，我也已经更新了。

**Comment by lzxcs** [comment]
刚才调试又遇到了个问题，用LuaPanda调试，然后不能查看TArry和TMap的值，请问你遇到过吗？@hxhb 
一查看就触发死循环，__index' chain too long; possible loop
