### ISSUE TITLE
请问 UObject 和 LuaEnv 是如何关联的呢？

### ISSUE THREAD

**Issue by GotGimhong** [Tencent/UnLua#611]
根据 `ULuaEnvLocator` 类的实现，它应该是用来关联 UObject 和 LuaEnv 的，不过在 `ULuaEnvLocator::Locate` 函数中，`Object` 参数并没有引用，也就是说无论是什么样的 UObject，都会指向一个默认的 LuaEnv。
```c++
UnLua::FLuaEnv* ULuaEnvLocator::Locate(const UObject* Object)
{
    if (!Env)
    {
        Env = MakeShared<UnLua::FLuaEnv, ESPMode::ThreadSafe>();
        Env->Start();
    }
    return Env.Get();
}
```

我们留意到了 `ULuaEnvLocator_ByGameInstance` 这个类，它是通过 GameInstance 来让 UObject 和 LuaEnv 建立关联的，不过它没有被显式的引用。我们提出这个问题是因为我们打算使用多虚拟机机制，需要确定一个 UObject 所在的 Lua 虚拟机。请问 `ULuaEnvLocator` 和 `ULuaEnvLocator_ByGameInstance` 类是不是分别为单虚拟机和多虚拟机两种情况所准备的呢？

**Comment by GotGimhong** [comment]
说到多虚拟机，我们还有一个困惑。我们留意到 `FClassRegistry` 和 `FEnumRegistry` 类的反注册是针对全局所有 Lua 虚拟机的。
```c++
// ClassRegistry.cpp
bool FClassRegistry::StaticUnregister(const UObjectBase* Type)
{
    FClassDesc* ClassDesc;
    if (!Classes.RemoveAndCopyValue((UStruct*)Type, ClassDesc))
        return false;
    ClassDesc->UnLoad();
    for (auto Pair : FLuaEnv::AllEnvs)
    {
        auto Registry = Pair.Value->GetClassRegistry();
        Registry->Unregister(ClassDesc);
    }
    return true;
}
```
```c++
// EnumRegistry.cpp
bool FEnumRegistry::StaticUnregister(const UObjectBase* Enum)
{
    FEnumDesc* EnumDesc;
    if (!Enums.RemoveAndCopyValue((UEnum*)Enum, EnumDesc))
        return false;
    EnumDesc->UnLoad();
    return true;
}
```

那么，如果想要只对某一个 Lua 虚拟机执行清理的话，请问要怎么做呢？

**Comment by xuyanghuang-tencent** [comment]
> 根据 `ULuaEnvLocator` 类的实现，它应该是用来关联 UObject 和 LuaEnv 的，不过在 `ULuaEnvLocator::Locate` 函数中，`Object` 参数并没有引用，也就是说无论是什么样的 UObject，都会指向一个默认的 LuaEnv。
> 
> ```c++
> UnLua::FLuaEnv* ULuaEnvLocator::Locate(const UObject* Object)
> {
>     if (!Env)
>     {
>         Env = MakeShared<UnLua::FLuaEnv, ESPMode::ThreadSafe>();
>         Env->Start();
>     }
>     return Env.Get();
> }
> ```
> 
> 我们留意到了 `ULuaEnvLocator_ByGameInstance` 这个类，它是通过 GameInstance 来让 UObject 和 LuaEnv 建立关联的，不过它没有被显式的引用。我们提出这个问题是因为我们打算使用多虚拟机机制，需要确定一个 UObject 所在的 Lua 虚拟机。请问 `ULuaEnvLocator` 和 `ULuaEnvLocator_ByGameInstance` 类是不是分别为单虚拟机和多虚拟机两种情况所准备的呢？

是的，参考[lua环境分配器](https://github.com/Tencent/UnLua/blob/master/Docs/CN/Settings.md#lua%E7%8E%AF%E5%A2%83%E5%88%86%E9%85%8D%E5%99%A8)

**Comment by xuyanghuang-tencent** [comment]
> 说到多虚拟机，我们还有一个困惑。我们留意到 `FClassRegistry` 和 `FEnumRegistry` 类的反注册是针对全局所有 Lua 虚拟机的。
> 
> ```c++
> // ClassRegistry.cpp
> bool FClassRegistry::StaticUnregister(const UObjectBase* Type)
> {
>     FClassDesc* ClassDesc;
>     if (!Classes.RemoveAndCopyValue((UStruct*)Type, ClassDesc))
>         return false;
>     ClassDesc->UnLoad();
>     for (auto Pair : FLuaEnv::AllEnvs)
>     {
>         auto Registry = Pair.Value->GetClassRegistry();
>         Registry->Unregister(ClassDesc);
>     }
>     return true;
> }
> ```
> 
> ```c++
> // EnumRegistry.cpp
> bool FEnumRegistry::StaticUnregister(const UObjectBase* Enum)
> {
>     FEnumDesc* EnumDesc;
>     if (!Enums.RemoveAndCopyValue((UEnum*)Enum, EnumDesc))
>         return false;
>     EnumDesc->UnLoad();
>     return true;
> }
> ```
> 
> 那么，如果想要只对某一个 Lua 虚拟机执行清理的话，请问要怎么做呢？

原来考虑到类型信息没有必要单独卸载，就做成静态共享了，后面版本会把这个拆出来

**Comment by GotGimhong** [comment]
好的，以上明白了，谢谢解答~
