### ISSUE TITLE
UI蓝图绑定的unlua 在函数里调用，蓝图暴露的属性偶现拿不到，报错导致异常

### ISSUE THREAD

**Issue by yangguodang0502** [Tencent/UnLua#613]
![image](https://user-images.githubusercontent.com/12682429/231984821-d27405da-6707-4791-bccf-8a998cf52431.png)
![image](https://user-images.githubusercontent.com/12682429/231984877-0da864cb-40cc-4598-80e1-33052cf6bce5.png)
![image](https://user-images.githubusercontent.com/12682429/231984946-b45ef7b9-122c-4dd0-afe4-95c39c78182e.png)
UE里面 没有看到过 只在手机上出现
![image](https://user-images.githubusercontent.com/12682429/231985183-fe264c4b-0f5f-4863-8c9b-cfa4e32e31ed.png)
界面也会显示出来 只不过 因为报错 有些显示异常

**Comment by Carl92** [comment]
我们项目也有这个问题，日志显示绑定的PropertyPtr 为空
![image](https://user-images.githubusercontent.com/24953607/232443331-2786eef5-a0c3-4569-bb24-ad2a7dd5f1fd.png)
![image](https://user-images.githubusercontent.com/24953607/232443430-b993a697-a7dd-4f33-8616-8c7b182263c3.png)

**Comment by yangguodang0502** [comment]
已找到问题，跟：修复PushMetatable时会使用旧的metatable的问题 #515 一样的问题

**Comment by jozhn** [comment]
这个问题还是存在的，没有彻底解决，有其他情况会导致用了错误的metatable

**Comment by jozhn** [comment]
https://github.com/Tencent/UnLua/pull/662
