### ISSUE TITLE
lua访问蓝图容器或结构体变量偶现类型错误崩溃或Inner非Valid

### ISSUE THREAD

**Issue by jozhn** [Tencent/UnLua#618]
比如频繁创建销毁一个UI蓝图，蓝图中PreConstruct函数给蓝图变量赋值，Lua中在Construct访问，会出现变量非Valid的情况
![image](https://github.com/Tencent/UnLua/assets/19300336/b8b67efb-b532-46e5-9baf-e0bd31c29361)

**Comment by aleverys** [comment]
unlua缓存了一个容器指针到lua的userdata的map 如果容器被销毁后在 在原来的内存上重建一个新的容器 但是element的type不同 就会出现问题

**Comment by aleverys** [comment]
一个可行的解决方法是在LuaCore.cpp的CacheScritptContainer函数里面做一个inner type的类型判断 类型就新建一个，不走缓存

**Comment by jozhn** [comment]
> unlua缓存了一个容器指针到lua的userdata的map 如果容器被销毁后在 在原来的内存上重建一个新的容器 但是element的type不同 就会出现问题

没缓存也会这样，不是那个缓存的问题

**Comment by xuyanghuang-tencent** [comment]
[2.3.5](https://github.com/Tencent/UnLua/releases/tag/v2.3.5)
