### ISSUE TITLE
-game运行时会出现蓝图创建后recompile导致覆写被清空的情况

### ISSUE THREAD

**Issue by jozhn** [Tencent/UnLua#619]
绑定是在蓝图create时触发的，但是-game运行编辑器时会出现蓝图创建后recompile，导致覆写被清空。

需要监听蓝图recompile事件，清理绑定信息。
```[tasklist]
### Tasks
```

**Comment by aleverys** [comment]
蓝图重编译是大坑 不懂unlua为什么一直不修

**Comment by xuyanghuang-tencent** [comment]
[v2.3.6](https://github.com/Tencent/UnLua/releases/tag/v2.3.6)
