### ISSUE TITLE
导出USceneComponent中函数GetCollisionObjectType报错

### ISSUE THREAD

**Issue by fdcumt** [Tencent/UnLua#62]
BEGIN_EXPORT_REFLECTED_CLASS(USceneComponent)
ADD_FUNCTION(GetCollisionObjectType)
END_EXPORT_CLASS()
IMPLEMENT_EXPORTED_CLASS(USceneComponent)

1>d:\github\unlua\plugins\unlua\source\unlua\public\UnLuaTemplate.h(126): error C2838: “StaticStruct”: 成员声明中的限定名称非法
1>  d:\github\unlua\plugins\unlua\source\unlua\public\UnLuaTemplate.h(126): note: 编译 类 模板 成员函数 "UScriptStruct *UnLua::TScriptStructTraits<T>::Get(void)" 时

**Comment by fdcumt** [comment]
添加DEFINE_TYPE(ECollisionChannel)后解决, 
有没有把UENUM(BlueprintType)都导出的方法?

**Comment by rowechien** [comment]
@fdcumt 呃，这个真没有。。。事实上也不是所有的都需要导出，按需吧
