### ISSUE TITLE
请问如何在UnLua重写特殊参数的BlueprintEvent

### ISSUE THREAD

**Issue by thecrydream** [Tencent/UnLua#63]
例如在UserWidget类中的OnPaint函数，该函数在c++中声明如下：
UFUNCTION(BlueprintImplementableEvent, BlueprintCosmetic, Category="User Interface | Painting")
void OnPaint(UPARAM(ref) FPaintContext& Context) const;
我按照文档中的方法在Lua中重写了OnPaint，但是重写的逻辑不会被执行。
我应该在Lua中如何重写这类的BlueprintEvent？

**Comment by lvpengfeifei** [comment]
去掉关键字Const 试试

**Comment by thecrydream** [comment]
> 去掉关键字Const 试试

这个是引擎的代码，不再万不得已的情况下我们不会考虑修改引擎代码的

**Comment by lvpengfeifei** [comment]
看一下管官网的文档，C++类要Create一个蓝图类，蓝图类实现LuaInterface。。。最后在对应的lua文件里面直接重写标志有UFUNCTION的函数

**Comment by thecrydream** [comment]
> 看一下管官网的文档，C++类要Create一个蓝图类，蓝图类实现LuaInterface。。。最后在对应的lua文件里面直接重写标志有UFUNCTION的函数

正如正文所说的，重写是按照文档提供的方法操作的
