### ISSUE TITLE
ue5.2.1 xcode15 beta 3error

### ISSUE THREAD

**Issue by meilaopo** [Tencent/UnLua#631]
Showing All Messages
/Users/admin/Documents/Code/UnLua/Plugins/UnLuaTestSuite/Source/UnLuaTestSuite/Private/Specs/UnLuaEnum.spec.cpp:68:33: temporary whose address is used as value of local variable 'Actual' will be destroyed at the end of the full-expression [-Werror,-Wdangling]

fix:
change    const auto Actual = UTF8_TO_TCHAR(lua_tostring(L, -1));
to             const FString Actual = UTF8_TO_TCHAR(lua_tostring(L, -1));

**Comment by xuyanghuang-tencent** [comment]
[v2.3.6](https://github.com/Tencent/UnLua/releases/tag/v2.3.6)
