### ISSUE TITLE
怎么把组件的事件监听写到lua里

### ISSUE THREAD

**Issue by qinweishuai** [Tencent/UnLua#64]
譬如在蓝图里给一个actor增加一个box_collision的组件，在蓝图里点击这个box可以实现监听overlap等事件，如果想把这些监听的实现放到lua里可以做到么？

**Comment by qinweishuai** [comment]
知道了，参考`BP_AICharacter_C:ReceiveBeginPlay`这个里面的写法

**Comment by rowechien** [comment]
@qinweishuai 抱歉因为这段时间忙没能及时回复，其实插件的很多用法在这个示例工程里都有体现。
