### ISSUE TITLE
DS单进程模式下，蓝图Recompile导致UClass的FuncMap被清空，导致没有调用到LuaFunction

### ISSUE THREAD

**Issue by 610789338** [Tencent/UnLua#644]
已经和xuyanghuang沟通过了，详细描述，直接看内网这篇KM吧：
https://km.woa.com/group/29321/articles/show/551987?ts=1694692817

**Comment by jozhn** [comment]
不需要ds下，-game运行就会recompile清空funcmap，在recompile的事件里面重新bind也不行的，这个我很早之前跟xuyang反馈过也试过了。目前解决办法是-game下允许UClass重复绑定。这个问题只会出现在非打包模式下，就是本地-game运行编辑器或ds。

**Comment by jozhn** [comment]
https://github.com/Tencent/UnLua/issues/619

**Comment by 610789338** [comment]
嗯嗯，我们自己加了个兼容

**Comment by xuyanghuang-tencent** [comment]
[v2.3.6](https://github.com/Tencent/UnLua/releases/tag/v2.3.6)
