### ISSUE TITLE
UE5.3 编译 链接错误

### ISSUE THREAD

**Issue by guojunping** [Tencent/UnLua#649]
[2/4] Link [x64] UnrealEditor-UnLua.dll
  正在创建库 D:\UE5Project\TestProject\Plugins\UnLua\Intermediate\Build\Win64\x64\UnrealEditor\Development\UnLua\UnrealEditor-UnLua.sup.lib 和对象 D:\UE5Project\TestProject\Plugins\UnLua\Intermediate\Build\Win64\x64\UnrealEditor\Development\UnLua\UnrealEditor-UnLua.sup.exp
10>Module.UnLua.cpp.obj: Error LNK2019 : 无法解析的外部符号 "public: static void __cdecl UObject::ProcessInternal(class UObject *,struct FFrame &,void * const)" (?ProcessInternal@UObject@@SAXPEAV1@AEAUFFrame@@QEAX@Z)，函数 "public: virtual void __cdecl ULuaFunction::Bind(void)" (?Bind@ULuaFunction@@UEAAXXZ) 中引用了该符号
10>Module.UnLua.cpp.obj: Error LNK2019 : 无法解析的外部符号 "public: __cdecl FTextProperty::FTextProperty(class FFieldVariant,struct UECodeGen_Private::FGenericPropertyParams const &)" (??0FTextProperty@@QEAA@VFFieldVariant@@AEBUFGenericPropertyParams@UECodeGen_Private@@@Z)，函数 "private: class TSharedPtr<struct UnLua::ITypeInterface,1> __cdecl UnLua::FPropertyRegistry::GetTextProperty(void)" (?GetTextProperty@FPropertyRegistry@UnLua@@AEAA?AV?$TSharedPtr@UITypeInterface@UnLua@@$00@@XZ) 中引用了该符号
10>UnrealEditor-UnLua.dll: Error LNK1120 : 2 个无法解析的外部命令

**Comment by xuyanghuang-tencent** [comment]
#642

**Comment by xuyanghuang-tencent** [comment]
[v2.3.6](https://github.com/Tencent/UnLua/releases/tag/v2.3.6)
