### ISSUE TITLE
UserWidget中无法执行Tick

### ISSUE THREAD

**Issue by l747369** [Tencent/UnLua#65]
只有当蓝图中的Tick事件启用时，Lua中的Tick才会执行，蓝图里没用Tick时，Lua层的Tick无法执行。

**Comment by rowechien** [comment]
是这样的，下面是相关代码
![Snipaste_2019-11-19_14-53-55](https://user-images.githubusercontent.com/7972243/69123579-af65f900-0adc-11ea-82a2-271033fd4733.png)
![Snipaste_2019-11-19_14-56-05](https://user-images.githubusercontent.com/7972243/69123661-e3d9b500-0adc-11ea-9890-1158be8cf767.png)
