### ISSUE TITLE
LuaOverridesClass.cpp Error C2440 Lines 61 and 82

### ISSUE THREAD

**Issue by V2iDanAbend** [Tencent/UnLua#655]
Getting a compile error when compiling the plugin for UE5.3.1 in VS2022. 

`C2440 '=': cannot convert from 'UField **' to 'TObjectPtr<UField> *' `

The code is in the to AddToOwner and RemoveFromOwner functions.

```
	const auto Class = Owner.Get();
	if (!Class)
		return;

	auto Field = &Class->Children;
	while (*Field)
		Field = &(*Field)->Next; //This line here
	*Field = this;

	if (Class->IsRooted() || GUObjectArray.IsDisregardForGC(Class))
		AddToRoot();
```

Any fix for this?

**Comment by xuyanghuang-tencent** [comment]
#642

**Comment by xuyanghuang-tencent** [comment]
[v2.3.6](https://github.com/Tencent/UnLua/releases/tag/v2.3.6)
