### ISSUE TITLE
UnLuaDebugBase.cpp Error C2445 Lines 487 and 501

### ISSUE THREAD

**Issue by V2iDanAbend** [Tencent/UnLua#656]
Getting compile errors compiling plugin for 5.3.1. 

`C2445	result type of conditional expression is ambiguous: types 'UClass *' and 'TObjectPtr<UClass>' can be converted to multiple common types`

Can be found in GetPropertyType function 

```
					FClassProperty* ClassProperty = (FClassProperty*)ObjectProperty;
					UClass* Class = Cast<UClass>(ObjectProperty->GetPropertyValue(ValuePtr));
					UClass* MetaClass = Class ? Class : ClassProperty->MetaClass; //This line here
                    if (MetaClass == UClass::StaticClass())
```

Any help or fix for this?

**Comment by xuyanghuang-tencent** [comment]
#642

**Comment by xuyanghuang-tencent** [comment]
[v2.3.6](https://github.com/Tencent/UnLua/releases/tag/v2.3.6)
