### ISSUE TITLE
请问支持Linux Shipping吗？我看WhitelistPlatforms里没有Linux

### ISSUE THREAD

**Issue by Checkmate** [Tencent/UnLua#66]

**Comment by lvpengfeifei** [comment]
很显然啊  插件里面都没有lua原生的支持linux的.so类库，应该是要自己去搞了，UnLua封装的C++部分应该不用变吧

**Comment by Checkmate** [comment]
有官方的人出来回答一下吗？我已经自己尝试了一下改了改插件，能够支持Linux Shipping了，打包部署到服务器也运行成功了。我想知道官方没有默认支持Linux的原因是什么，是有什么无法解决的坑或者难题吗？

**Comment by rowechien** [comment]
@Checkmate 暂时没有支持Linux，但有使用该插件的项目组自己加过支持，插件本身没有什么修改，如果你方便的话，可以提个Pull request，多谢！

**Comment by MacroGu** [comment]
应该需要增加一个 Linux 引用lua库的目录， 不是 so， 就 .a的静态库
