### ISSUE TITLE
Unlua函数绑定多个代理导致崩溃疑问

### ISSUE THREAD

**Issue by mheappy** [Tencent/UnLua#660]
![img_v2_8cbb7615-7ba5-468a-aac2-0ff76561fadg](https://github.com/Tencent/UnLua/assets/85383570/945c9a4c-723e-4ed5-b07e-782985c7d5d4)
如果多个代理声明形参不一致，这里Cached重新BindTo Delegate, 导致Broadcast类型可能和调用参数类型不一致，导致函数入栈可能会发生崩溃。

比如：
ADelegate(int) -->Handler1
BDelegate(Fstring) --> Handler2
LuaFuncion 同时绑定这两个代理，并且持有了这两个bind返回的Handler
然后Handler1.Broadcast(int),在读取解释参数那里发生了混乱

想请教一下大佬
这里的设计Cached是否预料到了这种情况？
或者这是不是隐性规定不允许这样用？
```[tasklist]
### Tasks
```

**Comment by xuyanghuang-tencent** [comment]
[v2.3.6](https://github.com/Tencent/UnLua/releases/tag/v2.3.6)
