### ISSUE TITLE
频繁创建销毁继承蓝图类的蓝图类对象，访问继承自父类的property会出现invalid property

### ISSUE THREAD

**Issue by jozhn** [Tencent/UnLua#661]
实际上property应该有效，但使用了之前缓存的处于BeginDestroy状态的父类的property。因为父类还没有被gc，所以子类metatable缓存的父类的property还在

**Comment by jozhn** [comment]
https://github.com/Tencent/UnLua/issues/613

**Comment by xuyanghuang-tencent** [comment]
[v2.3.6](https://github.com/Tencent/UnLua/releases/tag/v2.3.6)
