### ISSUE TITLE
FLuaValue和LuaEnv强绑定，通过GetMainState取lua_State，没有考虑协程的情况

### ISSUE THREAD

**Issue by icannotwait** [Tencent/UnLua#666]
协程调用时的lua_State是从global_State里分配的
从协程里调用导出的CFUNCTION接口，如果通过例如FLuaValue/FLuaTable的方式，会错误取到mainthread栈上的元素
建议仍然提供通过lua_State构造FLuaValue/FLuaTable及访问元素的方式

**Comment by xuyanghuang-tencent** [comment]
[v2.3.6](https://github.com/Tencent/UnLua/releases/tag/v2.3.6)
