### ISSUE TITLE
请问Unlua怎么加载本地的图片

### ISSUE THREAD

**Issue by Usidelip** [Tencent/UnLua#67]
LoadObject这个方法似乎并没有导出来，如果我要改变UI里Image的内容要怎么做呢

**Comment by HoHooHo** [comment]
这个方法有导出啊

**Comment by HoHooHo** [comment]
> LoadObject这个方法似乎并没有导出来，如果我要改变UI里Image的内容要怎么做呢

这个方法有导出啊

**Comment by Usidelip** [comment]
这个吗？
这么写会报参数错误哦，UE4.***后面错了吗



在 2019-11-05 15:24:49，"疯狂暴走哇" <notifications@github.com> 写道：


LoadObject这个方法似乎并没有导出来，如果我要改变UI里Image的内容要怎么做呢

这个方法有导出啊

**Comment by HoHooHo** [comment]
我这里可以 没有报错

**Comment by Usidelip** [comment]
![image](https://user-images.githubusercontent.com/3844601/68390930-5378a780-01a1-11ea-9281-28686bc85c60.png)
这样不会报参数错误？

**Comment by HoHooHo** [comment]
> ![image](https://user-images.githubusercontent.com/3844601/68390930-5378a780-01a1-11ea-9281-28686bc85c60.png)
> 这样不会报参数错误？

把 null 去掉，只有一个参数
UE.LoadObject("/Game/StarterContent/Textures/close")

**Comment by Usidelip** [comment]
了然，找错原型方法了
![image](https://user-images.githubusercontent.com/3844601/68448014-0f2aed00-021d-11ea-9939-a98d9349d514.png)
那再进一步找方法的正确姿势是？还是说第一个参数Object* Outer这个参数并不需要传过去？

**Comment by HoHooHo** [comment]
你找错了。这个是绑定的lua函数，并不是直接映射的。
![image](https://user-images.githubusercontent.com/2968872/68459847-5fb44180-0241-11ea-8799-e4ab7451ac75.png)

**Comment by Usidelip** [comment]
多谢

**Comment by woshiyigefeiwu** [comment]
**感谢！**
