### ISSUE TITLE
请问UnLua可以导出结构体指针吗？结构体指针在非PROPERTY、UFUCNTION的属性或者函数中是可以使用的

### ISSUE THREAD

**Issue by lvpengfeifei** [Tencent/UnLua#68]

**Comment by rowechien** [comment]
@lvpengfeifei 你好，我的理解是想要导出非反射体系内的数据？如果是的话，[Programming Guide](https://github.com/Tencent/UnLua/blob/master/UnLua_Programming_Guide_EN.md)里有具体描述。如果我理解不对，能否具体描述一些，谢谢！
