### ISSUE TITLE
UnLua只能运行一份实例?

### ISSUE THREAD

**Issue by XYdreamorigin** [Tencent/UnLua#703]
lua中定义的全局变量，在本地多人的情况下，是共享一份数据的么？

**Comment by cgsgood** [comment]
我这边发现是的，所以最好自己改造一下，能够适配多个World

**Comment by cgsgood** [comment]
https://github.com/cgsgood/UnLua
@XYdreamorigin 这是我改造的版本，可以支持UE5多实例
