### ISSUE TITLE
可以改用lua源码吗？调试很不方便啊，不用lua源码是有什么顾虑吗？

### ISSUE THREAD

**Issue by hbulmt** [Tencent/UnLua#71]

**Comment by tary** [comment]
编译快

**Comment by rowechien** [comment]
你是想调试lua源码吗？如果是的，应该是可以做到的，不过我只在windows上尝试过，把UnLua\Source\ThirdParty\Lua\下对应的库文件替换成自己编译出来的lua库文件，然后应该就可以调试lua源码了。
不直接把lua源码放到插件里没有什么特殊的顾虑，就是一个选择，就像引擎依赖的很多第三方库也不会把代码放进来和引擎一块编译一样，如果你有这方面的需求，可以自己调整一下插件结构，事实上也是有使用者这样干的。
