### ISSUE TITLE
带有lua脚本的UObject对象, 只有在world进行切换的时候才会被销毁

### ISSUE THREAD

**Issue by fdcumt** [Tencent/UnLua#73]
那些带lua脚本的UObject对象, 只有在world切换的时候才会被销毁, 如果我确定在该世界中, 这个UObject就是没有用了, 它也不会自动销毁. 
经查找,是在NewLuaObject中调用luaL_ref(L, LUA_REGISTRYINDEX); (789行)进行了引用.这使得该lua对象始终被引用, 到UUnLuaManager::Cleanup时候才会手动执行解引用.
(除非手动销毁, 类actor对象调用destroy)

为什么设计成这样? 是在项目中有什么bug才进行强制引用不销毁的吗??

**Comment by fdcumt** [comment]
我这里的解决方法是在NewLuaObject函数中增加销毁函数进行手动解引用, 目前发现这种做法有什么bug.
这种做法的前提是: 确定这个对象不会再次被使用了.

// 在UUnLuaManager中添加如下代码:
`	int32* FindLuaObjRef(UObjectBaseUtility *Object) { return AttachedObjects.Find(Object);  }`

// 在NewLuaObject中添加如下代码:
```
    lua_getfield(L, LUA_REGISTRYINDEX, "ObjectMap");
    lua_pushlightuserdata(L, Object);
    lua_newtable(L);                                            // create a Lua table ('INSTANCE')

	// lua强制自身解引用
	lua_pushstring(L, "LuaDestroy");
	lua_pushcfunction(L, LuaObjectTableUnReference);
	lua_rawset(L, -3);
```

// 在NewLuaObject函数上边添加函数LuaObjectTableUnReference
```
int32 LuaObjectTableUnReference(lua_State *L)
{
	int32 NumParams = lua_gettop(L);
	if (NumParams != 1)
	{
		UE_LOG(LogUnLua, Log, TEXT("%s: Invalid parameters!"), ANSI_TO_TCHAR(__FUNCTION__));
		return 0;
	}

	UObject *pObj = UnLua::GetUObject(L, 1);
	if (!pObj)
	{
		UE_LOG(LogUnLua, Log, TEXT("%s: Invalid Obj!"), ANSI_TO_TCHAR(__FUNCTION__));
		return 0;
	}

	int32 *pLuaRef = GLuaCxt->GetManager()->FindLuaObjRef(pObj);
	if (pLuaRef)
	{
		luaL_unref(L, LUA_REGISTRYINDEX, *pLuaRef);
	}
	return 0;
}
```

**Comment by rowechien** [comment]
@fdcumt 是的，确实是在切换关卡时才会尝试去销毁这些对象，后面会加上手动销毁的接口，和你上面写的类似，目前还有些问题，没有完全卸载赶紧，好了之后会上传的

**Comment by futouyiba** [comment]
这个问题为何关闭呢？这不是个没解决的问题吗

**Comment by rowechien** [comment]
@fdcumt @futouyiba fixed in [5df8813](https://github.com/Tencent/UnLua/commit/ccaa2bd8d60ec3d391bed2f8fe9207d4a5354042)
用法可以参考[#123](https://github.com/Tencent/UnLua/issues/123)中的说明
