### ISSUE TITLE
unlua获取编辑器里创建的结构体

### ISSUE THREAD

**Issue by VacantOne** [Tencent/UnLua#736]
大家好，我是unlua新手，请教一下，目前在ue编辑器里创建的结构体MyStruct如何在unlua里获取，我测试通过local Row = FMyStruct()获取好像会报空，现在是不支持这样获取了吗

**Comment by ryanzhoooou** [comment]
蓝图结构体需要先Load，Load后才能创建。

**Comment by ryanzhoooou** [comment]
参考Issue668的用法
`

        const auto Chunk = R"(
            local StructType = UE.UObject.Load("/UnLuaTestSuite/Tests/Regression/Issue668/Struct_Issue668.Struct_Issue668")
			local Array = UE.TArray(StructType)
            local Struct1 = StructType()
            local Struct2 = StructType()
			Array:Add(Struct1)
            Array:Add(Struct2)
        )";
        UnLua::RunChunk(L, Chunk);
`

**Comment by VacantOne** [comment]
好的，谢谢
