### ISSUE TITLE
TArray Add UObject失败

### ISSUE THREAD

**Issue by fdcumt** [Tencent/UnLua#75]
这个问题是问题#72的延续, 我好像没有权限reopen, 所以只能重新开一个, 因为原问题已经close掉, 我担心即使提交了新的回复, 也不会有相关人员回复了, 所以新开了一个, 特此说明一下.

我贴的复现代码确实有问题, 因为我在项目里, 实现了一个继承自UObject的类, 然后暴露给蓝图, 直接NewObject创建的, 但是经过测试, 即使是AActor子类, 也会有同样问题.
以下是我的测试代码以及测试结果:
测试代码:
![image](https://user-images.githubusercontent.com/10294860/69219469-df310180-0bad-11ea-950c-1136f52dc2c5.png)

调用堆栈信息:
![image](https://user-images.githubusercontent.com/10294860/69219442-cf192200-0bad-11ea-9282-f6f32244aa1b.png)

关键函数Cast后是nullptr
![image](https://user-images.githubusercontent.com/10294860/69219518-fd96fd00-0bad-11ea-839b-b3e804867adf.png)

**Comment by fdcumt** [comment]
这里还要说明一下, 为了防止GetUObject是空, 我还特意改了一下源码, 看了UObject的值:
![image](https://user-images.githubusercontent.com/10294860/69220599-5bc4df80-0bb0-11ea-8a23-1bc9909a2870.png)
以此来证明确实是Cast<UClass>出了问题.
难道你们用的都没问题吗?? 还是我的使用方法有问题??? 不过看代码确实不能将此类UObject cast成UClass啊.

**Comment by rowechien** [comment]
@fdcumt 我在#72里说了：
local Array1 = UE4.TArray(pClass); 这句创建的是一个UClass的TArray，类似于C++代码TArray<UClass*> Array1;
放在你这段代码里local TestArray = UE4.TArray(WeaponClass)也是创建了一个UClass的TArray，而不是Weapon实例的TArray。。。
你按照我在#72里给你的写法试试吧，也就是改成local TestArray = UE4.TArray(ABP_DefaultWeapon_C)

**Comment by fdcumt** [comment]
理解了, 感谢!!!
