### ISSUE TITLE
请问支持多个lua_State嘛？

### ISSUE THREAD

**Issue by godshow** [Tencent/UnLua#78]

**Comment by interlyx** [comment]
关注

**Comment by zh5243a** [comment]
关注

**Comment by rowechien** [comment]
不支持。。。

**Comment by interlyx** [comment]
不支持的话，会导致单进程模式下运行，rpc调用异常。
slua支持多luastate

**Comment by jarjin2000** [comment]
因为unlua不支持多luastate，我们在pie模式下开多个窗口，会导致公用变量冲突问题，就是A客户端初始化了公用变量，B跟C客户端却访问不到，请问PIE多窗口模式是不是有什么特殊设置与开关之类的？

**Comment by Rebuild-failed** [comment]
关注

**Comment by futouyiba** [comment]
> 因为unlua不支持多luastate，我们在pie模式下开多个窗口，会导致公用变量冲突问题，就是A客户端初始化了公用变量，B跟C客户端却访问不到，请问PIE多窗口模式是不是有什么特殊设置与开关之类的？

也就是说，如果在编辑器中调试多人游戏，有很大概率碰到此问题吗……

**Comment by rowechien** [comment]
多state短时间内不会去支持。
这里说的“公用变量”是lua全局变量的意思吧？如果是的话肯定是不保证逻辑的正确，editor里多个pie窗口本质上还是同一个进程，相同的情况下你在c++里写全局变量照样有问题。。。如果你的游戏支持ds/client模式，又想在editor里模拟，写逻辑时就要考虑全局变量（不管是lua还是c++）是否合适。
从另一个角度来看，blueprint里有全局变量这个概念嘛？如果真有类似“全局变量”的需求，我觉得可以用GameInstance实例上的变量来达到目的。

先不关了，就当feature request吧

**Comment by luciferzsw** [comment]
多个窗口就会启动多个GameInstance，但LuaContext只有一个，无论是本地DS，还是多个窗口，都是同一个LuaContext。

**Comment by yangruihan** [comment]
关注

**Comment by liuhao0620** [comment]
我找了一下，UnLua当中总共存在六个全局变量，分别是GLuaCxt、GReflectionRegistry、GLuaDynamicBinding、GDefaultParamCollection、GLuaSrcRelativePath、GLuaSrcFullPath。看了代码，如果想要支持多个WorldContext的UnLua互相隔离，至少需要存在多份GLuaCxt和GReflectionRegistry。我现在有一个思路是建立一个UnLua全局变量的管理器,在WorldContext创建/销毁时创建/删除一份全局变量。在函数调用入口处，根据上下文把真正的全局变量切换一下。不知道是否可行，正在试验当中，有兴趣的朋友可以交流一下。

**Comment by liuhao0620** [comment]
SManager也需要处理一下，或许还需要处理更多的全局变量。各位有什么更好的思路吗？

**Comment by hernanzhou** [comment]
ue 有个设置，可以让 多个 GameInstance 作为单独进程运行，则不会有共用 luastate 的问题

**Comment by dzCxy** [comment]
关注
