### ISSUE TITLE
CacheScriptContainer的实现有bug

### ISSUE THREAD

**Issue by interlyx** [Tencent/UnLua#81]
C++上写一个单播代理（代理参数包括一个容器可以是array、map或者set），在lua上写个循环，重复执行绑定、触发、解绑操作。就会产生崩溃。代码见下图
![image](https://user-images.githubusercontent.com/33210468/69723888-a668cd80-1155-11ea-88a6-609811ff10f0.png)

![image](https://user-images.githubusercontent.com/33210468/69723834-8a652c00-1155-11ea-8bde-494f89f35118.png)

分析了下，CacheScriptContainer在lua的stack上的ScriptContainerMap缓存了几种FContainerDesc的userdata对象（FLuaArray、FLuaMap、FLuaSet），这几个对象存储了这几种容器在Desc上的InnerProperty，但是在delegate的unbind的时候，会释放functionDesc，继而释放PropertyDesc，然而缓存没有删除，InnerProperty变成野指针。导致在下一次bind后重新execute，就会产生野指针访问异常。

解决办法应该要在propertydesc释放的时候清除ScriptContainerMap里的缓存。

**Comment by interlyx** [comment]
@rowechien

**Comment by rowechien** [comment]
@interlyx 我试了下，并没有发现问题啊。
![image](https://user-images.githubusercontent.com/7972243/70124813-8767bf80-16b0-11ea-81d4-eecf3ba317cf.png)
![image](https://user-images.githubusercontent.com/7972243/70124834-92baeb00-16b0-11ea-8bc8-d3afbfa6aa56.png)
![image](https://user-images.githubusercontent.com/7972243/70125026-f5ac8200-16b0-11ea-9784-99b6085d06f4.png)
![image](https://user-images.githubusercontent.com/7972243/70124903-b1b97d00-16b0-11ea-8fcd-41ce4fc335f8.png)
![image](https://user-images.githubusercontent.com/7972243/70125037-00ffad80-16b1-11ea-9b43-bce635185861.png)

**Comment by interlyx** [comment]
我开个仓库传测试代码上来

**Comment by interlyx** [comment]
https://gitee.com/ndinterlyx/TestUnlua.git
github速度比较慢，在码云上开了一个仓库
测试代码在feature/lyx/crashtest分支上
lua上，所有会产生crash的点用“--crash”注释了

**Comment by interlyx** [comment]
直接clone后switch就可以

**Comment by interlyx** [comment]
github上我也传了一份
https://github.com/interlyx/testunlua
测试分支同样是feature/lyx/crashtest

**Comment by interlyx** [comment]
我提的两个issue都在这个demo上展示了
启动时UnLuaPerformanceTestProxy:ReceiveBeginPlay函数里会产生本issue的崩溃
![image](https://user-images.githubusercontent.com/33210468/70150740-72f1ea00-16e5-11ea-821b-1a12ea4388dd.png)

进入游戏以后点左键开火可以测试#77的问题
![image](https://user-images.githubusercontent.com/33210468/70150614-3de59780-16e5-11ea-8658-0b8682afa915.png)

**Comment by interlyx** [comment]
知道你的测试不会崩溃的原因了，如果unbind函数调用的时候触发FArrayPropertyDesc里析构函数释放的InnerProperty内存地址和下一次bind时候调用FArrayPropertyDesc的构造函数时new出来的InnerProperty地址刚好一样的时候，缓存即使没有被更新也不会有问题。一般来说，操作系统会有一定几率重复利用刚刚释放的内存。所以像这种连续bind和unbind的情况运气好就不会崩溃。如果操作系统在下一次create的时候，分配了新的内存，就一定会崩溃了。主要的问题还是缓存没有更新。
![image](https://user-images.githubusercontent.com/33210468/70154296-4214b380-16eb-11ea-8703-94f1cc04d03d.png)
在这两个位置把指针地址打出来就很容易知道问题了。

现在的问题是我不知道怎么去重建这块缓存。。。这块缓存是通过key来查找的。但是key在FArrayPropertyDesc析构的时候没办法知道。。。没办法DelCachedScriptContainer

@rowechien

**Comment by interlyx** [comment]
![image](https://user-images.githubusercontent.com/33210468/70199772-8769cd00-174d-11ea-8e17-1f5b73b0d1cc.png)
这种情况会崩溃

**Comment by interlyx** [comment]
注意要开启Dedicate Server.否则会崩溃的代码运行不到

**Comment by interlyx** [comment]
![image](https://user-images.githubusercontent.com/33210468/70199979-1aa30280-174e-11ea-9291-ef26b2d9b824.png)
这种情况不会崩溃，因为内存在不断被复用

**Comment by rowechien** [comment]
@interlyx 我能重现了，修正后会上传的

**Comment by rowechien** [comment]
@interlyx 最新的上传9e58299修正了野指针问题，你可以试试。这应该没有解决cached内容无效的情况，但野指针引起的crash应该不存在了，之后再考虑更完美的改法。

**Comment by interlyx** [comment]
这个缓存的问题解决了，但是rpc传数组还是有问题。这个issue先关了
