### ISSUE TITLE
单进程下，rpc调用异常

### ISSUE THREAD

**Issue by zh5243a** [Tencent/UnLua#82]
1，单进程下， 开启专用服务器
2，创建rpc函数（服务端执行）
3，lua对该函数进行覆写
4，从lua调用该rpc函数

执行失败，且没有任何日志

**Comment by rowechien** [comment]
@zh5243a 麻烦你描述更具体点，从issues里能看成rpc函数的覆写有些问题，暂时没时间来调试修改。。。

**Comment by zh5243a** [comment]
正常情况下， 调用rpc函数，服务端应该要触发对应的响应函数，但是单进程下无法触发

**Comment by lvpengfeifei** [comment]
RPC不支持单进程调试 开多进程才行，也遇到这个问题

**Comment by rowechien** [comment]
@zh5243a @lvpengfeifei fixed in [630447b](https://github.com/Tencent/UnLua/commit/29bee56d1c4f9b5026ccbc3510c6340d4d8c662b). 当然，首先要保证：1. 将UnLua.Build.cs里的bSupportsRpcCall设为True; 2. 对应的覆写的rpc函数在lua里需要加上“_RPC”后缀，这个可以参考progamming guide。
如果还是没有解决你们的问题再reopen。。。

**Comment by rowechien** [comment]
@zh5243a @lvpengfeifei fixed in [cc10354](cc10354c35910a5bcdec9606ef6f83a6d48b09b9). reopen the issue if it doesn't work.
