### ISSUE TITLE
请问如果使用widget:GetWidgetFromName扩展函数？直接调用报空。

### ISSUE THREAD

**Issue by jarjin2000** [Tencent/UnLua#84]
请问如果使用widget:GetWidgetFromName扩展函数？直接调用报空。

**Comment by rowechien** [comment]
这种非UFUNCTION函数，你需要导出后才能使用。具体参加[Programming Guide](https://github.com/Tencent/UnLua/blob/master/UnLua_Programming_Guide_EN.md)
