### ISSUE TITLE
创建了一个蓝图AnimNotify, 添加了UUnLuaInterface后，只有第一次运行会调用lua方法，第二次运行游戏没有

### ISSUE THREAD

**Issue by FireLeaf** [Tencent/UnLua#85]
notify代码如下
function TestNotify_C:Received_Notify()
	print("test nottify")
end
第一次跑游戏显示
LogUnLua: == UNLUA_PRINT : test nottify    
第二次跑游戏就没有日志打印了， 建的AnimNotifyState也是

不知道哪里有问题

**Comment by rowechien** [comment]
@FireLeaf 我感觉你描述的问题应该是在PIE模式下吧？Editor下AnimNotify这些应该是以及在AnimSequence加载后就创建好了，PIE时它们不会再重新创建，而UnLua是在PIE时才开始工作（FLuaContext::PreBeginPIE），PIE结束后停止工作（FLuaContext::PrePIEEnded），所以会有这种情况出现。
如果standalone模式（-game）或者打包的版本出这个问题，那应该就是bug了。
