### ISSUE TITLE
lua中重写的Actor的RecieveTick方法不会被调用

### ISSUE THREAD

**Issue by D3ZAX** [Tencent/UnLua#86]
目前只有在蓝图中点亮了事件图表里的Tick节点才能使lua中重写的RecieveTick方法被调用，请问能否在lua的RecieveBeginPlay方法里调用一些接口来使RecieveTick工作？

最好能调整为lua中重写了RecieveTick方法就可以直接生效

**Comment by rowechien** [comment]
UE4.21开始，只会对Blueprint类调用ReceiveTick，也就是说如果你的引擎版本在4.21或者更新，从C++层面实现UnLuaInterface，这种情况下ReceiveTick是不会执行的。
除了上面说的原因，我还没碰到过蓝图的Actor类不能覆写ReceiveTick的情况，如果你碰到的问题就是蓝图Actor类，那可能要麻烦你描述具体点，方便的话放些代码出来。
至于修改，这是个插件，不会去修改引擎，插件所有功能都不建立在要对引擎做修改的场景下。但开发者可以根据自己的情况去对引擎做些修改来满足自己的需求。

**Comment by D3ZAX** [comment]
我的意思是lua里的RecieveTick在运行游戏时不会自动被引擎调用，使用的引擎版本是 4.22.3

放上两个Actor的设置和lua代码：
![image](https://user-images.githubusercontent.com/15343372/70765203-0639b800-1d95-11ea-80cb-8d5b3969bedb.png)
![image](https://user-images.githubusercontent.com/15343372/70765035-7136bf00-1d94-11ea-91e4-0413f8b497be.png)

这是日志：
![image](https://user-images.githubusercontent.com/15343372/70765257-2cf7ee80-1d95-11ea-9fe7-f1e65e5ab78a.png)

另外附上工程文件：
[UnLuaTest.zip](https://github.com/Tencent/UnLua/files/3958782/UnLuaTest.zip)

**Comment by kimixuchen** [comment]
这个是UE4自己的设计，开启Tick有两种方法，一种是在C++中把bCanEverTick设为true，另一种就是在蓝图中创建Event Tick节点，可见FKismetCompilerContext::SetCanEverTick()函数。在ReceiveBeginPlay里操作时机就晚了，而且感觉也不是干净的做法。

**Comment by SkadyCat** [comment]
HotReload 一下....
