### ISSUE TITLE
请问如何释放FScriptDelegate类型的委托函数引用？

### ISSUE THREAD

**Issue by GotGimhong** [Tencent/UnLua#87]
通过LuaLib_Delegate的实现得知，对于FScriptDelegate类型，在Lua可以通过Bind函数绑定一个UObject以及委托函数，通过Unbind函数清理绑定。目前发现如果使用Lua函数作为委托函数，例如：
`local function Callback() ... end`
`scriptDelegate:Bind(uobject, Callback)`
即使执行Unbind也无法释放委托函数的引用，UE4内存报告中DelegateFunction类型的引用数并不会减少。
查看FDelegateHelper类的Unbind函数了解到，只有当委托函数为UObject的蓝图函数时才能正常释放引用，因此请问对于使用Lua函数作为委托函数的情况，应该如何释放委托函数引用呢？（组播类型FMulticastScriptDelegate则没有这个问题，因为Remove函数中没有判断委托函数是否为UObject的蓝图函数）
![Unbind](https://user-images.githubusercontent.com/16437644/70583349-6c3d0880-1bf8-11ea-9995-efa565b3e9d9.png)

**Comment by GotGimhong** [comment]
另外，我发现在FDelegatePropertyDesc类的SetValueInternal函数中也有类似FScriptDelegate_Bind的实现。
![QQ截图20191211141644](https://user-images.githubusercontent.com/16437644/70597050-43ca0400-1c22-11ea-8e8c-ee55cf7c72a9.png)

目前尝试过，从Lua向C++传递委托类型变量的话，例如：
C++
`UFUNCTION(BlueprintCallable)`
`void AddDelegate(const FMyDelegate& Delegate);`
Lua
`local luaDelegate = { uobject, callback }`
`myObject:AddDelegate(luaDelegate)`
无论FMyDelegate属于单播还是组播类型，即使对其执行Clear也是无法释放委托函数引用的，请问对于这种情况又该如何处理呢？（两种情况都是因为通过FDelegateHelper::CreateSignature函数添加的引用记录无法被清理）

**Comment by GotGimhong** [comment]
@rowechien 请问这个问题是我描述得不够清楚，还是属于底层问题正在修复当中呢？如果是前者，我们可以再交流下，看看需要我做些怎样的补充；如果是后者，能否先让我们了解下大致的修复情况？目前我们的项目确实在这一部分出现了内存泄漏的问题，希望至少能够先有一个基本的解决思路和方向。

**Comment by rowechien** [comment]
@GotGimhong 我本地测试了一下，把结果贴一下：
C++代码里的Delegate定义：
![image](https://user-images.githubusercontent.com/7972243/71654861-fe0ae200-2d6e-11ea-9fb1-effd6a40ffbb.png)
Lua代码：
![image](https://user-images.githubusercontent.com/7972243/71654873-10851b80-2d6f-11ea-982a-c246d2066915.png)
运行起来输入命令行：Obj Refs name=BP_PlayerCharacter_C
结果中并未发现OnHpUpdate对应的UFunction。
修改Lua代码：
![image](https://user-images.githubusercontent.com/7972243/71654969-8db09080-2d6f-11ea-97ab-94a733a4da76.png)
运行起来输入命令行：Obj Refs name=BP_PlayerCharacter_C
结果中能发现:
![image](https://user-images.githubusercontent.com/7972243/71654995-b3d63080-2d6f-11ea-9048-1283e43efc6c.png)

你描述的Unbind后UFunction引用没有被清除，从上面结果看是不存在的。所以，是我没有理解你的问题，还是我测试的case不对？

或者你方便，把你认为有问题并且可以重现的case做个小的测试工程放到github上，我来看看。

**Comment by GotGimhong** [comment]
@rowechien 感谢回复。

在你的测试样例中，BP_PlayerCharacter_C必须是实现了UnLuaInterface的蓝图类型吧？如此一来，OnHpUpdateDelegate函数就相当于是它的一个蓝图函数了，按照你的设计，这种写法确实可以正常释放DelegateFunction的引用。
而在我的测试样例中，OnHpUpdateDelegate是一个纯Lua对象的函数，例如：
`local MyLuaObject = {}`
`function MyLuaObject:OnHpUpdateDelegate(HP)`
`    -- TODO`
`end`
这样的话就会出现DelegateFunction引用无法释放的问题了，请用我的写法测试一下吧。

另外以上只是针对我反馈的第一种情况，第二种情况则是通过一个蓝图函数直接传递委托，也是会出现类似的问题。我晚点会把我的详细测试样例截图发上来。

**Comment by rowechien** [comment]
@GotGimhong 即使是你说的这种情况也不会有问题的啊，本质上都是lua function。这里你说的的委托函数（SignatureFunction，是个UFunction）是运行时复制出来的，不论你传什么lua function这个委托函数都会被复制，它的trunk function被替换了，执行时实际上是在调用和它关联的lua function。

**Comment by rowechien** [comment]
@GotGimhong 方便的话，放一个可重现的小测试工程到github上，我可以帮你调试

**Comment by GotGimhong** [comment]
> @GotGimhong 方便的话，放一个可重现的小测试工程到github上，我可以帮你调试

感谢。
我看了一下，我们项目使用的UnLua有一段时间没有更新了，我先更新一下再测试看看是否还有问题。另外最近也比较忙，如果还是有问题的话，我到时放一个测试工程到github上，然后再通知下你吧。请你先忙，有情况我再跟你反馈。

**Comment by GotGimhong** [comment]
@rowechien 重新测试过，DelegateFunction的问题属于项目个别代码写法不规范，以及内存测试时无意触发了引擎GC所致，与UnLua无关，委托函数引用是可以正常释放的。感谢协助，这个Issue可以先关闭了。
另外前两天发现一个在Lua调用EditableTextBox控件SetText函数可能会引起断点异常的问题，测试工程和相关文档我已经放到Github上了，也加了你（https://github.com/GotGimhong/UnLuaTest/invitations），能否抽空帮忙测试下？

**Comment by GotGimhong** [comment]
@rowechien 抱歉，关于FScriptDelegate类型的测试，有一种情况我漏考虑了——对于无法在Lua进行Unbind的委托，它们的DelegateFunction引用是释放不掉的。

例如引擎UserWidget动画结束事件的监听：
![QQ截图20200108105216](https://user-images.githubusercontent.com/16437644/71946567-2c703d80-3205-11ea-8c37-ca90a83ac5c7.png)
在这种情况下，委托的DelegateFunction是会有残留的，因为没有经过FDelegateHelper的Unbind，请先自行测试下。我晚点会在我的Github上补充一下测试样例和文档。

**Comment by rowechien** [comment]
@GotGimhong 后面这个特殊情况确实无法清理干净，原因就是你说的没有Unbind，我上传了个改动[5df8813](https://github.com/Tencent/UnLua/commit/5df8813b291bed7d8ce81a158bd8e382491c03c8)，应该可以了。针对你这个场景，在BP_MyUserWidget_C:Destruct()函数开头增加一行：FScriptDelegate.Unbind(self.delegate)

**Comment by C209** [comment]
> @GotGimhong 后面这个特殊情况确实无法清理干净，原因就是你说的没有Unbind，我上传了个改动[5df8813](https://github.com/Tencent/UnLua/commit/5df8813b291bed7d8ce81a158bd8e382491c03c8)，应该可以了。针对你这个场景，在BP_MyUserWidget_C:Destruct()函数开头增加一行：FScriptDelegate.Unbind(self.delegate)
> 
> 

针对该问题，如果在绑定的回调中执行了UnbindFromAnimationFinished()那样的反注册过程，然后调用FScriptDelegate.Unbind()，在回调执行完毕时就会产生check fail，因为反注册时又将table传入导致绑定次数加一了。
