### ISSUE TITLE
FLuaContext::TryToBindLua函数，需要忽略掉class前缀是“REINST_”和"SKEL_"的object

### ISSUE THREAD

**Issue by interlyx** [Tencent/UnLua#91]
class是“REINST_”前缀的，在绑定的时候会失败
CDO上获取ModuleName拿到的是空

**Comment by interlyx** [comment]
bool FLuaContext::TryToBindLua(UObjectBaseUtility *Object)
{
    if (!bEnable || !Object || !Manager)
    {
        return false;
    }

#if WITH_EDITOR
    if (GIsEditor && !bIsPIE)
    {
        return false;
    }
#endif

    static UClass *InterfaceClass = UUnLuaInterface::StaticClass();
    if (!Object->HasAnyFlags(RF_ClassDefaultObject | RF_ArchetypeObject))           // filter out CDO and ArchetypeObjects
    {
        check(!Object->IsPendingKill());
        UClass *Class = Object->GetClass();
		if (Class->GetName().StartsWith("REINST_") || Class->GetName().StartsWith("SKEL_"))
		{
			return false;
		}

        if (Class->IsChildOf<UPackage>() || Class->IsChildOf<UClass>())             // filter out UPackage and UClass
        {
            return false;
        }

......

**Comment by interlyx** [comment]
bool FLuaContext::TryToBindLua(UObjectBaseUtility *Object)
{
    if (!bEnable || !Object || !Manager)
    {
        return false;
    }

#if WITH_EDITOR
    if (GIsEditor && !bIsPIE)
    {
        return false;
    }
#endif

    static UClass *InterfaceClass = UUnLuaInterface::StaticClass();
    if (!Object->HasAnyFlags(RF_ClassDefaultObject | RF_ArchetypeObject))           // filter out CDO and ArchetypeObjects
    {
        check(!Object->IsPendingKill());
        UClass *Class = Object->GetClass();
//check
		if (Class->GetName().StartsWith("REINST_") || Class->GetName().StartsWith("SKEL_"))
		{
			return false;
		}

        if (Class->IsChildOf<UPackage>() || Class->IsChildOf<UClass>())             // filter out UPackage and UClass
        {
            return false;
        }
        if (Class->ImplementsInterface(InterfaceClass))                             // static binding
        {
            UFunction *Func = Class->FindFunctionByName(FName("GetModuleName"));    // find UFunction 'GetModuleName'. hard coded!!!
            if (Func)
            {
                if (Func->GetNativeFunc() && IsInGameThread())
                {

。。。。。。

**Comment by interlyx** [comment]
bool FLuaContext::TryToBindLua(UObjectBaseUtility *Object)
{
    if (!bEnable || !Object || !Manager)
    {
        return false;
    }

#if WITH_EDITOR
    if (GIsEditor && !bIsPIE)
    {
        return false;
    }
#endif

    static UClass *InterfaceClass = UUnLuaInterface::StaticClass();
    if (!Object->HasAnyFlags(RF_ClassDefaultObject | RF_ArchetypeObject))           // filter out CDO and ArchetypeObjects
    {
        check(!Object->IsPendingKill());
        UClass *Class = Object->GetClass();
		if (Class->GetName().StartsWith("REINST_") || Class->GetName().StartsWith("SKEL_"))
		{
			return false;//check prefix
		}

        if (Class->IsChildOf<UPackage>() || Class->IsChildOf<UClass>())             // filter out UPackage and UClass
        {
            return false;
        }
        if (Class->ImplementsInterface(InterfaceClass))                             // static binding
        {
            UFunction *Func = Class->FindFunctionByName(FName("GetModuleName"));    // find UFunction 'GetModuleName'. hard coded!!!
            if (Func)
            {
                if (Func->GetNativeFunc() && IsInGameThread())
                {

**Comment by interlyx** [comment]
今天网络比较差，贴不上图

**Comment by rowechien** [comment]
我先本地试试

**Comment by rowechien** [comment]
@interlyx 请问能否给我个简单的测试工程，放在github就行，我无法重现这个问题，没有检查到REINST_开头的类，一些SKEL_开头的类都被if (!Object->HasAnyFlags(RF_ClassDefaultObject | RF_ArchetypeObject))这个判断过滤了

**Comment by interlyx** [comment]
可以。我弄一个
rpc传数组崩溃的问题为啥你始终没回复？
@rowechien

**Comment by rowechien** [comment]
@interlyx 我有不少别的开发工作要做，并不是全职只维护这个插件，在不是工作重心的情况下只能在有空的时候看下，请理解。。。RPC相关的问题我争取休息时间统一处理了

**Comment by interlyx** [comment]
好的，辛苦了。主要是我这边定位很久没发现问题，否则先给出一些思路会方便你定位问题。@rowechien

**Comment by interlyx** [comment]
复现不了了。不知道是不是升到4.24的缘故。这个无视吧。。。。

**Comment by tary** [comment]
我也遇到这个问题了, 4.24.2 每次启动编辑器**第一次**运行会出现, 之后再Play就会没这个Log了
REINST_开头的, @interlyx 你解决了吗

**Comment by interlyx** [comment]
我贴的代码里有我们的解决方案，你可以看看
@tary

**Comment by tary** [comment]
先这么着吧, @interlyx  谢了
