### ISSUE TITLE
更新最新版代码编译报错。。。

### ISSUE THREAD

**Issue by jarjin2000** [Tencent/UnLua#94]
单纯下载本项目编译也是一样报错
![image](https://user-images.githubusercontent.com/15137027/71468903-7d923180-2802-11ea-80e7-e5ae9df66993.png)

**Comment by jarjin2000** [comment]
这段代码先临时回退了。
![image](https://user-images.githubusercontent.com/15137027/71470510-5b4ee280-2807-11ea-8251-312ca05b3cdd.png)

**Comment by rowechien** [comment]
fixed!
