### ISSUE TITLE
standalone game中Lua调用C++函数默认参数问题

### ISSUE THREAD

**Issue by FireLeaf** [Tencent/UnLua#95]
local sound = UE4.UGameplayStatics.SpawnSound2D(self.UserWidget, object, 1.0, 1.0)
--sound:SetVolumeMultiplier(1.0)
--sound:SetPitchMultiplier(1.0)
print("create sound", sound, sound:IsPlaying(), sound.VolumeMultiplier, sound.PitchMultiplier)
  这块如果 UE4.UGameplayStatics.SpawnSound2D(self.UserWidget, object)这样调用，声音播不出来，看了下sound.VolumeMultiplier, sound.PitchMultiplier都为0 ， 需要强制设置调用参数为1.0, 但是C++中是有默认值为1.0的

**Comment by rowechien** [comment]
@FireLeaf 请问你说的standalone game是指加-game启动游戏么？我本地试了下，没有发现问题啊。
Lua代码：
![image](https://user-images.githubusercontent.com/7972243/71653978-31973d80-2d6a-11ea-885c-970a9b2433b4.png)
vs里的调试窗口：
![image](https://user-images.githubusercontent.com/7972243/71654000-4c69b200-2d6a-11ea-8adf-5fd6f3337bb4.png)

**Comment by FireLeaf** [comment]
![picture](https://user-images.githubusercontent.com/4057681/72222874-609c8300-35a4-11ea-982f-09d885e87f14.png)
这个模式的

**Comment by rowechien** [comment]
@FireLeaf 按这个standalone game也没有问题啊
![image](https://user-images.githubusercontent.com/7972243/75623290-75c88200-5be3-11ea-9e2d-43be9565dd79.png)
只要不是listen server或者dedicated server模式，这个和直接加-game启动游戏本质一样，也会加上-game参数：
![image](https://user-images.githubusercontent.com/7972243/75623419-b379da80-5be4-11ea-8b9a-da92892241f8.png)
你可以再确认一下是否有其他情况，比如是否静态导出了这个函数
