### ISSUE TITLE
Android打包编译出错(NDK-r14b)

### ISSUE THREAD

**Issue by ugsgame** [Tencent/UnLua#96]
Android打包编译出错，ndk版本android-ndk-r14b，提示是ITypeInterface无虚构析函数，解决办在ITypeInterface添加virtual ~ITypeInterface() {}就可以了

**Comment by ugsgame** [comment]
![{6B3B9E2C-F51F-400A-AC11-087157A761BF}](https://user-images.githubusercontent.com/2774943/71865927-71ca3780-313f-11ea-81dc-31e082a0f61f.png)

**Comment by xinbay** [comment]
@ugsgame tks

**Comment by rowechien** [comment]
@ugsgame fixed！ Thanks!
