### ISSUE TITLE
weakobjectptr弱引用指针被lua强引用

### ISSUE THREAD

**Issue by interlyx** [Tencent/UnLua#97]
目前CPT_WeakObjectReference和CPT_ObjectReference的处理完全一样。会导致lua对弱引用对象产生强引用。这块是有意为之吗?但是事实上这种情况我们希望是对象的生命周期由c++进行管理
![image](https://user-images.githubusercontent.com/33210468/71877279-b667ca00-3163-11ea-9ac8-b241d4e6b88e.png)

**Comment by rowechien** [comment]
@interlyx 即使是弱引用，一旦在lua里被使用了，就需要给它加个引用，lua一旦把它清理了再释放。不然如果引擎先于lua释放了这个弱引用，lua代码里还在使用的话就会产生问题，甚至crash

**Comment by interlyx** [comment]
一般来说强引用的地方我们都只允许一处，是真正对这块数据进行管理的地方，如果lua也强引用，会导致c++真正管理这块数据的地方无法准确控制引用的对象的生命周期。目前我们是把弱引用指针给lua的时候不增加UE4的强引用计数，lua脚本要使用的时候要进行valid判断。

**Comment by interlyx** [comment]
@rowechien
