### ISSUE TITLE
UObject引用问题

### ISSUE THREAD

**Issue by kimixuchen** [Tencent/UnLua#98]
你好，关于UObject的引用我想请教一下。
在绑定流程中会调用AddAttachedObject函数，从而对该UObject添加UEGC的引用。而GObjectReferencer去掉这个引用需要收到NotifyUObjectDeleted通知，但UObject因为有来自lua的引用，所以不会自动被GC删除。虽然lua中绑定的table在被lua gc时也会从ReferencedObjects删掉UObject，但这个table的gc也un_ref也依赖于NotifyUObjectDeleted通知。

这样一来，是不是这个UObject就gc不掉了？

**Comment by rowechien** [comment]
@kimixuchen UObject对应的lua实例（table或者userdata）一旦被lua虚拟机gc了就会清除对应的引用，也就是调用GObjectReferencer.RemoveObjectRef。静态绑定的UObject在lua里的实例（table）在注册表中保留的引用（luaL_ref），它们会在切换地图或者手动删除（AActor::K2_DestroyActor）的情况下被清理，当然，对Object还没有提供手动的删除办法。。。
